// Chapter 17: Clothing & Fashion (100 Essential Words)
// Words related to clothing, accessories, fashion, and personal appearance

import { LanguageWord } from './chapter01-basic-everyday'

export const chapter17Words: LanguageWord[] = [
  // Basic Clothing (25 words)
  { id: 'clothing1', english: 'Clothes', vietnamese: 'Quần áo', pronunciation: 'quan ao', category: 'clothing', chapter: 'chapter17', difficulty: 1, examples: ['Wash dirty clothes.'] },
  { id: 'clothing2', english: 'Shirt', vietnamese: 'Áo sơ mi', pronunciation: 'ao so mi', category: 'clothing', chapter: 'chapter17', difficulty: 1, examples: ['White shirt for office.'] },
  { id: 'clothing3', english: 'T-shirt', vietnamese: 'Áo thun', pronunciation: 'ao thun', category: 'clothing', chapter: 'chapter17', difficulty: 1, examples: ['Comfortable cotton t-shirt.'] },
  { id: 'clothing4', english: 'Pants', vietnamese: 'Quần dài', pronunciation: 'quan dai', category: 'clothing', chapter: 'chapter17', difficulty: 1, examples: ['Black pants formal.'] },
  { id: 'clothing5', english: 'Jeans', vietnamese: 'Quần jean', pronunciation: 'quan jean', category: 'clothing', chapter: 'chapter17', difficulty: 1, examples: ['Blue jeans casual.'] },
  { id: 'clothing6', english: 'Shorts', vietnamese: 'Quần ngắn', pronunciation: 'quan ngan', category: 'clothing', chapter: 'chapter17', difficulty: 1, examples: ['Summer shorts cool.'] },
  { id: 'clothing7', english: 'Skirt', vietnamese: 'Váy', pronunciation: 'vay', category: 'clothing', chapter: 'chapter17', difficulty: 1, examples: ['Long skirt elegant.'] },
  { id: 'clothing8', english: 'Dress', vietnamese: 'Đầm', pronunciation: 'dam', category: 'clothing', chapter: 'chapter17', difficulty: 1, examples: ['Beautiful dress party.'] },
  { id: 'clothing9', english: 'Blouse', vietnamese: 'Áo kiểu', pronunciation: 'ao kieu', category: 'clothing', chapter: 'chapter17', difficulty: 1, examples: ['Silk blouse expensive.'] },
  { id: 'clothing10', english: 'Sweater', vietnamese: 'Áo len', pronunciation: 'ao len', category: 'clothing', chapter: 'chapter17', difficulty: 1, examples: ['Warm sweater winter.'] },
  { id: 'clothing11', english: 'Jacket', vietnamese: 'Áo khoác', pronunciation: 'ao khoac', category: 'clothing', chapter: 'chapter17', difficulty: 1, examples: ['Leather jacket stylish.'] },
  { id: 'clothing12', english: 'Coat', vietnamese: 'Áo choàng', pronunciation: 'ao choang', category: 'clothing', chapter: 'chapter17', difficulty: 1, examples: ['Heavy coat protects cold.'] },
  { id: 'clothing13', english: 'Hoodie', vietnamese: 'Áo hoodie', pronunciation: 'ao hoodie', category: 'clothing', chapter: 'chapter17', difficulty: 1, examples: ['Comfortable hoodie casual.'] },
  { id: 'clothing14', english: 'Cardigan', vietnamese: 'Áo cardigan', pronunciation: 'ao cardigan', category: 'clothing', chapter: 'chapter17', difficulty: 1, examples: ['Buttoned cardigan warm.'] },
  { id: 'clothing15', english: 'Vest', vietnamese: 'Áo gile', pronunciation: 'ao gile', category: 'clothing', chapter: 'chapter17', difficulty: 1, examples: ['Formal vest suit.'] },
  { id: 'clothing16', english: 'Tank top', vietnamese: 'Áo ba lỗ', pronunciation: 'ao ba lo', category: 'clothing', chapter: 'chapter17', difficulty: 1, examples: ['Tank top summer.'] },
  { id: 'clothing17', english: 'Polo shirt', vietnamese: 'Áo polo', pronunciation: 'ao polo', category: 'clothing', chapter: 'chapter17', difficulty: 1, examples: ['Polo shirt sporty.'] },
  { id: 'clothing18', english: 'Button-up', vietnamese: 'Áo cài khuy', pronunciation: 'ao cai khuy', category: 'clothing', chapter: 'chapter17', difficulty: 1, examples: ['Button-up shirt professional.'] },
  { id: 'clothing19', english: 'Turtleneck', vietnamese: 'Áo cổ lọ', pronunciation: 'ao co lo', category: 'clothing', chapter: 'chapter17', difficulty: 1, examples: ['Turtleneck keeps neck warm.'] },
  { id: 'clothing20', english: 'Blazer', vietnamese: 'Áo blazer', pronunciation: 'ao blazer', category: 'clothing', chapter: 'chapter17', difficulty: 1, examples: ['Navy blazer formal.'] },
  { id: 'clothing21', english: 'Suit', vietnamese: 'Bộ vest', pronunciation: 'bo vest', category: 'clothing', chapter: 'chapter17', difficulty: 1, examples: ['Business suit required.'] },
  { id: 'clothing22', english: 'Uniform', vietnamese: 'Đồng phục', pronunciation: 'dong phuc', category: 'clothing', chapter: 'chapter17', difficulty: 1, examples: ['School uniform mandatory.'] },
  { id: 'clothing23', english: 'Pajamas', vietnamese: 'Đồ ngủ', pronunciation: 'do ngu', category: 'clothing', chapter: 'chapter17', difficulty: 1, examples: ['Comfortable pajamas sleep.'] },
  { id: 'clothing24', english: 'Robe', vietnamese: 'Áo choàng tắm', pronunciation: 'ao choang tam', category: 'clothing', chapter: 'chapter17', difficulty: 1, examples: ['Soft robe after shower.'] },
  { id: 'clothing25', english: 'Jumpsuit', vietnamese: 'Jumpsuit', pronunciation: 'jumpsuit', category: 'clothing', chapter: 'chapter17', difficulty: 1, examples: ['Fashionable jumpsuit trend.'] },

  // Shoes & Footwear (25 words)
  { id: 'shoe1', english: 'Shoes', vietnamese: 'Giày', pronunciation: 'giay', category: 'footwear', chapter: 'chapter17', difficulty: 1, examples: ['Comfortable walking shoes.'] },
  { id: 'shoe2', english: 'Sneakers', vietnamese: 'Giày thể thao', pronunciation: 'giay the thao', category: 'footwear', chapter: 'chapter17', difficulty: 1, examples: ['White sneakers clean.'] },
  { id: 'shoe3', english: 'Boots', vietnamese: 'Bốt', pronunciation: 'bot', category: 'footwear', chapter: 'chapter17', difficulty: 1, examples: ['Leather boots durable.'] },
  { id: 'shoe4', english: 'Sandals', vietnamese: 'Dép xăng đan', pronunciation: 'dep xang dan', category: 'footwear', chapter: 'chapter17', difficulty: 1, examples: ['Summer sandals breathable.'] },
  { id: 'shoe5', english: 'Flip-flops', vietnamese: 'Dép tông', pronunciation: 'dep tong', category: 'footwear', chapter: 'chapter17', difficulty: 1, examples: ['Beach flip-flops convenient.'] },
  { id: 'shoe6', english: 'Slippers', vietnamese: 'Dép trong nhà', pronunciation: 'dep trong nha', category: 'footwear', chapter: 'chapter17', difficulty: 1, examples: ['Warm slippers cozy.'] },
  { id: 'shoe7', english: 'High heels', vietnamese: 'Giày cao gót', pronunciation: 'giay cao got', category: 'footwear', chapter: 'chapter17', difficulty: 1, examples: ['High heels elegant.'] },
  { id: 'shoe8', english: 'Flats', vietnamese: 'Giày bệt', pronunciation: 'giay bet', category: 'footwear', chapter: 'chapter17', difficulty: 1, examples: ['Ballet flats comfortable.'] },
  { id: 'shoe9', english: 'Loafers', vietnamese: 'Giày lười', pronunciation: 'giay luoi', category: 'footwear', chapter: 'chapter17', difficulty: 1, examples: ['Leather loafers professional.'] },
  { id: 'shoe10', english: 'Oxfords', vietnamese: 'Giày oxford', pronunciation: 'giay oxford', category: 'footwear', chapter: 'chapter17', difficulty: 2, examples: ['Classic oxford shoes.'] },
  { id: 'shoe11', english: 'Pumps', vietnamese: 'Giày pump', pronunciation: 'giay pump', category: 'footwear', chapter: 'chapter17', difficulty: 2, examples: ['Black pumps formal.'] },
  { id: 'shoe12', english: 'Wedges', vietnamese: 'Giày đế xuồng', pronunciation: 'giay de xuong', category: 'footwear', chapter: 'chapter17', difficulty: 1, examples: ['Wedge sandals stable.'] },
  { id: 'shoe13', english: 'Clogs', vietnamese: 'Giày clog', pronunciation: 'giay clog', category: 'footwear', chapter: 'chapter17', difficulty: 2, examples: ['Wooden clogs traditional.'] },
  { id: 'shoe14', english: 'Moccasins', vietnamese: 'Giày moccasin', pronunciation: 'giay moccasin', category: 'footwear', chapter: 'chapter17', difficulty: 2, examples: ['Soft moccasins comfortable.'] },
  { id: 'shoe15', english: 'Espadrilles', vietnamese: 'Giày espadrille', pronunciation: 'giay espadrille', category: 'footwear', chapter: 'chapter17', difficulty: 2, examples: ['Summer espadrilles stylish.'] },
  { id: 'shoe16', english: 'Rain boots', vietnamese: 'Ủng đi mưa', pronunciation: 'ung di mua', category: 'footwear', chapter: 'chapter17', difficulty: 1, examples: ['Rain boots waterproof.'] },
  { id: 'shoe17', english: 'Hiking boots', vietnamese: 'Giày leo núi', pronunciation: 'giay leo nui', category: 'footwear', chapter: 'chapter17', difficulty: 1, examples: ['Hiking boots sturdy.'] },
  { id: 'shoe18', english: 'Running shoes', vietnamese: 'Giày chạy bộ', pronunciation: 'giay chay bo', category: 'footwear', chapter: 'chapter17', difficulty: 1, examples: ['Running shoes lightweight.'] },
  { id: 'shoe19', english: 'Dress shoes', vietnamese: 'Giày tây', pronunciation: 'giay tay', category: 'footwear', chapter: 'chapter17', difficulty: 1, examples: ['Dress shoes formal events.'] },
  { id: 'shoe20', english: 'Work boots', vietnamese: 'Giày bảo hộ', pronunciation: 'giay bao ho', category: 'footwear', chapter: 'chapter17', difficulty: 1, examples: ['Work boots safety.'] },
  { id: 'shoe21', english: 'Snow boots', vietnamese: 'Giày tuyết', pronunciation: 'giay tuyet', category: 'footwear', chapter: 'chapter17', difficulty: 1, examples: ['Snow boots warm.'] },
  { id: 'shoe22', english: 'Socks', vietnamese: 'Tất', pronunciation: 'tat', category: 'footwear', chapter: 'chapter17', difficulty: 1, examples: ['Clean socks daily.'] },
  { id: 'shoe23', english: 'Stockings', vietnamese: 'Vớ dài', pronunciation: 'vo dai', category: 'footwear', chapter: 'chapter17', difficulty: 1, examples: ['Silk stockings elegant.'] },
  { id: 'shoe24', english: 'Tights', vietnamese: 'Quần tất', pronunciation: 'quan tat', category: 'footwear', chapter: 'chapter17', difficulty: 1, examples: ['Black tights formal.'] },
  { id: 'shoe25', english: 'Ankle socks', vietnamese: 'Tất cổ ngắn', pronunciation: 'tat co ngan', category: 'footwear', chapter: 'chapter17', difficulty: 1, examples: ['Ankle socks sporty.'] },

  // Accessories (25 words)
  { id: 'accessory1', english: 'Hat', vietnamese: 'Mũ', pronunciation: 'mu', category: 'accessory', chapter: 'chapter17', difficulty: 1, examples: ['Sun hat protects.'] },
  { id: 'accessory2', english: 'Cap', vietnamese: 'Nón', pronunciation: 'non', category: 'accessory', chapter: 'chapter17', difficulty: 1, examples: ['Baseball cap casual.'] },
  { id: 'accessory3', english: 'Scarf', vietnamese: 'Khăn quàng', pronunciation: 'khan quang', category: 'accessory', chapter: 'chapter17', difficulty: 1, examples: ['Wool scarf warm.'] },
  { id: 'accessory4', english: 'Gloves', vietnamese: 'Găng tay', pronunciation: 'gang tay', category: 'accessory', chapter: 'chapter17', difficulty: 1, examples: ['Leather gloves elegant.'] },
  { id: 'accessory5', english: 'Belt', vietnamese: 'Thắt lưng', pronunciation: 'that lung', category: 'accessory', chapter: 'chapter17', difficulty: 1, examples: ['Black belt matches.'] },
  { id: 'accessory6', english: 'Tie', vietnamese: 'Cà vạt', pronunciation: 'ca vat', category: 'accessory', chapter: 'chapter17', difficulty: 1, examples: ['Silk tie formal.'] },
  { id: 'accessory7', english: 'Bow tie', vietnamese: 'Nơ cổ', pronunciation: 'no co', category: 'accessory', chapter: 'chapter17', difficulty: 1, examples: ['Bow tie elegant.'] },
  { id: 'accessory8', english: 'Watch', vietnamese: 'Đồng hồ', pronunciation: 'dong ho', category: 'accessory', chapter: 'chapter17', difficulty: 1, examples: ['Gold watch expensive.'] },
  { id: 'accessory9', english: 'Jewelry', vietnamese: 'Trang sức', pronunciation: 'trang suc', category: 'accessory', chapter: 'chapter17', difficulty: 1, examples: ['Diamond jewelry sparkles.'] },
  { id: 'accessory10', english: 'Necklace', vietnamese: 'Dây chuyền', pronunciation: 'day chuyen', category: 'accessory', chapter: 'chapter17', difficulty: 1, examples: ['Pearl necklace classic.'] },
  { id: 'accessory11', english: 'Earrings', vietnamese: 'Bông tai', pronunciation: 'bong tai', category: 'accessory', chapter: 'chapter17', difficulty: 1, examples: ['Silver earrings shine.'] },
  { id: 'accessory12', english: 'Bracelet', vietnamese: 'Vòng tay', pronunciation: 'vong tay', category: 'accessory', chapter: 'chapter17', difficulty: 1, examples: ['Gold bracelet beautiful.'] },
  { id: 'accessory13', english: 'Ring', vietnamese: 'Nhẫn', pronunciation: 'nhan', category: 'accessory', chapter: 'chapter17', difficulty: 1, examples: ['Wedding ring symbol.'] },
  { id: 'accessory14', english: 'Sunglasses', vietnamese: 'Kính râm', pronunciation: 'kinh ram', category: 'accessory', chapter: 'chapter17', difficulty: 1, examples: ['Sunglasses protect eyes.'] },
  { id: 'accessory15', english: 'Glasses', vietnamese: 'Kính mắt', pronunciation: 'kinh mat', category: 'accessory', chapter: 'chapter17', difficulty: 1, examples: ['Reading glasses helpful.'] },
  { id: 'accessory16', english: 'Bag', vietnamese: 'Túi', pronunciation: 'tui', category: 'accessory', chapter: 'chapter17', difficulty: 1, examples: ['Leather bag durable.'] },
  { id: 'accessory17', english: 'Purse', vietnamese: 'Túi xách', pronunciation: 'tui xach', category: 'accessory', chapter: 'chapter17', difficulty: 1, examples: ['Designer purse expensive.'] },
  { id: 'accessory18', english: 'Backpack', vietnamese: 'Ba lô', pronunciation: 'ba lo', category: 'accessory', chapter: 'chapter17', difficulty: 1, examples: ['School backpack heavy.'] },
  { id: 'accessory19', english: 'Wallet', vietnamese: 'Ví', pronunciation: 'vi', category: 'accessory', chapter: 'chapter17', difficulty: 1, examples: ['Wallet holds money.'] },
  { id: 'accessory20', english: 'Handkerchief', vietnamese: 'Khăn tay', pronunciation: 'khan tay', category: 'accessory', chapter: 'chapter17', difficulty: 1, examples: ['Cotton handkerchief soft.'] },
  { id: 'accessory21', english: 'Umbrella', vietnamese: 'Ô', pronunciation: 'o', category: 'accessory', chapter: 'chapter17', difficulty: 1, examples: ['Umbrella protects rain.'] },
  { id: 'accessory22', english: 'Cufflinks', vietnamese: 'Khuy măng sét', pronunciation: 'khuy mang set', category: 'accessory', chapter: 'chapter17', difficulty: 2, examples: ['Gold cufflinks formal.'] },
  { id: 'accessory23', english: 'Pin', vietnamese: 'Ghim cài áo', pronunciation: 'ghim cai ao', category: 'accessory', chapter: 'chapter17', difficulty: 1, examples: ['Decorative pin stylish.'] },
  { id: 'accessory24', english: 'Badge', vietnamese: 'Huy hiệu', pronunciation: 'huy hieu', category: 'accessory', chapter: 'chapter17', difficulty: 1, examples: ['Name badge identification.'] },
  { id: 'accessory25', english: 'Hair tie', vietnamese: 'Dây buộc tóc', pronunciation: 'day buoc toc', category: 'accessory', chapter: 'chapter17', difficulty: 1, examples: ['Hair tie keeps neat.'] },

  // Fashion & Style Terms (25 words)
  { id: 'fashion1', english: 'Fashion', vietnamese: 'Thời trang', pronunciation: 'thoi trang', category: 'fashion', chapter: 'chapter17', difficulty: 1, examples: ['Fashion trends change.'] },
  { id: 'fashion2', english: 'Style', vietnamese: 'Phong cách', pronunciation: 'phong cach', category: 'fashion', chapter: 'chapter17', difficulty: 1, examples: ['Personal style unique.'] },
  { id: 'fashion3', english: 'Trendy', vietnamese: 'Hợp thời trang', pronunciation: 'hop thoi trang', category: 'fashion', chapter: 'chapter17', difficulty: 1, examples: ['Trendy outfit popular.'] },
  { id: 'fashion4', english: 'Fashionable', vietnamese: 'Thời trang', pronunciation: 'thoi trang', category: 'fashion', chapter: 'chapter17', difficulty: 1, examples: ['Fashionable dress attracts.'] },
  { id: 'fashion5', english: 'Stylish', vietnamese: 'Sành điệu', pronunciation: 'sanh dieu', category: 'fashion', chapter: 'chapter17', difficulty: 1, examples: ['Stylish appearance impressive.'] },
  { id: 'fashion6', english: 'Elegant', vietnamese: 'Thanh lịch', pronunciation: 'thanh lich', category: 'fashion', chapter: 'chapter17', difficulty: 1, examples: ['Elegant evening gown.'] },
  { id: 'fashion7', english: 'Casual', vietnamese: 'Thường ngày', pronunciation: 'thuong ngay', category: 'fashion', chapter: 'chapter17', difficulty: 1, examples: ['Casual Friday dress.'] },
  { id: 'fashion8', english: 'Formal', vietnamese: 'Trang trọng', pronunciation: 'trang trong', category: 'fashion', chapter: 'chapter17', difficulty: 1, examples: ['Formal dinner attire.'] },
  { id: 'fashion9', english: 'Professional', vietnamese: 'Chuyên nghiệp', pronunciation: 'chuyen nghiep', category: 'fashion', chapter: 'chapter17', difficulty: 1, examples: ['Professional business look.'] },
  { id: 'fashion10', english: 'Sporty', vietnamese: 'Thể thao', pronunciation: 'the thao', category: 'fashion', chapter: 'chapter17', difficulty: 1, examples: ['Sporty outfit comfortable.'] },
  { id: 'fashion11', english: 'Vintage', vietnamese: 'Cổ điển', pronunciation: 'co dien', category: 'fashion', chapter: 'chapter17', difficulty: 1, examples: ['Vintage dress classic.'] },
  { id: 'fashion12', english: 'Modern', vietnamese: 'Hiện đại', pronunciation: 'hien dai', category: 'fashion', chapter: 'chapter17', difficulty: 1, examples: ['Modern design innovative.'] },
  { id: 'fashion13', english: 'Classic', vietnamese: 'Cổ điển', pronunciation: 'co dien', category: 'fashion', chapter: 'chapter17', difficulty: 1, examples: ['Classic style timeless.'] },
  { id: 'fashion14', english: 'Chic', vietnamese: 'Sang trọng', pronunciation: 'sang trong', category: 'fashion', chapter: 'chapter17', difficulty: 2, examples: ['Chic outfit sophisticated.'] },
  { id: 'fashion15', english: 'Trendsetter', vietnamese: 'Người dẫn đầu xu hướng', pronunciation: 'nguoi dan dau xu huong', category: 'fashion', chapter: 'chapter17', difficulty: 2, examples: ['Fashion trendsetter influential.'] },
  { id: 'fashion16', english: 'Outfit', vietnamese: 'Trang phục', pronunciation: 'trang phuc', category: 'fashion', chapter: 'chapter17', difficulty: 1, examples: ['Complete outfit coordinated.'] },
  { id: 'fashion17', english: 'Wardrobe', vietnamese: 'Tủ quần áo', pronunciation: 'tu quan ao', category: 'fashion', chapter: 'chapter17', difficulty: 1, examples: ['Organized wardrobe helpful.'] },
  { id: 'fashion18', english: 'Closet', vietnamese: 'Tủ đồ', pronunciation: 'tu do', category: 'fashion', chapter: 'chapter17', difficulty: 1, examples: ['Walk-in closet spacious.'] },
  { id: 'fashion19', english: 'Designer', vietnamese: 'Nhà thiết kế', pronunciation: 'nha thiet ke', category: 'fashion', chapter: 'chapter17', difficulty: 1, examples: ['Famous designer creates.'] },
  { id: 'fashion20', english: 'Brand', vietnamese: 'Thương hiệu', pronunciation: 'thuong hieu', category: 'fashion', chapter: 'chapter17', difficulty: 1, examples: ['Luxury brand expensive.'] },
  { id: 'fashion21', english: 'Label', vietnamese: 'Nhãn hiệu', pronunciation: 'nhan hieu', category: 'fashion', chapter: 'chapter17', difficulty: 1, examples: ['Designer label prestigious.'] },
  { id: 'fashion22', english: 'Fabric', vietnamese: 'Vải', pronunciation: 'vai', category: 'fashion', chapter: 'chapter17', difficulty: 1, examples: ['Silk fabric luxurious.'] },
  { id: 'fashion23', english: 'Material', vietnamese: 'Chất liệu', pronunciation: 'chat lieu', category: 'fashion', chapter: 'chapter17', difficulty: 1, examples: ['Cotton material breathable.'] },
  { id: 'fashion24', english: 'Texture', vietnamese: 'Kết cấu', pronunciation: 'ket cau', category: 'fashion', chapter: 'chapter17', difficulty: 1, examples: ['Smooth texture pleasant.'] },
  { id: 'fashion25', english: 'Pattern', vietnamese: 'Họa tiết', pronunciation: 'hoa tiet', category: 'fashion', chapter: 'chapter17', difficulty: 1, examples: ['Floral pattern feminine.'] }
]
