// Chapter 3: Food & Drink (100 Essential Words)
// Words related to food, beverages, cooking, and dining

import { LanguageWord } from './chapter01-basic-everyday'

export const chapter03Words: LanguageWord[] = [
  // Basic Foods (25 words)
  { id: 'food1', english: 'Food', vietnamese: 'Thức ăn', pronunciation: 'thuc an', category: 'food', chapter: 'chapter03', difficulty: 1, examples: ['I love Vietnamese food.'] },
  { id: 'food2', english: 'Rice', vietnamese: 'Cơm', pronunciation: 'com', category: 'food', chapter: 'chapter03', difficulty: 1, examples: ['Rice is the main food in Vietnam.'] },
  { id: 'food3', english: 'Bread', vietnamese: 'Bánh mì', pronunciation: 'banh mi', category: 'food', chapter: 'chapter03', difficulty: 1, examples: ['Vietnamese bread is delicious.'] },
  { id: 'food4', english: 'Noodles', vietnamese: 'Mì', pronunciation: 'mi', category: 'food', chapter: 'chapter03', difficulty: 1, examples: ['Pho noodles are famous.'] },
  { id: 'food5', english: 'Meat', vietnamese: 'Thịt', pronunciation: 'thit', category: 'food', chapter: 'chapter03', difficulty: 1, examples: ['This meat is fresh.'] },
  { id: 'food6', english: 'Chicken', vietnamese: 'Thịt gà', pronunciation: 'thit ga', category: 'food', chapter: 'chapter03', difficulty: 1, examples: ['Chicken curry is spicy.'] },
  { id: 'food7', english: 'Beef', vietnamese: 'Thịt bò', pronunciation: 'thit bo', category: 'food', chapter: 'chapter03', difficulty: 1, examples: ['Beef noodle soup is popular.'] },
  { id: 'food8', english: 'Pork', vietnamese: 'Thịt heo', pronunciation: 'thit heo', category: 'food', chapter: 'chapter03', difficulty: 1, examples: ['Pork is common in Vietnamese cuisine.'] },
  { id: 'food9', english: 'Fish', vietnamese: 'Cá', pronunciation: 'ca', category: 'food', chapter: 'chapter03', difficulty: 1, examples: ['Fresh fish from the market.'] },
  { id: 'food10', english: 'Shrimp', vietnamese: 'Tôm', pronunciation: 'tom', category: 'food', chapter: 'chapter03', difficulty: 1, examples: ['Grilled shrimp is tasty.'] },
  { id: 'food11', english: 'Egg', vietnamese: 'Trứng', pronunciation: 'trung', category: 'food', chapter: 'chapter03', difficulty: 1, examples: ['Fried egg for breakfast.'] },
  { id: 'food12', english: 'Vegetable', vietnamese: 'Rau', pronunciation: 'rau', category: 'food', chapter: 'chapter03', difficulty: 1, examples: ['Eat more vegetables.'] },
  { id: 'food13', english: 'Fruit', vietnamese: 'Trái cây', pronunciation: 'chai cay', category: 'food', chapter: 'chapter03', difficulty: 1, examples: ['Tropical fruits are sweet.'] },
  { id: 'food14', english: 'Apple', vietnamese: 'Táo', pronunciation: 'tao', category: 'food', chapter: 'chapter03', difficulty: 1, examples: ['Red apple is crispy.'] },
  { id: 'food15', english: 'Banana', vietnamese: 'Chuối', pronunciation: 'chuoi', category: 'food', chapter: 'chapter03', difficulty: 1, examples: ['Banana is nutritious.'] },
  { id: 'food16', english: 'Orange', vietnamese: 'Cam', pronunciation: 'cam', category: 'food', chapter: 'chapter03', difficulty: 1, examples: ['Orange juice is refreshing.'] },
  { id: 'food17', english: 'Mango', vietnamese: 'Xoài', pronunciation: 'xoai', category: 'food', chapter: 'chapter03', difficulty: 1, examples: ['Mango is my favorite fruit.'] },
  { id: 'food18', english: 'Coconut', vietnamese: 'Dừa', pronunciation: 'dua', category: 'food', chapter: 'chapter03', difficulty: 1, examples: ['Coconut water is cooling.'] },
  { id: 'food19', english: 'Soup', vietnamese: 'Canh', pronunciation: 'canh', category: 'food', chapter: 'chapter03', difficulty: 1, examples: ['Hot soup on cold days.'] },
  { id: 'food20', english: 'Salad', vietnamese: 'Salad', pronunciation: 'salad', category: 'food', chapter: 'chapter03', difficulty: 1, examples: ['Fresh vegetable salad.'] },
  { id: 'food21', english: 'Cake', vietnamese: 'Bánh ngọt', pronunciation: 'banh ngot', category: 'food', chapter: 'chapter03', difficulty: 1, examples: ['Birthday cake is sweet.'] },
  { id: 'food22', english: 'Cookie', vietnamese: 'Bánh quy', pronunciation: 'banh quy', category: 'food', chapter: 'chapter03', difficulty: 1, examples: ['Chocolate cookies are popular.'] },
  { id: 'food23', english: 'Ice cream', vietnamese: 'Kem', pronunciation: 'kem', category: 'food', chapter: 'chapter03', difficulty: 1, examples: ['Ice cream on hot days.'] },
  { id: 'food24', english: 'Candy', vietnamese: 'Kẹo', pronunciation: 'keo', category: 'food', chapter: 'chapter03', difficulty: 1, examples: ['Children love candy.'] },
  { id: 'food25', english: 'Chocolate', vietnamese: 'Sô cô la', pronunciation: 'so co la', category: 'food', chapter: 'chapter03', difficulty: 1, examples: ['Dark chocolate is healthy.'] },

  // Drinks (20 words)
  { id: 'drink1', english: 'Water', vietnamese: 'Nước', pronunciation: 'nuoc', category: 'drink', chapter: 'chapter03', difficulty: 1, examples: ['Drink more water daily.'] },
  { id: 'drink2', english: 'Tea', vietnamese: 'Trà', pronunciation: 'tra', category: 'drink', chapter: 'chapter03', difficulty: 1, examples: ['Green tea is healthy.'] },
  { id: 'drink3', english: 'Coffee', vietnamese: 'Cà phê', pronunciation: 'ca phe', category: 'drink', chapter: 'chapter03', difficulty: 1, examples: ['Vietnamese coffee is strong.'] },
  { id: 'drink4', english: 'Milk', vietnamese: 'Sữa', pronunciation: 'sua', category: 'drink', chapter: 'chapter03', difficulty: 1, examples: ['Fresh milk for breakfast.'] },
  { id: 'drink5', english: 'Juice', vietnamese: 'Nước ép', pronunciation: 'nuoc ep', category: 'drink', chapter: 'chapter03', difficulty: 1, examples: ['Orange juice is vitamin-rich.'] },
  { id: 'drink6', english: 'Soda', vietnamese: 'Nước ngọt', pronunciation: 'nuoc ngot', category: 'drink', chapter: 'chapter03', difficulty: 1, examples: ['Soda is not healthy.'] },
  { id: 'drink7', english: 'Beer', vietnamese: 'Bia', pronunciation: 'bia', category: 'drink', chapter: 'chapter03', difficulty: 1, examples: ['Cold beer on hot days.'] },
  { id: 'drink8', english: 'Wine', vietnamese: 'Rượu vang', pronunciation: 'ruou vang', category: 'drink', chapter: 'chapter03', difficulty: 1, examples: ['Wine with dinner.'] },
  { id: 'drink9', english: 'Smoothie', vietnamese: 'Sinh tố', pronunciation: 'sinh to', category: 'drink', chapter: 'chapter03', difficulty: 1, examples: ['Fruit smoothie is nutritious.'] },
  { id: 'drink10', english: 'Coconut water', vietnamese: 'Nước dừa', pronunciation: 'nuoc dua', category: 'drink', chapter: 'chapter03', difficulty: 1, examples: ['Coconut water is refreshing.'] },
  { id: 'drink11', english: 'Lemonade', vietnamese: 'Nước chanh', pronunciation: 'nuoc chanh', category: 'drink', chapter: 'chapter03', difficulty: 1, examples: ['Fresh lemonade in summer.'] },
  { id: 'drink12', english: 'Hot chocolate', vietnamese: 'Sô cô la nóng', pronunciation: 'so co la nong', category: 'drink', chapter: 'chapter03', difficulty: 1, examples: ['Hot chocolate in winter.'] },
  { id: 'drink13', english: 'Energy drink', vietnamese: 'Nước tăng lực', pronunciation: 'nuoc tang luc', category: 'drink', chapter: 'chapter03', difficulty: 1, examples: ['Energy drink for studying.'] },
  { id: 'drink14', english: 'Iced tea', vietnamese: 'Trà đá', pronunciation: 'tra da', category: 'drink', chapter: 'chapter03', difficulty: 1, examples: ['Iced tea is popular.'] },
  { id: 'drink15', english: 'Bubble tea', vietnamese: 'Trà sữa', pronunciation: 'tra sua', category: 'drink', chapter: 'chapter03', difficulty: 1, examples: ['Bubble tea is trendy.'] },
  { id: 'drink16', english: 'Sparkling water', vietnamese: 'Nước có ga', pronunciation: 'nuoc co ga', category: 'drink', chapter: 'chapter03', difficulty: 1, examples: ['Sparkling water with lemon.'] },
  { id: 'drink17', english: 'Sports drink', vietnamese: 'Nước thể thao', pronunciation: 'nuoc the thao', category: 'drink', chapter: 'chapter03', difficulty: 1, examples: ['Sports drink after exercise.'] },
  { id: 'drink18', english: 'Cocktail', vietnamese: 'Cocktail', pronunciation: 'cocktail', category: 'drink', chapter: 'chapter03', difficulty: 1, examples: ['Cocktail at the party.'] },
  { id: 'drink19', english: 'Shake', vietnamese: 'Nước lắc', pronunciation: 'nuoc lac', category: 'drink', chapter: 'chapter03', difficulty: 1, examples: ['Protein shake after workout.'] },
  { id: 'drink20', english: 'Herbal tea', vietnamese: 'Trà thảo mộc', pronunciation: 'tra thao moc', category: 'drink', chapter: 'chapter03', difficulty: 1, examples: ['Herbal tea for relaxation.'] },

  // Cooking & Kitchen (25 words)
  { id: 'cooking1', english: 'Cook', vietnamese: 'Nấu ăn', pronunciation: 'nau an', category: 'cooking', chapter: 'chapter03', difficulty: 1, examples: ['I cook dinner every day.'] },
  { id: 'cooking2', english: 'Kitchen', vietnamese: 'Nhà bếp', pronunciation: 'nha bep', category: 'cooking', chapter: 'chapter03', difficulty: 1, examples: ['Clean kitchen after cooking.'] },
  { id: 'cooking3', english: 'Recipe', vietnamese: 'Công thức', pronunciation: 'cong thuc', category: 'cooking', chapter: 'chapter03', difficulty: 1, examples: ['Follow the recipe carefully.'] },
  { id: 'cooking4', english: 'Ingredient', vietnamese: 'Nguyên liệu', pronunciation: 'nguyen lieu', category: 'cooking', chapter: 'chapter03', difficulty: 1, examples: ['Fresh ingredients make good food.'] },
  { id: 'cooking5', english: 'Spice', vietnamese: 'Gia vị', pronunciation: 'za vi', category: 'cooking', chapter: 'chapter03', difficulty: 1, examples: ['Vietnamese food uses many spices.'] },
  { id: 'cooking6', english: 'Salt', vietnamese: 'Muối', pronunciation: 'muoi', category: 'cooking', chapter: 'chapter03', difficulty: 1, examples: ['Add salt to taste.'] },
  { id: 'cooking7', english: 'Sugar', vietnamese: 'Đường', pronunciation: 'duong', category: 'cooking', chapter: 'chapter03', difficulty: 1, examples: ['Sugar makes coffee sweet.'] },
  { id: 'cooking8', english: 'Oil', vietnamese: 'Dầu', pronunciation: 'dau', category: 'cooking', chapter: 'chapter03', difficulty: 1, examples: ['Use oil for frying.'] },
  { id: 'cooking9', english: 'Sauce', vietnamese: 'Nước chấm', pronunciation: 'nuoc cham', category: 'cooking', chapter: 'chapter03', difficulty: 1, examples: ['Fish sauce is essential.'] },
  { id: 'cooking10', english: 'Pepper', vietnamese: 'Tiêu', pronunciation: 'tieu', category: 'cooking', chapter: 'chapter03', difficulty: 1, examples: ['Black pepper adds flavor.'] },
  { id: 'cooking11', english: 'Garlic', vietnamese: 'Tỏi', pronunciation: 'toi', category: 'cooking', chapter: 'chapter03', difficulty: 1, examples: ['Garlic makes food aromatic.'] },
  { id: 'cooking12', english: 'Onion', vietnamese: 'Hành', pronunciation: 'hanh', category: 'cooking', chapter: 'chapter03', difficulty: 1, examples: ['Onion makes me cry.'] },
  { id: 'cooking13', english: 'Ginger', vietnamese: 'Gừng', pronunciation: 'gung', category: 'cooking', chapter: 'chapter03', difficulty: 1, examples: ['Ginger tea is warming.'] },
  { id: 'cooking14', english: 'Lemon', vietnamese: 'Chanh', pronunciation: 'chanh', category: 'cooking', chapter: 'chapter03', difficulty: 1, examples: ['Lemon adds freshness.'] },
  { id: 'cooking15', english: 'Herb', vietnamese: 'Thảo mộc', pronunciation: 'thao moc', category: 'cooking', chapter: 'chapter03', difficulty: 1, examples: ['Fresh herbs in pho.'] },
  { id: 'cooking16', english: 'Pot', vietnamese: 'Nồi', pronunciation: 'noi', category: 'cooking', chapter: 'chapter03', difficulty: 1, examples: ['Cook rice in a pot.'] },
  { id: 'cooking17', english: 'Pan', vietnamese: 'Chảo', pronunciation: 'chao', category: 'cooking', chapter: 'chapter03', difficulty: 1, examples: ['Fry eggs in a pan.'] },
  { id: 'cooking18', english: 'Knife', vietnamese: 'Dao', pronunciation: 'dao', category: 'cooking', chapter: 'chapter03', difficulty: 1, examples: ['Sharp knife for cutting.'] },
  { id: 'cooking19', english: 'Spoon', vietnamese: 'Thìa', pronunciation: 'thia', category: 'cooking', chapter: 'chapter03', difficulty: 1, examples: ['Stir with a spoon.'] },
  { id: 'cooking20', english: 'Fork', vietnamese: 'Nĩa', pronunciation: 'nia', category: 'cooking', chapter: 'chapter03', difficulty: 1, examples: ['Eat with fork and knife.'] },
  { id: 'cooking21', english: 'Chopsticks', vietnamese: 'Đũa', pronunciation: 'dua', category: 'cooking', chapter: 'chapter03', difficulty: 1, examples: ['Use chopsticks for noodles.'] },
  { id: 'cooking22', english: 'Bowl', vietnamese: 'Bát', pronunciation: 'bat', category: 'cooking', chapter: 'chapter03', difficulty: 1, examples: ['Serve rice in a bowl.'] },
  { id: 'cooking23', english: 'Plate', vietnamese: 'Đĩa', pronunciation: 'dia', category: 'cooking', chapter: 'chapter03', difficulty: 1, examples: ['Put food on the plate.'] },
  { id: 'cooking24', english: 'Cup', vietnamese: 'Cốc', pronunciation: 'coc', category: 'cooking', chapter: 'chapter03', difficulty: 1, examples: ['Drink water from a cup.'] },
  { id: 'cooking25', english: 'Glass', vietnamese: 'Ly', pronunciation: 'ly', category: 'cooking', chapter: 'chapter03', difficulty: 1, examples: ['Wine glass for special occasions.'] },

  // Dining & Restaurant (15 words)
  { id: 'dining1', english: 'Restaurant', vietnamese: 'Nhà hàng', pronunciation: 'nha hang', category: 'dining', chapter: 'chapter03', difficulty: 1, examples: ['Eat at a nice restaurant.'] },
  { id: 'dining2', english: 'Menu', vietnamese: 'Thực đơn', pronunciation: 'thuc don', category: 'dining', chapter: 'chapter03', difficulty: 1, examples: ['Look at the menu first.'] },
  { id: 'dining3', english: 'Order', vietnamese: 'Gọi món', pronunciation: 'goi mon', category: 'dining', chapter: 'chapter03', difficulty: 1, examples: ['Order your favorite dish.'] },
  { id: 'dining4', english: 'Waiter', vietnamese: 'Phục vụ', pronunciation: 'phuc vu', category: 'dining', chapter: 'chapter03', difficulty: 1, examples: ['Call the waiter for service.'] },
  { id: 'dining5', english: 'Bill', vietnamese: 'Hóa đơn', pronunciation: 'hoa don', category: 'dining', chapter: 'chapter03', difficulty: 1, examples: ['Pay the bill after eating.'] },
  { id: 'dining6', english: 'Tip', vietnamese: 'Tiền típ', pronunciation: 'tien tip', category: 'dining', chapter: 'chapter03', difficulty: 1, examples: ['Leave a tip for good service.'] },
  { id: 'dining7', english: 'Reservation', vietnamese: 'Đặt bàn', pronunciation: 'dat ban', category: 'dining', chapter: 'chapter03', difficulty: 1, examples: ['Make a reservation for dinner.'] },
  { id: 'dining8', english: 'Table', vietnamese: 'Bàn', pronunciation: 'ban', category: 'dining', chapter: 'chapter03', difficulty: 1, examples: ['Sit at this table.'] },
  { id: 'dining9', english: 'Chair', vietnamese: 'Ghế', pronunciation: 'ghe', category: 'dining', chapter: 'chapter03', difficulty: 1, examples: ['Comfortable dining chair.'] },
  { id: 'dining10', english: 'Napkin', vietnamese: 'Khăn ăn', pronunciation: 'khan an', category: 'dining', chapter: 'chapter03', difficulty: 1, examples: ['Use napkin to clean hands.'] },
  { id: 'dining11', english: 'Takeaway', vietnamese: 'Mang về', pronunciation: 'mang ve', category: 'dining', chapter: 'chapter03', difficulty: 1, examples: ['Order takeaway for home.'] },
  { id: 'dining12', english: 'Delivery', vietnamese: 'Giao hàng', pronunciation: 'zao hang', category: 'dining', chapter: 'chapter03', difficulty: 1, examples: ['Food delivery to your door.'] },
  { id: 'dining13', english: 'Buffet', vietnamese: 'Tiệc buffet', pronunciation: 'tiec buffet', category: 'dining', chapter: 'chapter03', difficulty: 1, examples: ['All-you-can-eat buffet.'] },
  { id: 'dining14', english: 'Fast food', vietnamese: 'Thức ăn nhanh', pronunciation: 'thuc an nhanh', category: 'dining', chapter: 'chapter03', difficulty: 1, examples: ['Fast food is convenient.'] },
  { id: 'dining15', english: 'Street food', vietnamese: 'Thức ăn đường phố', pronunciation: 'thuc an duong pho', category: 'dining', chapter: 'chapter03', difficulty: 1, examples: ['Vietnamese street food is famous.'] },

  // Taste & Flavor (15 words)
  { id: 'taste1', english: 'Taste', vietnamese: 'Vị', pronunciation: 'vi', category: 'taste', chapter: 'chapter03', difficulty: 1, examples: ['This has a good taste.'] },
  { id: 'taste2', english: 'Sweet', vietnamese: 'Ngọt', pronunciation: 'ngot', category: 'taste', chapter: 'chapter03', difficulty: 1, examples: ['Cake is sweet.'], antonym: 'Bitter' },
  { id: 'taste3', english: 'Sour', vietnamese: 'Chua', pronunciation: 'chua', category: 'taste', chapter: 'chapter03', difficulty: 1, examples: ['Lemon is sour.'], antonym: 'Sweet' },
  { id: 'taste4', english: 'Bitter', vietnamese: 'Đắng', pronunciation: 'dang', category: 'taste', chapter: 'chapter03', difficulty: 1, examples: ['Coffee is bitter.'], antonym: 'Sweet' },
  { id: 'taste5', english: 'Salty', vietnamese: 'Mặn', pronunciation: 'man', category: 'taste', chapter: 'chapter03', difficulty: 1, examples: ['This soup is too salty.'] },
  { id: 'taste6', english: 'Spicy', vietnamese: 'Cay', pronunciation: 'cay', category: 'taste', chapter: 'chapter03', difficulty: 1, examples: ['Vietnamese food can be spicy.'], antonym: 'Mild' },
  { id: 'taste7', english: 'Hot', vietnamese: 'Nóng', pronunciation: 'nong', category: 'taste', chapter: 'chapter03', difficulty: 1, examples: ['Hot soup on cold days.'], antonym: 'Cold' },
  { id: 'taste8', english: 'Cold', vietnamese: 'Lạnh', pronunciation: 'lanh', category: 'taste', chapter: 'chapter03', difficulty: 1, examples: ['Cold ice cream in summer.'], antonym: 'Hot' },
  { id: 'taste9', english: 'Fresh', vietnamese: 'Tươi', pronunciation: 'tuoi', category: 'taste', chapter: 'chapter03', difficulty: 1, examples: ['Fresh vegetables from market.'], antonym: 'Stale' },
  { id: 'taste10', english: 'Delicious', vietnamese: 'Ngon', pronunciation: 'ngon', category: 'taste', chapter: 'chapter03', difficulty: 1, examples: ['This food is delicious.'], antonym: 'Disgusting' },
  { id: 'taste11', english: 'Tasty', vietnamese: 'Có vị', pronunciation: 'co vi', category: 'taste', chapter: 'chapter03', difficulty: 1, examples: ['Very tasty meal.'] },
  { id: 'taste12', english: 'Bland', vietnamese: 'Nhạt', pronunciation: 'nhat', category: 'taste', chapter: 'chapter03', difficulty: 1, examples: ['This food is too bland.'] },
  { id: 'taste13', english: 'Crispy', vietnamese: 'Giòn', pronunciation: 'gion', category: 'taste', chapter: 'chapter03', difficulty: 1, examples: ['Crispy fried chicken.'] },
  { id: 'taste14', english: 'Soft', vietnamese: 'Mềm', pronunciation: 'mem', category: 'taste', chapter: 'chapter03', difficulty: 1, examples: ['Soft bread for breakfast.'], antonym: 'Hard' },
  { id: 'taste15', english: 'Juicy', vietnamese: 'Nhiều nước', pronunciation: 'nhieu nuoc', category: 'taste', chapter: 'chapter03', difficulty: 1, examples: ['Juicy orange is refreshing.'] }
]
