// Chapter 31: Punctuation & Symbols (100 Essential Characters)
// Essential punctuation marks, symbols, and special characters for communication

import { LanguageWord } from './chapter01-basic-everyday'

export const chapter31Words: LanguageWord[] = [
  // Basic Punctuation (25 words)
  { id: 'punct1', english: 'Period', vietnamese: 'Dấu chấm', pronunciation: 'dau cham', category: 'punctuation', chapter: 'chapter31', difficulty: 1, examples: ['Period ends sentence.'] },
  { id: 'punct2', english: 'Comma', vietnamese: 'Dấu phẩy', pronunciation: 'dau phay', category: 'punctuation', chapter: 'chapter31', difficulty: 1, examples: ['Comma separates items.'] },
  { id: 'punct3', english: 'Question mark', vietnamese: 'Dấu hỏi', pronunciation: 'dau hoi', category: 'punctuation', chapter: 'chapter31', difficulty: 1, examples: ['Question mark asks.'] },
  { id: 'punct4', english: 'Exclamation point', vietnamese: 'Dấu chấm than', pronunciation: 'dau cham than', category: 'punctuation', chapter: 'chapter31', difficulty: 1, examples: ['Exclamation point shows emotion.'] },
  { id: 'punct5', english: 'Semicolon', vietnamese: 'Dấu chấm phẩy', pronunciation: 'dau cham phay', category: 'punctuation', chapter: 'chapter31', difficulty: 1, examples: ['Semicolon connects clauses.'] },
  { id: 'punct6', english: 'Colon', vietnamese: 'Dấu hai chấm', pronunciation: 'dau hai cham', category: 'punctuation', chapter: 'chapter31', difficulty: 1, examples: ['Colon introduces list.'] },
  { id: 'punct7', english: 'Apostrophe', vietnamese: 'Dấu nháy đơn', pronunciation: 'dau nhay don', category: 'punctuation', chapter: 'chapter31', difficulty: 1, examples: ['Apostrophe shows possession.'] },
  { id: 'punct8', english: 'Quotation marks', vietnamese: 'Dấu nháy kép', pronunciation: 'dau nhay kep', category: 'punctuation', chapter: 'chapter31', difficulty: 1, examples: ['Quotation marks quote speech.'] },
  { id: 'punct9', english: 'Hyphen', vietnamese: 'Dấu gạch ngang', pronunciation: 'dau gach ngang', category: 'punctuation', chapter: 'chapter31', difficulty: 1, examples: ['Hyphen connects words.'] },
  { id: 'punct10', english: 'Dash', vietnamese: 'Dấu gạch dài', pronunciation: 'dau gach dai', category: 'punctuation', chapter: 'chapter31', difficulty: 1, examples: ['Dash shows pause.'] },
  { id: 'punct11', english: 'Parentheses', vietnamese: 'Dấu ngoặc đơn', pronunciation: 'dau ngoac don', category: 'punctuation', chapter: 'chapter31', difficulty: 1, examples: ['Parentheses add information.'] },
  { id: 'punct12', english: 'Brackets', vietnamese: 'Dấu ngoặc vuông', pronunciation: 'dau ngoac vuong', category: 'punctuation', chapter: 'chapter31', difficulty: 1, examples: ['Brackets modify text.'] },
  { id: 'punct13', english: 'Braces', vietnamese: 'Dấu ngoặc nhọn', pronunciation: 'dau ngoac nhon', category: 'punctuation', chapter: 'chapter31', difficulty: 1, examples: ['Braces group items.'] },
  { id: 'punct14', english: 'Slash', vietnamese: 'Dấu gạch chéo', pronunciation: 'dau gach cheo', category: 'punctuation', chapter: 'chapter31', difficulty: 1, examples: ['Slash separates options.'] },
  { id: 'punct15', english: 'Backslash', vietnamese: 'Dấu gạch chéo ngược', pronunciation: 'dau gach cheo nguoc', category: 'punctuation', chapter: 'chapter31', difficulty: 1, examples: ['Backslash computer path.'] },
  { id: 'punct16', english: 'Underscore', vietnamese: 'Dấu gạch dưới', pronunciation: 'dau gach duoi', category: 'punctuation', chapter: 'chapter31', difficulty: 1, examples: ['Underscore connects words.'] },
  { id: 'punct17', english: 'Ellipsis', vietnamese: 'Dấu ba chấm', pronunciation: 'dau ba cham', category: 'punctuation', chapter: 'chapter31', difficulty: 1, examples: ['Ellipsis shows continuation.'] },
  { id: 'punct18', english: 'Asterisk', vietnamese: 'Dấu sao', pronunciation: 'dau sao', category: 'punctuation', chapter: 'chapter31', difficulty: 1, examples: ['Asterisk marks footnote.'] },
  { id: 'punct19', english: 'Ampersand', vietnamese: 'Dấu và', pronunciation: 'dau va', category: 'punctuation', chapter: 'chapter31', difficulty: 1, examples: ['Ampersand means and.'] },
  { id: 'punct20', english: 'Number sign', vietnamese: 'Dấu thăng', pronunciation: 'dau thang', category: 'punctuation', chapter: 'chapter31', difficulty: 1, examples: ['Number sign hashtag.'] },
  { id: 'punct21', english: 'Percent sign', vietnamese: 'Dấu phần trăm', pronunciation: 'dau phan tram', category: 'punctuation', chapter: 'chapter31', difficulty: 1, examples: ['Percent sign shows percentage.'] },
  { id: 'punct22', english: 'At sign', vietnamese: 'Dấu a còng', pronunciation: 'dau a cong', category: 'punctuation', chapter: 'chapter31', difficulty: 1, examples: ['At sign email address.'] },
  { id: 'punct23', english: 'Dollar sign', vietnamese: 'Dấu đô la', pronunciation: 'dau do la', category: 'punctuation', chapter: 'chapter31', difficulty: 1, examples: ['Dollar sign currency.'] },
  { id: 'punct24', english: 'Tilde', vietnamese: 'Dấu sóng', pronunciation: 'dau song', category: 'punctuation', chapter: 'chapter31', difficulty: 1, examples: ['Tilde approximation symbol.'] },
  { id: 'punct25', english: 'Caret', vietnamese: 'Dấu mũ', pronunciation: 'dau mu', category: 'punctuation', chapter: 'chapter31', difficulty: 1, examples: ['Caret insertion point.'] },

  // Mathematical Symbols (25 words)
  { id: 'math_sym1', english: 'Plus sign', vietnamese: 'Dấu cộng', pronunciation: 'dau cong', category: 'math_symbols', chapter: 'chapter31', difficulty: 1, examples: ['Plus sign addition.'] },
  { id: 'math_sym2', english: 'Minus sign', vietnamese: 'Dấu trừ', pronunciation: 'dau tru', category: 'math_symbols', chapter: 'chapter31', difficulty: 1, examples: ['Minus sign subtraction.'] },
  { id: 'math_sym3', english: 'Multiplication sign', vietnamese: 'Dấu nhân', pronunciation: 'dau nhan', category: 'math_symbols', chapter: 'chapter31', difficulty: 1, examples: ['Multiplication sign times.'] },
  { id: 'math_sym4', english: 'Division sign', vietnamese: 'Dấu chia', pronunciation: 'dau chia', category: 'math_symbols', chapter: 'chapter31', difficulty: 1, examples: ['Division sign divides.'] },
  { id: 'math_sym5', english: 'Equals sign', vietnamese: 'Dấu bằng', pronunciation: 'dau bang', category: 'math_symbols', chapter: 'chapter31', difficulty: 1, examples: ['Equals sign same value.'] },
  { id: 'math_sym6', english: 'Greater than', vietnamese: 'Lớn hơn', pronunciation: 'lon hon', category: 'math_symbols', chapter: 'chapter31', difficulty: 1, examples: ['Greater than comparison.'] },
  { id: 'math_sym7', english: 'Less than', vietnamese: 'Nhỏ hơn', pronunciation: 'nho hon', category: 'math_symbols', chapter: 'chapter31', difficulty: 1, examples: ['Less than comparison.'] },
  { id: 'math_sym8', english: 'Greater than or equal', vietnamese: 'Lớn hơn hoặc bằng', pronunciation: 'lon hon hoac bang', category: 'math_symbols', chapter: 'chapter31', difficulty: 2, examples: ['Greater than or equal.'] },
  { id: 'math_sym9', english: 'Less than or equal', vietnamese: 'Nhỏ hơn hoặc bằng', pronunciation: 'nho hon hoac bang', category: 'math_symbols', chapter: 'chapter31', difficulty: 2, examples: ['Less than or equal.'] },
  { id: 'math_sym10', english: 'Not equal', vietnamese: 'Không bằng', pronunciation: 'khong bang', category: 'math_symbols', chapter: 'chapter31', difficulty: 1, examples: ['Not equal different values.'] },
  { id: 'math_sym11', english: 'Approximately equal', vietnamese: 'Xấp xỉ bằng', pronunciation: 'xap xi bang', category: 'math_symbols', chapter: 'chapter31', difficulty: 2, examples: ['Approximately equal close values.'] },
  { id: 'math_sym12', english: 'Square root', vietnamese: 'Căn bậc hai', pronunciation: 'can bac hai', category: 'math_symbols', chapter: 'chapter31', difficulty: 1, examples: ['Square root mathematical operation.'] },
  { id: 'math_sym13', english: 'Infinity', vietnamese: 'Vô cực', pronunciation: 'vo cuc', category: 'math_symbols', chapter: 'chapter31', difficulty: 1, examples: ['Infinity endless amount.'] },
  { id: 'math_sym14', english: 'Pi', vietnamese: 'Số pi', pronunciation: 'so pi', category: 'math_symbols', chapter: 'chapter31', difficulty: 1, examples: ['Pi circle constant.'] },
  { id: 'math_sym15', english: 'Degree', vietnamese: 'Độ', pronunciation: 'do', category: 'math_symbols', chapter: 'chapter31', difficulty: 1, examples: ['Degree temperature angle.'] },
  { id: 'math_sym16', english: 'Parallel', vietnamese: 'Song song', pronunciation: 'song song', category: 'math_symbols', chapter: 'chapter31', difficulty: 1, examples: ['Parallel lines never meet.'] },
  { id: 'math_sym17', english: 'Perpendicular', vietnamese: 'Vuông góc', pronunciation: 'vuong goc', category: 'math_symbols', chapter: 'chapter31', difficulty: 1, examples: ['Perpendicular right angle.'] },
  { id: 'math_sym18', english: 'Angle', vietnamese: 'Góc', pronunciation: 'goc', category: 'math_symbols', chapter: 'chapter31', difficulty: 1, examples: ['Angle measurement symbol.'] },
  { id: 'math_sym19', english: 'Triangle', vietnamese: 'Tam giác', pronunciation: 'tam giac', category: 'math_symbols', chapter: 'chapter31', difficulty: 1, examples: ['Triangle three sides.'] },
  { id: 'math_sym20', english: 'Circle', vietnamese: 'Hình tròn', pronunciation: 'hinh tron', category: 'math_symbols', chapter: 'chapter31', difficulty: 1, examples: ['Circle round shape.'] },
  { id: 'math_sym21', english: 'Square', vietnamese: 'Hình vuông', pronunciation: 'hinh vuong', category: 'math_symbols', chapter: 'chapter31', difficulty: 1, examples: ['Square four equal sides.'] },
  { id: 'math_sym22', english: 'Rectangle', vietnamese: 'Hình chữ nhật', pronunciation: 'hinh chu nhat', category: 'math_symbols', chapter: 'chapter31', difficulty: 1, examples: ['Rectangle four right angles.'] },
  { id: 'math_sym23', english: 'Diamond', vietnamese: 'Hình thoi', pronunciation: 'hinh thoi', category: 'math_symbols', chapter: 'chapter31', difficulty: 1, examples: ['Diamond four equal sides.'] },
  { id: 'math_sym24', english: 'Star', vietnamese: 'Hình sao', pronunciation: 'hinh sao', category: 'math_symbols', chapter: 'chapter31', difficulty: 1, examples: ['Star pointed shape.'] },
  { id: 'math_sym25', english: 'Heart', vietnamese: 'Hình trái tim', pronunciation: 'hinh trai tim', category: 'math_symbols', chapter: 'chapter31', difficulty: 1, examples: ['Heart love symbol.'] },

  // Digital & Technology Symbols (25 words)
  { id: 'digital1', english: 'Emoji', vietnamese: 'Biểu tượng cảm xúc', pronunciation: 'bieu tuong cam xuc', category: 'digital', chapter: 'chapter31', difficulty: 1, examples: ['Emoji expresses feelings.'] },
  { id: 'digital2', english: 'Hashtag', vietnamese: 'Thẻ bắt đầu bằng thăng', pronunciation: 'the bat dau bang thang', category: 'digital', chapter: 'chapter31', difficulty: 1, examples: ['Hashtag social media tag.'] },
  { id: 'digital3', english: 'Mention', vietnamese: 'Nhắc đến', pronunciation: 'nhac den', category: 'digital', chapter: 'chapter31', difficulty: 1, examples: ['Mention tag someone.'] },
  { id: 'digital4', english: 'Link', vietnamese: 'Liên kết', pronunciation: 'lien ket', category: 'digital', chapter: 'chapter31', difficulty: 1, examples: ['Link connects pages.'] },
  { id: 'digital5', english: 'URL', vietnamese: 'Địa chỉ web', pronunciation: 'dia chi web', category: 'digital', chapter: 'chapter31', difficulty: 1, examples: ['URL website address.'] },
  { id: 'digital6', english: 'Email', vietnamese: 'Thư điện tử', pronunciation: 'thu dien tu', category: 'digital', chapter: 'chapter31', difficulty: 1, examples: ['Email electronic message.'] },
  { id: 'digital7', english: 'Password', vietnamese: 'Mật khẩu', pronunciation: 'mat khau', category: 'digital', chapter: 'chapter31', difficulty: 1, examples: ['Password secret code.'] },
  { id: 'digital8', english: 'Username', vietnamese: 'Tên người dùng', pronunciation: 'ten nguoi dung', category: 'digital', chapter: 'chapter31', difficulty: 1, examples: ['Username account name.'] },
  { id: 'digital9', english: 'Download', vietnamese: 'Tải xuống', pronunciation: 'tai xuong', category: 'digital', chapter: 'chapter31', difficulty: 1, examples: ['Download get file.'] },
  { id: 'digital10', english: 'Upload', vietnamese: 'Tải lên', pronunciation: 'tai len', category: 'digital', chapter: 'chapter31', difficulty: 1, examples: ['Upload send file.'] },
  { id: 'digital11', english: 'Share', vietnamese: 'Chia sẻ', pronunciation: 'chia se', category: 'digital', chapter: 'chapter31', difficulty: 1, examples: ['Share send others.'] },
  { id: 'digital12', english: 'Like', vietnamese: 'Thích', pronunciation: 'thich', category: 'digital', chapter: 'chapter31', difficulty: 1, examples: ['Like appreciate content.'] },
  { id: 'digital13', english: 'Comment', vietnamese: 'Bình luận', pronunciation: 'binh luan', category: 'digital', chapter: 'chapter31', difficulty: 1, examples: ['Comment add opinion.'] },
  { id: 'digital14', english: 'Follow', vietnamese: 'Theo dõi', pronunciation: 'theo doi', category: 'digital', chapter: 'chapter31', difficulty: 1, examples: ['Follow get updates.'] },
  { id: 'digital15', english: 'Subscribe', vietnamese: 'Đăng ký', pronunciation: 'dang ky', category: 'digital', chapter: 'chapter31', difficulty: 1, examples: ['Subscribe regular updates.'] },
  { id: 'digital16', english: 'Notification', vietnamese: 'Thông báo', pronunciation: 'thong bao', category: 'digital', chapter: 'chapter31', difficulty: 1, examples: ['Notification alert message.'] },
  { id: 'digital17', english: 'Settings', vietnamese: 'Cài đặt', pronunciation: 'cai dat', category: 'digital', chapter: 'chapter31', difficulty: 1, examples: ['Settings change options.'] },
  { id: 'digital18', english: 'Profile', vietnamese: 'Hồ sơ', pronunciation: 'ho so', category: 'digital', chapter: 'chapter31', difficulty: 1, examples: ['Profile personal information.'] },
  { id: 'digital19', english: 'Account', vietnamese: 'Tài khoản', pronunciation: 'tai khoan', category: 'digital', chapter: 'chapter31', difficulty: 1, examples: ['Account user registration.'] },
  { id: 'digital20', english: 'Login', vietnamese: 'Đăng nhập', pronunciation: 'dang nhap', category: 'digital', chapter: 'chapter31', difficulty: 1, examples: ['Login enter account.'] },
  { id: 'digital21', english: 'Logout', vietnamese: 'Đăng xuất', pronunciation: 'dang xuat', category: 'digital', chapter: 'chapter31', difficulty: 1, examples: ['Logout exit account.'] },
  { id: 'digital22', english: 'Backup', vietnamese: 'Sao lưu', pronunciation: 'sao luu', category: 'digital', chapter: 'chapter31', difficulty: 1, examples: ['Backup save copy.'] },
  { id: 'digital23', english: 'Delete', vietnamese: 'Xóa', pronunciation: 'xoa', category: 'digital', chapter: 'chapter31', difficulty: 1, examples: ['Delete remove permanently.'] },
  { id: 'digital24', english: 'Copy', vietnamese: 'Sao chép', pronunciation: 'sao chep', category: 'digital', chapter: 'chapter31', difficulty: 1, examples: ['Copy duplicate content.'] },
  { id: 'digital25', english: 'Paste', vietnamese: 'Dán', pronunciation: 'dan', category: 'digital', chapter: 'chapter31', difficulty: 1, examples: ['Paste insert copied.'] },

  // Currency & Financial Symbols (25 words)
  { id: 'currency1', english: 'Dollar', vietnamese: 'Đô la', pronunciation: 'do la', category: 'currency', chapter: 'chapter31', difficulty: 1, examples: ['Dollar US currency.'] },
  { id: 'currency2', english: 'Euro', vietnamese: 'Euro', pronunciation: 'euro', category: 'currency', chapter: 'chapter31', difficulty: 1, examples: ['Euro European currency.'] },
  { id: 'currency3', english: 'Pound', vietnamese: 'Bảng Anh', pronunciation: 'bang anh', category: 'currency', chapter: 'chapter31', difficulty: 1, examples: ['Pound British currency.'] },
  { id: 'currency4', english: 'Yen', vietnamese: 'Yên', pronunciation: 'yen', category: 'currency', chapter: 'chapter31', difficulty: 1, examples: ['Yen Japanese currency.'] },
  { id: 'currency5', english: 'Won', vietnamese: 'Won', pronunciation: 'won', category: 'currency', chapter: 'chapter31', difficulty: 1, examples: ['Won Korean currency.'] },
  { id: 'currency6', english: 'Yuan', vietnamese: 'Nhân dân tệ', pronunciation: 'nhan dan te', category: 'currency', chapter: 'chapter31', difficulty: 1, examples: ['Yuan Chinese currency.'] },
  { id: 'currency7', english: 'Dong', vietnamese: 'Đồng Việt Nam', pronunciation: 'dong viet nam', category: 'currency', chapter: 'chapter31', difficulty: 1, examples: ['Dong Vietnamese currency.'] },
  { id: 'currency8', english: 'Cent', vietnamese: 'Xu', pronunciation: 'xu', category: 'currency', chapter: 'chapter31', difficulty: 1, examples: ['Cent small currency.'] },
  { id: 'currency9', english: 'Penny', vietnamese: 'Xu', pronunciation: 'xu', category: 'currency', chapter: 'chapter31', difficulty: 1, examples: ['Penny one cent.'] },
  { id: 'currency10', english: 'Bitcoin', vietnamese: 'Bitcoin', pronunciation: 'bitcoin', category: 'currency', chapter: 'chapter31', difficulty: 1, examples: ['Bitcoin digital currency.'] },
  { id: 'currency11', english: 'Credit card', vietnamese: 'Thẻ tín dụng', pronunciation: 'the tin dung', category: 'currency', chapter: 'chapter31', difficulty: 1, examples: ['Credit card payment method.'] },
  { id: 'currency12', english: 'Debit card', vietnamese: 'Thẻ ghi nợ', pronunciation: 'the ghi no', category: 'currency', chapter: 'chapter31', difficulty: 1, examples: ['Debit card bank card.'] },
  { id: 'currency13', english: 'Cash', vietnamese: 'Tiền mặt', pronunciation: 'tien mat', category: 'currency', chapter: 'chapter31', difficulty: 1, examples: ['Cash physical money.'] },
  { id: 'currency14', english: 'Check', vietnamese: 'Séc', pronunciation: 'sec', category: 'currency', chapter: 'chapter31', difficulty: 1, examples: ['Check written payment.'] },
  { id: 'currency15', english: 'Receipt', vietnamese: 'Hóa đơn', pronunciation: 'hoa don', category: 'currency', chapter: 'chapter31', difficulty: 1, examples: ['Receipt payment proof.'] },
  { id: 'currency16', english: 'Invoice', vietnamese: 'Hóa đơn thanh toán', pronunciation: 'hoa don thanh toan', category: 'currency', chapter: 'chapter31', difficulty: 1, examples: ['Invoice payment request.'] },
  { id: 'currency17', english: 'Tax', vietnamese: 'Thuế', pronunciation: 'thue', category: 'currency', chapter: 'chapter31', difficulty: 1, examples: ['Tax government fee.'] },
  { id: 'currency18', english: 'Discount', vietnamese: 'Giảm giá', pronunciation: 'giam gia', category: 'currency', chapter: 'chapter31', difficulty: 1, examples: ['Discount reduced price.'] },
  { id: 'currency19', english: 'Sale', vietnamese: 'Khuyến mãi', pronunciation: 'khuyen mai', category: 'currency', chapter: 'chapter31', difficulty: 1, examples: ['Sale special price.'] },
  { id: 'currency20', english: 'Free', vietnamese: 'Miễn phí', pronunciation: 'mien phi', category: 'currency', chapter: 'chapter31', difficulty: 1, examples: ['Free no cost.'] },
  { id: 'currency21', english: 'Expensive', vietnamese: 'Đắt', pronunciation: 'dat', category: 'currency', chapter: 'chapter31', difficulty: 1, examples: ['Expensive high cost.'] },
  { id: 'currency22', english: 'Cheap', vietnamese: 'Rẻ', pronunciation: 're', category: 'currency', chapter: 'chapter31', difficulty: 1, examples: ['Cheap low cost.'] },
  { id: 'currency23', english: 'Price', vietnamese: 'Giá', pronunciation: 'gia', category: 'currency', chapter: 'chapter31', difficulty: 1, examples: ['Price cost amount.'] },
  { id: 'currency24', english: 'Cost', vietnamese: 'Chi phí', pronunciation: 'chi phi', category: 'currency', chapter: 'chapter31', difficulty: 1, examples: ['Cost required payment.'] },
  { id: 'currency25', english: 'Value', vietnamese: 'Giá trị', pronunciation: 'gia tri', category: 'currency', chapter: 'chapter31', difficulty: 1, examples: ['Value worth amount.'] }
]
