// Chapter 16: Colors & Descriptions (100 Essential Words)
// Words related to colors, visual appearance, and descriptive adjectives

import { LanguageWord } from './chapter01-basic-everyday'

export const chapter16Words: LanguageWord[] = [
  // Basic Colors (25 words)
  { id: 'color1', english: 'Color', vietnamese: 'Màu sắc', pronunciation: 'mau sac', category: 'color', chapter: 'chapter16', difficulty: 1, examples: ['Favorite color is blue.'] },
  { id: 'color2', english: 'Red', vietnamese: 'Đỏ', pronunciation: 'do', category: 'color', chapter: 'chapter16', difficulty: 1, examples: ['Red roses are beautiful.'] },
  { id: 'color3', english: 'Blue', vietnamese: 'Xanh dương', pronunciation: 'xanh duong', category: 'color', chapter: 'chapter16', difficulty: 1, examples: ['Blue sky today.'] },
  { id: 'color4', english: 'Green', vietnamese: 'Xanh lá', pronunciation: 'xanh la', category: 'color', chapter: 'chapter16', difficulty: 1, examples: ['Green grass grows.'] },
  { id: 'color5', english: 'Yellow', vietnamese: 'Vàng', pronunciation: 'vang', category: 'color', chapter: 'chapter16', difficulty: 1, examples: ['Yellow sunflowers bloom.'] },
  { id: 'color6', english: 'Orange', vietnamese: 'Cam', pronunciation: 'cam', category: 'color', chapter: 'chapter16', difficulty: 1, examples: ['Orange sunset beautiful.'] },
  { id: 'color7', english: 'Purple', vietnamese: 'Tím', pronunciation: 'tim', category: 'color', chapter: 'chapter16', difficulty: 1, examples: ['Purple dress elegant.'] },
  { id: 'color8', english: 'Pink', vietnamese: 'Hồng', pronunciation: 'hong', category: 'color', chapter: 'chapter16', difficulty: 1, examples: ['Pink cherry blossoms.'] },
  { id: 'color9', english: 'Brown', vietnamese: 'Nâu', pronunciation: 'nau', category: 'color', chapter: 'chapter16', difficulty: 1, examples: ['Brown wooden table.'] },
  { id: 'color10', english: 'Black', vietnamese: 'Đen', pronunciation: 'den', category: 'color', chapter: 'chapter16', difficulty: 1, examples: ['Black cat sleeps.'] },
  { id: 'color11', english: 'White', vietnamese: 'Trắng', pronunciation: 'trang', category: 'color', chapter: 'chapter16', difficulty: 1, examples: ['White snow falls.'] },
  { id: 'color12', english: 'Gray', vietnamese: 'Xám', pronunciation: 'xam', category: 'color', chapter: 'chapter16', difficulty: 1, examples: ['Gray clouds gather.'] },
  { id: 'color13', english: 'Silver', vietnamese: 'Bạc', pronunciation: 'bac', category: 'color', chapter: 'chapter16', difficulty: 1, examples: ['Silver jewelry shines.'] },
  { id: 'color14', english: 'Gold', vietnamese: 'Vàng óng', pronunciation: 'vang ong', category: 'color', chapter: 'chapter16', difficulty: 1, examples: ['Gold ring expensive.'] },
  { id: 'color15', english: 'Beige', vietnamese: 'Be', pronunciation: 'be', category: 'color', chapter: 'chapter16', difficulty: 1, examples: ['Beige walls neutral.'] },
  { id: 'color16', english: 'Maroon', vietnamese: 'Đỏ thẫm', pronunciation: 'do tham', category: 'color', chapter: 'chapter16', difficulty: 2, examples: ['Maroon curtains elegant.'] },
  { id: 'color17', english: 'Navy', vietnamese: 'Xanh navy', pronunciation: 'xanh navy', category: 'color', chapter: 'chapter16', difficulty: 1, examples: ['Navy blue uniform.'] },
  { id: 'color18', english: 'Turquoise', vietnamese: 'Xanh ngọc', pronunciation: 'xanh ngoc', category: 'color', chapter: 'chapter16', difficulty: 2, examples: ['Turquoise ocean water.'] },
  { id: 'color19', english: 'Violet', vietnamese: 'Tím violet', pronunciation: 'tim violet', category: 'color', chapter: 'chapter16', difficulty: 2, examples: ['Violet flowers fragrant.'] },
  { id: 'color20', english: 'Magenta', vietnamese: 'Đỏ tím', pronunciation: 'do tim', category: 'color', chapter: 'chapter16', difficulty: 2, examples: ['Magenta paint bright.'] },
  { id: 'color21', english: 'Cyan', vietnamese: 'Xanh lơ', pronunciation: 'xanh lo', category: 'color', chapter: 'chapter16', difficulty: 2, examples: ['Cyan ink cartridge.'] },
  { id: 'color22', english: 'Lime', vietnamese: 'Xanh chanh', pronunciation: 'xanh chanh', category: 'color', chapter: 'chapter16', difficulty: 2, examples: ['Lime green shirt.'] },
  { id: 'color23', english: 'Coral', vietnamese: 'Màu san hô', pronunciation: 'mau san ho', category: 'color', chapter: 'chapter16', difficulty: 2, examples: ['Coral reef colorful.'] },
  { id: 'color24', english: 'Salmon', vietnamese: 'Màu cá hồi', pronunciation: 'mau ca hoi', category: 'color', chapter: 'chapter16', difficulty: 2, examples: ['Salmon pink dress.'] },
  { id: 'color25', english: 'Tan', vietnamese: 'Màu nâu nhạt', pronunciation: 'mau nau nhat', category: 'color', chapter: 'chapter16', difficulty: 2, examples: ['Tan leather shoes.'] },

  // Visual Appearance (25 words)
  { id: 'visual1', english: 'Bright', vietnamese: 'Sáng', pronunciation: 'sang', category: 'visual', chapter: 'chapter16', difficulty: 1, examples: ['Bright sunshine today.'] },
  { id: 'visual2', english: 'Dark', vietnamese: 'Tối', pronunciation: 'toi', category: 'visual', chapter: 'chapter16', difficulty: 1, examples: ['Dark night sky.'] },
  { id: 'visual3', english: 'Light', vietnamese: 'Nhạt', pronunciation: 'nhat', category: 'visual', chapter: 'chapter16', difficulty: 1, examples: ['Light blue color.'] },
  { id: 'visual4', english: 'Deep', vietnamese: 'Đậm', pronunciation: 'dam', category: 'visual', chapter: 'chapter16', difficulty: 1, examples: ['Deep red wine.'] },
  { id: 'visual5', english: 'Pale', vietnamese: 'Nhợt', pronunciation: 'nhot', category: 'visual', chapter: 'chapter16', difficulty: 1, examples: ['Pale yellow moon.'] },
  { id: 'visual6', english: 'Vivid', vietnamese: 'Sống động', pronunciation: 'song dong', category: 'visual', chapter: 'chapter16', difficulty: 2, examples: ['Vivid colors attract.'] },
  { id: 'visual7', english: 'Dull', vietnamese: 'Mờ', pronunciation: 'mo', category: 'visual', chapter: 'chapter16', difficulty: 1, examples: ['Dull gray weather.'] },
  { id: 'visual8', english: 'Shiny', vietnamese: 'Sáng bóng', pronunciation: 'sang bong', category: 'visual', chapter: 'chapter16', difficulty: 1, examples: ['Shiny new car.'] },
  { id: 'visual9', english: 'Glossy', vietnamese: 'Bóng loáng', pronunciation: 'bong loang', category: 'visual', chapter: 'chapter16', difficulty: 1, examples: ['Glossy magazine cover.'] },
  { id: 'visual10', english: 'Matte', vietnamese: 'Mờ', pronunciation: 'mo', category: 'visual', chapter: 'chapter16', difficulty: 2, examples: ['Matte paint finish.'] },
  { id: 'visual11', english: 'Transparent', vietnamese: 'Trong suốt', pronunciation: 'trong suot', category: 'visual', chapter: 'chapter16', difficulty: 1, examples: ['Transparent glass window.'] },
  { id: 'visual12', english: 'Opaque', vietnamese: 'Đục', pronunciation: 'duc', category: 'visual', chapter: 'chapter16', difficulty: 2, examples: ['Opaque curtains block light.'] },
  { id: 'visual13', english: 'Clear', vietnamese: 'Trong', pronunciation: 'trong', category: 'visual', chapter: 'chapter16', difficulty: 1, examples: ['Clear water bottle.'] },
  { id: 'visual14', english: 'Cloudy', vietnamese: 'Vẩn đục', pronunciation: 'van duc', category: 'visual', chapter: 'chapter16', difficulty: 1, examples: ['Cloudy glass needs cleaning.'] },
  { id: 'visual15', english: 'Colorful', vietnamese: 'Nhiều màu', pronunciation: 'nhieu mau', category: 'visual', chapter: 'chapter16', difficulty: 1, examples: ['Colorful garden flowers.'] },
  { id: 'visual16', english: 'Colorless', vietnamese: 'Không màu', pronunciation: 'khong mau', category: 'visual', chapter: 'chapter16', difficulty: 1, examples: ['Colorless water pure.'] },
  { id: 'visual17', english: 'Faded', vietnamese: 'Phai màu', pronunciation: 'phai mau', category: 'visual', chapter: 'chapter16', difficulty: 1, examples: ['Faded old photograph.'] },
  { id: 'visual18', english: 'Fresh', vietnamese: 'Tươi', pronunciation: 'tuoi', category: 'visual', chapter: 'chapter16', difficulty: 1, examples: ['Fresh paint smell.'] },
  { id: 'visual19', english: 'Sparkly', vietnamese: 'Lấp lánh', pronunciation: 'lap lanh', category: 'visual', chapter: 'chapter16', difficulty: 1, examples: ['Sparkly diamond ring.'] },
  { id: 'visual20', english: 'Glittery', vietnamese: 'Kim tuyến', pronunciation: 'kim tuyen', category: 'visual', chapter: 'chapter16', difficulty: 1, examples: ['Glittery party dress.'] },
  { id: 'visual21', english: 'Metallic', vietnamese: 'Kim loại', pronunciation: 'kim loai', category: 'visual', chapter: 'chapter16', difficulty: 1, examples: ['Metallic silver paint.'] },
  { id: 'visual22', english: 'Neon', vietnamese: 'Neon', pronunciation: 'neon', category: 'visual', chapter: 'chapter16', difficulty: 1, examples: ['Neon sign bright.'] },
  { id: 'visual23', english: 'Fluorescent', vietnamese: 'Huỳnh quang', pronunciation: 'huynh quang', category: 'visual', chapter: 'chapter16', difficulty: 2, examples: ['Fluorescent office lighting.'] },
  { id: 'visual24', english: 'Iridescent', vietnamese: 'Óng ánh', pronunciation: 'ong anh', category: 'visual', chapter: 'chapter16', difficulty: 2, examples: ['Iridescent soap bubbles.'] },
  { id: 'visual25', english: 'Pearlescent', vietnamese: 'Ánh ngọc trai', pronunciation: 'anh ngoc trai', category: 'visual', chapter: 'chapter16', difficulty: 2, examples: ['Pearlescent car finish.'] },

  // Size & Shape Descriptions (25 words)
  { id: 'size1', english: 'Big', vietnamese: 'To', pronunciation: 'to', category: 'size', chapter: 'chapter16', difficulty: 1, examples: ['Big house comfortable.'] },
  { id: 'size2', english: 'Small', vietnamese: 'Nhỏ', pronunciation: 'nho', category: 'size', chapter: 'chapter16', difficulty: 1, examples: ['Small dog cute.'] },
  { id: 'size3', english: 'Large', vietnamese: 'Lớn', pronunciation: 'lon', category: 'size', chapter: 'chapter16', difficulty: 1, examples: ['Large pizza feeds many.'] },
  { id: 'size4', english: 'Tiny', vietnamese: 'Tí hon', pronunciation: 'ti hon', category: 'size', chapter: 'chapter16', difficulty: 1, examples: ['Tiny baby shoes.'] },
  { id: 'size5', english: 'Huge', vietnamese: 'Khổng lồ', pronunciation: 'khong lo', category: 'size', chapter: 'chapter16', difficulty: 1, examples: ['Huge elephant walks.'] },
  { id: 'size6', english: 'Enormous', vietnamese: 'To lớn', pronunciation: 'to lon', category: 'size', chapter: 'chapter16', difficulty: 2, examples: ['Enormous building towers.'] },
  { id: 'size7', english: 'Massive', vietnamese: 'Khổng lồ', pronunciation: 'khong lo', category: 'size', chapter: 'chapter16', difficulty: 2, examples: ['Massive mountain peak.'] },
  { id: 'size8', english: 'Miniature', vietnamese: 'Thu nhỏ', pronunciation: 'thu nho', category: 'size', chapter: 'chapter16', difficulty: 2, examples: ['Miniature toy car.'] },
  { id: 'size9', english: 'Tall', vietnamese: 'Cao', pronunciation: 'cao', category: 'size', chapter: 'chapter16', difficulty: 1, examples: ['Tall basketball player.'] },
  { id: 'size10', english: 'Short', vietnamese: 'Thấp', pronunciation: 'thap', category: 'size', chapter: 'chapter16', difficulty: 1, examples: ['Short fence around garden.'] },
  { id: 'size11', english: 'Long', vietnamese: 'Dài', pronunciation: 'dai', category: 'size', chapter: 'chapter16', difficulty: 1, examples: ['Long river flows.'] },
  { id: 'size12', english: 'Wide', vietnamese: 'Rộng', pronunciation: 'rong', category: 'size', chapter: 'chapter16', difficulty: 1, examples: ['Wide road ahead.'] },
  { id: 'size13', english: 'Narrow', vietnamese: 'Hẹp', pronunciation: 'hep', category: 'size', chapter: 'chapter16', difficulty: 1, examples: ['Narrow alley between buildings.'] },
  { id: 'size14', english: 'Thick', vietnamese: 'Dày', pronunciation: 'day', category: 'size', chapter: 'chapter16', difficulty: 1, examples: ['Thick book contains knowledge.'] },
  { id: 'size15', english: 'Thin', vietnamese: 'Mỏng', pronunciation: 'mong', category: 'size', chapter: 'chapter16', difficulty: 1, examples: ['Thin paper tears easily.'] },
  { id: 'size16', english: 'Round', vietnamese: 'Tròn', pronunciation: 'tron', category: 'size', chapter: 'chapter16', difficulty: 1, examples: ['Round ball bounces.'] },
  { id: 'size17', english: 'Square', vietnamese: 'Vuông', pronunciation: 'vuong', category: 'size', chapter: 'chapter16', difficulty: 1, examples: ['Square table fits four.'] },
  { id: 'size18', english: 'Rectangular', vietnamese: 'Chữ nhật', pronunciation: 'chu nhat', category: 'size', chapter: 'chapter16', difficulty: 1, examples: ['Rectangular window frame.'] },
  { id: 'size19', english: 'Oval', vietnamese: 'Oval', pronunciation: 'oval', category: 'size', chapter: 'chapter16', difficulty: 1, examples: ['Oval mirror elegant.'] },
  { id: 'size20', english: 'Triangular', vietnamese: 'Tam giác', pronunciation: 'tam giac', category: 'size', chapter: 'chapter16', difficulty: 1, examples: ['Triangular warning sign.'] },
  { id: 'size21', english: 'Curved', vietnamese: 'Cong', pronunciation: 'cong', category: 'size', chapter: 'chapter16', difficulty: 1, examples: ['Curved road dangerous.'] },
  { id: 'size22', english: 'Straight', vietnamese: 'Thẳng', pronunciation: 'thang', category: 'size', chapter: 'chapter16', difficulty: 1, examples: ['Straight line shortest.'] },
  { id: 'size23', english: 'Flat', vietnamese: 'Phẳng', pronunciation: 'phang', category: 'size', chapter: 'chapter16', difficulty: 1, examples: ['Flat surface smooth.'] },
  { id: 'size24', english: 'Steep', vietnamese: 'Dốc', pronunciation: 'doc', category: 'size', chapter: 'chapter16', difficulty: 1, examples: ['Steep hill climb.'] },
  { id: 'size25', english: 'Sharp', vietnamese: 'Nhọn', pronunciation: 'nhon', category: 'size', chapter: 'chapter16', difficulty: 1, examples: ['Sharp knife cuts.'] },

  // Texture & Pattern (25 words)
  { id: 'texture1', english: 'Smooth', vietnamese: 'Mịn', pronunciation: 'min', category: 'texture', chapter: 'chapter16', difficulty: 1, examples: ['Smooth silk fabric.'] },
  { id: 'texture2', english: 'Rough', vietnamese: 'Thô', pronunciation: 'tho', category: 'texture', chapter: 'chapter16', difficulty: 1, examples: ['Rough tree bark.'] },
  { id: 'texture3', english: 'Soft', vietnamese: 'Mềm', pronunciation: 'mem', category: 'texture', chapter: 'chapter16', difficulty: 1, examples: ['Soft pillow comfortable.'] },
  { id: 'texture4', english: 'Hard', vietnamese: 'Cứng', pronunciation: 'cung', category: 'texture', chapter: 'chapter16', difficulty: 1, examples: ['Hard rock surface.'] },
  { id: 'texture5', english: 'Bumpy', vietnamese: 'Gồ ghề', pronunciation: 'go ghe', category: 'texture', chapter: 'chapter16', difficulty: 1, examples: ['Bumpy road uncomfortable.'] },
  { id: 'texture6', english: 'Fuzzy', vietnamese: 'Bông', pronunciation: 'bong', category: 'texture', chapter: 'chapter16', difficulty: 1, examples: ['Fuzzy teddy bear.'] },
  { id: 'texture7', english: 'Silky', vietnamese: 'Như lụa', pronunciation: 'nhu lua', category: 'texture', chapter: 'chapter16', difficulty: 1, examples: ['Silky hair shines.'] },
  { id: 'texture8', english: 'Velvety', vietnamese: 'Như nhung', pronunciation: 'nhu nhung', category: 'texture', chapter: 'chapter16', difficulty: 2, examples: ['Velvety rose petals.'] },
  { id: 'texture9', english: 'Coarse', vietnamese: 'Thô ráp', pronunciation: 'tho rap', category: 'texture', chapter: 'chapter16', difficulty: 2, examples: ['Coarse sandpaper surface.'] },
  { id: 'texture10', english: 'Fine', vietnamese: 'Mịn', pronunciation: 'min', category: 'texture', chapter: 'chapter16', difficulty: 1, examples: ['Fine sand beach.'] },
  { id: 'texture11', english: 'Sticky', vietnamese: 'Dính', pronunciation: 'dinh', category: 'texture', chapter: 'chapter16', difficulty: 1, examples: ['Sticky honey drips.'] },
  { id: 'texture12', english: 'Slippery', vietnamese: 'Trơn', pronunciation: 'tron', category: 'texture', chapter: 'chapter16', difficulty: 1, examples: ['Slippery wet floor.'] },
  { id: 'texture13', english: 'Crispy', vietnamese: 'Giòn', pronunciation: 'gion', category: 'texture', chapter: 'chapter16', difficulty: 1, examples: ['Crispy fried chicken.'] },
  { id: 'texture14', english: 'Creamy', vietnamese: 'Kem', pronunciation: 'kem', category: 'texture', chapter: 'chapter16', difficulty: 1, examples: ['Creamy ice cream.'] },
  { id: 'texture15', english: 'Grainy', vietnamese: 'Có hạt', pronunciation: 'co hat', category: 'texture', chapter: 'chapter16', difficulty: 1, examples: ['Grainy wood surface.'] },
  { id: 'texture16', english: 'Striped', vietnamese: 'Sọc', pronunciation: 'soc', category: 'pattern', chapter: 'chapter16', difficulty: 1, examples: ['Striped shirt fashionable.'] },
  { id: 'texture17', english: 'Spotted', vietnamese: 'Đốm', pronunciation: 'dom', category: 'pattern', chapter: 'chapter16', difficulty: 1, examples: ['Spotted leopard beautiful.'] },
  { id: 'texture18', english: 'Checkered', vietnamese: 'Ô vuông', pronunciation: 'o vuong', category: 'pattern', chapter: 'chapter16', difficulty: 1, examples: ['Checkered tablecloth classic.'] },
  { id: 'texture19', english: 'Floral', vietnamese: 'Hoa', pronunciation: 'hoa', category: 'pattern', chapter: 'chapter16', difficulty: 1, examples: ['Floral dress pretty.'] },
  { id: 'texture20', english: 'Plain', vietnamese: 'Trơn', pronunciation: 'tron', category: 'pattern', chapter: 'chapter16', difficulty: 1, examples: ['Plain white shirt.'] },
  { id: 'texture21', english: 'Patterned', vietnamese: 'Có họa tiết', pronunciation: 'co hoa tiet', category: 'pattern', chapter: 'chapter16', difficulty: 1, examples: ['Patterned wallpaper decorative.'] },
  { id: 'texture22', english: 'Dotted', vietnamese: 'Chấm bi', pronunciation: 'cham bi', category: 'pattern', chapter: 'chapter16', difficulty: 1, examples: ['Dotted line marks boundary.'] },
  { id: 'texture23', english: 'Geometric', vietnamese: 'Hình học', pronunciation: 'hinh hoc', category: 'pattern', chapter: 'chapter16', difficulty: 2, examples: ['Geometric design modern.'] },
  { id: 'texture24', english: 'Abstract', vietnamese: 'Trừu tượng', pronunciation: 'truu tuong', category: 'pattern', chapter: 'chapter16', difficulty: 2, examples: ['Abstract art creative.'] },
  { id: 'texture25', english: 'Solid', vietnamese: 'Đặc', pronunciation: 'dac', category: 'pattern', chapter: 'chapter16', difficulty: 1, examples: ['Solid color background.'] }
]
