// Chapter 2: Family & People (100 Essential Words)
// Words related to family members, relationships, and people

import { LanguageWord } from './chapter01-basic-everyday'

export const chapter02Words: LanguageWord[] = [
  // Family Members (25 words)
  { id: 'family1', english: 'Family', vietnamese: 'Gia đình', pronunciation: 'za dinh', category: 'family', chapter: 'chapter02', difficulty: 1, examples: ['My family is big.'] },
  { id: 'family2', english: 'Father', vietnamese: 'Bố', pronunciation: 'bo', category: 'family', chapter: 'chapter02', difficulty: 1, examples: ['My father works hard.'] },
  { id: 'family3', english: 'Mother', vietnamese: 'Mẹ', pronunciation: 'me', category: 'family', chapter: 'chapter02', difficulty: 1, examples: ['Mother cooks dinner.'] },
  { id: 'family4', english: 'Son', vietnamese: 'Con trai', pronunciation: 'gon chai', category: 'family', chapter: 'chapter02', difficulty: 1, examples: ['Their son is smart.'] },
  { id: 'family5', english: 'Daughter', vietnamese: 'Con gái', pronunciation: 'gon gai', category: 'family', chapter: 'chapter02', difficulty: 1, examples: ['My daughter loves music.'] },
  { id: 'family6', english: 'Brother', vietnamese: 'Anh trai', pronunciation: 'anh chai', category: 'family', chapter: 'chapter02', difficulty: 1, examples: ['My brother is tall.'] },
  { id: 'family7', english: 'Sister', vietnamese: 'Em gái', pronunciation: 'em gai', category: 'family', chapter: 'chapter02', difficulty: 1, examples: ['Sister helps me study.'] },
  { id: 'family8', english: 'Grandfather', vietnamese: 'Ông', pronunciation: 'ong', category: 'family', chapter: 'chapter02', difficulty: 1, examples: ['Grandfather tells stories.'] },
  { id: 'family9', english: 'Grandmother', vietnamese: 'Bà', pronunciation: 'ba', category: 'family', chapter: 'chapter02', difficulty: 1, examples: ['Grandmother makes cookies.'] },
  { id: 'family10', english: 'Uncle', vietnamese: 'Chú', pronunciation: 'chu', category: 'family', chapter: 'chapter02', difficulty: 1, examples: ['Uncle lives nearby.'] },
  { id: 'family11', english: 'Aunt', vietnamese: 'Cô', pronunciation: 'co', category: 'family', chapter: 'chapter02', difficulty: 1, examples: ['Aunt visits us often.'] },
  { id: 'family12', english: 'Cousin', vietnamese: 'Anh em họ', pronunciation: 'anh em ho', category: 'family', chapter: 'chapter02', difficulty: 1, examples: ['My cousin is funny.'] },
  { id: 'family13', english: 'Husband', vietnamese: 'Chồng', pronunciation: 'chong', category: 'family', chapter: 'chapter02', difficulty: 1, examples: ['Her husband is kind.'] },
  { id: 'family14', english: 'Wife', vietnamese: 'Vợ', pronunciation: 'vo', category: 'family', chapter: 'chapter02', difficulty: 1, examples: ['His wife is beautiful.'] },
  { id: 'family15', english: 'Baby', vietnamese: 'Em bé', pronunciation: 'em be', category: 'family', chapter: 'chapter02', difficulty: 1, examples: ['The baby is sleeping.'] },
  { id: 'family16', english: 'Child', vietnamese: 'Trẻ em', pronunciation: 'tre em', category: 'family', chapter: 'chapter02', difficulty: 1, examples: ['The child plays outside.'] },
  { id: 'family17', english: 'Adult', vietnamese: 'Người lớn', pronunciation: 'nguoi lon', category: 'family', chapter: 'chapter02', difficulty: 1, examples: ['Adults work every day.'] },
  { id: 'family18', english: 'Parent', vietnamese: 'Cha mẹ', pronunciation: 'cha me', category: 'family', chapter: 'chapter02', difficulty: 1, examples: ['Parents love their children.'] },
  { id: 'family19', english: 'Grandparent', vietnamese: 'Ông bà', pronunciation: 'ong ba', category: 'family', chapter: 'chapter02', difficulty: 1, examples: ['Grandparents are wise.'] },
  { id: 'family20', english: 'Sibling', vietnamese: 'Anh em', pronunciation: 'anh em', category: 'family', chapter: 'chapter02', difficulty: 1, examples: ['I have three siblings.'] },
  { id: 'family21', english: 'Nephew', vietnamese: 'Cháu trai', pronunciation: 'chau chai', category: 'family', chapter: 'chapter02', difficulty: 1, examples: ['My nephew is five years old.'] },
  { id: 'family22', english: 'Niece', vietnamese: 'Cháu gái', pronunciation: 'chau gai', category: 'family', chapter: 'chapter02', difficulty: 1, examples: ['My niece loves dancing.'] },
  { id: 'family23', english: 'Twin', vietnamese: 'Song sinh', pronunciation: 'song sinh', category: 'family', chapter: 'chapter02', difficulty: 1, examples: ['They are twins.'] },
  { id: 'family24', english: 'Relative', vietnamese: 'Họ hàng', pronunciation: 'ho hang', category: 'family', chapter: 'chapter02', difficulty: 1, examples: ['We have many relatives.'] },
  { id: 'family25', english: 'Generation', vietnamese: 'Thế hệ', pronunciation: 'the he', category: 'family', chapter: 'chapter02', difficulty: 1, examples: ['Three generations live together.'] },

  // People & Relationships (20 words)
  { id: 'people1', english: 'Friend', vietnamese: 'Bạn', pronunciation: 'ban', category: 'people', chapter: 'chapter02', difficulty: 1, examples: ['My friend is helpful.'] },
  { id: 'people2', english: 'Neighbor', vietnamese: 'Hàng xóm', pronunciation: 'hang xom', category: 'people', chapter: 'chapter02', difficulty: 1, examples: ['Our neighbor is friendly.'] },
  { id: 'people3', english: 'Stranger', vietnamese: 'Người lạ', pronunciation: 'nguoi la', category: 'people', chapter: 'chapter02', difficulty: 1, examples: ['Do not talk to strangers.'] },
  { id: 'people4', english: 'Person', vietnamese: 'Người', pronunciation: 'nguoi', category: 'people', chapter: 'chapter02', difficulty: 1, examples: ['That person is nice.'] },
  { id: 'people5', english: 'People', vietnamese: 'Mọi người', pronunciation: 'moi nguoi', category: 'people', chapter: 'chapter02', difficulty: 1, examples: ['Many people came to the party.'] },
  { id: 'people6', english: 'Man', vietnamese: 'Đàn ông', pronunciation: 'dan ong', category: 'people', chapter: 'chapter02', difficulty: 1, examples: ['The man is walking.'] },
  { id: 'people7', english: 'Woman', vietnamese: 'Phụ nữ', pronunciation: 'phu nu', category: 'people', chapter: 'chapter02', difficulty: 1, examples: ['The woman is reading.'] },
  { id: 'people8', english: 'Boy', vietnamese: 'Cậu bé', pronunciation: 'cau be', category: 'people', chapter: 'chapter02', difficulty: 1, examples: ['The boy plays soccer.'] },
  { id: 'people9', english: 'Girl', vietnamese: 'Cô bé', pronunciation: 'co be', category: 'people', chapter: 'chapter02', difficulty: 1, examples: ['The girl likes flowers.'] },
  { id: 'people10', english: 'Teenager', vietnamese: 'Thiếu niên', pronunciation: 'thieu nien', category: 'people', chapter: 'chapter02', difficulty: 1, examples: ['Teenagers love technology.'] },
  { id: 'people11', english: 'Elderly', vietnamese: 'Người già', pronunciation: 'nguoi gia', category: 'people', chapter: 'chapter02', difficulty: 1, examples: ['Elderly people need care.'] },
  { id: 'people12', english: 'Couple', vietnamese: 'Cặp đôi', pronunciation: 'cap doi', category: 'people', chapter: 'chapter02', difficulty: 1, examples: ['The couple is happy.'] },
  { id: 'people13', english: 'Single', vietnamese: 'Độc thân', pronunciation: 'doc than', category: 'people', chapter: 'chapter02', difficulty: 1, examples: ['He is still single.'] },
  { id: 'people14', english: 'Married', vietnamese: 'Đã kết hôn', pronunciation: 'da ket hon', category: 'people', chapter: 'chapter02', difficulty: 1, examples: ['They got married last year.'] },
  { id: 'people15', english: 'Divorced', vietnamese: 'Ly hôn', pronunciation: 'ly hon', category: 'people', chapter: 'chapter02', difficulty: 1, examples: ['My parents are divorced.'] },
  { id: 'people16', english: 'Boyfriend', vietnamese: 'Bạn trai', pronunciation: 'ban chai', category: 'people', chapter: 'chapter02', difficulty: 1, examples: ['Her boyfriend is handsome.'] },
  { id: 'people17', english: 'Girlfriend', vietnamese: 'Bạn gái', pronunciation: 'ban gai', category: 'people', chapter: 'chapter02', difficulty: 1, examples: ['His girlfriend is smart.'] },
  { id: 'people18', english: 'Best friend', vietnamese: 'Bạn thân', pronunciation: 'ban than', category: 'people', chapter: 'chapter02', difficulty: 1, examples: ['She is my best friend.'] },
  { id: 'people19', english: 'Classmate', vietnamese: 'Bạn cùng lớp', pronunciation: 'ban cung lop', category: 'people', chapter: 'chapter02', difficulty: 1, examples: ['My classmate helps me.'] },
  { id: 'people20', english: 'Roommate', vietnamese: 'Bạn cùng phòng', pronunciation: 'ban cung phong', category: 'people', chapter: 'chapter02', difficulty: 1, examples: ['My roommate is clean.'] },

  // Personal Characteristics (25 words)
  { id: 'character1', english: 'Kind', vietnamese: 'Tử tế', pronunciation: 'tu te', category: 'character', chapter: 'chapter02', difficulty: 1, examples: ['She is very kind.'], antonym: 'Mean' },
  { id: 'character2', english: 'Mean', vietnamese: 'Xấu tính', pronunciation: 'sau tinh', category: 'character', chapter: 'chapter02', difficulty: 1, examples: ['Do not be mean.'], antonym: 'Kind' },
  { id: 'character3', english: 'Smart', vietnamese: 'Thông minh', pronunciation: 'thong minh', category: 'character', chapter: 'chapter02', difficulty: 1, examples: ['He is smart.'], antonym: 'Stupid' },
  { id: 'character4', english: 'Stupid', vietnamese: 'Ngu ngốc', pronunciation: 'ngu ngoc', category: 'character', chapter: 'chapter02', difficulty: 1, examples: ['That was stupid.'], antonym: 'Smart' },
  { id: 'character5', english: 'Funny', vietnamese: 'Vui tính', pronunciation: 'vui tinh', category: 'character', chapter: 'chapter02', difficulty: 1, examples: ['My brother is funny.'], antonym: 'Serious' },
  { id: 'character6', english: 'Serious', vietnamese: 'Nghiêm túc', pronunciation: 'nghiem tuc', category: 'character', chapter: 'chapter02', difficulty: 1, examples: ['This is serious.'], antonym: 'Funny' },
  { id: 'character7', english: 'Friendly', vietnamese: 'Thân thiện', pronunciation: 'than thien', category: 'character', chapter: 'chapter02', difficulty: 1, examples: ['Everyone is friendly here.'], antonym: 'Unfriendly' },
  { id: 'character8', english: 'Shy', vietnamese: 'Nhút nhát', pronunciation: 'nhut nhat', category: 'character', chapter: 'chapter02', difficulty: 1, examples: ['She is very shy.'], antonym: 'Outgoing' },
  { id: 'character9', english: 'Outgoing', vietnamese: 'Hướng ngoại', pronunciation: 'huong ngoai', category: 'character', chapter: 'chapter02', difficulty: 1, examples: ['He is outgoing.'], antonym: 'Shy' },
  { id: 'character10', english: 'Honest', vietnamese: 'Thành thật', pronunciation: 'thanh that', category: 'character', chapter: 'chapter02', difficulty: 1, examples: ['Always be honest.'], antonym: 'Dishonest' },
  { id: 'character11', english: 'Lazy', vietnamese: 'Lười biếng', pronunciation: 'luoi bieng', category: 'character', chapter: 'chapter02', difficulty: 1, examples: ['Do not be lazy.'], antonym: 'Hardworking' },
  { id: 'character12', english: 'Hardworking', vietnamese: 'Chăm chỉ', pronunciation: 'cham chi', category: 'character', chapter: 'chapter02', difficulty: 1, examples: ['Students should be hardworking.'], antonym: 'Lazy' },
  { id: 'character13', english: 'Patient', vietnamese: 'Kiên nhẫn', pronunciation: 'kien nhan', category: 'character', chapter: 'chapter02', difficulty: 1, examples: ['Teachers must be patient.'], antonym: 'Impatient' },
  { id: 'character14', english: 'Impatient', vietnamese: 'Thiếu kiên nhẫn', pronunciation: 'thieu kien nhan', category: 'character', chapter: 'chapter02', difficulty: 1, examples: ['He is impatient.'], antonym: 'Patient' },
  { id: 'character15', english: 'Brave', vietnamese: 'Dũng cảm', pronunciation: 'dung cam', category: 'character', chapter: 'chapter02', difficulty: 1, examples: ['Firefighters are brave.'], antonym: 'Coward' },
  { id: 'character16', english: 'Scared', vietnamese: 'Sợ hãi', pronunciation: 'so hai', category: 'character', chapter: 'chapter02', difficulty: 1, examples: ['I am scared of spiders.'], antonym: 'Brave' },
  { id: 'character17', english: 'Polite', vietnamese: 'Lịch sự', pronunciation: 'lich su', category: 'character', chapter: 'chapter02', difficulty: 1, examples: ['Children should be polite.'], antonym: 'Rude' },
  { id: 'character18', english: 'Rude', vietnamese: 'Thô lỗ', pronunciation: 'tho lo', category: 'character', chapter: 'chapter02', difficulty: 1, examples: ['Do not be rude.'], antonym: 'Polite' },
  { id: 'character19', english: 'Generous', vietnamese: 'Hào phóng', pronunciation: 'hao phong', category: 'character', chapter: 'chapter02', difficulty: 1, examples: ['My uncle is generous.'], antonym: 'Stingy' },
  { id: 'character20', english: 'Selfish', vietnamese: 'Ích kỷ', pronunciation: 'ich ky', category: 'character', chapter: 'chapter02', difficulty: 1, examples: ['Do not be selfish.'], antonym: 'Generous' },
  { id: 'character21', english: 'Calm', vietnamese: 'Bình tĩnh', pronunciation: 'binh tinh', category: 'character', chapter: 'chapter02', difficulty: 1, examples: ['Stay calm.'], antonym: 'Angry' },
  { id: 'character22', english: 'Angry', vietnamese: 'Tức giận', pronunciation: 'tuc gian', category: 'character', chapter: 'chapter02', difficulty: 1, examples: ['He looks angry.'], antonym: 'Calm' },
  { id: 'character23', english: 'Cheerful', vietnamese: 'Vui vẻ', pronunciation: 'vui ve', category: 'character', chapter: 'chapter02', difficulty: 1, examples: ['She is always cheerful.'], antonym: 'Gloomy' },
  { id: 'character24', english: 'Responsible', vietnamese: 'Có trách nhiệm', pronunciation: 'co trach nhiem', category: 'character', chapter: 'chapter02', difficulty: 1, examples: ['Be responsible for your actions.'] },
  { id: 'character25', english: 'Helpful', vietnamese: 'Hay giúp đỡ', pronunciation: 'hay giup do', category: 'character', chapter: 'chapter02', difficulty: 1, examples: ['My neighbor is helpful.'] },

  // Physical Appearance (15 words)
  { id: 'appearance1', english: 'Tall', vietnamese: 'Cao', pronunciation: 'kao', category: 'appearance', chapter: 'chapter02', difficulty: 1, examples: ['He is tall.'], antonym: 'Short' },
  { id: 'appearance2', english: 'Short', vietnamese: 'Thấp', pronunciation: 'thap', category: 'appearance', chapter: 'chapter02', difficulty: 1, examples: ['She is short.'], antonym: 'Tall' },
  { id: 'appearance3', english: 'Fat', vietnamese: 'Béo', pronunciation: 'beo', category: 'appearance', chapter: 'chapter02', difficulty: 1, examples: ['The cat is fat.'], antonym: 'Thin' },
  { id: 'appearance4', english: 'Thin', vietnamese: 'Gầy', pronunciation: 'gay', category: 'appearance', chapter: 'chapter02', difficulty: 1, examples: ['She is very thin.'], antonym: 'Fat' },
  { id: 'appearance5', english: 'Young', vietnamese: 'Trẻ', pronunciation: 'tre', category: 'appearance', chapter: 'chapter02', difficulty: 1, examples: ['They are young.'], antonym: 'Old' },
  { id: 'appearance6', english: 'Old', vietnamese: 'Già', pronunciation: 'gia', category: 'appearance', chapter: 'chapter02', difficulty: 1, examples: ['My grandfather is old.'], antonym: 'Young' },
  { id: 'appearance7', english: 'Handsome', vietnamese: 'Đẹp trai', pronunciation: 'dep chai', category: 'appearance', chapter: 'chapter02', difficulty: 1, examples: ['He is handsome.'] },
  { id: 'appearance8', english: 'Pretty', vietnamese: 'Xinh đẹp', pronunciation: 'xinh dep', category: 'appearance', chapter: 'chapter02', difficulty: 1, examples: ['She is pretty.'] },
  { id: 'appearance9', english: 'Cute', vietnamese: 'Dễ thương', pronunciation: 'de thuong', category: 'appearance', chapter: 'chapter02', difficulty: 1, examples: ['The baby is cute.'] },
  { id: 'appearance10', english: 'Strong', vietnamese: 'Khỏe', pronunciation: 'khoe', category: 'appearance', chapter: 'chapter02', difficulty: 1, examples: ['He is strong.'], antonym: 'Weak' },
  { id: 'appearance11', english: 'Weak', vietnamese: 'Yếu', pronunciation: 'yeu', category: 'appearance', chapter: 'chapter02', difficulty: 1, examples: ['I feel weak today.'], antonym: 'Strong' },
  { id: 'appearance12', english: 'Hair', vietnamese: 'Tóc', pronunciation: 'toc', category: 'appearance', chapter: 'chapter02', difficulty: 1, examples: ['She has long hair.'] },
  { id: 'appearance13', english: 'Eyes', vietnamese: 'Mắt', pronunciation: 'mat', category: 'appearance', chapter: 'chapter02', difficulty: 1, examples: ['He has blue eyes.'] },
  { id: 'appearance14', english: 'Smile', vietnamese: 'Nụ cười', pronunciation: 'nu cuoi', category: 'appearance', chapter: 'chapter02', difficulty: 1, examples: ['She has a beautiful smile.'] },
  { id: 'appearance15', english: 'Face', vietnamese: 'Mặt', pronunciation: 'mat', category: 'appearance', chapter: 'chapter02', difficulty: 1, examples: ['Wash your face.'] },

  // Age & Life Stages (15 words)
  { id: 'age1', english: 'Age', vietnamese: 'Tuổi', pronunciation: 'tuoi', category: 'age', chapter: 'chapter02', difficulty: 1, examples: ['What is your age?'] },
  { id: 'age2', english: 'Birth', vietnamese: 'Sinh', pronunciation: 'sinh', category: 'age', chapter: 'chapter02', difficulty: 1, examples: ['Date of birth.'] },
  { id: 'age3', english: 'Birthday', vietnamese: 'Sinh nhật', pronunciation: 'sinh nhat', category: 'age', chapter: 'chapter02', difficulty: 1, examples: ['Happy birthday!'] },
  { id: 'age4', english: 'Childhood', vietnamese: 'Tuổi thơ', pronunciation: 'tuoi tho', category: 'age', chapter: 'chapter02', difficulty: 1, examples: ['I remember my childhood.'] },
  { id: 'age5', english: 'Youth', vietnamese: 'Tuổi trẻ', pronunciation: 'tuoi tre', category: 'age', chapter: 'chapter02', difficulty: 1, examples: ['Youth is beautiful.'] },
  { id: 'age6', english: 'Middle-aged', vietnamese: 'Trung niên', pronunciation: 'trung nien', category: 'age', chapter: 'chapter02', difficulty: 1, examples: ['Middle-aged people work hard.'] },
  { id: 'age7', english: 'Senior', vietnamese: 'Cao tuổi', pronunciation: 'kao tuoi', category: 'age', chapter: 'chapter02', difficulty: 1, examples: ['Senior citizens get discounts.'] },
  { id: 'age8', english: 'Grow up', vietnamese: 'Lớn lên', pronunciation: 'lon len', category: 'age', chapter: 'chapter02', difficulty: 1, examples: ['Children grow up fast.'] },
  { id: 'age9', english: 'Mature', vietnamese: 'Trưởng thành', pronunciation: 'truong thanh', category: 'age', chapter: 'chapter02', difficulty: 1, examples: ['He is very mature.'] },
  { id: 'age10', english: 'Infant', vietnamese: 'Trẻ sơ sinh', pronunciation: 'tre so sinh', category: 'age', chapter: 'chapter02', difficulty: 1, examples: ['The infant sleeps a lot.'] },
  { id: 'age11', english: 'Toddler', vietnamese: 'Trẻ mới biết đi', pronunciation: 'tre moi biet di', category: 'age', chapter: 'chapter02', difficulty: 1, examples: ['Toddlers love to explore.'] },
  { id: 'age12', english: 'Kid', vietnamese: 'Trẻ con', pronunciation: 'tre con', category: 'age', chapter: 'chapter02', difficulty: 1, examples: ['Kids play in the park.'] },
  { id: 'age13', english: 'Teen', vietnamese: 'Thanh thiếu niên', pronunciation: 'thanh thieu nien', category: 'age', chapter: 'chapter02', difficulty: 1, examples: ['Teens use social media.'] },
  { id: 'age14', english: 'Adult', vietnamese: 'Người trưởng thành', pronunciation: 'nguoi truong thanh', category: 'age', chapter: 'chapter02', difficulty: 1, examples: ['Adults have responsibilities.'] },
  { id: 'age15', english: 'Elder', vietnamese: 'Người già', pronunciation: 'nguoi gia', category: 'age', chapter: 'chapter02', difficulty: 1, examples: ['Respect your elders.'] }
]
