// Chapter 24: Arts & Culture (100 Essential Words)
// Words related to arts, culture, music, literature, and creative expression

import { LanguageWord } from './chapter01-basic-everyday'

export const chapter24Words: LanguageWord[] = [
  // Visual Arts (25 words)
  { id: 'visual1', english: 'Art', vietnamese: 'Nghệ thuật', pronunciation: 'nghe thuat', category: 'visual', chapter: 'chapter24', difficulty: 1, examples: ['Art expresses creativity.'] },
  { id: 'visual2', english: 'Painting', vietnamese: 'Tranh vẽ', pronunciation: 'tranh ve', category: 'visual', chapter: 'chapter24', difficulty: 1, examples: ['Painting hangs wall.'] },
  { id: 'visual3', english: 'Drawing', vietnamese: 'Bản vẽ', pronunciation: 'ban ve', category: 'visual', chapter: 'chapter24', difficulty: 1, examples: ['Drawing shows detail.'] },
  { id: 'visual4', english: 'Sculpture', vietnamese: 'Tác phẩm điêu khắc', pronunciation: 'tac pham dieu khac', category: 'visual', chapter: 'chapter24', difficulty: 2, examples: ['Sculpture three dimensional.'] },
  { id: 'visual5', english: 'Artist', vietnamese: 'Nghệ sĩ', pronunciation: 'nghe si', category: 'visual', chapter: 'chapter24', difficulty: 1, examples: ['Artist creates beauty.'] },
  { id: 'visual6', english: 'Gallery', vietnamese: 'Phòng tranh', pronunciation: 'phong tranh', category: 'visual', chapter: 'chapter24', difficulty: 1, examples: ['Gallery displays art.'] },
  { id: 'visual7', english: 'Museum', vietnamese: 'Bảo tàng', pronunciation: 'bao tang', category: 'visual', chapter: 'chapter24', difficulty: 1, examples: ['Museum preserves history.'] },
  { id: 'visual8', english: 'Exhibition', vietnamese: 'Triển lãm', pronunciation: 'trien lam', category: 'visual', chapter: 'chapter24', difficulty: 1, examples: ['Exhibition showcases works.'] },
  { id: 'visual9', english: 'Canvas', vietnamese: 'Vải bạt', pronunciation: 'vai bat', category: 'visual', chapter: 'chapter24', difficulty: 1, examples: ['Canvas holds paint.'] },
  { id: 'visual10', english: 'Brush', vietnamese: 'Cọ vẽ', pronunciation: 'co ve', category: 'visual', chapter: 'chapter24', difficulty: 1, examples: ['Brush applies color.'] },
  { id: 'visual11', english: 'Paint', vietnamese: 'Màu sơn', pronunciation: 'mau son', category: 'visual', chapter: 'chapter24', difficulty: 1, examples: ['Paint creates colors.'] },
  { id: 'visual12', english: 'Color', vietnamese: 'Màu sắc', pronunciation: 'mau sac', category: 'visual', chapter: 'chapter24', difficulty: 1, examples: ['Color affects mood.'] },
  { id: 'visual13', english: 'Palette', vietnamese: 'Bảng màu', pronunciation: 'bang mau', category: 'visual', chapter: 'chapter24', difficulty: 1, examples: ['Palette mixes colors.'] },
  { id: 'visual14', english: 'Portrait', vietnamese: 'Chân dung', pronunciation: 'chan dung', category: 'visual', chapter: 'chapter24', difficulty: 1, examples: ['Portrait shows person.'] },
  { id: 'visual15', english: 'Landscape', vietnamese: 'Phong cảnh', pronunciation: 'phong canh', category: 'visual', chapter: 'chapter24', difficulty: 1, examples: ['Landscape depicts nature.'] },
  { id: 'visual16', english: 'Still life', vietnamese: 'Tranh tĩnh vật', pronunciation: 'tranh tinh vat', category: 'visual', chapter: 'chapter24', difficulty: 2, examples: ['Still life shows objects.'] },
  { id: 'visual17', english: 'Abstract', vietnamese: 'Trừu tượng', pronunciation: 'tru tuong', category: 'visual', chapter: 'chapter24', difficulty: 2, examples: ['Abstract art conceptual.'] },
  { id: 'visual18', english: 'Realistic', vietnamese: 'Thực tế', pronunciation: 'thuc te', category: 'visual', chapter: 'chapter24', difficulty: 1, examples: ['Realistic painting detailed.'] },
  { id: 'visual19', english: 'Frame', vietnamese: 'Khung', pronunciation: 'khung', category: 'visual', chapter: 'chapter24', difficulty: 1, examples: ['Frame borders artwork.'] },
  { id: 'visual20', english: 'Sketch', vietnamese: 'Phác thảo', pronunciation: 'phac thao', category: 'visual', chapter: 'chapter24', difficulty: 1, examples: ['Sketch quick drawing.'] },
  { id: 'visual21', english: 'Masterpiece', vietnamese: 'Kiệt tác', pronunciation: 'kiet tac', category: 'visual', chapter: 'chapter24', difficulty: 2, examples: ['Masterpiece famous artwork.'] },
  { id: 'visual22', english: 'Creative', vietnamese: 'Sáng tạo', pronunciation: 'sang tao', category: 'visual', chapter: 'chapter24', difficulty: 1, examples: ['Creative mind innovates.'] },
  { id: 'visual23', english: 'Inspiration', vietnamese: 'Cảm hứng', pronunciation: 'cam hung', category: 'visual', chapter: 'chapter24', difficulty: 1, examples: ['Inspiration motivates artists.'] },
  { id: 'visual24', english: 'Style', vietnamese: 'Phong cách', pronunciation: 'phong cach', category: 'visual', chapter: 'chapter24', difficulty: 1, examples: ['Style shows personality.'] },
  { id: 'visual25', english: 'Technique', vietnamese: 'Kỹ thuật', pronunciation: 'ky thuat', category: 'visual', chapter: 'chapter24', difficulty: 1, examples: ['Technique requires skill.'] },

  // Music & Performance (25 words)
  { id: 'music1', english: 'Music', vietnamese: 'Âm nhạc', pronunciation: 'am nhac', category: 'music', chapter: 'chapter24', difficulty: 1, examples: ['Music touches souls.'] },
  { id: 'music2', english: 'Song', vietnamese: 'Bài hát', pronunciation: 'bai hat', category: 'music', chapter: 'chapter24', difficulty: 1, examples: ['Song tells story.'] },
  { id: 'music3', english: 'Melody', vietnamese: 'Giai điệu', pronunciation: 'giai dieu', category: 'music', chapter: 'chapter24', difficulty: 1, examples: ['Melody flows beautifully.'] },
  { id: 'music4', english: 'Rhythm', vietnamese: 'Nhịp điệu', pronunciation: 'nhip dieu', category: 'music', chapter: 'chapter24', difficulty: 1, examples: ['Rhythm drives music.'] },
  { id: 'music5', english: 'Beat', vietnamese: 'Nhịp', pronunciation: 'nhip', category: 'music', chapter: 'chapter24', difficulty: 1, examples: ['Beat keeps time.'] },
  { id: 'music6', english: 'Tempo', vietnamese: 'Nhịp độ', pronunciation: 'nhip do', category: 'music', chapter: 'chapter24', difficulty: 1, examples: ['Tempo controls speed.'] },
  { id: 'music7', english: 'Harmony', vietnamese: 'Hòa âm', pronunciation: 'hoa am', category: 'music', chapter: 'chapter24', difficulty: 1, examples: ['Harmony blends notes.'] },
  { id: 'music8', english: 'Instrument', vietnamese: 'Nhạc cụ', pronunciation: 'nhac cu', category: 'music', chapter: 'chapter24', difficulty: 1, examples: ['Instrument makes sound.'] },
  { id: 'music9', english: 'Orchestra', vietnamese: 'Dàn nhạc giao hưởng', pronunciation: 'dan nhac giao huong', category: 'music', chapter: 'chapter24', difficulty: 2, examples: ['Orchestra plays symphony.'] },
  { id: 'music10', english: 'Band', vietnamese: 'Ban nhạc', pronunciation: 'ban nhac', category: 'music', chapter: 'chapter24', difficulty: 1, examples: ['Band performs together.'] },
  { id: 'music11', english: 'Choir', vietnamese: 'Dàn hợp xướng', pronunciation: 'dan hop xuong', category: 'music', chapter: 'chapter24', difficulty: 2, examples: ['Choir sings harmony.'] },
  { id: 'music12', english: 'Concert', vietnamese: 'Buổi hòa nhạc', pronunciation: 'buoi hoa nhac', category: 'music', chapter: 'chapter24', difficulty: 1, examples: ['Concert entertains audience.'] },
  { id: 'music13', english: 'Performance', vietnamese: 'Buổi biểu diễn', pronunciation: 'buoi bieu dien', category: 'music', chapter: 'chapter24', difficulty: 1, examples: ['Performance captivates crowd.'] },
  { id: 'music14', english: 'Stage', vietnamese: 'Sân khấu', pronunciation: 'san khau', category: 'music', chapter: 'chapter24', difficulty: 1, examples: ['Stage hosts performers.'] },
  { id: 'music15', english: 'Audience', vietnamese: 'Khán giả', pronunciation: 'khan gia', category: 'music', chapter: 'chapter24', difficulty: 1, examples: ['Audience enjoys show.'] },
  { id: 'music16', english: 'Singer', vietnamese: 'Ca sĩ', pronunciation: 'ca si', category: 'music', chapter: 'chapter24', difficulty: 1, examples: ['Singer has voice.'] },
  { id: 'music17', english: 'Musician', vietnamese: 'Nhạc sĩ', pronunciation: 'nhac si', category: 'music', chapter: 'chapter24', difficulty: 1, examples: ['Musician plays instruments.'] },
  { id: 'music18', english: 'Composer', vietnamese: 'Nhà soạn nhạc', pronunciation: 'nha soan nhac', category: 'music', chapter: 'chapter24', difficulty: 2, examples: ['Composer writes music.'] },
  { id: 'music19', english: 'Conductor', vietnamese: 'Người chỉ huy', pronunciation: 'nguoi chi huy', category: 'music', chapter: 'chapter24', difficulty: 2, examples: ['Conductor leads orchestra.'] },
  { id: 'music20', english: 'Genre', vietnamese: 'Thể loại', pronunciation: 'the loai', category: 'music', chapter: 'chapter24', difficulty: 1, examples: ['Jazz popular genre.'] },
  { id: 'music21', english: 'Classical', vietnamese: 'Cổ điển', pronunciation: 'co dien', category: 'music', chapter: 'chapter24', difficulty: 1, examples: ['Classical music timeless.'] },
  { id: 'music22', english: 'Jazz', vietnamese: 'Nhạc jazz', pronunciation: 'nhac jazz', category: 'music', chapter: 'chapter24', difficulty: 1, examples: ['Jazz improvisational music.'] },
  { id: 'music23', english: 'Rock', vietnamese: 'Nhạc rock', pronunciation: 'nhac rock', category: 'music', chapter: 'chapter24', difficulty: 1, examples: ['Rock music energetic.'] },
  { id: 'music24', english: 'Pop', vietnamese: 'Nhạc pop', pronunciation: 'nhac pop', category: 'music', chapter: 'chapter24', difficulty: 1, examples: ['Pop music popular.'] },
  { id: 'music25', english: 'Folk', vietnamese: 'Dân gian', pronunciation: 'dan gian', category: 'music', chapter: 'chapter24', difficulty: 1, examples: ['Folk music traditional.'] },

  // Literature & Theater (25 words)
  { id: 'literature1', english: 'Literature', vietnamese: 'Văn học', pronunciation: 'van hoc', category: 'literature', chapter: 'chapter24', difficulty: 1, examples: ['Literature reflects society.'] },
  { id: 'literature2', english: 'Book', vietnamese: 'Cuốn sách', pronunciation: 'cuon sach', category: 'literature', chapter: 'chapter24', difficulty: 1, examples: ['Book contains stories.'] },
  { id: 'literature3', english: 'Novel', vietnamese: 'Tiểu thuyết', pronunciation: 'tieu thuyet', category: 'literature', chapter: 'chapter24', difficulty: 1, examples: ['Novel tells long story.'] },
  { id: 'literature4', english: 'Poetry', vietnamese: 'Thơ ca', pronunciation: 'tho ca', category: 'literature', chapter: 'chapter24', difficulty: 1, examples: ['Poetry expresses emotions.'] },
  { id: 'literature5', english: 'Poem', vietnamese: 'Bài thơ', pronunciation: 'bai tho', category: 'literature', chapter: 'chapter24', difficulty: 1, examples: ['Poem uses metaphors.'] },
  { id: 'literature6', english: 'Story', vietnamese: 'Câu chuyện', pronunciation: 'cau chuyen', category: 'literature', chapter: 'chapter24', difficulty: 1, examples: ['Story entertains readers.'] },
  { id: 'literature7', english: 'Author', vietnamese: 'Tác giả', pronunciation: 'tac gia', category: 'literature', chapter: 'chapter24', difficulty: 1, examples: ['Author writes books.'] },
  { id: 'literature8', english: 'Writer', vietnamese: 'Nhà văn', pronunciation: 'nha van', category: 'literature', chapter: 'chapter24', difficulty: 1, examples: ['Writer creates stories.'] },
  { id: 'literature9', english: 'Poet', vietnamese: 'Nhà thơ', pronunciation: 'nha tho', category: 'literature', chapter: 'chapter24', difficulty: 1, examples: ['Poet writes verses.'] },
  { id: 'literature10', english: 'Character', vietnamese: 'Nhân vật', pronunciation: 'nhan vat', category: 'literature', chapter: 'chapter24', difficulty: 1, examples: ['Character drives plot.'] },
  { id: 'literature11', english: 'Plot', vietnamese: 'Cốt truyện', pronunciation: 'cot truyen', category: 'literature', chapter: 'chapter24', difficulty: 1, examples: ['Plot unfolds gradually.'] },
  { id: 'literature12', english: 'Theme', vietnamese: 'Chủ đề', pronunciation: 'chu de', category: 'literature', chapter: 'chapter24', difficulty: 1, examples: ['Theme conveys message.'] },
  { id: 'literature13', english: 'Chapter', vietnamese: 'Chương', pronunciation: 'chuong', category: 'literature', chapter: 'chapter24', difficulty: 1, examples: ['Chapter divides book.'] },
  { id: 'literature14', english: 'Paragraph', vietnamese: 'Đoạn văn', pronunciation: 'doan van', category: 'literature', chapter: 'chapter24', difficulty: 1, examples: ['Paragraph organizes thoughts.'] },
  { id: 'literature15', english: 'Library', vietnamese: 'Thư viện', pronunciation: 'thu vien', category: 'literature', chapter: 'chapter24', difficulty: 1, examples: ['Library stores books.'] },
  { id: 'literature16', english: 'Theater', vietnamese: 'Nhà hát', pronunciation: 'nha hat', category: 'literature', chapter: 'chapter24', difficulty: 1, examples: ['Theater presents plays.'] },
  { id: 'literature17', english: 'Play', vietnamese: 'Vở kịch', pronunciation: 'vo kich', category: 'literature', chapter: 'chapter24', difficulty: 1, examples: ['Play tells dramatic story.'] },
  { id: 'literature18', english: 'Drama', vietnamese: 'Kịch', pronunciation: 'kich', category: 'literature', chapter: 'chapter24', difficulty: 1, examples: ['Drama explores conflict.'] },
  { id: 'literature19', english: 'Comedy', vietnamese: 'Hài kịch', pronunciation: 'hai kich', category: 'literature', chapter: 'chapter24', difficulty: 1, examples: ['Comedy makes laugh.'] },
  { id: 'literature20', english: 'Tragedy', vietnamese: 'Bi kịch', pronunciation: 'bi kich', category: 'literature', chapter: 'chapter24', difficulty: 1, examples: ['Tragedy ends sadly.'] },
  { id: 'literature21', english: 'Actor', vietnamese: 'Diễn viên', pronunciation: 'dien vien', category: 'literature', chapter: 'chapter24', difficulty: 1, examples: ['Actor plays role.'] },
  { id: 'literature22', english: 'Actress', vietnamese: 'Nữ diễn viên', pronunciation: 'nu dien vien', category: 'literature', chapter: 'chapter24', difficulty: 1, examples: ['Actress performs beautifully.'] },
  { id: 'literature23', english: 'Script', vietnamese: 'Kịch bản', pronunciation: 'kich ban', category: 'literature', chapter: 'chapter24', difficulty: 1, examples: ['Script contains dialogue.'] },
  { id: 'literature24', english: 'Dialogue', vietnamese: 'Đối thoại', pronunciation: 'doi thoai', category: 'literature', chapter: 'chapter24', difficulty: 1, examples: ['Dialogue reveals character.'] },
  { id: 'literature25', english: 'Critic', vietnamese: 'Nhà phê bình', pronunciation: 'nha phe binh', category: 'literature', chapter: 'chapter24', difficulty: 2, examples: ['Critic reviews works.'] },

  // Culture & Traditions (25 words)
  { id: 'culture1', english: 'Culture', vietnamese: 'Văn hóa', pronunciation: 'van hoa', category: 'culture', chapter: 'chapter24', difficulty: 1, examples: ['Culture shapes identity.'] },
  { id: 'culture2', english: 'Tradition', vietnamese: 'Truyền thống', pronunciation: 'truyen thong', category: 'culture', chapter: 'chapter24', difficulty: 1, examples: ['Tradition passes generations.'] },
  { id: 'culture3', english: 'Custom', vietnamese: 'Phong tục', pronunciation: 'phong tuc', category: 'culture', chapter: 'chapter24', difficulty: 1, examples: ['Custom local practice.'] },
  { id: 'culture4', english: 'Festival', vietnamese: 'Lễ hội', pronunciation: 'le hoi', category: 'culture', chapter: 'chapter24', difficulty: 1, examples: ['Festival celebrates culture.'] },
  { id: 'culture5', english: 'Holiday', vietnamese: 'Ngày lễ', pronunciation: 'ngay le', category: 'culture', chapter: 'chapter24', difficulty: 1, examples: ['Holiday brings families.'] },
  { id: 'culture6', english: 'Celebration', vietnamese: 'Lễ kỷ niệm', pronunciation: 'le ky niem', category: 'culture', chapter: 'chapter24', difficulty: 1, examples: ['Celebration marks occasion.'] },
  { id: 'culture7', english: 'Ceremony', vietnamese: 'Nghi lễ', pronunciation: 'nghi le', category: 'culture', chapter: 'chapter24', difficulty: 1, examples: ['Ceremony honors tradition.'] },
  { id: 'culture8', english: 'Ritual', vietnamese: 'Nghi thức', pronunciation: 'nghi thuc', category: 'culture', chapter: 'chapter24', difficulty: 1, examples: ['Ritual has meaning.'] },
  { id: 'culture9', english: 'Heritage', vietnamese: 'Di sản', pronunciation: 'di san', category: 'culture', chapter: 'chapter24', difficulty: 1, examples: ['Heritage preserves past.'] },
  { id: 'culture10', english: 'History', vietnamese: 'Lịch sử', pronunciation: 'lich su', category: 'culture', chapter: 'chapter24', difficulty: 1, examples: ['History teaches lessons.'] },
  { id: 'culture11', english: 'Ancient', vietnamese: 'Cổ xưa', pronunciation: 'co xua', category: 'culture', chapter: 'chapter24', difficulty: 1, examples: ['Ancient civilization advanced.'] },
  { id: 'culture12', english: 'Modern', vietnamese: 'Hiện đại', pronunciation: 'hien dai', category: 'culture', chapter: 'chapter24', difficulty: 1, examples: ['Modern technology convenient.'] },
  { id: 'culture13', english: 'Traditional', vietnamese: 'Truyền thống', pronunciation: 'truyen thong', category: 'culture', chapter: 'chapter24', difficulty: 1, examples: ['Traditional values important.'] },
  { id: 'culture14', english: 'Contemporary', vietnamese: 'Đương đại', pronunciation: 'duong dai', category: 'culture', chapter: 'chapter24', difficulty: 2, examples: ['Contemporary art innovative.'] },
  { id: 'culture15', english: 'Folk', vietnamese: 'Dân gian', pronunciation: 'dan gian', category: 'culture', chapter: 'chapter24', difficulty: 1, examples: ['Folk tales wisdom.'] },
  { id: 'culture16', english: 'Legend', vietnamese: 'Huyền thoại', pronunciation: 'huyen thoai', category: 'culture', chapter: 'chapter24', difficulty: 1, examples: ['Legend explains origins.'] },
  { id: 'culture17', english: 'Myth', vietnamese: 'Thần thoại', pronunciation: 'than thoai', category: 'culture', chapter: 'chapter24', difficulty: 1, examples: ['Myth ancient story.'] },
  { id: 'culture18', english: 'Symbol', vietnamese: 'Biểu tượng', pronunciation: 'bieu tuong', category: 'culture', chapter: 'chapter24', difficulty: 1, examples: ['Symbol represents idea.'] },
  { id: 'culture19', english: 'Identity', vietnamese: 'Bản sắc', pronunciation: 'ban sac', category: 'culture', chapter: 'chapter24', difficulty: 1, examples: ['Identity defines person.'] },
  { id: 'culture20', english: 'Values', vietnamese: 'Giá trị', pronunciation: 'gia tri', category: 'culture', chapter: 'chapter24', difficulty: 1, examples: ['Values guide behavior.'] },
  { id: 'culture21', english: 'Belief', vietnamese: 'Niềm tin', pronunciation: 'niem tin', category: 'culture', chapter: 'chapter24', difficulty: 1, examples: ['Belief shapes worldview.'] },
  { id: 'culture22', english: 'Religion', vietnamese: 'Tôn giáo', pronunciation: 'ton giao', category: 'culture', chapter: 'chapter24', difficulty: 1, examples: ['Religion provides guidance.'] },
  { id: 'culture23', english: 'Spiritual', vietnamese: 'Tâm linh', pronunciation: 'tam linh', category: 'culture', chapter: 'chapter24', difficulty: 1, examples: ['Spiritual practice peaceful.'] },
  { id: 'culture24', english: 'Sacred', vietnamese: 'Thiêng liêng', pronunciation: 'thieng lieng', category: 'culture', chapter: 'chapter24', difficulty: 2, examples: ['Sacred place respected.'] },
  { id: 'culture25', english: 'Diversity', vietnamese: 'Đa dạng', pronunciation: 'da dang', category: 'culture', chapter: 'chapter24', difficulty: 1, examples: ['Diversity enriches society.'] }
]
