// Chapter 14: Time & Calendar (100 Essential Words)
// Words related to time, dates, calendar, schedules, and temporal expressions

import { LanguageWord } from './chapter01-basic-everyday'

export const chapter14Words: LanguageWord[] = [
  // Time Units (25 words)
  { id: 'time1', english: 'Time', vietnamese: 'Thời gian', pronunciation: 'thoi gian', category: 'time', chapter: 'chapter14', difficulty: 1, examples: ['Time flies quickly.'] },
  { id: 'time2', english: 'Second', vietnamese: 'Giây', pronunciation: 'giay', category: 'time', chapter: 'chapter14', difficulty: 1, examples: ['Wait one second.'] },
  { id: 'time3', english: 'Minute', vietnamese: 'Phút', pronunciation: 'phut', category: 'time', chapter: 'chapter14', difficulty: 1, examples: ['Five minutes late.'] },
  { id: 'time4', english: 'Hour', vietnamese: 'Giờ', pronunciation: 'gio', category: 'time', chapter: 'chapter14', difficulty: 1, examples: ['Work eight hours daily.'] },
  { id: 'time5', english: 'Day', vietnamese: 'Ngày', pronunciation: 'ngay', category: 'time', chapter: 'chapter14', difficulty: 1, examples: ['Beautiful day today.'] },
  { id: 'time6', english: 'Week', vietnamese: 'Tuần', pronunciation: 'tuan', category: 'time', chapter: 'chapter14', difficulty: 1, examples: ['Busy week ahead.'] },
  { id: 'time7', english: 'Month', vietnamese: 'Tháng', pronunciation: 'thang', category: 'time', chapter: 'chapter14', difficulty: 1, examples: ['Next month vacation.'] },
  { id: 'time8', english: 'Year', vietnamese: 'Năm', pronunciation: 'nam', category: 'time', chapter: 'chapter14', difficulty: 1, examples: ['Happy new year.'] },
  { id: 'time9', english: 'Decade', vietnamese: 'Thập kỷ', pronunciation: 'thap ky', category: 'time', chapter: 'chapter14', difficulty: 2, examples: ['Technology advances each decade.'] },
  { id: 'time10', english: 'Century', vietnamese: 'Thế kỷ', pronunciation: 'the ky', category: 'time', chapter: 'chapter14', difficulty: 2, examples: ['Twenty-first century innovations.'] },
  { id: 'time11', english: 'Morning', vietnamese: 'Buổi sáng', pronunciation: 'buoi sang', category: 'time', chapter: 'chapter14', difficulty: 1, examples: ['Fresh morning air.'] },
  { id: 'time12', english: 'Afternoon', vietnamese: 'Buổi chiều', pronunciation: 'buoi chieu', category: 'time', chapter: 'chapter14', difficulty: 1, examples: ['Lazy afternoon nap.'] },
  { id: 'time13', english: 'Evening', vietnamese: 'Buổi tối', pronunciation: 'buoi toi', category: 'time', chapter: 'chapter14', difficulty: 1, examples: ['Quiet evening reading.'] },
  { id: 'time14', english: 'Night', vietnamese: 'Đêm', pronunciation: 'dem', category: 'time', chapter: 'chapter14', difficulty: 1, examples: ['Peaceful night sleep.'] },
  { id: 'time15', english: 'Midnight', vietnamese: 'Nửa đêm', pronunciation: 'nua dem', category: 'time', chapter: 'chapter14', difficulty: 1, examples: ['Midnight train departure.'] },
  { id: 'time16', english: 'Noon', vietnamese: 'Trưa', pronunciation: 'trua', category: 'time', chapter: 'chapter14', difficulty: 1, examples: ['Lunch at noon.'] },
  { id: 'time17', english: 'Dawn', vietnamese: 'Bình minh', pronunciation: 'binh minh', category: 'time', chapter: 'chapter14', difficulty: 1, examples: ['Beautiful dawn sky.'] },
  { id: 'time18', english: 'Dusk', vietnamese: 'Hoàng hôn', pronunciation: 'hoang hon', category: 'time', chapter: 'chapter14', difficulty: 1, examples: ['Orange dusk colors.'] },
  { id: 'time19', english: 'Sunrise', vietnamese: 'Mặt trời mọc', pronunciation: 'mat troi moc', category: 'time', chapter: 'chapter14', difficulty: 1, examples: ['Watch sunrise daily.'] },
  { id: 'time20', english: 'Sunset', vietnamese: 'Mặt trời lặn', pronunciation: 'mat troi lan', category: 'time', chapter: 'chapter14', difficulty: 1, examples: ['Romantic sunset view.'] },
  { id: 'time21', english: 'Today', vietnamese: 'Hôm nay', pronunciation: 'hom nay', category: 'time', chapter: 'chapter14', difficulty: 1, examples: ['Today is special day.'] },
  { id: 'time22', english: 'Yesterday', vietnamese: 'Hôm qua', pronunciation: 'hom qua', category: 'time', chapter: 'chapter14', difficulty: 1, examples: ['Yesterday was busy.'] },
  { id: 'time23', english: 'Tomorrow', vietnamese: 'Ngày mai', pronunciation: 'ngay mai', category: 'time', chapter: 'chapter14', difficulty: 1, examples: ['Tomorrow brings opportunities.'] },
  { id: 'time24', english: 'Now', vietnamese: 'Bây giờ', pronunciation: 'bay gio', category: 'time', chapter: 'chapter14', difficulty: 1, examples: ['Do it now.'] },
  { id: 'time25', english: 'Later', vietnamese: 'Sau này', pronunciation: 'sau nay', category: 'time', chapter: 'chapter14', difficulty: 1, examples: ['Call you later.'] },

  // Days of Week (7 words)
  { id: 'day1', english: 'Monday', vietnamese: 'Thứ hai', pronunciation: 'thu hai', category: 'day', chapter: 'chapter14', difficulty: 1, examples: ['Monday starts work week.'] },
  { id: 'day2', english: 'Tuesday', vietnamese: 'Thứ ba', pronunciation: 'thu ba', category: 'day', chapter: 'chapter14', difficulty: 1, examples: ['Tuesday meeting scheduled.'] },
  { id: 'day3', english: 'Wednesday', vietnamese: 'Thứ tư', pronunciation: 'thu tu', category: 'day', chapter: 'chapter14', difficulty: 1, examples: ['Wednesday is mid-week.'] },
  { id: 'day4', english: 'Thursday', vietnamese: 'Thứ năm', pronunciation: 'thu nam', category: 'day', chapter: 'chapter14', difficulty: 1, examples: ['Thursday presentation ready.'] },
  { id: 'day5', english: 'Friday', vietnamese: 'Thứ sáu', pronunciation: 'thu sau', category: 'day', chapter: 'chapter14', difficulty: 1, examples: ['Friday afternoon relaxation.'] },
  { id: 'day6', english: 'Saturday', vietnamese: 'Thứ bảy', pronunciation: 'thu bay', category: 'day', chapter: 'chapter14', difficulty: 1, examples: ['Saturday family time.'] },
  { id: 'day7', english: 'Sunday', vietnamese: 'Chủ nhật', pronunciation: 'chu nhat', category: 'day', chapter: 'chapter14', difficulty: 1, examples: ['Sunday rest day.'] },

  // Months of Year (12 words)
  { id: 'month1', english: 'January', vietnamese: 'Tháng một', pronunciation: 'thang mot', category: 'month', chapter: 'chapter14', difficulty: 1, examples: ['January starts new year.'] },
  { id: 'month2', english: 'February', vietnamese: 'Tháng hai', pronunciation: 'thang hai', category: 'month', chapter: 'chapter14', difficulty: 1, examples: ['February is shortest month.'] },
  { id: 'month3', english: 'March', vietnamese: 'Tháng ba', pronunciation: 'thang ba', category: 'month', chapter: 'chapter14', difficulty: 1, examples: ['March brings spring.'] },
  { id: 'month4', english: 'April', vietnamese: 'Tháng tư', pronunciation: 'thang tu', category: 'month', chapter: 'chapter14', difficulty: 1, examples: ['April showers bring flowers.'] },
  { id: 'month5', english: 'May', vietnamese: 'Tháng năm', pronunciation: 'thang nam', category: 'month', chapter: 'chapter14', difficulty: 1, examples: ['May weather is pleasant.'] },
  { id: 'month6', english: 'June', vietnamese: 'Tháng sáu', pronunciation: 'thang sau', category: 'month', chapter: 'chapter14', difficulty: 1, examples: ['June graduation ceremony.'] },
  { id: 'month7', english: 'July', vietnamese: 'Tháng bảy', pronunciation: 'thang bay', category: 'month', chapter: 'chapter14', difficulty: 1, examples: ['July summer vacation.'] },
  { id: 'month8', english: 'August', vietnamese: 'Tháng tám', pronunciation: 'thang tam', category: 'month', chapter: 'chapter14', difficulty: 1, examples: ['August heat wave.'] },
  { id: 'month9', english: 'September', vietnamese: 'Tháng chín', pronunciation: 'thang chin', category: 'month', chapter: 'chapter14', difficulty: 1, examples: ['September school starts.'] },
  { id: 'month10', english: 'October', vietnamese: 'Tháng mười', pronunciation: 'thang muoi', category: 'month', chapter: 'chapter14', difficulty: 1, examples: ['October autumn colors.'] },
  { id: 'month11', english: 'November', vietnamese: 'Tháng mười một', pronunciation: 'thang muoi mot', category: 'month', chapter: 'chapter14', difficulty: 1, examples: ['November thanksgiving dinner.'] },
  { id: 'month12', english: 'December', vietnamese: 'Tháng mười hai', pronunciation: 'thang muoi hai', category: 'month', chapter: 'chapter14', difficulty: 1, examples: ['December holiday season.'] },

  // Seasons & Calendar Terms (31 words)
  { id: 'season1', english: 'Spring', vietnamese: 'Mùa xuân', pronunciation: 'mua xuan', category: 'season', chapter: 'chapter14', difficulty: 1, examples: ['Spring flowers bloom.'] },
  { id: 'season2', english: 'Summer', vietnamese: 'Mùa hè', pronunciation: 'mua he', category: 'season', chapter: 'chapter14', difficulty: 1, examples: ['Summer vacation fun.'] },
  { id: 'season3', english: 'Autumn', vietnamese: 'Mùa thu', pronunciation: 'mua thu', category: 'season', chapter: 'chapter14', difficulty: 1, examples: ['Autumn leaves change color.'] },
  { id: 'season4', english: 'Winter', vietnamese: 'Mùa đông', pronunciation: 'mua dong', category: 'season', chapter: 'chapter14', difficulty: 1, examples: ['Winter snow falls.'] },
  { id: 'calendar1', english: 'Calendar', vietnamese: 'Lịch', pronunciation: 'lich', category: 'calendar', chapter: 'chapter14', difficulty: 1, examples: ['Check calendar for dates.'] },
  { id: 'calendar2', english: 'Date', vietnamese: 'Ngày tháng', pronunciation: 'ngay thang', category: 'calendar', chapter: 'chapter14', difficulty: 1, examples: ['Important date to remember.'] },
  { id: 'calendar3', english: 'Schedule', vietnamese: 'Lịch trình', pronunciation: 'lich trinh', category: 'calendar', chapter: 'chapter14', difficulty: 1, examples: ['Busy schedule today.'] },
  { id: 'calendar4', english: 'Appointment', vietnamese: 'Cuộc hẹn', pronunciation: 'cuoc hen', category: 'calendar', chapter: 'chapter14', difficulty: 1, examples: ['Doctor appointment tomorrow.'] },
  { id: 'calendar5', english: 'Meeting', vietnamese: 'Cuộc họp', pronunciation: 'cuoc hop', category: 'calendar', chapter: 'chapter14', difficulty: 1, examples: ['Important meeting scheduled.'] },
  { id: 'calendar6', english: 'Deadline', vietnamese: 'Hạn chót', pronunciation: 'han chot', category: 'calendar', chapter: 'chapter14', difficulty: 1, examples: ['Project deadline approaching.'] },
  { id: 'calendar7', english: 'Event', vietnamese: 'Sự kiện', pronunciation: 'su kien', category: 'calendar', chapter: 'chapter14', difficulty: 1, examples: ['Special event planned.'] },
  { id: 'calendar8', english: 'Holiday', vietnamese: 'Ngày lễ', pronunciation: 'ngay le', category: 'calendar', chapter: 'chapter14', difficulty: 1, examples: ['National holiday celebration.'] },
  { id: 'calendar9', english: 'Weekend', vietnamese: 'Cuối tuần', pronunciation: 'cuoi tuan', category: 'calendar', chapter: 'chapter14', difficulty: 1, examples: ['Relaxing weekend plans.'] },
  { id: 'calendar10', english: 'Weekday', vietnamese: 'Ngày trong tuần', pronunciation: 'ngay trong tuan', category: 'calendar', chapter: 'chapter14', difficulty: 1, examples: ['Busy weekday schedule.'] },
  { id: 'calendar11', english: 'Birthday', vietnamese: 'Sinh nhật', pronunciation: 'sinh nhat', category: 'calendar', chapter: 'chapter14', difficulty: 1, examples: ['Birthday party invitation.'] },
  { id: 'calendar12', english: 'Anniversary', vietnamese: 'Kỷ niệm', pronunciation: 'ky niem', category: 'calendar', chapter: 'chapter14', difficulty: 1, examples: ['Wedding anniversary celebration.'] },
  { id: 'calendar13', english: 'Age', vietnamese: 'Tuổi', pronunciation: 'tuoi', category: 'calendar', chapter: 'chapter14', difficulty: 1, examples: ['Age is just number.'] },
  { id: 'time26', english: 'Clock', vietnamese: 'Đồng hồ', pronunciation: 'dong ho', category: 'time', chapter: 'chapter14', difficulty: 1, examples: ['Wall clock shows time.'] },
  { id: 'time27', english: 'Watch', vietnamese: 'Đồng hồ đeo tay', pronunciation: 'dong ho deo tay', category: 'time', chapter: 'chapter14', difficulty: 1, examples: ['Smart watch tracks steps.'] },
  { id: 'time28', english: 'Timer', vietnamese: 'Đồng hồ bấm giờ', pronunciation: 'dong ho bam gio', category: 'time', chapter: 'chapter14', difficulty: 1, examples: ['Set timer for cooking.'] },
  { id: 'time29', english: 'Alarm', vietnamese: 'Báo thức', pronunciation: 'bao thuc', category: 'time', chapter: 'chapter14', difficulty: 1, examples: ['Alarm rings at seven.'] },
  { id: 'time30', english: 'Early', vietnamese: 'Sớm', pronunciation: 'som', category: 'time', chapter: 'chapter14', difficulty: 1, examples: ['Arrive early for meeting.'] },
  { id: 'time31', english: 'Late', vietnamese: 'Muộn', pronunciation: 'muon', category: 'time', chapter: 'chapter14', difficulty: 1, examples: ['Running late for work.'] },
  { id: 'time32', english: 'On time', vietnamese: 'Đúng giờ', pronunciation: 'dung gio', category: 'time', chapter: 'chapter14', difficulty: 1, examples: ['Always arrive on time.'] },
  { id: 'time33', english: 'Fast', vietnamese: 'Nhanh', pronunciation: 'nhanh', category: 'time', chapter: 'chapter14', difficulty: 1, examples: ['Fast internet connection.'] },
  { id: 'time34', english: 'Slow', vietnamese: 'Chậm', pronunciation: 'cham', category: 'time', chapter: 'chapter14', difficulty: 1, examples: ['Slow traffic today.'] },
  { id: 'time35', english: 'Quick', vietnamese: 'Nhanh chóng', pronunciation: 'nhanh chong', category: 'time', chapter: 'chapter14', difficulty: 1, examples: ['Quick response needed.'] },
  { id: 'time36', english: 'Immediate', vietnamese: 'Ngay lập tức', pronunciation: 'ngay lap tuc', category: 'time', chapter: 'chapter14', difficulty: 1, examples: ['Immediate action required.'] },
  { id: 'time37', english: 'Sudden', vietnamese: 'Đột ngột', pronunciation: 'dot ngot', category: 'time', chapter: 'chapter14', difficulty: 1, examples: ['Sudden weather change.'] },
  { id: 'time38', english: 'Gradual', vietnamese: 'Dần dần', pronunciation: 'dan dan', category: 'time', chapter: 'chapter14', difficulty: 1, examples: ['Gradual improvement noticed.'] },
  { id: 'time39', english: 'Temporary', vietnamese: 'Tạm thời', pronunciation: 'tam thoi', category: 'time', chapter: 'chapter14', difficulty: 1, examples: ['Temporary solution works.'] },
  { id: 'time40', english: 'Permanent', vietnamese: 'Vĩnh viễn', pronunciation: 'vinh vien', category: 'time', chapter: 'chapter14', difficulty: 1, examples: ['Permanent job position.'] },
  { id: 'time41', english: 'Forever', vietnamese: 'Mãi mãi', pronunciation: 'mai mai', category: 'time', chapter: 'chapter14', difficulty: 1, examples: ['Love lasts forever.'] },
  { id: 'time42', english: 'Never', vietnamese: 'Không bao giờ', pronunciation: 'khong bao gio', category: 'time', chapter: 'chapter14', difficulty: 1, examples: ['Never give up dreams.'] },
  { id: 'time43', english: 'Always', vietnamese: 'Luôn luôn', pronunciation: 'luon luon', category: 'time', chapter: 'chapter14', difficulty: 1, examples: ['Always be kind.'] },
  { id: 'time44', english: 'Sometimes', vietnamese: 'Thỉnh thoảng', pronunciation: 'thinh thoang', category: 'time', chapter: 'chapter14', difficulty: 1, examples: ['Sometimes need break.'] },
  { id: 'time45', english: 'Often', vietnamese: 'Thường xuyên', pronunciation: 'thuong xuyen', category: 'time', chapter: 'chapter14', difficulty: 1, examples: ['Often visit family.'] }
]
