// Chapter 25: Emotions & Feelings (100 Essential Words)
// Words related to emotions, feelings, moods, and psychological states

import { LanguageWord } from './chapter01-basic-everyday'

export const chapter25Words: LanguageWord[] = [
  // Positive Emotions (25 words)
  { id: 'positive1', english: 'Happy', vietnamese: 'Vui vẻ', pronunciation: 'vui ve', category: 'positive', chapter: 'chapter25', difficulty: 1, examples: ['Happy birthday celebration.'] },
  { id: 'positive2', english: 'Joy', vietnamese: 'Niềm vui', pronunciation: 'niem vui', category: 'positive', chapter: 'chapter25', difficulty: 1, examples: ['Joy fills heart.'] },
  { id: 'positive3', english: 'Excited', vietnamese: 'Phấn khích', pronunciation: 'phan khich', category: 'positive', chapter: 'chapter25', difficulty: 1, examples: ['Excited about trip.'] },
  { id: 'positive4', english: 'Cheerful', vietnamese: 'Vui tươi', pronunciation: 'vui tuoi', category: 'positive', chapter: 'chapter25', difficulty: 1, examples: ['Cheerful morning greeting.'] },
  { id: 'positive5', english: 'Delighted', vietnamese: 'Thích thú', pronunciation: 'thich thu', category: 'positive', chapter: 'chapter25', difficulty: 1, examples: ['Delighted with gift.'] },
  { id: 'positive6', english: 'Pleased', vietnamese: 'Hài lòng', pronunciation: 'hai long', category: 'positive', chapter: 'chapter25', difficulty: 1, examples: ['Pleased with results.'] },
  { id: 'positive7', english: 'Satisfied', vietnamese: 'Hài lòng', pronunciation: 'hai long', category: 'positive', chapter: 'chapter25', difficulty: 1, examples: ['Satisfied with work.'] },
  { id: 'positive8', english: 'Content', vietnamese: 'Bằng lòng', pronunciation: 'bang long', category: 'positive', chapter: 'chapter25', difficulty: 1, examples: ['Content with life.'] },
  { id: 'positive9', english: 'Grateful', vietnamese: 'Biết ơn', pronunciation: 'biet on', category: 'positive', chapter: 'chapter25', difficulty: 1, examples: ['Grateful for help.'] },
  { id: 'positive10', english: 'Thankful', vietnamese: 'Cảm ơn', pronunciation: 'cam on', category: 'positive', chapter: 'chapter25', difficulty: 1, examples: ['Thankful for friendship.'] },
  { id: 'positive11', english: 'Proud', vietnamese: 'Tự hào', pronunciation: 'tu hao', category: 'positive', chapter: 'chapter25', difficulty: 1, examples: ['Proud of achievement.'] },
  { id: 'positive12', english: 'Confident', vietnamese: 'Tự tin', pronunciation: 'tu tin', category: 'positive', chapter: 'chapter25', difficulty: 1, examples: ['Confident in abilities.'] },
  { id: 'positive13', english: 'Optimistic', vietnamese: 'Lạc quan', pronunciation: 'lac quan', category: 'positive', chapter: 'chapter25', difficulty: 1, examples: ['Optimistic about future.'] },
  { id: 'positive14', english: 'Hopeful', vietnamese: 'Hy vọng', pronunciation: 'hy vong', category: 'positive', chapter: 'chapter25', difficulty: 1, examples: ['Hopeful for success.'] },
  { id: 'positive15', english: 'Enthusiastic', vietnamese: 'Nhiệt tình', pronunciation: 'nhiet tinh', category: 'positive', chapter: 'chapter25', difficulty: 2, examples: ['Enthusiastic about project.'] },
  { id: 'positive16', english: 'Energetic', vietnamese: 'Năng động', pronunciation: 'nang dong', category: 'positive', chapter: 'chapter25', difficulty: 1, examples: ['Energetic morning exercise.'] },
  { id: 'positive17', english: 'Relaxed', vietnamese: 'Thư giãn', pronunciation: 'thu gian', category: 'positive', chapter: 'chapter25', difficulty: 1, examples: ['Relaxed weekend mood.'] },
  { id: 'positive18', english: 'Peaceful', vietnamese: 'Bình yên', pronunciation: 'binh yen', category: 'positive', chapter: 'chapter25', difficulty: 1, examples: ['Peaceful garden setting.'] },
  { id: 'positive19', english: 'Calm', vietnamese: 'Bình tĩnh', pronunciation: 'binh tinh', category: 'positive', chapter: 'chapter25', difficulty: 1, examples: ['Calm during crisis.'] },
  { id: 'positive20', english: 'Comfortable', vietnamese: 'Thoải mái', pronunciation: 'thoai mai', category: 'positive', chapter: 'chapter25', difficulty: 1, examples: ['Comfortable at home.'] },
  { id: 'positive21', english: 'Amazed', vietnamese: 'Ngạc nhiên', pronunciation: 'ngac nhien', category: 'positive', chapter: 'chapter25', difficulty: 1, examples: ['Amazed by beauty.'] },
  { id: 'positive22', english: 'Impressed', vietnamese: 'Ấn tượng', pronunciation: 'an tuong', category: 'positive', chapter: 'chapter25', difficulty: 1, examples: ['Impressed with performance.'] },
  { id: 'positive23', english: 'Inspired', vietnamese: 'Cảm hứng', pronunciation: 'cam hung', category: 'positive', chapter: 'chapter25', difficulty: 1, examples: ['Inspired by story.'] },
  { id: 'positive24', english: 'Motivated', vietnamese: 'Có động lực', pronunciation: 'co dong luc', category: 'positive', chapter: 'chapter25', difficulty: 1, examples: ['Motivated to succeed.'] },
  { id: 'positive25', english: 'Blessed', vietnamese: 'May mắn', pronunciation: 'may man', category: 'positive', chapter: 'chapter25', difficulty: 1, examples: ['Blessed with family.'] },

  // Negative Emotions (25 words)
  { id: 'negative1', english: 'Sad', vietnamese: 'Buồn', pronunciation: 'buon', category: 'negative', chapter: 'chapter25', difficulty: 1, examples: ['Sad about departure.'] },
  { id: 'negative2', english: 'Angry', vietnamese: 'Tức giận', pronunciation: 'tuc gian', category: 'negative', chapter: 'chapter25', difficulty: 1, examples: ['Angry at injustice.'] },
  { id: 'negative3', english: 'Upset', vietnamese: 'Bực mình', pronunciation: 'buc minh', category: 'negative', chapter: 'chapter25', difficulty: 1, examples: ['Upset about news.'] },
  { id: 'negative4', english: 'Worried', vietnamese: 'Lo lắng', pronunciation: 'lo lang', category: 'negative', chapter: 'chapter25', difficulty: 1, examples: ['Worried about test.'] },
  { id: 'negative5', english: 'Anxious', vietnamese: 'Âu lo', pronunciation: 'au lo', category: 'negative', chapter: 'chapter25', difficulty: 1, examples: ['Anxious before interview.'] },
  { id: 'negative6', english: 'Nervous', vietnamese: 'Bồn chồn', pronunciation: 'bon chon', category: 'negative', chapter: 'chapter25', difficulty: 1, examples: ['Nervous first day.'] },
  { id: 'negative7', english: 'Scared', vietnamese: 'Sợ hãi', pronunciation: 'so hai', category: 'negative', chapter: 'chapter25', difficulty: 1, examples: ['Scared of darkness.'] },
  { id: 'negative8', english: 'Afraid', vietnamese: 'Sợ', pronunciation: 'so', category: 'negative', chapter: 'chapter25', difficulty: 1, examples: ['Afraid of heights.'] },
  { id: 'negative9', english: 'Frightened', vietnamese: 'Hoảng sợ', pronunciation: 'hoang so', category: 'negative', chapter: 'chapter25', difficulty: 1, examples: ['Frightened by noise.'] },
  { id: 'negative10', english: 'Disappointed', vietnamese: 'Thất vọng', pronunciation: 'that vong', category: 'negative', chapter: 'chapter25', difficulty: 1, examples: ['Disappointed with outcome.'] },
  { id: 'negative11', english: 'Frustrated', vietnamese: 'Thất bại', pronunciation: 'that bai', category: 'negative', chapter: 'chapter25', difficulty: 1, examples: ['Frustrated with delay.'] },
  { id: 'negative12', english: 'Annoyed', vietnamese: 'Khó chịu', pronunciation: 'kho chiu', category: 'negative', chapter: 'chapter25', difficulty: 1, examples: ['Annoyed by noise.'] },
  { id: 'negative13', english: 'Irritated', vietnamese: 'Bực tức', pronunciation: 'buc tuc', category: 'negative', chapter: 'chapter25', difficulty: 1, examples: ['Irritated by interruption.'] },
  { id: 'negative14', english: 'Stressed', vietnamese: 'Căng thẳng', pronunciation: 'cang thang', category: 'negative', chapter: 'chapter25', difficulty: 1, examples: ['Stressed about deadline.'] },
  { id: 'negative15', english: 'Overwhelmed', vietnamese: 'Quá tải', pronunciation: 'qua tai', category: 'negative', chapter: 'chapter25', difficulty: 2, examples: ['Overwhelmed with work.'] },
  { id: 'negative16', english: 'Depressed', vietnamese: 'Trầm cảm', pronunciation: 'tram cam', category: 'negative', chapter: 'chapter25', difficulty: 2, examples: ['Depressed after loss.'] },
  { id: 'negative17', english: 'Lonely', vietnamese: 'Cô đơn', pronunciation: 'co don', category: 'negative', chapter: 'chapter25', difficulty: 1, examples: ['Lonely without friends.'] },
  { id: 'negative18', english: 'Jealous', vietnamese: 'Ghen tức', pronunciation: 'ghen tuc', category: 'negative', chapter: 'chapter25', difficulty: 1, examples: ['Jealous of success.'] },
  { id: 'negative19', english: 'Envious', vietnamese: 'Ganh tỵ', pronunciation: 'ganh ty', category: 'negative', chapter: 'chapter25', difficulty: 2, examples: ['Envious of lifestyle.'] },
  { id: 'negative20', english: 'Guilty', vietnamese: 'Cảm thấy tội lỗi', pronunciation: 'cam thay toi loi', category: 'negative', chapter: 'chapter25', difficulty: 1, examples: ['Guilty about mistake.'] },
  { id: 'negative21', english: 'Ashamed', vietnamese: 'Xấu hổ', pronunciation: 'xau ho', category: 'negative', chapter: 'chapter25', difficulty: 1, examples: ['Ashamed of behavior.'] },
  { id: 'negative22', english: 'Embarrassed', vietnamese: 'Ngại ngùng', pronunciation: 'ngai ngung', category: 'negative', chapter: 'chapter25', difficulty: 1, examples: ['Embarrassed by fall.'] },
  { id: 'negative23', english: 'Confused', vietnamese: 'Bối rối', pronunciation: 'boi roi', category: 'negative', chapter: 'chapter25', difficulty: 1, examples: ['Confused about directions.'] },
  { id: 'negative24', english: 'Doubtful', vietnamese: 'Nghi ngờ', pronunciation: 'nghi ngo', category: 'negative', chapter: 'chapter25', difficulty: 1, examples: ['Doubtful about plan.'] },
  { id: 'negative25', english: 'Hopeless', vietnamese: 'Tuyệt vọng', pronunciation: 'tuyet vong', category: 'negative', chapter: 'chapter25', difficulty: 1, examples: ['Hopeless situation difficult.'] },

  // Neutral & Complex Emotions (25 words)
  { id: 'neutral1', english: 'Surprised', vietnamese: 'Ngạc nhiên', pronunciation: 'ngac nhien', category: 'neutral', chapter: 'chapter25', difficulty: 1, examples: ['Surprised by visit.'] },
  { id: 'neutral2', english: 'Shocked', vietnamese: 'Sốc', pronunciation: 'soc', category: 'neutral', chapter: 'chapter25', difficulty: 1, examples: ['Shocked by news.'] },
  { id: 'neutral3', english: 'Curious', vietnamese: 'Tò mò', pronunciation: 'to mo', category: 'neutral', chapter: 'chapter25', difficulty: 1, examples: ['Curious about result.'] },
  { id: 'neutral4', english: 'Interested', vietnamese: 'Quan tâm', pronunciation: 'quan tam', category: 'neutral', chapter: 'chapter25', difficulty: 1, examples: ['Interested in subject.'] },
  { id: 'neutral5', english: 'Bored', vietnamese: 'Chán', pronunciation: 'chan', category: 'neutral', chapter: 'chapter25', difficulty: 1, examples: ['Bored with routine.'] },
  { id: 'neutral6', english: 'Tired', vietnamese: 'Mệt', pronunciation: 'met', category: 'neutral', chapter: 'chapter25', difficulty: 1, examples: ['Tired after work.'] },
  { id: 'neutral7', english: 'Sleepy', vietnamese: 'Buồn ngủ', pronunciation: 'buon ngu', category: 'neutral', chapter: 'chapter25', difficulty: 1, examples: ['Sleepy late night.'] },
  { id: 'neutral8', english: 'Awake', vietnamese: 'Tỉnh táo', pronunciation: 'tinh tao', category: 'neutral', chapter: 'chapter25', difficulty: 1, examples: ['Awake early morning.'] },
  { id: 'neutral9', english: 'Alert', vietnamese: 'Cảnh giác', pronunciation: 'canh giac', category: 'neutral', chapter: 'chapter25', difficulty: 1, examples: ['Alert to danger.'] },
  { id: 'neutral10', english: 'Focused', vietnamese: 'Tập trung', pronunciation: 'tap trung', category: 'neutral', chapter: 'chapter25', difficulty: 1, examples: ['Focused on task.'] },
  { id: 'neutral11', english: 'Distracted', vietnamese: 'Mất tập trung', pronunciation: 'mat tap trung', category: 'neutral', chapter: 'chapter25', difficulty: 1, examples: ['Distracted by noise.'] },
  { id: 'neutral12', english: 'Thoughtful', vietnamese: 'Suy nghĩ', pronunciation: 'suy nghi', category: 'neutral', chapter: 'chapter25', difficulty: 1, examples: ['Thoughtful about decision.'] },
  { id: 'neutral13', english: 'Serious', vietnamese: 'Nghiêm túc', pronunciation: 'nghiem tuc', category: 'neutral', chapter: 'chapter25', difficulty: 1, examples: ['Serious about goals.'] },
  { id: 'neutral14', english: 'Playful', vietnamese: 'Nghịch ngợm', pronunciation: 'nghich ngom', category: 'neutral', chapter: 'chapter25', difficulty: 1, examples: ['Playful with children.'] },
  { id: 'neutral15', english: 'Patient', vietnamese: 'Kiên nhẫn', pronunciation: 'kien nhan', category: 'neutral', chapter: 'chapter25', difficulty: 1, examples: ['Patient with learning.'] },
  { id: 'neutral16', english: 'Impatient', vietnamese: 'Thiếu kiên nhẫn', pronunciation: 'thieu kien nhan', category: 'neutral', chapter: 'chapter25', difficulty: 1, examples: ['Impatient for results.'] },
  { id: 'neutral17', english: 'Determined', vietnamese: 'Quyết tâm', pronunciation: 'quyet tam', category: 'neutral', chapter: 'chapter25', difficulty: 1, examples: ['Determined to succeed.'] },
  { id: 'neutral18', english: 'Stubborn', vietnamese: 'Bướng bỉnh', pronunciation: 'buong binh', category: 'neutral', chapter: 'chapter25', difficulty: 1, examples: ['Stubborn about opinion.'] },
  { id: 'neutral19', english: 'Flexible', vietnamese: 'Linh hoạt', pronunciation: 'linh hoat', category: 'neutral', chapter: 'chapter25', difficulty: 1, examples: ['Flexible with plans.'] },
  { id: 'neutral20', english: 'Understanding', vietnamese: 'Hiểu biết', pronunciation: 'hieu biet', category: 'neutral', chapter: 'chapter25', difficulty: 1, examples: ['Understanding friend supportive.'] },
  { id: 'neutral21', english: 'Sympathetic', vietnamese: 'Thông cảm', pronunciation: 'thong cam', category: 'neutral', chapter: 'chapter25', difficulty: 2, examples: ['Sympathetic to problems.'] },
  { id: 'neutral22', english: 'Indifferent', vietnamese: 'Thờ ơ', pronunciation: 'tho o', category: 'neutral', chapter: 'chapter25', difficulty: 2, examples: ['Indifferent to outcome.'] },
  { id: 'neutral23', english: 'Nostalgic', vietnamese: 'Hoài niệm', pronunciation: 'hoai niem', category: 'neutral', chapter: 'chapter25', difficulty: 2, examples: ['Nostalgic about childhood.'] },
  { id: 'neutral24', english: 'Melancholic', vietnamese: 'U sầu', pronunciation: 'u sau', category: 'neutral', chapter: 'chapter25', difficulty: 2, examples: ['Melancholic autumn mood.'] },
  { id: 'neutral25', english: 'Balanced', vietnamese: 'Cân bằng', pronunciation: 'can bang', category: 'neutral', chapter: 'chapter25', difficulty: 1, examples: ['Balanced emotional state.'] },

  // Emotional Expressions & Actions (25 words)
  { id: 'expression1', english: 'Smile', vietnamese: 'Mỉm cười', pronunciation: 'mim cuoi', category: 'expression', chapter: 'chapter25', difficulty: 1, examples: ['Smile shows happiness.'] },
  { id: 'expression2', english: 'Laugh', vietnamese: 'Cười', pronunciation: 'cuoi', category: 'expression', chapter: 'chapter25', difficulty: 1, examples: ['Laugh at joke.'] },
  { id: 'expression3', english: 'Cry', vietnamese: 'Khóc', pronunciation: 'khoc', category: 'expression', chapter: 'chapter25', difficulty: 1, examples: ['Cry from sadness.'] },
  { id: 'expression4', english: 'Tears', vietnamese: 'Nước mắt', pronunciation: 'nuoc mat', category: 'expression', chapter: 'chapter25', difficulty: 1, examples: ['Tears show emotion.'] },
  { id: 'expression5', english: 'Frown', vietnamese: 'Cau mày', pronunciation: 'cau may', category: 'expression', chapter: 'chapter25', difficulty: 1, examples: ['Frown shows disapproval.'] },
  { id: 'expression6', english: 'Sigh', vietnamese: 'Thở dài', pronunciation: 'tho dai', category: 'expression', chapter: 'chapter25', difficulty: 1, examples: ['Sigh shows relief.'] },
  { id: 'expression7', english: 'Yawn', vietnamese: 'Ngáp', pronunciation: 'ngap', category: 'expression', chapter: 'chapter25', difficulty: 1, examples: ['Yawn shows tiredness.'] },
  { id: 'expression8', english: 'Blush', vietnamese: 'Đỏ mặt', pronunciation: 'do mat', category: 'expression', chapter: 'chapter25', difficulty: 1, examples: ['Blush from embarrassment.'] },
  { id: 'expression9', english: 'Shiver', vietnamese: 'Run rẩy', pronunciation: 'run ray', category: 'expression', chapter: 'chapter25', difficulty: 1, examples: ['Shiver from cold.'] },
  { id: 'expression10', english: 'Tremble', vietnamese: 'Rung', pronunciation: 'rung', category: 'expression', chapter: 'chapter25', difficulty: 1, examples: ['Tremble with fear.'] },
  { id: 'expression11', english: 'Gasp', vietnamese: 'Thở hổn hển', pronunciation: 'tho hon hen', category: 'expression', chapter: 'chapter25', difficulty: 1, examples: ['Gasp in surprise.'] },
  { id: 'expression12', english: 'Scream', vietnamese: 'La hét', pronunciation: 'la het', category: 'expression', chapter: 'chapter25', difficulty: 1, examples: ['Scream in terror.'] },
  { id: 'expression13', english: 'Whisper', vietnamese: 'Thì thầm', pronunciation: 'thi tham', category: 'expression', chapter: 'chapter25', difficulty: 1, examples: ['Whisper secret softly.'] },
  { id: 'expression14', english: 'Hug', vietnamese: 'Ôm', pronunciation: 'om', category: 'expression', chapter: 'chapter25', difficulty: 1, examples: ['Hug shows affection.'] },
  { id: 'expression15', english: 'Kiss', vietnamese: 'Hôn', pronunciation: 'hon', category: 'expression', chapter: 'chapter25', difficulty: 1, examples: ['Kiss goodbye tender.'] },
  { id: 'expression16', english: 'Wave', vietnamese: 'Vẫy tay', pronunciation: 'vay tay', category: 'expression', chapter: 'chapter25', difficulty: 1, examples: ['Wave hello friendly.'] },
  { id: 'expression17', english: 'Nod', vietnamese: 'Gật đầu', pronunciation: 'gat dau', category: 'expression', chapter: 'chapter25', difficulty: 1, examples: ['Nod shows agreement.'] },
  { id: 'expression18', english: 'Shake head', vietnamese: 'Lắc đầu', pronunciation: 'lac dau', category: 'expression', chapter: 'chapter25', difficulty: 1, examples: ['Shake head means no.'] },
  { id: 'expression19', english: 'Clap', vietnamese: 'Vỗ tay', pronunciation: 'vo tay', category: 'expression', chapter: 'chapter25', difficulty: 1, examples: ['Clap hands applause.'] },
  { id: 'expression20', english: 'Point', vietnamese: 'Chỉ', pronunciation: 'chi', category: 'expression', chapter: 'chapter25', difficulty: 1, examples: ['Point at object.'] },
  { id: 'expression21', english: 'Gesture', vietnamese: 'Cử chỉ', pronunciation: 'cu chi', category: 'expression', chapter: 'chapter25', difficulty: 1, examples: ['Gesture communicates meaning.'] },
  { id: 'expression22', english: 'Expression', vietnamese: 'Biểu hiện', pronunciation: 'bieu hien', category: 'expression', chapter: 'chapter25', difficulty: 1, examples: ['Expression shows feeling.'] },
  { id: 'expression23', english: 'Mood', vietnamese: 'Tâm trạng', pronunciation: 'tam trang', category: 'expression', chapter: 'chapter25', difficulty: 1, examples: ['Mood changes daily.'] },
  { id: 'expression24', english: 'Feeling', vietnamese: 'Cảm giác', pronunciation: 'cam giac', category: 'expression', chapter: 'chapter25', difficulty: 1, examples: ['Feeling happy today.'] },
  { id: 'expression25', english: 'Emotion', vietnamese: 'Cảm xúc', pronunciation: 'cam xuc', category: 'expression', chapter: 'chapter25', difficulty: 1, examples: ['Emotion affects behavior.'] }
]
