// Chapter 15: Transportation & Travel (100 Essential Words)
// Words related to vehicles, travel, transportation, and movement

import { LanguageWord } from './chapter01-basic-everyday'

export const chapter15Words: LanguageWord[] = [
  // Vehicles & Transportation (25 words)
  { id: 'vehicle1', english: 'Car', vietnamese: 'Ô tô', pronunciation: 'o to', category: 'vehicle', chapter: 'chapter15', difficulty: 1, examples: ['Drive car to work.'] },
  { id: 'vehicle2', english: 'Bus', vietnamese: 'Xe buýt', pronunciation: 'xe buyt', category: 'vehicle', chapter: 'chapter15', difficulty: 1, examples: ['Take bus downtown.'] },
  { id: 'vehicle3', english: 'Train', vietnamese: 'Tàu hỏa', pronunciation: 'tau hoa', category: 'vehicle', chapter: 'chapter15', difficulty: 1, examples: ['Fast train service.'] },
  { id: 'vehicle4', english: 'Airplane', vietnamese: 'Máy bay', pronunciation: 'may bay', category: 'vehicle', chapter: 'chapter15', difficulty: 1, examples: ['Airplane flies high.'] },
  { id: 'vehicle5', english: 'Ship', vietnamese: 'Tàu thủy', pronunciation: 'tau thuy', category: 'vehicle', chapter: 'chapter15', difficulty: 1, examples: ['Ship crosses ocean.'] },
  { id: 'vehicle6', english: 'Boat', vietnamese: 'Thuyền', pronunciation: 'thuyen', category: 'vehicle', chapter: 'chapter15', difficulty: 1, examples: ['Small boat on lake.'] },
  { id: 'vehicle7', english: 'Bicycle', vietnamese: 'Xe đạp', pronunciation: 'xe dap', category: 'vehicle', chapter: 'chapter15', difficulty: 1, examples: ['Ride bicycle for exercise.'] },
  { id: 'vehicle8', english: 'Motorcycle', vietnamese: 'Xe máy', pronunciation: 'xe may', category: 'vehicle', chapter: 'chapter15', difficulty: 1, examples: ['Fast motorcycle ride.'] },
  { id: 'vehicle9', english: 'Truck', vietnamese: 'Xe tải', pronunciation: 'xe tai', category: 'vehicle', chapter: 'chapter15', difficulty: 1, examples: ['Truck delivers goods.'] },
  { id: 'vehicle10', english: 'Van', vietnamese: 'Xe van', pronunciation: 'xe van', category: 'vehicle', chapter: 'chapter15', difficulty: 1, examples: ['Van carries passengers.'] },
  { id: 'vehicle11', english: 'Taxi', vietnamese: 'Taxi', pronunciation: 'taxi', category: 'vehicle', chapter: 'chapter15', difficulty: 1, examples: ['Call taxi to airport.'] },
  { id: 'vehicle12', english: 'Subway', vietnamese: 'Tàu điện ngầm', pronunciation: 'tau dien ngam', category: 'vehicle', chapter: 'chapter15', difficulty: 1, examples: ['Subway runs underground.'] },
  { id: 'vehicle13', english: 'Helicopter', vietnamese: 'Trực thăng', pronunciation: 'truc thang', category: 'vehicle', chapter: 'chapter15', difficulty: 1, examples: ['Helicopter rescues people.'] },
  { id: 'vehicle14', english: 'Scooter', vietnamese: 'Xe scooter', pronunciation: 'xe scooter', category: 'vehicle', chapter: 'chapter15', difficulty: 1, examples: ['Electric scooter rental.'] },
  { id: 'vehicle15', english: 'Skateboard', vietnamese: 'Ván trượt', pronunciation: 'van truot', category: 'vehicle', chapter: 'chapter15', difficulty: 1, examples: ['Skateboard in park.'] },
  { id: 'vehicle16', english: 'Trolley', vietnamese: 'Xe điện', pronunciation: 'xe dien', category: 'vehicle', chapter: 'chapter15', difficulty: 1, examples: ['Historic trolley tour.'] },
  { id: 'vehicle17', english: 'Ferry', vietnamese: 'Phà', pronunciation: 'pha', category: 'vehicle', chapter: 'chapter15', difficulty: 1, examples: ['Ferry crosses river.'] },
  { id: 'vehicle18', english: 'Yacht', vietnamese: 'Du thuyền', pronunciation: 'du thuyen', category: 'vehicle', chapter: 'chapter15', difficulty: 1, examples: ['Luxury yacht cruise.'] },
  { id: 'vehicle19', english: 'Jet', vietnamese: 'Máy bay phản lực', pronunciation: 'may bay phan luc', category: 'vehicle', chapter: 'chapter15', difficulty: 2, examples: ['Private jet travel.'] },
  { id: 'vehicle20', english: 'Rocket', vietnamese: 'Tên lửa', pronunciation: 'ten lua', category: 'vehicle', chapter: 'chapter15', difficulty: 1, examples: ['Rocket launches to space.'] },
  { id: 'vehicle21', english: 'Ambulance', vietnamese: 'Xe cứu thương', pronunciation: 'xe cuu thuong', category: 'vehicle', chapter: 'chapter15', difficulty: 1, examples: ['Ambulance rushes to hospital.'] },
  { id: 'vehicle22', english: 'Fire truck', vietnamese: 'Xe cứu hỏa', pronunciation: 'xe cuu hoa', category: 'vehicle', chapter: 'chapter15', difficulty: 1, examples: ['Fire truck responds quickly.'] },
  { id: 'vehicle23', english: 'Police car', vietnamese: 'Xe cảnh sát', pronunciation: 'xe canh sat', category: 'vehicle', chapter: 'chapter15', difficulty: 1, examples: ['Police car patrols streets.'] },
  { id: 'vehicle24', english: 'Limousine', vietnamese: 'Xe limousine', pronunciation: 'xe limousine', category: 'vehicle', chapter: 'chapter15', difficulty: 1, examples: ['Wedding limousine service.'] },
  { id: 'vehicle25', english: 'Caravan', vietnamese: 'Xe caravan', pronunciation: 'xe caravan', category: 'vehicle', chapter: 'chapter15', difficulty: 1, examples: ['Camping with caravan.'] },

  // Travel & Journey (25 words)
  { id: 'travel1', english: 'Travel', vietnamese: 'Du lịch', pronunciation: 'du lich', category: 'travel', chapter: 'chapter15', difficulty: 1, examples: ['Love to travel abroad.'] },
  { id: 'travel2', english: 'Trip', vietnamese: 'Chuyến đi', pronunciation: 'chuyen di', category: 'travel', chapter: 'chapter15', difficulty: 1, examples: ['Business trip next week.'] },
  { id: 'travel3', english: 'Journey', vietnamese: 'Hành trình', pronunciation: 'hanh trinh', category: 'travel', chapter: 'chapter15', difficulty: 1, examples: ['Long journey ahead.'] },
  { id: 'travel4', english: 'Vacation', vietnamese: 'Kỳ nghỉ', pronunciation: 'ky nghi', category: 'travel', chapter: 'chapter15', difficulty: 1, examples: ['Summer vacation plans.'] },
  { id: 'travel5', english: 'Holiday', vietnamese: 'Ngày lễ', pronunciation: 'ngay le', category: 'travel', chapter: 'chapter15', difficulty: 1, examples: ['Holiday celebration time.'] },
  { id: 'travel6', english: 'Tour', vietnamese: 'Chuyến tham quan', pronunciation: 'chuyen tham quan', category: 'travel', chapter: 'chapter15', difficulty: 1, examples: ['Guided city tour.'] },
  { id: 'travel7', english: 'Adventure', vietnamese: 'Cuộc phiêu lưu', pronunciation: 'cuoc phieu luu', category: 'travel', chapter: 'chapter15', difficulty: 1, examples: ['Adventure in mountains.'] },
  { id: 'travel8', english: 'Expedition', vietnamese: 'Thám hiểm', pronunciation: 'tham hiem', category: 'travel', chapter: 'chapter15', difficulty: 2, examples: ['Scientific expedition team.'] },
  { id: 'travel9', english: 'Cruise', vietnamese: 'Du thuyền', pronunciation: 'du thuyen', category: 'travel', chapter: 'chapter15', difficulty: 1, examples: ['Ocean cruise vacation.'] },
  { id: 'travel10', english: 'Safari', vietnamese: 'Safari', pronunciation: 'safari', category: 'travel', chapter: 'chapter15', difficulty: 1, examples: ['African safari adventure.'] },
  { id: 'travel11', english: 'Pilgrimage', vietnamese: 'Hành hương', pronunciation: 'hanh huong', category: 'travel', chapter: 'chapter15', difficulty: 2, examples: ['Religious pilgrimage journey.'] },
  { id: 'travel12', english: 'Migration', vietnamese: 'Di cư', pronunciation: 'di cu', category: 'travel', chapter: 'chapter15', difficulty: 2, examples: ['Bird migration season.'] },
  { id: 'travel13', english: 'Commute', vietnamese: 'Đi làm', pronunciation: 'di lam', category: 'travel', chapter: 'chapter15', difficulty: 1, examples: ['Daily commute to office.'] },
  { id: 'travel14', english: 'Route', vietnamese: 'Tuyến đường', pronunciation: 'tuyen duong', category: 'travel', chapter: 'chapter15', difficulty: 1, examples: ['Best route to destination.'] },
  { id: 'travel15', english: 'Path', vietnamese: 'Con đường', pronunciation: 'con duong', category: 'travel', chapter: 'chapter15', difficulty: 1, examples: ['Mountain hiking path.'] },
  { id: 'travel16', english: 'Trail', vietnamese: 'Đường mòn', pronunciation: 'duong mon', category: 'travel', chapter: 'chapter15', difficulty: 1, examples: ['Forest trail exploration.'] },
  { id: 'travel17', english: 'Road', vietnamese: 'Đường', pronunciation: 'duong', category: 'travel', chapter: 'chapter15', difficulty: 1, examples: ['Long road to success.'] },
  { id: 'travel18', english: 'Highway', vietnamese: 'Đường cao tốc', pronunciation: 'duong cao toc', category: 'travel', chapter: 'chapter15', difficulty: 1, examples: ['Highway traffic jam.'] },
  { id: 'travel19', english: 'Street', vietnamese: 'Phố', pronunciation: 'pho', category: 'travel', chapter: 'chapter15', difficulty: 1, examples: ['Busy street market.'] },
  { id: 'travel20', english: 'Avenue', vietnamese: 'Đại lộ', pronunciation: 'dai lo', category: 'travel', chapter: 'chapter15', difficulty: 1, examples: ['Famous shopping avenue.'] },
  { id: 'travel21', english: 'Bridge', vietnamese: 'Cầu', pronunciation: 'cau', category: 'travel', chapter: 'chapter15', difficulty: 1, examples: ['Beautiful bridge design.'] },
  { id: 'travel22', english: 'Tunnel', vietnamese: 'Đường hầm', pronunciation: 'duong ham', category: 'travel', chapter: 'chapter15', difficulty: 1, examples: ['Underground tunnel system.'] },
  { id: 'travel23', english: 'Intersection', vietnamese: 'Giao lộ', pronunciation: 'giao lo', category: 'travel', chapter: 'chapter15', difficulty: 1, examples: ['Busy intersection crossing.'] },
  { id: 'travel24', english: 'Roundabout', vietnamese: 'Vòng xoay', pronunciation: 'vong xoay', category: 'travel', chapter: 'chapter15', difficulty: 1, examples: ['Navigate roundabout carefully.'] },
  { id: 'travel25', english: 'Detour', vietnamese: 'Đường vòng', pronunciation: 'duong vong', category: 'travel', chapter: 'chapter15', difficulty: 1, examples: ['Take detour due construction.'] },

  // Transportation Actions (25 words)
  { id: 'action1', english: 'Drive', vietnamese: 'Lái xe', pronunciation: 'lai xe', category: 'action', chapter: 'chapter15', difficulty: 1, examples: ['Drive carefully in rain.'] },
  { id: 'action2', english: 'Ride', vietnamese: 'Đi', pronunciation: 'di', category: 'action', chapter: 'chapter15', difficulty: 1, examples: ['Ride bicycle to school.'] },
  { id: 'action3', english: 'Walk', vietnamese: 'Đi bộ', pronunciation: 'di bo', category: 'action', chapter: 'chapter15', difficulty: 1, examples: ['Walk in the park.'] },
  { id: 'action4', english: 'Run', vietnamese: 'Chạy', pronunciation: 'chay', category: 'action', chapter: 'chapter15', difficulty: 1, examples: ['Run to catch bus.'] },
  { id: 'action5', english: 'Fly', vietnamese: 'Bay', pronunciation: 'bay', category: 'action', chapter: 'chapter15', difficulty: 1, examples: ['Fly to different country.'] },
  { id: 'action6', english: 'Sail', vietnamese: 'Đi thuyền', pronunciation: 'di thuyen', category: 'action', chapter: 'chapter15', difficulty: 1, examples: ['Sail across ocean.'] },
  { id: 'action7', english: 'Board', vietnamese: 'Lên tàu', pronunciation: 'len tau', category: 'action', chapter: 'chapter15', difficulty: 1, examples: ['Board airplane early.'] },
  { id: 'action8', english: 'Get off', vietnamese: 'Xuống', pronunciation: 'xuong', category: 'action', chapter: 'chapter15', difficulty: 1, examples: ['Get off at next stop.'] },
  { id: 'action9', english: 'Depart', vietnamese: 'Khởi hành', pronunciation: 'khoi hanh', category: 'action', chapter: 'chapter15', difficulty: 1, examples: ['Train departs on time.'] },
  { id: 'action10', english: 'Arrive', vietnamese: 'Đến', pronunciation: 'den', category: 'action', chapter: 'chapter15', difficulty: 1, examples: ['Arrive at destination safely.'] },
  { id: 'action11', english: 'Stop', vietnamese: 'Dừng', pronunciation: 'dung', category: 'action', chapter: 'chapter15', difficulty: 1, examples: ['Stop at red light.'] },
  { id: 'action12', english: 'Park', vietnamese: 'Đậu xe', pronunciation: 'dau xe', category: 'action', chapter: 'chapter15', difficulty: 1, examples: ['Park car in garage.'] },
  { id: 'action13', english: 'Turn', vietnamese: 'Rẽ', pronunciation: 're', category: 'action', chapter: 'chapter15', difficulty: 1, examples: ['Turn left at corner.'] },
  { id: 'action14', english: 'Reverse', vietnamese: 'Lùi', pronunciation: 'lui', category: 'action', chapter: 'chapter15', difficulty: 1, examples: ['Reverse into parking space.'] },
  { id: 'action15', english: 'Accelerate', vietnamese: 'Tăng tốc', pronunciation: 'tang toc', category: 'action', chapter: 'chapter15', difficulty: 1, examples: ['Accelerate on highway.'] },
  { id: 'action16', english: 'Brake', vietnamese: 'Phanh', pronunciation: 'phanh', category: 'action', chapter: 'chapter15', difficulty: 1, examples: ['Brake before intersection.'] },
  { id: 'action17', english: 'Navigate', vietnamese: 'Điều hướng', pronunciation: 'dieu huong', category: 'action', chapter: 'chapter15', difficulty: 1, examples: ['Navigate using GPS.'] },
  { id: 'action18', english: 'Transfer', vietnamese: 'Chuyển', pronunciation: 'chuyen', category: 'action', chapter: 'chapter15', difficulty: 1, examples: ['Transfer to different train.'] },
  { id: 'action19', english: 'Overtake', vietnamese: 'Vượt', pronunciation: 'vuot', category: 'action', chapter: 'chapter15', difficulty: 1, examples: ['Overtake slow vehicle.'] },
  { id: 'action20', english: 'Merge', vietnamese: 'Nhập làn', pronunciation: 'nhap lan', category: 'action', chapter: 'chapter15', difficulty: 1, examples: ['Merge into traffic.'] },
  { id: 'action21', english: 'Honk', vietnamese: 'Bấm còi', pronunciation: 'bam coi', category: 'action', chapter: 'chapter15', difficulty: 1, examples: ['Honk horn for warning.'] },
  { id: 'action22', english: 'Signal', vietnamese: 'Báo hiệu', pronunciation: 'bao hieu', category: 'action', chapter: 'chapter15', difficulty: 1, examples: ['Signal before turning.'] },
  { id: 'action23', english: 'Yield', vietnamese: 'Nhường đường', pronunciation: 'nhuong duong', category: 'action', chapter: 'chapter15', difficulty: 1, examples: ['Yield to pedestrians.'] },
  { id: 'action24', english: 'Cruise', vietnamese: 'Đi chậm', pronunciation: 'di cham', category: 'action', chapter: 'chapter15', difficulty: 1, examples: ['Cruise at steady speed.'] },
  { id: 'action25', english: 'Steer', vietnamese: 'Lái', pronunciation: 'lai', category: 'action', chapter: 'chapter15', difficulty: 1, examples: ['Steer wheel carefully.'] },

  // Travel Facilities & Terms (25 words)
  { id: 'facility1', english: 'Airport', vietnamese: 'Sân bay', pronunciation: 'san bay', category: 'facility', chapter: 'chapter15', difficulty: 1, examples: ['Arrive at airport early.'] },
  { id: 'facility2', english: 'Station', vietnamese: 'Ga', pronunciation: 'ga', category: 'facility', chapter: 'chapter15', difficulty: 1, examples: ['Train station nearby.'] },
  { id: 'facility3', english: 'Terminal', vietnamese: 'Nhà ga', pronunciation: 'nha ga', category: 'facility', chapter: 'chapter15', difficulty: 1, examples: ['Bus terminal downtown.'] },
  { id: 'facility4', english: 'Port', vietnamese: 'Cảng', pronunciation: 'cang', category: 'facility', chapter: 'chapter15', difficulty: 1, examples: ['Ship docks at port.'] },
  { id: 'facility5', english: 'Harbor', vietnamese: 'Bến cảng', pronunciation: 'ben cang', category: 'facility', chapter: 'chapter15', difficulty: 1, examples: ['Safe harbor for boats.'] },
  { id: 'facility6', english: 'Dock', vietnamese: 'Bến tàu', pronunciation: 'ben tau', category: 'facility', chapter: 'chapter15', difficulty: 1, examples: ['Ferry arrives at dock.'] },
  { id: 'facility7', english: 'Platform', vietnamese: 'Sân ga', pronunciation: 'san ga', category: 'facility', chapter: 'chapter15', difficulty: 1, examples: ['Wait on platform.'] },
  { id: 'facility8', english: 'Gate', vietnamese: 'Cổng', pronunciation: 'cong', category: 'facility', chapter: 'chapter15', difficulty: 1, examples: ['Boarding gate number.'] },
  { id: 'facility9', english: 'Parking', vietnamese: 'Bãi đậu xe', pronunciation: 'bai dau xe', category: 'facility', chapter: 'chapter15', difficulty: 1, examples: ['Find parking space.'] },
  { id: 'facility10', english: 'Garage', vietnamese: 'Nhà để xe', pronunciation: 'nha de xe', category: 'facility', chapter: 'chapter15', difficulty: 1, examples: ['Park in garage.'] },
  { id: 'facility11', english: 'Fuel station', vietnamese: 'Trạm xăng', pronunciation: 'tram xang', category: 'facility', chapter: 'chapter15', difficulty: 1, examples: ['Stop at fuel station.'] },
  { id: 'facility12', english: 'Rest area', vietnamese: 'Khu nghỉ', pronunciation: 'khu nghi', category: 'facility', chapter: 'chapter15', difficulty: 1, examples: ['Rest area on highway.'] },
  { id: 'facility13', english: 'Checkpoint', vietnamese: 'Trạm kiểm soát', pronunciation: 'tram kiem soat', category: 'facility', chapter: 'chapter15', difficulty: 1, examples: ['Security checkpoint required.'] },
  { id: 'facility14', english: 'Customs', vietnamese: 'Hải quan', pronunciation: 'hai quan', category: 'facility', chapter: 'chapter15', difficulty: 1, examples: ['Pass through customs.'] },
  { id: 'facility15', english: 'Immigration', vietnamese: 'Xuất nhập cảnh', pronunciation: 'xuat nhap canh', category: 'facility', chapter: 'chapter15', difficulty: 2, examples: ['Immigration control booth.'] },
  { id: 'facility16', english: 'Baggage claim', vietnamese: 'Khu lấy hành lý', pronunciation: 'khu lay hanh ly', category: 'facility', chapter: 'chapter15', difficulty: 1, examples: ['Wait at baggage claim.'] },
  { id: 'facility17', english: 'Check-in', vietnamese: 'Làm thủ tục', pronunciation: 'lam thu tuc', category: 'facility', chapter: 'chapter15', difficulty: 1, examples: ['Hotel check-in process.'] },
  { id: 'facility18', english: 'Waiting room', vietnamese: 'Phòng chờ', pronunciation: 'phong cho', category: 'facility', chapter: 'chapter15', difficulty: 1, examples: ['Comfortable waiting room.'] },
  { id: 'facility19', english: 'Information desk', vietnamese: 'Quầy thông tin', pronunciation: 'quay thong tin', category: 'facility', chapter: 'chapter15', difficulty: 1, examples: ['Ask at information desk.'] },
  { id: 'facility20', english: 'Ticket office', vietnamese: 'Phòng vé', pronunciation: 'phong ve', category: 'facility', chapter: 'chapter15', difficulty: 1, examples: ['Buy tickets at office.'] },
  { id: 'facility21', english: 'Lounge', vietnamese: 'Phòng chờ VIP', pronunciation: 'phong cho VIP', category: 'facility', chapter: 'chapter15', difficulty: 1, examples: ['Relax in airport lounge.'] },
  { id: 'facility22', english: 'Escalator', vietnamese: 'Thang cuốn', pronunciation: 'thang cuon', category: 'facility', chapter: 'chapter15', difficulty: 1, examples: ['Take escalator upstairs.'] },
  { id: 'facility23', english: 'Elevator', vietnamese: 'Thang máy', pronunciation: 'thang may', category: 'facility', chapter: 'chapter15', difficulty: 1, examples: ['Use elevator to floor.'] },
  { id: 'facility24', english: 'Walkway', vietnamese: 'Lối đi', pronunciation: 'loi di', category: 'facility', chapter: 'chapter15', difficulty: 1, examples: ['Moving walkway helps.'] },
  { id: 'facility25', english: 'Exit', vietnamese: 'Lối ra', pronunciation: 'loi ra', category: 'facility', chapter: 'chapter15', difficulty: 1, examples: ['Emergency exit sign.'] }
]
