// Chapter 11: Sports & Recreation (100 Essential Words)
// Words related to sports, exercise, games, and recreational activities

import { LanguageWord } from './chapter01-basic-everyday'

export const chapter11Words: LanguageWord[] = [
  // Popular Sports (25 words)
  { id: 'sport1', english: 'Football', vietnamese: 'Bóng đá', pronunciation: 'bong da', category: 'sport', chapter: 'chapter11', difficulty: 1, examples: ['Play football every weekend.'] },
  { id: 'sport2', english: 'Basketball', vietnamese: 'Bóng rổ', pronunciation: 'bong ro', category: 'sport', chapter: 'chapter11', difficulty: 1, examples: ['Basketball is popular sport.'] },
  { id: 'sport3', english: 'Tennis', vietnamese: 'Quần vợt', pronunciation: 'quan vot', category: 'sport', chapter: 'chapter11', difficulty: 1, examples: ['Tennis requires good coordination.'] },
  { id: 'sport4', english: 'Swimming', vietnamese: 'Bơi lội', pronunciation: 'boi loi', category: 'sport', chapter: 'chapter11', difficulty: 1, examples: ['Swimming is great exercise.'] },
  { id: 'sport5', english: 'Running', vietnamese: 'Chạy bộ', pronunciation: 'chay bo', category: 'sport', chapter: 'chapter11', difficulty: 1, examples: ['Running keeps me healthy.'] },
  { id: 'sport6', english: 'Cycling', vietnamese: 'Đạp xe', pronunciation: 'dap xe', category: 'sport', chapter: 'chapter11', difficulty: 1, examples: ['Cycling to work daily.'] },
  { id: 'sport7', english: 'Baseball', vietnamese: 'Bóng chày', pronunciation: 'bong chay', category: 'sport', chapter: 'chapter11', difficulty: 1, examples: ['Baseball season starts soon.'] },
  { id: 'sport8', english: 'Volleyball', vietnamese: 'Bóng chuyền', pronunciation: 'bong chuyen', category: 'sport', chapter: 'chapter11', difficulty: 1, examples: ['Play volleyball at beach.'] },
  { id: 'sport9', english: 'Golf', vietnamese: 'Golf', pronunciation: 'golf', category: 'sport', chapter: 'chapter11', difficulty: 1, examples: ['Golf requires patience.'] },
  { id: 'sport10', english: 'Boxing', vietnamese: 'Đấm bốc', pronunciation: 'dam boc', category: 'sport', chapter: 'chapter11', difficulty: 1, examples: ['Boxing builds strength.'] },
  { id: 'sport11', english: 'Wrestling', vietnamese: 'Đấu vật', pronunciation: 'dau vat', category: 'sport', chapter: 'chapter11', difficulty: 1, examples: ['Wrestling is ancient sport.'] },
  { id: 'sport12', english: 'Martial arts', vietnamese: 'Võ thuật', pronunciation: 'vo thuat', category: 'sport', chapter: 'chapter11', difficulty: 1, examples: ['Learn martial arts for defense.'] },
  { id: 'sport13', english: 'Yoga', vietnamese: 'Yoga', pronunciation: 'yoga', category: 'sport', chapter: 'chapter11', difficulty: 1, examples: ['Yoga improves flexibility.'] },
  { id: 'sport14', english: 'Gymnastics', vietnamese: 'Thể dục dụng cụ', pronunciation: 'the duc dung cu', category: 'sport', chapter: 'chapter11', difficulty: 2, examples: ['Gymnastics requires balance.'] },
  { id: 'sport15', english: 'Skiing', vietnamese: 'Trượt tuyết', pronunciation: 'truot tuyet', category: 'sport', chapter: 'chapter11', difficulty: 1, examples: ['Skiing in winter mountains.'] },
  { id: 'sport16', english: 'Snowboarding', vietnamese: 'Trượt ván tuyết', pronunciation: 'truot van tuyet', category: 'sport', chapter: 'chapter11', difficulty: 1, examples: ['Snowboarding is exciting.'] },
  { id: 'sport17', english: 'Surfing', vietnamese: 'Lướt sóng', pronunciation: 'luot song', category: 'sport', chapter: 'chapter11', difficulty: 1, examples: ['Surfing requires balance.'] },
  { id: 'sport18', english: 'Climbing', vietnamese: 'Leo núi', pronunciation: 'leo nui', category: 'sport', chapter: 'chapter11', difficulty: 1, examples: ['Rock climbing is challenging.'] },
  { id: 'sport19', english: 'Hiking', vietnamese: 'Đi bộ đường dài', pronunciation: 'di bo duong dai', category: 'sport', chapter: 'chapter11', difficulty: 1, examples: ['Hiking in national park.'] },
  { id: 'sport20', english: 'Fishing', vietnamese: 'Câu cá', pronunciation: 'cau ca', category: 'sport', chapter: 'chapter11', difficulty: 1, examples: ['Fishing is relaxing hobby.'] },
  { id: 'sport21', english: 'Hunting', vietnamese: 'Săn bắn', pronunciation: 'san ban', category: 'sport', chapter: 'chapter11', difficulty: 1, examples: ['Hunting season opens.'] },
  { id: 'sport22', english: 'Dancing', vietnamese: 'Khiêu vũ', pronunciation: 'khieu vu', category: 'sport', chapter: 'chapter11', difficulty: 1, examples: ['Dancing is fun exercise.'] },
  { id: 'sport23', english: 'Ice skating', vietnamese: 'Trượt băng', pronunciation: 'truot bang', category: 'sport', chapter: 'chapter11', difficulty: 1, examples: ['Ice skating in winter.'] },
  { id: 'sport24', english: 'Bowling', vietnamese: 'Bowling', pronunciation: 'bowling', category: 'sport', chapter: 'chapter11', difficulty: 1, examples: ['Bowling with friends.'] },
  { id: 'sport25', english: 'Badminton', vietnamese: 'Cầu lông', pronunciation: 'cau long', category: 'sport', chapter: 'chapter11', difficulty: 1, examples: ['Badminton is indoor sport.'] },

  // Sports Equipment (25 words)
  { id: 'equip1', english: 'Ball', vietnamese: 'Bóng', pronunciation: 'bong', category: 'equipment', chapter: 'chapter11', difficulty: 1, examples: ['Kick ball into goal.'] },
  { id: 'equip2', english: 'Bat', vietnamese: 'Gậy bóng chày', pronunciation: 'gay bong chay', category: 'equipment', chapter: 'chapter11', difficulty: 1, examples: ['Swing bat at ball.'] },
  { id: 'equip3', english: 'Racket', vietnamese: 'Vợt', pronunciation: 'vot', category: 'equipment', chapter: 'chapter11', difficulty: 1, examples: ['Tennis racket needs strings.'] },
  { id: 'equip4', english: 'Club', vietnamese: 'Gậy golf', pronunciation: 'gay golf', category: 'equipment', chapter: 'chapter11', difficulty: 1, examples: ['Choose right golf club.'] },
  { id: 'equip5', english: 'Glove', vietnamese: 'Găng tay', pronunciation: 'gang tay', category: 'equipment', chapter: 'chapter11', difficulty: 1, examples: ['Wear gloves for protection.'] },
  { id: 'equip6', english: 'Helmet', vietnamese: 'Mũ bảo hiểm', pronunciation: 'mu bao hiem', category: 'equipment', chapter: 'chapter11', difficulty: 1, examples: ['Always wear safety helmet.'] },
  { id: 'equip7', english: 'Shoes', vietnamese: 'Giày', pronunciation: 'giay', category: 'equipment', chapter: 'chapter11', difficulty: 1, examples: ['Buy running shoes.'] },
  { id: 'equip8', english: 'Uniform', vietnamese: 'Đồng phục', pronunciation: 'dong phuc', category: 'equipment', chapter: 'chapter11', difficulty: 1, examples: ['Team uniform looks good.'] },
  { id: 'equip9', english: 'Jersey', vietnamese: 'Áo đội', pronunciation: 'ao doi', category: 'equipment', chapter: 'chapter11', difficulty: 1, examples: ['Wear team jersey proudly.'] },
  { id: 'equip10', english: 'Shorts', vietnamese: 'Quần ngắn', pronunciation: 'quan ngan', category: 'equipment', chapter: 'chapter11', difficulty: 1, examples: ['Sports shorts are comfortable.'] },
  { id: 'equip11', english: 'Net', vietnamese: 'Lưới', pronunciation: 'luoi', category: 'equipment', chapter: 'chapter11', difficulty: 1, examples: ['Ball hit the net.'] },
  { id: 'equip12', english: 'Goal', vietnamese: 'Khung thành', pronunciation: 'khung thanh', category: 'equipment', chapter: 'chapter11', difficulty: 1, examples: ['Shoot ball at goal.'] },
  { id: 'equip13', english: 'Field', vietnamese: 'Sân', pronunciation: 'san', category: 'equipment', chapter: 'chapter11', difficulty: 1, examples: ['Play on grass field.'] },
  { id: 'equip14', english: 'Court', vietnamese: 'Sân', pronunciation: 'san', category: 'equipment', chapter: 'chapter11', difficulty: 1, examples: ['Basketball court is busy.'] },
  { id: 'equip15', english: 'Track', vietnamese: 'Đường chạy', pronunciation: 'duong chay', category: 'equipment', chapter: 'chapter11', difficulty: 1, examples: ['Run on track daily.'] },
  { id: 'equip16', english: 'Pool', vietnamese: 'Hồ bơi', pronunciation: 'ho boi', category: 'equipment', chapter: 'chapter11', difficulty: 1, examples: ['Swimming pool is clean.'] },
  { id: 'equip17', english: 'Gym', vietnamese: 'Phòng tập', pronunciation: 'phong tap', category: 'equipment', chapter: 'chapter11', difficulty: 1, examples: ['Exercise at gym daily.'] },
  { id: 'equip18', english: 'Weight', vietnamese: 'Tạ', pronunciation: 'ta', category: 'equipment', chapter: 'chapter11', difficulty: 1, examples: ['Lift heavy weights carefully.'] },
  { id: 'equip19', english: 'Dumbbell', vietnamese: 'Tạ đơn', pronunciation: 'ta don', category: 'equipment', chapter: 'chapter11', difficulty: 1, examples: ['Use dumbbells for arms.'] },
  { id: 'equip20', english: 'Barbell', vietnamese: 'Tạ đòn', pronunciation: 'ta don', category: 'equipment', chapter: 'chapter11', difficulty: 1, examples: ['Barbell for heavy lifting.'] },
  { id: 'equip21', english: 'Treadmill', vietnamese: 'Máy chạy bộ', pronunciation: 'may chay bo', category: 'equipment', chapter: 'chapter11', difficulty: 1, examples: ['Run on treadmill indoors.'] },
  { id: 'equip22', english: 'Bicycle', vietnamese: 'Xe đạp', pronunciation: 'xe dap', category: 'equipment', chapter: 'chapter11', difficulty: 1, examples: ['Ride bicycle to park.'] },
  { id: 'equip23', english: 'Skateboard', vietnamese: 'Ván trượt', pronunciation: 'van truot', category: 'equipment', chapter: 'chapter11', difficulty: 1, examples: ['Learn skateboard tricks.'] },
  { id: 'equip24', english: 'Skis', vietnamese: 'Ván trượt tuyết', pronunciation: 'van truot tuyet', category: 'equipment', chapter: 'chapter11', difficulty: 1, examples: ['Wax skis before skiing.'] },
  { id: 'equip25', english: 'Surfboard', vietnamese: 'Ván lướt sóng', pronunciation: 'van luot song', category: 'equipment', chapter: 'chapter11', difficulty: 1, examples: ['Balance on surfboard.'] },

  // Sports Actions & Terms (25 words)
  { id: 'action1', english: 'Play', vietnamese: 'Chơi', pronunciation: 'choi', category: 'action', chapter: 'chapter11', difficulty: 1, examples: ['Play sports for fun.'] },
  { id: 'action2', english: 'Practice', vietnamese: 'Luyện tập', pronunciation: 'luyen tap', category: 'action', chapter: 'chapter11', difficulty: 1, examples: ['Practice every day.'] },
  { id: 'action3', english: 'Train', vietnamese: 'Huấn luyện', pronunciation: 'huan luyen', category: 'action', chapter: 'chapter11', difficulty: 1, examples: ['Train for competition.'] },
  { id: 'action4', english: 'Exercise', vietnamese: 'Tập thể dục', pronunciation: 'tap the duc', category: 'action', chapter: 'chapter11', difficulty: 1, examples: ['Exercise keeps healthy.'] },
  { id: 'action5', english: 'Compete', vietnamese: 'Thi đấu', pronunciation: 'thi dau', category: 'action', chapter: 'chapter11', difficulty: 1, examples: ['Compete in tournament.'] },
  { id: 'action6', english: 'Win', vietnamese: 'Thắng', pronunciation: 'thang', category: 'action', chapter: 'chapter11', difficulty: 1, examples: ['Win championship game.'] },
  { id: 'action7', english: 'Lose', vietnamese: 'Thua', pronunciation: 'thua', category: 'action', chapter: 'chapter11', difficulty: 1, examples: ['Sometimes you lose games.'] },
  { id: 'action8', english: 'Score', vietnamese: 'Ghi điểm', pronunciation: 'ghi diem', category: 'action', chapter: 'chapter11', difficulty: 1, examples: ['Score winning goal.'] },
  { id: 'action9', english: 'Kick', vietnamese: 'Đá', pronunciation: 'da', category: 'action', chapter: 'chapter11', difficulty: 1, examples: ['Kick ball hard.'] },
  { id: 'action10', english: 'Throw', vietnamese: 'Ném', pronunciation: 'nem', category: 'action', chapter: 'chapter11', difficulty: 1, examples: ['Throw ball accurately.'] },
  { id: 'action11', english: 'Catch', vietnamese: 'Bắt', pronunciation: 'bat', category: 'action', chapter: 'chapter11', difficulty: 1, examples: ['Catch ball with glove.'] },
  { id: 'action12', english: 'Hit', vietnamese: 'Đánh', pronunciation: 'danh', category: 'action', chapter: 'chapter11', difficulty: 1, examples: ['Hit ball with bat.'] },
  { id: 'action13', english: 'Run', vietnamese: 'Chạy', pronunciation: 'chay', category: 'action', chapter: 'chapter11', difficulty: 1, examples: ['Run to finish line.'] },
  { id: 'action14', english: 'Jump', vietnamese: 'Nhảy', pronunciation: 'nhay', category: 'action', chapter: 'chapter11', difficulty: 1, examples: ['Jump over hurdle.'] },
  { id: 'action15', english: 'Swim', vietnamese: 'Bơi', pronunciation: 'boi', category: 'action', chapter: 'chapter11', difficulty: 1, examples: ['Swim across pool.'] },
  { id: 'action16', english: 'Lift', vietnamese: 'Nâng', pronunciation: 'nang', category: 'action', chapter: 'chapter11', difficulty: 1, examples: ['Lift weights safely.'] },
  { id: 'action17', english: 'Stretch', vietnamese: 'Duỗi', pronunciation: 'duoi', category: 'action', chapter: 'chapter11', difficulty: 1, examples: ['Stretch before exercise.'] },
  { id: 'action18', english: 'Warm up', vietnamese: 'Khởi động', pronunciation: 'khoi dong', category: 'action', chapter: 'chapter11', difficulty: 1, examples: ['Warm up before game.'] },
  { id: 'action19', english: 'Cool down', vietnamese: 'Thư giãn', pronunciation: 'thu gian', category: 'action', chapter: 'chapter11', difficulty: 1, examples: ['Cool down after workout.'] },
  { id: 'action20', english: 'Rest', vietnamese: 'Nghỉ ngơi', pronunciation: 'nghi ngoi', category: 'action', chapter: 'chapter11', difficulty: 1, examples: ['Rest between sets.'] },
  { id: 'action21', english: 'Breathe', vietnamese: 'Thở', pronunciation: 'tho', category: 'action', chapter: 'chapter11', difficulty: 1, examples: ['Breathe deeply during yoga.'] },
  { id: 'action22', english: 'Balance', vietnamese: 'Cân bằng', pronunciation: 'can bang', category: 'action', chapter: 'chapter11', difficulty: 1, examples: ['Balance on one foot.'] },
  { id: 'action23', english: 'Focus', vietnamese: 'Tập trung', pronunciation: 'tap trung', category: 'action', chapter: 'chapter11', difficulty: 1, examples: ['Focus on technique.'] },
  { id: 'action24', english: 'Relax', vietnamese: 'Thư giãn', pronunciation: 'thu gian', category: 'action', chapter: 'chapter11', difficulty: 1, examples: ['Relax after hard training.'] },
  { id: 'action25', english: 'Improve', vietnamese: 'Cải thiện', pronunciation: 'cai thien', category: 'action', chapter: 'chapter11', difficulty: 1, examples: ['Improve performance daily.'] },

  // Game & Competition Terms (25 words)
  { id: 'game1', english: 'Game', vietnamese: 'Trò chơi', pronunciation: 'tro choi', category: 'game', chapter: 'chapter11', difficulty: 1, examples: ['Enjoy playing games.'] },
  { id: 'game2', english: 'Match', vietnamese: 'Trận đấu', pronunciation: 'tran dau', category: 'game', chapter: 'chapter11', difficulty: 1, examples: ['Watch football match.'] },
  { id: 'game3', english: 'Tournament', vietnamese: 'Giải đấu', pronunciation: 'giai dau', category: 'game', chapter: 'chapter11', difficulty: 1, examples: ['Enter tennis tournament.'] },
  { id: 'game4', english: 'Championship', vietnamese: 'Vô địch', pronunciation: 'vo dich', category: 'game', chapter: 'chapter11', difficulty: 1, examples: ['Win world championship.'] },
  { id: 'game5', english: 'League', vietnamese: 'Giải đấu', pronunciation: 'giai dau', category: 'game', chapter: 'chapter11', difficulty: 1, examples: ['Join local league.'] },
  { id: 'game6', english: 'Team', vietnamese: 'Đội', pronunciation: 'doi', category: 'game', chapter: 'chapter11', difficulty: 1, examples: ['Support favorite team.'] },
  { id: 'game7', english: 'Player', vietnamese: 'Cầu thủ', pronunciation: 'cau thu', category: 'game', chapter: 'chapter11', difficulty: 1, examples: ['Best player scores.'] },
  { id: 'game8', english: 'Coach', vietnamese: 'Huấn luyện viên', pronunciation: 'huan luyen vien', category: 'game', chapter: 'chapter11', difficulty: 1, examples: ['Coach gives instructions.'] },
  { id: 'game9', english: 'Referee', vietnamese: 'Trọng tài', pronunciation: 'trong tai', category: 'game', chapter: 'chapter11', difficulty: 1, examples: ['Referee makes decisions.'] },
  { id: 'game10', english: 'Judge', vietnamese: 'Giám khảo', pronunciation: 'giam khao', category: 'game', chapter: 'chapter11', difficulty: 1, examples: ['Judge scores performance.'] },
  { id: 'game11', english: 'Captain', vietnamese: 'Đội trưởng', pronunciation: 'doi truong', category: 'game', chapter: 'chapter11', difficulty: 1, examples: ['Captain leads team.'] },
  { id: 'game12', english: 'Opponent', vietnamese: 'Đối thủ', pronunciation: 'doi thu', category: 'game', chapter: 'chapter11', difficulty: 1, examples: ['Respect your opponent.'] },
  { id: 'game13', english: 'Fan', vietnamese: 'Người hâm mộ', pronunciation: 'nguoi ham mo', category: 'game', chapter: 'chapter11', difficulty: 1, examples: ['Fans cheer loudly.'] },
  { id: 'game14', english: 'Spectator', vietnamese: 'Khán giả', pronunciation: 'khan gia', category: 'game', chapter: 'chapter11', difficulty: 1, examples: ['Many spectators attend.'] },
  { id: 'game15', english: 'Stadium', vietnamese: 'Sân vận động', pronunciation: 'san van dong', category: 'game', chapter: 'chapter11', difficulty: 1, examples: ['Stadium holds thousands.'] },
  { id: 'game16', english: 'Arena', vietnamese: 'Đấu trường', pronunciation: 'dau truong', category: 'game', chapter: 'chapter11', difficulty: 1, examples: ['Basketball arena is loud.'] },
  { id: 'game17', english: 'Score', vietnamese: 'Tỷ số', pronunciation: 'ty so', category: 'game', chapter: 'chapter11', difficulty: 1, examples: ['Final score is tied.'] },
  { id: 'game18', english: 'Point', vietnamese: 'Điểm', pronunciation: 'diem', category: 'game', chapter: 'chapter11', difficulty: 1, examples: ['Score one point.'] },
  { id: 'game19', english: 'Goal', vietnamese: 'Bàn thắng', pronunciation: 'ban thang', category: 'game', chapter: 'chapter11', difficulty: 1, examples: ['Score beautiful goal.'] },
  { id: 'game20', english: 'Record', vietnamese: 'Kỷ lục', pronunciation: 'ky luc', category: 'game', chapter: 'chapter11', difficulty: 1, examples: ['Break world record.'] },
  { id: 'game21', english: 'Medal', vietnamese: 'Huy chương', pronunciation: 'huy chuong', category: 'game', chapter: 'chapter11', difficulty: 1, examples: ['Win gold medal.'] },
  { id: 'game22', english: 'Trophy', vietnamese: 'Cúp', pronunciation: 'cup', category: 'game', chapter: 'chapter11', difficulty: 1, examples: ['Lift championship trophy.'] },
  { id: 'game23', english: 'Prize', vietnamese: 'Giải thưởng', pronunciation: 'giai thuong', category: 'game', chapter: 'chapter11', difficulty: 1, examples: ['Win first prize.'] },
  { id: 'game24', english: 'Victory', vietnamese: 'Chiến thắng', pronunciation: 'chien thang', category: 'game', chapter: 'chapter11', difficulty: 1, examples: ['Celebrate sweet victory.'] },
  { id: 'game25', english: 'Defeat', vietnamese: 'Thất bại', pronunciation: 'that bai', category: 'game', chapter: 'chapter11', difficulty: 1, examples: ['Learn from defeat.'] }
]
