// Chapter 29: Daily Routines & Time (100 Essential Words)
// Words related to daily activities, time, schedules, and routines

import { LanguageWord } from './chapter01-basic-everyday'

export const chapter29Words: LanguageWord[] = [
  // Morning Routines (25 words)
  { id: 'morning1', english: 'Morning', vietnamese: 'Buổi sáng', pronunciation: 'buoi sang', category: 'morning', chapter: 'chapter29', difficulty: 1, examples: ['Morning starts day.'] },
  { id: 'morning2', english: 'Wake up', vietnamese: 'Thức dậy', pronunciation: 'thuc day', category: 'morning', chapter: 'chapter29', difficulty: 1, examples: ['Wake up early.'] },
  { id: 'morning3', english: 'Get up', vietnamese: 'Dậy', pronunciation: 'day', category: 'morning', chapter: 'chapter29', difficulty: 1, examples: ['Get up from bed.'] },
  { id: 'morning4', english: 'Alarm clock', vietnamese: 'Đồng hồ báo thức', pronunciation: 'dong ho bao thuc', category: 'morning', chapter: 'chapter29', difficulty: 1, examples: ['Alarm clock wakes me.'] },
  { id: 'morning5', english: 'Stretch', vietnamese: 'Duỗi người', pronunciation: 'duoi nguoi', category: 'morning', chapter: 'chapter29', difficulty: 1, examples: ['Stretch after sleeping.'] },
  { id: 'morning6', english: 'Brush teeth', vietnamese: 'Đánh răng', pronunciation: 'danh rang', category: 'morning', chapter: 'chapter29', difficulty: 1, examples: ['Brush teeth daily.'] },
  { id: 'morning7', english: 'Wash face', vietnamese: 'Rửa mặt', pronunciation: 'rua mat', category: 'morning', chapter: 'chapter29', difficulty: 1, examples: ['Wash face clean.'] },
  { id: 'morning8', english: 'Take shower', vietnamese: 'Tắm', pronunciation: 'tam', category: 'morning', chapter: 'chapter29', difficulty: 1, examples: ['Take shower refreshing.'] },
  { id: 'morning9', english: 'Get dressed', vietnamese: 'Mặc quần áo', pronunciation: 'mac quan ao', category: 'morning', chapter: 'chapter29', difficulty: 1, examples: ['Get dressed quickly.'] },
  { id: 'morning10', english: 'Comb hair', vietnamese: 'Chải tóc', pronunciation: 'chai toc', category: 'morning', chapter: 'chapter29', difficulty: 1, examples: ['Comb hair neat.'] },
  { id: 'morning11', english: 'Make bed', vietnamese: 'Dọn giường', pronunciation: 'don giuong', category: 'morning', chapter: 'chapter29', difficulty: 1, examples: ['Make bed tidy.'] },
  { id: 'morning12', english: 'Breakfast', vietnamese: 'Bữa sáng', pronunciation: 'bua sang', category: 'morning', chapter: 'chapter29', difficulty: 1, examples: ['Breakfast important meal.'] },
  { id: 'morning13', english: 'Coffee', vietnamese: 'Cà phê', pronunciation: 'ca phe', category: 'morning', chapter: 'chapter29', difficulty: 1, examples: ['Coffee morning drink.'] },
  { id: 'morning14', english: 'Tea', vietnamese: 'Trà', pronunciation: 'tra', category: 'morning', chapter: 'chapter29', difficulty: 1, examples: ['Tea healthy beverage.'] },
  { id: 'morning15', english: 'Newspaper', vietnamese: 'Báo', pronunciation: 'bao', category: 'morning', chapter: 'chapter29', difficulty: 1, examples: ['Newspaper daily news.'] },
  { id: 'morning16', english: 'Check phone', vietnamese: 'Kiểm tra điện thoại', pronunciation: 'kiem tra dien thoai', category: 'morning', chapter: 'chapter29', difficulty: 1, examples: ['Check phone messages.'] },
  { id: 'morning17', english: 'Pack bag', vietnamese: 'Sắp xếp túi', pronunciation: 'sap xep tui', category: 'morning', chapter: 'chapter29', difficulty: 1, examples: ['Pack bag school.'] },
  { id: 'morning18', english: 'Leave house', vietnamese: 'Ra khỏi nhà', pronunciation: 'ra khoi nha', category: 'morning', chapter: 'chapter29', difficulty: 1, examples: ['Leave house work.'] },
  { id: 'morning19', english: 'Lock door', vietnamese: 'Khóa cửa', pronunciation: 'khoa cua', category: 'morning', chapter: 'chapter29', difficulty: 1, examples: ['Lock door secure.'] },
  { id: 'morning20', english: 'Commute', vietnamese: 'Di chuyển', pronunciation: 'di chuyen', category: 'morning', chapter: 'chapter29', difficulty: 1, examples: ['Commute to work.'] },
  { id: 'morning21', english: 'Bus', vietnamese: 'Xe buýt', pronunciation: 'xe buyt', category: 'morning', chapter: 'chapter29', difficulty: 1, examples: ['Bus public transport.'] },
  { id: 'morning22', english: 'Train', vietnamese: 'Tàu hỏa', pronunciation: 'tau hoa', category: 'morning', chapter: 'chapter29', difficulty: 1, examples: ['Train fast transport.'] },
  { id: 'morning23', english: 'Drive', vietnamese: 'Lái xe', pronunciation: 'lai xe', category: 'morning', chapter: 'chapter29', difficulty: 1, examples: ['Drive car work.'] },
  { id: 'morning24', english: 'Walk', vietnamese: 'Đi bộ', pronunciation: 'di bo', category: 'morning', chapter: 'chapter29', difficulty: 1, examples: ['Walk healthy exercise.'] },
  { id: 'morning25', english: 'Arrive', vietnamese: 'Đến', pronunciation: 'den', category: 'morning', chapter: 'chapter29', difficulty: 1, examples: ['Arrive work early.'] },

  // Work & Daily Activities (25 words)
  { id: 'work1', english: 'Work', vietnamese: 'Làm việc', pronunciation: 'lam viec', category: 'work', chapter: 'chapter29', difficulty: 1, examples: ['Work daily activity.'] },
  { id: 'work2', english: 'Office', vietnamese: 'Văn phòng', pronunciation: 'van phong', category: 'work', chapter: 'chapter29', difficulty: 1, examples: ['Office work place.'] },
  { id: 'work3', english: 'Meeting', vietnamese: 'Cuộc họp', pronunciation: 'cuoc hop', category: 'work', chapter: 'chapter29', difficulty: 1, examples: ['Meeting discusses plans.'] },
  { id: 'work4', english: 'Computer', vietnamese: 'Máy tính', pronunciation: 'may tinh', category: 'work', chapter: 'chapter29', difficulty: 1, examples: ['Computer work tool.'] },
  { id: 'work5', english: 'Email', vietnamese: 'Thư điện tử', pronunciation: 'thu dien tu', category: 'work', chapter: 'chapter29', difficulty: 1, examples: ['Email digital message.'] },
  { id: 'work6', english: 'Phone call', vietnamese: 'Cuộc gọi', pronunciation: 'cuoc goi', category: 'work', chapter: 'chapter29', difficulty: 1, examples: ['Phone call communication.'] },
  { id: 'work7', english: 'Break', vietnamese: 'Nghỉ giải lao', pronunciation: 'nghi giai lao', category: 'work', chapter: 'chapter29', difficulty: 1, examples: ['Break rest time.'] },
  { id: 'work8', english: 'Lunch', vietnamese: 'Bữa trưa', pronunciation: 'bua trua', category: 'work', chapter: 'chapter29', difficulty: 1, examples: ['Lunch midday meal.'] },
  { id: 'work9', english: 'Colleague', vietnamese: 'Đồng nghiệp', pronunciation: 'dong nghiep', category: 'work', chapter: 'chapter29', difficulty: 1, examples: ['Colleague work friend.'] },
  { id: 'work10', english: 'Boss', vietnamese: 'Sếp', pronunciation: 'sep', category: 'work', chapter: 'chapter29', difficulty: 1, examples: ['Boss manages team.'] },
  { id: 'work11', english: 'Task', vietnamese: 'Nhiệm vụ', pronunciation: 'nhiem vu', category: 'work', chapter: 'chapter29', difficulty: 1, examples: ['Task work assignment.'] },
  { id: 'work12', english: 'Project', vietnamese: 'Dự án', pronunciation: 'du an', category: 'work', chapter: 'chapter29', difficulty: 1, examples: ['Project long work.'] },
  { id: 'work13', english: 'Deadline', vietnamese: 'Hạn chót', pronunciation: 'han chot', category: 'work', chapter: 'chapter29', difficulty: 1, examples: ['Deadline time limit.'] },
  { id: 'work14', english: 'Presentation', vietnamese: 'Thuyết trình', pronunciation: 'thuyet trinh', category: 'work', chapter: 'chapter29', difficulty: 1, examples: ['Presentation shows ideas.'] },
  { id: 'work15', english: 'Report', vietnamese: 'Báo cáo', pronunciation: 'bao cao', category: 'work', chapter: 'chapter29', difficulty: 1, examples: ['Report work summary.'] },
  { id: 'work16', english: 'Document', vietnamese: 'Tài liệu', pronunciation: 'tai lieu', category: 'work', chapter: 'chapter29', difficulty: 1, examples: ['Document written paper.'] },
  { id: 'work17', english: 'Schedule', vietnamese: 'Lịch trình', pronunciation: 'lich trinh', category: 'work', chapter: 'chapter29', difficulty: 1, examples: ['Schedule time plan.'] },
  { id: 'work18', english: 'Appointment', vietnamese: 'Cuộc hẹn', pronunciation: 'cuoc hen', category: 'work', chapter: 'chapter29', difficulty: 1, examples: ['Appointment planned meeting.'] },
  { id: 'work19', english: 'Busy', vietnamese: 'Bận rộn', pronunciation: 'ban ron', category: 'work', chapter: 'chapter29', difficulty: 1, examples: ['Busy lots work.'] },
  { id: 'work20', english: 'Free time', vietnamese: 'Thời gian rảnh', pronunciation: 'thoi gian ranh', category: 'work', chapter: 'chapter29', difficulty: 1, examples: ['Free time relax.'] },
  { id: 'work21', english: 'Overtime', vietnamese: 'Làm thêm giờ', pronunciation: 'lam them gio', category: 'work', chapter: 'chapter29', difficulty: 1, examples: ['Overtime extra work.'] },
  { id: 'work22', english: 'Salary', vietnamese: 'Lương', pronunciation: 'luong', category: 'work', chapter: 'chapter29', difficulty: 1, examples: ['Salary work payment.'] },
  { id: 'work23', english: 'Promotion', vietnamese: 'Thăng chức', pronunciation: 'thang chuc', category: 'work', chapter: 'chapter29', difficulty: 1, examples: ['Promotion career advance.'] },
  { id: 'work24', english: 'Vacation', vietnamese: 'Kỳ nghỉ', pronunciation: 'ky nghi', category: 'work', chapter: 'chapter29', difficulty: 1, examples: ['Vacation rest period.'] },
  { id: 'work25', english: 'Retire', vietnamese: 'Nghỉ hưu', pronunciation: 'nghi huu', category: 'work', chapter: 'chapter29', difficulty: 1, examples: ['Retire stop working.'] },

  // Evening & Night Routines (25 words)
  { id: 'evening1', english: 'Evening', vietnamese: 'Buổi tối', pronunciation: 'buoi toi', category: 'evening', chapter: 'chapter29', difficulty: 1, examples: ['Evening ends day.'] },
  { id: 'evening2', english: 'Come home', vietnamese: 'Về nhà', pronunciation: 've nha', category: 'evening', chapter: 'chapter29', difficulty: 1, examples: ['Come home after work.'] },
  { id: 'evening3', english: 'Relax', vietnamese: 'Thư giãn', pronunciation: 'thu gian', category: 'evening', chapter: 'chapter29', difficulty: 1, examples: ['Relax after work.'] },
  { id: 'evening4', english: 'Change clothes', vietnamese: 'Thay quần áo', pronunciation: 'thay quan ao', category: 'evening', chapter: 'chapter29', difficulty: 1, examples: ['Change clothes comfortable.'] },
  { id: 'evening5', english: 'Dinner', vietnamese: 'Bữa tối', pronunciation: 'bua toi', category: 'evening', chapter: 'chapter29', difficulty: 1, examples: ['Dinner family meal.'] },
  { id: 'evening6', english: 'Cook', vietnamese: 'Nấu ăn', pronunciation: 'nau an', category: 'evening', chapter: 'chapter29', difficulty: 1, examples: ['Cook delicious food.'] },
  { id: 'evening7', english: 'Eat', vietnamese: 'Ăn', pronunciation: 'an', category: 'evening', chapter: 'chapter29', difficulty: 1, examples: ['Eat healthy food.'] },
  { id: 'evening8', english: 'Wash dishes', vietnamese: 'Rửa chén', pronunciation: 'rua chen', category: 'evening', chapter: 'chapter29', difficulty: 1, examples: ['Wash dishes clean.'] },
  { id: 'evening9', english: 'Watch TV', vietnamese: 'Xem tivi', pronunciation: 'xem tivi', category: 'evening', chapter: 'chapter29', difficulty: 1, examples: ['Watch TV entertainment.'] },
  { id: 'evening10', english: 'Read book', vietnamese: 'Đọc sách', pronunciation: 'doc sach', category: 'evening', chapter: 'chapter29', difficulty: 1, examples: ['Read book knowledge.'] },
  { id: 'evening11', english: 'Listen music', vietnamese: 'Nghe nhạc', pronunciation: 'nghe nhac', category: 'evening', chapter: 'chapter29', difficulty: 1, examples: ['Listen music relaxing.'] },
  { id: 'evening12', english: 'Exercise', vietnamese: 'Tập thể dục', pronunciation: 'tap the duc', category: 'evening', chapter: 'chapter29', difficulty: 1, examples: ['Exercise keeps healthy.'] },
  { id: 'evening13', english: 'Study', vietnamese: 'Học', pronunciation: 'hoc', category: 'evening', chapter: 'chapter29', difficulty: 1, examples: ['Study improves knowledge.'] },
  { id: 'evening14', english: 'Homework', vietnamese: 'Bài tập về nhà', pronunciation: 'bai tap ve nha', category: 'evening', chapter: 'chapter29', difficulty: 1, examples: ['Homework school assignment.'] },
  { id: 'evening15', english: 'Call family', vietnamese: 'Gọi gia đình', pronunciation: 'goi gia dinh', category: 'evening', chapter: 'chapter29', difficulty: 1, examples: ['Call family stay connected.'] },
  { id: 'evening16', english: 'Chat friends', vietnamese: 'Trò chuyện bạn bè', pronunciation: 'tro chuyen ban be', category: 'evening', chapter: 'chapter29', difficulty: 1, examples: ['Chat friends social.'] },
  { id: 'evening17', english: 'Social media', vietnamese: 'Mạng xã hội', pronunciation: 'mang xa hoi', category: 'evening', chapter: 'chapter29', difficulty: 1, examples: ['Social media connects people.'] },
  { id: 'evening18', english: 'Plan tomorrow', vietnamese: 'Lên kế hoạch ngày mai', pronunciation: 'len ke hoach ngay mai', category: 'evening', chapter: 'chapter29', difficulty: 2, examples: ['Plan tomorrow organize.'] },
  { id: 'evening19', english: 'Prepare', vietnamese: 'Chuẩn bị', pronunciation: 'chuan bi', category: 'evening', chapter: 'chapter29', difficulty: 1, examples: ['Prepare next day.'] },
  { id: 'evening20', english: 'Night', vietnamese: 'Đêm', pronunciation: 'dem', category: 'evening', chapter: 'chapter29', difficulty: 1, examples: ['Night time sleep.'] },
  { id: 'evening21', english: 'Sleep', vietnamese: 'Ngủ', pronunciation: 'ngu', category: 'evening', chapter: 'chapter29', difficulty: 1, examples: ['Sleep restores energy.'] },
  { id: 'evening22', english: 'Go to bed', vietnamese: 'Đi ngủ', pronunciation: 'di ngu', category: 'evening', chapter: 'chapter29', difficulty: 1, examples: ['Go to bed early.'] },
  { id: 'evening23', english: 'Turn off lights', vietnamese: 'Tắt đèn', pronunciation: 'tat den', category: 'evening', chapter: 'chapter29', difficulty: 1, examples: ['Turn off lights save energy.'] },
  { id: 'evening24', english: 'Dream', vietnamese: 'Mơ', pronunciation: 'mo', category: 'evening', chapter: 'chapter29', difficulty: 1, examples: ['Dream while sleeping.'] },
  { id: 'evening25', english: 'Rest', vietnamese: 'Nghỉ ngơi', pronunciation: 'nghi ngoi', category: 'evening', chapter: 'chapter29', difficulty: 1, examples: ['Rest recovers strength.'] },

  // Time & Schedule Words (25 words)
  { id: 'time1', english: 'Time', vietnamese: 'Thời gian', pronunciation: 'thoi gian', category: 'time', chapter: 'chapter29', difficulty: 1, examples: ['Time passes quickly.'] },
  { id: 'time2', english: 'Clock', vietnamese: 'Đồng hồ', pronunciation: 'dong ho', category: 'time', chapter: 'chapter29', difficulty: 1, examples: ['Clock shows time.'] },
  { id: 'time3', english: 'Watch', vietnamese: 'Đồng hồ đeo tay', pronunciation: 'dong ho deo tay', category: 'time', chapter: 'chapter29', difficulty: 1, examples: ['Watch on wrist.'] },
  { id: 'time4', english: 'Hour', vietnamese: 'Giờ', pronunciation: 'gio', category: 'time', chapter: 'chapter29', difficulty: 1, examples: ['Hour sixty minutes.'] },
  { id: 'time5', english: 'Minute', vietnamese: 'Phút', pronunciation: 'phut', category: 'time', chapter: 'chapter29', difficulty: 1, examples: ['Minute sixty seconds.'] },
  { id: 'time6', english: 'Second', vietnamese: 'Giây', pronunciation: 'giay', category: 'time', chapter: 'chapter29', difficulty: 1, examples: ['Second short time.'] },
  { id: 'time7', english: 'Early', vietnamese: 'Sớm', pronunciation: 'som', category: 'time', chapter: 'chapter29', difficulty: 1, examples: ['Early before time.'] },
  { id: 'time8', english: 'Late', vietnamese: 'Muộn', pronunciation: 'muon', category: 'time', chapter: 'chapter29', difficulty: 1, examples: ['Late after time.'] },
  { id: 'time9', english: 'On time', vietnamese: 'Đúng giờ', pronunciation: 'dung gio', category: 'time', chapter: 'chapter29', difficulty: 1, examples: ['On time punctual.'] },
  { id: 'time10', english: 'Quick', vietnamese: 'Nhanh', pronunciation: 'nhanh', category: 'time', chapter: 'chapter29', difficulty: 1, examples: ['Quick fast speed.'] },
  { id: 'time11', english: 'Slow', vietnamese: 'Chậm', pronunciation: 'cham', category: 'time', chapter: 'chapter29', difficulty: 1, examples: ['Slow careful pace.'] },
  { id: 'time12', english: 'Rush', vietnamese: 'Vội vàng', pronunciation: 'voi vang', category: 'time', chapter: 'chapter29', difficulty: 1, examples: ['Rush hurry quickly.'] },
  { id: 'time13', english: 'Wait', vietnamese: 'Chờ', pronunciation: 'cho', category: 'time', chapter: 'chapter29', difficulty: 1, examples: ['Wait patiently here.'] },
  { id: 'time14', english: 'Hurry', vietnamese: 'Nhanh lên', pronunciation: 'nhanh len', category: 'time', chapter: 'chapter29', difficulty: 1, examples: ['Hurry move fast.'] },
  { id: 'time15', english: 'Delay', vietnamese: 'Trì hoãn', pronunciation: 'tri hoan', category: 'time', chapter: 'chapter29', difficulty: 1, examples: ['Delay postpone later.'] },
  { id: 'time16', english: 'Cancel', vietnamese: 'Hủy bỏ', pronunciation: 'huy bo', category: 'time', chapter: 'chapter29', difficulty: 1, examples: ['Cancel stop plan.'] },
  { id: 'time17', english: 'Postpone', vietnamese: 'Hoãn lại', pronunciation: 'hoan lai', category: 'time', chapter: 'chapter29', difficulty: 1, examples: ['Postpone delay later.'] },
  { id: 'time18', english: 'Routine', vietnamese: 'Thói quen', pronunciation: 'thoi quen', category: 'time', chapter: 'chapter29', difficulty: 1, examples: ['Routine daily habit.'] },
  { id: 'time19', english: 'Habit', vietnamese: 'Tập quán', pronunciation: 'tap quan', category: 'time', chapter: 'chapter29', difficulty: 1, examples: ['Habit regular behavior.'] },
  { id: 'time20', english: 'Regular', vietnamese: 'Thường xuyên', pronunciation: 'thuong xuyen', category: 'time', chapter: 'chapter29', difficulty: 1, examples: ['Regular consistent pattern.'] },
  { id: 'time21', english: 'Sometimes', vietnamese: 'Thỉnh thoảng', pronunciation: 'thinh thoang', category: 'time', chapter: 'chapter29', difficulty: 1, examples: ['Sometimes occasionally happens.'] },
  { id: 'time22', english: 'Always', vietnamese: 'Luôn luôn', pronunciation: 'luon luon', category: 'time', chapter: 'chapter29', difficulty: 1, examples: ['Always every time.'] },
  { id: 'time23', english: 'Never', vietnamese: 'Không bao giờ', pronunciation: 'khong bao gio', category: 'time', chapter: 'chapter29', difficulty: 1, examples: ['Never not ever.'] },
  { id: 'time24', english: 'Often', vietnamese: 'Thường', pronunciation: 'thuong', category: 'time', chapter: 'chapter29', difficulty: 1, examples: ['Often frequently happens.'] },
  { id: 'time25', english: 'Rarely', vietnamese: 'Hiếm khi', pronunciation: 'hiem khi', category: 'time', chapter: 'chapter29', difficulty: 1, examples: ['Rarely seldom happens.'] }
]
