// Chapter 9: Technology & Communication (100 Essential Words)
// Words related to technology, devices, internet, and digital communication

import { LanguageWord } from './chapter01-basic-everyday'

export const chapter09Words: LanguageWord[] = [
  // Electronic Devices (25 words)
  { id: 'tech1', english: 'Computer', vietnamese: 'Máy tính', pronunciation: 'may tinh', category: 'device', chapter: 'chapter09', difficulty: 1, examples: ['Work on computer daily.'] },
  { id: 'tech2', english: 'Laptop', vietnamese: 'Máy tính xách tay', pronunciation: 'may tinh xach tay', category: 'device', chapter: 'chapter09', difficulty: 1, examples: ['Carry laptop for travel.'] },
  { id: 'tech3', english: 'Phone', vietnamese: 'Điện thoại', pronunciation: 'dien thoai', category: 'device', chapter: 'chapter09', difficulty: 1, examples: ['Answer phone call immediately.'] },
  { id: 'tech4', english: 'Smartphone', vietnamese: 'Điện thoại thông minh', pronunciation: 'dien thoai thong minh', category: 'device', chapter: 'chapter09', difficulty: 1, examples: ['Smartphone has many features.'] },
  { id: 'tech5', english: 'Tablet', vietnamese: 'Máy tính bảng', pronunciation: 'may tinh bang', category: 'device', chapter: 'chapter09', difficulty: 1, examples: ['Read books on tablet.'] },
  { id: 'tech6', english: 'Television', vietnamese: 'Tivi', pronunciation: 'tivi', category: 'device', chapter: 'chapter09', difficulty: 1, examples: ['Watch news on television.'] },
  { id: 'tech7', english: 'Radio', vietnamese: 'Đài', pronunciation: 'dai', category: 'device', chapter: 'chapter09', difficulty: 1, examples: ['Listen to music on radio.'] },
  { id: 'tech8', english: 'Camera', vietnamese: 'Máy ảnh', pronunciation: 'may anh', category: 'device', chapter: 'chapter09', difficulty: 1, examples: ['Take photos with camera.'] },
  { id: 'tech9', english: 'Video camera', vietnamese: 'Máy quay phim', pronunciation: 'may quay phim', category: 'device', chapter: 'chapter09', difficulty: 1, examples: ['Record video with camera.'] },
  { id: 'tech10', english: 'Headphones', vietnamese: 'Tai nghe', pronunciation: 'tai nghe', category: 'device', chapter: 'chapter09', difficulty: 1, examples: ['Listen with wireless headphones.'] },
  { id: 'tech11', english: 'Speaker', vietnamese: 'Loa', pronunciation: 'loa', category: 'device', chapter: 'chapter09', difficulty: 1, examples: ['Play music through speaker.'] },
  { id: 'tech12', english: 'Microphone', vietnamese: 'Micrô', pronunciation: 'micro', category: 'device', chapter: 'chapter09', difficulty: 1, examples: ['Speak into microphone clearly.'] },
  { id: 'tech13', english: 'Keyboard', vietnamese: 'Bàn phím', pronunciation: 'ban phim', category: 'device', chapter: 'chapter09', difficulty: 1, examples: ['Type fast on keyboard.'] },
  { id: 'tech14', english: 'Mouse', vietnamese: 'Chuột', pronunciation: 'chuot', category: 'device', chapter: 'chapter09', difficulty: 1, examples: ['Click mouse button twice.'] },
  { id: 'tech15', english: 'Monitor', vietnamese: 'Màn hình', pronunciation: 'man hinh', category: 'device', chapter: 'chapter09', difficulty: 1, examples: ['Large monitor shows details.'] },
  { id: 'tech16', english: 'Printer', vietnamese: 'Máy in', pronunciation: 'may in', category: 'device', chapter: 'chapter09', difficulty: 1, examples: ['Print documents on printer.'] },
  { id: 'tech17', english: 'Scanner', vietnamese: 'Máy quét', pronunciation: 'may quet', category: 'device', chapter: 'chapter09', difficulty: 1, examples: ['Scan photos into computer.'] },
  { id: 'tech18', english: 'Router', vietnamese: 'Bộ định tuyến', pronunciation: 'bo dinh tuyen', category: 'device', chapter: 'chapter09', difficulty: 2, examples: ['Router provides internet access.'] },
  { id: 'tech19', english: 'Modem', vietnamese: 'Modem', pronunciation: 'modem', category: 'device', chapter: 'chapter09', difficulty: 2, examples: ['Modem connects to internet.'] },
  { id: 'tech20', english: 'Hard drive', vietnamese: 'Ổ cứng', pronunciation: 'o cung', category: 'device', chapter: 'chapter09', difficulty: 2, examples: ['Store files on hard drive.'] },
  { id: 'tech21', english: 'USB', vietnamese: 'USB', pronunciation: 'USB', category: 'device', chapter: 'chapter09', difficulty: 1, examples: ['Transfer files with USB.'] },
  { id: 'tech22', english: 'Charger', vietnamese: 'Sạc', pronunciation: 'sac', category: 'device', chapter: 'chapter09', difficulty: 1, examples: ['Plug in phone charger.'] },
  { id: 'tech23', english: 'Battery', vietnamese: 'Pin', pronunciation: 'pin', category: 'device', chapter: 'chapter09', difficulty: 1, examples: ['Battery needs charging.'] },
  { id: 'tech24', english: 'Remote control', vietnamese: 'Điều khiển từ xa', pronunciation: 'dieu khien tu xa', category: 'device', chapter: 'chapter09', difficulty: 1, examples: ['Change channel with remote.'] },
  { id: 'tech25', english: 'Game console', vietnamese: 'Máy chơi game', pronunciation: 'may choi game', category: 'device', chapter: 'chapter09', difficulty: 1, examples: ['Play games on console.'] },

  // Internet & Online (25 words)
  { id: 'internet1', english: 'Internet', vietnamese: 'Internet', pronunciation: 'internet', category: 'internet', chapter: 'chapter09', difficulty: 1, examples: ['Browse internet for information.'] },
  { id: 'internet2', english: 'Website', vietnamese: 'Trang web', pronunciation: 'trang web', category: 'internet', chapter: 'chapter09', difficulty: 1, examples: ['Visit company website.'] },
  { id: 'internet3', english: 'Email', vietnamese: 'Email', pronunciation: 'email', category: 'internet', chapter: 'chapter09', difficulty: 1, examples: ['Send email to friend.'] },
  { id: 'internet4', english: 'Search', vietnamese: 'Tìm kiếm', pronunciation: 'tim kiem', category: 'internet', chapter: 'chapter09', difficulty: 1, examples: ['Search for restaurant online.'] },
  { id: 'internet5', english: 'Download', vietnamese: 'Tải xuống', pronunciation: 'tai xuong', category: 'internet', chapter: 'chapter09', difficulty: 1, examples: ['Download music from website.'] },
  { id: 'internet6', english: 'Upload', vietnamese: 'Tải lên', pronunciation: 'tai len', category: 'internet', chapter: 'chapter09', difficulty: 1, examples: ['Upload photos to cloud.'] },
  { id: 'internet7', english: 'Social media', vietnamese: 'Mạng xã hội', pronunciation: 'mang xa hoi', category: 'internet', chapter: 'chapter09', difficulty: 1, examples: ['Share on social media.'] },
  { id: 'internet8', english: 'Blog', vietnamese: 'Blog', pronunciation: 'blog', category: 'internet', chapter: 'chapter09', difficulty: 1, examples: ['Write travel blog daily.'] },
  { id: 'internet9', english: 'Video call', vietnamese: 'Gọi video', pronunciation: 'goi video', category: 'internet', chapter: 'chapter09', difficulty: 1, examples: ['Video call with family.'] },
  { id: 'internet10', english: 'Online shopping', vietnamese: 'Mua sắm trực tuyến', pronunciation: 'mua sam truc tuyen', category: 'internet', chapter: 'chapter09', difficulty: 1, examples: ['Online shopping is convenient.'] },
  { id: 'internet11', english: 'Stream', vietnamese: 'Phát trực tuyến', pronunciation: 'phat truc tuyen', category: 'internet', chapter: 'chapter09', difficulty: 1, examples: ['Stream movies online.'] },
  { id: 'internet12', english: 'Cloud', vietnamese: 'Đám mây', pronunciation: 'dam may', category: 'internet', chapter: 'chapter09', difficulty: 1, examples: ['Store files in cloud.'] },
  { id: 'internet13', english: 'Password', vietnamese: 'Mật khẩu', pronunciation: 'mat khau', category: 'internet', chapter: 'chapter09', difficulty: 1, examples: ['Create strong password.'] },
  { id: 'internet14', english: 'Username', vietnamese: 'Tên đăng nhập', pronunciation: 'ten dang nhap', category: 'internet', chapter: 'chapter09', difficulty: 1, examples: ['Enter username to login.'] },
  { id: 'internet15', english: 'Link', vietnamese: 'Liên kết', pronunciation: 'lien ket', category: 'internet', chapter: 'chapter09', difficulty: 1, examples: ['Click on blue link.'] },
  { id: 'internet16', english: 'Browser', vietnamese: 'Trình duyệt', pronunciation: 'trinh duyet', category: 'internet', chapter: 'chapter09', difficulty: 1, examples: ['Open new browser tab.'] },
  { id: 'internet17', english: 'App', vietnamese: 'Ứng dụng', pronunciation: 'ung dung', category: 'internet', chapter: 'chapter09', difficulty: 1, examples: ['Download useful app.'] },
  { id: 'internet18', english: 'Update', vietnamese: 'Cập nhật', pronunciation: 'cap nhat', category: 'internet', chapter: 'chapter09', difficulty: 1, examples: ['Update software regularly.'] },
  { id: 'internet19', english: 'Backup', vietnamese: 'Sao lưu', pronunciation: 'sao luu', category: 'internet', chapter: 'chapter09', difficulty: 1, examples: ['Backup important files.'] },
  { id: 'internet20', english: 'Virus', vietnamese: 'Virus', pronunciation: 'virus', category: 'internet', chapter: 'chapter09', difficulty: 1, examples: ['Protect computer from virus.'] },
  { id: 'internet21', english: 'WiFi', vietnamese: 'WiFi', pronunciation: 'wifi', category: 'internet', chapter: 'chapter09', difficulty: 1, examples: ['Connect to WiFi network.'] },
  { id: 'internet22', english: 'Data', vietnamese: 'Dữ liệu', pronunciation: 'du lieu', category: 'internet', chapter: 'chapter09', difficulty: 1, examples: ['Save important data safely.'] },
  { id: 'internet23', english: 'Network', vietnamese: 'Mạng', pronunciation: 'mang', category: 'internet', chapter: 'chapter09', difficulty: 1, examples: ['Join company network.'] },
  { id: 'internet24', english: 'Server', vietnamese: 'Máy chủ', pronunciation: 'may chu', category: 'internet', chapter: 'chapter09', difficulty: 2, examples: ['Server hosts website.'] },
  { id: 'internet25', english: 'Bandwidth', vietnamese: 'Băng thông', pronunciation: 'bang thong', category: 'internet', chapter: 'chapter09', difficulty: 2, examples: ['High bandwidth for fast internet.'] },

  // Communication Actions (25 words)
  { id: 'comm1', english: 'Call', vietnamese: 'Gọi', pronunciation: 'goi', category: 'communication', chapter: 'chapter09', difficulty: 1, examples: ['Call mom after work.'] },
  { id: 'comm2', english: 'Text', vietnamese: 'Nhắn tin', pronunciation: 'nhan tin', category: 'communication', chapter: 'chapter09', difficulty: 1, examples: ['Text message to friend.'] },
  { id: 'comm3', english: 'Chat', vietnamese: 'Trò chuyện', pronunciation: 'tro chuyen', category: 'communication', chapter: 'chapter09', difficulty: 1, examples: ['Chat online with colleagues.'] },
  { id: 'comm4', english: 'Message', vietnamese: 'Tin nhắn', pronunciation: 'tin nhan', category: 'communication', chapter: 'chapter09', difficulty: 1, examples: ['Send message through app.'] },
  { id: 'comm5', english: 'Reply', vietnamese: 'Trả lời', pronunciation: 'tra loi', category: 'communication', chapter: 'chapter09', difficulty: 1, examples: ['Reply to email quickly.'] },
  { id: 'comm6', english: 'Forward', vietnamese: 'Chuyển tiếp', pronunciation: 'chuyen tiep', category: 'communication', chapter: 'chapter09', difficulty: 1, examples: ['Forward email to team.'] },
  { id: 'comm7', english: 'Share', vietnamese: 'Chia sẻ', pronunciation: 'chia se', category: 'communication', chapter: 'chapter09', difficulty: 1, examples: ['Share photo on social media.'] },
  { id: 'comm8', english: 'Post', vietnamese: 'Đăng', pronunciation: 'dang', category: 'communication', chapter: 'chapter09', difficulty: 1, examples: ['Post update on timeline.'] },
  { id: 'comm9', english: 'Comment', vietnamese: 'Bình luận', pronunciation: 'binh luan', category: 'communication', chapter: 'chapter09', difficulty: 1, examples: ['Comment on friend post.'] },
  { id: 'comm10', english: 'Like', vietnamese: 'Thích', pronunciation: 'thich', category: 'communication', chapter: 'chapter09', difficulty: 1, examples: ['Like interesting posts.'] },
  { id: 'comm11', english: 'Subscribe', vietnamese: 'Đăng ký', pronunciation: 'dang ky', category: 'communication', chapter: 'chapter09', difficulty: 1, examples: ['Subscribe to news channel.'] },
  { id: 'comm12', english: 'Follow', vietnamese: 'Theo dõi', pronunciation: 'theo doi', category: 'communication', chapter: 'chapter09', difficulty: 1, examples: ['Follow favorite celebrity.'] },
  { id: 'comm13', english: 'Block', vietnamese: 'Chặn', pronunciation: 'chan', category: 'communication', chapter: 'chapter09', difficulty: 1, examples: ['Block spam messages.'] },
  { id: 'comm14', english: 'Connect', vietnamese: 'Kết nối', pronunciation: 'ket noi', category: 'communication', chapter: 'chapter09', difficulty: 1, examples: ['Connect with old friends.'] },
  { id: 'comm15', english: 'Disconnect', vietnamese: 'Ngắt kết nối', pronunciation: 'ngat ket noi', category: 'communication', chapter: 'chapter09', difficulty: 1, examples: ['Disconnect from network.'] },
  { id: 'comm16', english: 'Record', vietnamese: 'Ghi âm', pronunciation: 'ghi am', category: 'communication', chapter: 'chapter09', difficulty: 1, examples: ['Record voice message.'] },
  { id: 'comm17', english: 'Play', vietnamese: 'Phát', pronunciation: 'phat', category: 'communication', chapter: 'chapter09', difficulty: 1, examples: ['Play recorded message.'] },
  { id: 'comm18', english: 'Pause', vietnamese: 'Tạm dừng', pronunciation: 'tam dung', category: 'communication', chapter: 'chapter09', difficulty: 1, examples: ['Pause video playback.'] },
  { id: 'comm19', english: 'Stop', vietnamese: 'Dừng', pronunciation: 'dung', category: 'communication', chapter: 'chapter09', difficulty: 1, examples: ['Stop music player.'] },
  { id: 'comm20', english: 'Mute', vietnamese: 'Tắt tiếng', pronunciation: 'tat tieng', category: 'communication', chapter: 'chapter09', difficulty: 1, examples: ['Mute phone during meeting.'] },
  { id: 'comm21', english: 'Unmute', vietnamese: 'Bật tiếng', pronunciation: 'bat tieng', category: 'communication', chapter: 'chapter09', difficulty: 1, examples: ['Unmute microphone to speak.'] },
  { id: 'comm22', english: 'Volume', vietnamese: 'Âm lượng', pronunciation: 'am luong', category: 'communication', chapter: 'chapter09', difficulty: 1, examples: ['Adjust volume level.'] },
  { id: 'comm23', english: 'Notification', vietnamese: 'Thông báo', pronunciation: 'thong bao', category: 'communication', chapter: 'chapter09', difficulty: 1, examples: ['Check phone notifications.'] },
  { id: 'comm24', english: 'Alert', vietnamese: 'Cảnh báo', pronunciation: 'canh bao', category: 'communication', chapter: 'chapter09', difficulty: 1, examples: ['Set alert for appointment.'] },
  { id: 'comm25', english: 'Reminder', vietnamese: 'Nhắc nhở', pronunciation: 'nhac nho', category: 'communication', chapter: 'chapter09', difficulty: 1, examples: ['Phone reminder for meeting.'] },

  // Technology Terms (25 words)
  { id: 'term1', english: 'Software', vietnamese: 'Phần mềm', pronunciation: 'phan mem', category: 'term', chapter: 'chapter09', difficulty: 1, examples: ['Install new software.'] },
  { id: 'term2', english: 'Hardware', vietnamese: 'Phần cứng', pronunciation: 'phan cung', category: 'term', chapter: 'chapter09', difficulty: 1, examples: ['Computer hardware upgrade.'] },
  { id: 'term3', english: 'Program', vietnamese: 'Chương trình', pronunciation: 'chuong trinh', category: 'term', chapter: 'chapter09', difficulty: 1, examples: ['Run antivirus program.'] },
  { id: 'term4', english: 'File', vietnamese: 'Tệp tin', pronunciation: 'tep tin', category: 'term', chapter: 'chapter09', difficulty: 1, examples: ['Save file to desktop.'] },
  { id: 'term5', english: 'Folder', vietnamese: 'Thư mục', pronunciation: 'thu muc', category: 'term', chapter: 'chapter09', difficulty: 1, examples: ['Organize files in folders.'] },
  { id: 'term6', english: 'Document', vietnamese: 'Tài liệu', pronunciation: 'tai lieu', category: 'term', chapter: 'chapter09', difficulty: 1, examples: ['Edit document carefully.'] },
  { id: 'term7', english: 'Format', vietnamese: 'Định dạng', pronunciation: 'dinh dang', category: 'term', chapter: 'chapter09', difficulty: 1, examples: ['Format text properly.'] },
  { id: 'term8', english: 'Copy', vietnamese: 'Sao chép', pronunciation: 'sao chep', category: 'term', chapter: 'chapter09', difficulty: 1, examples: ['Copy text to clipboard.'] },
  { id: 'term9', english: 'Paste', vietnamese: 'Dán', pronunciation: 'dan', category: 'term', chapter: 'chapter09', difficulty: 1, examples: ['Paste copied text here.'] },
  { id: 'term10', english: 'Cut', vietnamese: 'Cắt', pronunciation: 'cat', category: 'term', chapter: 'chapter09', difficulty: 1, examples: ['Cut selected text.'] },
  { id: 'term11', english: 'Delete', vietnamese: 'Xóa', pronunciation: 'xoa', category: 'term', chapter: 'chapter09', difficulty: 1, examples: ['Delete old files.'] },
  { id: 'term12', english: 'Save', vietnamese: 'Lưu', pronunciation: 'luu', category: 'term', chapter: 'chapter09', difficulty: 1, examples: ['Save work frequently.'] },
  { id: 'term13', english: 'Open', vietnamese: 'Mở', pronunciation: 'mo', category: 'term', chapter: 'chapter09', difficulty: 1, examples: ['Open new document.'] },
  { id: 'term14', english: 'Close', vietnamese: 'Đóng', pronunciation: 'dong', category: 'term', chapter: 'chapter09', difficulty: 1, examples: ['Close all windows.'] },
  { id: 'term15', english: 'Install', vietnamese: 'Cài đặt', pronunciation: 'cai dat', category: 'term', chapter: 'chapter09', difficulty: 1, examples: ['Install required software.'] },
  { id: 'term16', english: 'Uninstall', vietnamese: 'Gỡ cài đặt', pronunciation: 'go cai dat', category: 'term', chapter: 'chapter09', difficulty: 1, examples: ['Uninstall unused programs.'] },
  { id: 'term17', english: 'Restart', vietnamese: 'Khởi động lại', pronunciation: 'khoi dong lai', category: 'term', chapter: 'chapter09', difficulty: 1, examples: ['Restart computer after update.'] },
  { id: 'term18', english: 'Shutdown', vietnamese: 'Tắt máy', pronunciation: 'tat may', category: 'term', chapter: 'chapter09', difficulty: 1, examples: ['Shutdown computer properly.'] },
  { id: 'term19', english: 'Login', vietnamese: 'Đăng nhập', pronunciation: 'dang nhap', category: 'term', chapter: 'chapter09', difficulty: 1, examples: ['Login to email account.'] },
  { id: 'term20', english: 'Logout', vietnamese: 'Đăng xuất', pronunciation: 'dang xuat', category: 'term', chapter: 'chapter09', difficulty: 1, examples: ['Logout when finished.'] },
  { id: 'term21', english: 'Refresh', vietnamese: 'Làm mới', pronunciation: 'lam moi', category: 'term', chapter: 'chapter09', difficulty: 1, examples: ['Refresh webpage for updates.'] },
  { id: 'term22', english: 'Zoom', vietnamese: 'Phóng to', pronunciation: 'phong to', category: 'term', chapter: 'chapter09', difficulty: 1, examples: ['Zoom in to see details.'] },
  { id: 'term23', english: 'Resolution', vietnamese: 'Độ phân giải', pronunciation: 'do phan giai', category: 'term', chapter: 'chapter09', difficulty: 2, examples: ['High resolution photo.'] },
  { id: 'term24', english: 'Memory', vietnamese: 'Bộ nhớ', pronunciation: 'bo nho', category: 'term', chapter: 'chapter09', difficulty: 1, examples: ['Computer needs more memory.'] },
  { id: 'term25', english: 'Storage', vietnamese: 'Lưu trữ', pronunciation: 'luu tru', category: 'term', chapter: 'chapter09', difficulty: 1, examples: ['Cloud storage saves space.'] }
]
