// Chapter 10: Shopping & Commerce (100 Essential Words)
// Words related to shopping, money, transactions, and commercial activities

import { LanguageWord } from './chapter01-basic-everyday'

export const chapter10Words: LanguageWord[] = [
  // Money & Payment (25 words)
  { id: 'money1', english: 'Money', vietnamese: 'Tiền', pronunciation: 'tien', category: 'money', chapter: 'chapter10', difficulty: 1, examples: ['Need money for shopping.'] },
  { id: 'money2', english: 'Cash', vietnamese: 'Tiền mặt', pronunciation: 'tien mat', category: 'money', chapter: 'chapter10', difficulty: 1, examples: ['Pay with cash only.'] },
  { id: 'money3', english: 'Credit card', vietnamese: 'Thẻ tín dụng', pronunciation: 'the tin dung', category: 'money', chapter: 'chapter10', difficulty: 1, examples: ['Use credit card for payment.'] },
  { id: 'money4', english: 'Debit card', vietnamese: 'Thẻ ghi nợ', pronunciation: 'the ghi no', category: 'money', chapter: 'chapter10', difficulty: 1, examples: ['Pay with debit card.'] },
  { id: 'money5', english: 'Bank', vietnamese: 'Ngân hàng', pronunciation: 'ngan hang', category: 'money', chapter: 'chapter10', difficulty: 1, examples: ['Go to bank for withdrawal.'] },
  { id: 'money6', english: 'ATM', vietnamese: 'Máy ATM', pronunciation: 'may ATM', category: 'money', chapter: 'chapter10', difficulty: 1, examples: ['Withdraw money from ATM.'] },
  { id: 'money7', english: 'Receipt', vietnamese: 'Hóa đơn', pronunciation: 'hoa don', category: 'money', chapter: 'chapter10', difficulty: 1, examples: ['Keep receipt for warranty.'] },
  { id: 'money8', english: 'Change', vietnamese: 'Tiền thối', pronunciation: 'tien thoi', category: 'money', chapter: 'chapter10', difficulty: 1, examples: ['Count change carefully.'] },
  { id: 'money9', english: 'Bill', vietnamese: 'Hóa đơn', pronunciation: 'hoa don', category: 'money', chapter: 'chapter10', difficulty: 1, examples: ['Pay electricity bill monthly.'] },
  { id: 'money10', english: 'Coin', vietnamese: 'Đồng xu', pronunciation: 'dong xu', category: 'money', chapter: 'chapter10', difficulty: 1, examples: ['Collect coins in jar.'] },
  { id: 'money11', english: 'Wallet', vietnamese: 'Ví', pronunciation: 'vi', category: 'money', chapter: 'chapter10', difficulty: 1, examples: ['Keep cards in wallet.'] },
  { id: 'money12', english: 'Purse', vietnamese: 'Túi xách', pronunciation: 'tui xach', category: 'money', chapter: 'chapter10', difficulty: 1, examples: ['Money in small purse.'] },
  { id: 'money13', english: 'Price', vietnamese: 'Giá', pronunciation: 'gia', category: 'money', chapter: 'chapter10', difficulty: 1, examples: ['Check price before buying.'] },
  { id: 'money14', english: 'Cost', vietnamese: 'Chi phí', pronunciation: 'chi phi', category: 'money', chapter: 'chapter10', difficulty: 1, examples: ['Calculate total cost.'] },
  { id: 'money15', english: 'Expensive', vietnamese: 'Đắt', pronunciation: 'dat', category: 'money', chapter: 'chapter10', difficulty: 1, examples: ['This car is expensive.'] },
  { id: 'money16', english: 'Cheap', vietnamese: 'Rẻ', pronunciation: 're', category: 'money', chapter: 'chapter10', difficulty: 1, examples: ['Find cheap alternatives.'] },
  { id: 'money17', english: 'Free', vietnamese: 'Miễn phí', pronunciation: 'mien phi', category: 'money', chapter: 'chapter10', difficulty: 1, examples: ['Free delivery available.'] },
  { id: 'money18', english: 'Discount', vietnamese: 'Giảm giá', pronunciation: 'giam gia', category: 'money', chapter: 'chapter10', difficulty: 1, examples: ['Get discount for bulk purchase.'] },
  { id: 'money19', english: 'Sale', vietnamese: 'Khuyến mãi', pronunciation: 'khuyen mai', category: 'money', chapter: 'chapter10', difficulty: 1, examples: ['Shopping during sale season.'] },
  { id: 'money20', english: 'Tax', vietnamese: 'Thuế', pronunciation: 'thue', category: 'money', chapter: 'chapter10', difficulty: 1, examples: ['Price includes tax.'] },
  { id: 'money21', english: 'Tip', vietnamese: 'Tiền tip', pronunciation: 'tien tip', category: 'money', chapter: 'chapter10', difficulty: 1, examples: ['Leave tip for waiter.'] },
  { id: 'money22', english: 'Budget', vietnamese: 'Ngân sách', pronunciation: 'ngan sach', category: 'money', chapter: 'chapter10', difficulty: 1, examples: ['Shop within budget.'] },
  { id: 'money23', english: 'Spend', vietnamese: 'Chi tiêu', pronunciation: 'chi tieu', category: 'money', chapter: 'chapter10', difficulty: 1, examples: ['Spend money wisely.'] },
  { id: 'money24', english: 'Save', vietnamese: 'Tiết kiệm', pronunciation: 'tiet kiem', category: 'money', chapter: 'chapter10', difficulty: 1, examples: ['Save money for vacation.'] },
  { id: 'money25', english: 'Refund', vietnamese: 'Hoàn tiền', pronunciation: 'hoan tien', category: 'money', chapter: 'chapter10', difficulty: 1, examples: ['Request refund for defective item.'] },

  // Shopping Places (25 words)
  { id: 'place1', english: 'Store', vietnamese: 'Cửa hàng', pronunciation: 'cua hang', category: 'place', chapter: 'chapter10', difficulty: 1, examples: ['Shop at local store.'] },
  { id: 'place2', english: 'Shop', vietnamese: 'Tiệm', pronunciation: 'tiem', category: 'place', chapter: 'chapter10', difficulty: 1, examples: ['Coffee shop opens early.'] },
  { id: 'place3', english: 'Mall', vietnamese: 'Trung tâm thương mại', pronunciation: 'trung tam thuong mai', category: 'place', chapter: 'chapter10', difficulty: 1, examples: ['Meet friends at mall.'] },
  { id: 'place4', english: 'Market', vietnamese: 'Chợ', pronunciation: 'cho', category: 'place', chapter: 'chapter10', difficulty: 1, examples: ['Buy fresh vegetables at market.'] },
  { id: 'place5', english: 'Supermarket', vietnamese: 'Siêu thị', pronunciation: 'sieu thi', category: 'place', chapter: 'chapter10', difficulty: 1, examples: ['Weekly shopping at supermarket.'] },
  { id: 'place6', english: 'Department store', vietnamese: 'Cửa hàng bách hóa', pronunciation: 'cua hang bach hoa', category: 'place', chapter: 'chapter10', difficulty: 1, examples: ['Find everything at department store.'] },
  { id: 'place7', english: 'Grocery store', vietnamese: 'Cửa hàng tạp hóa', pronunciation: 'cua hang tap hoa', category: 'place', chapter: 'chapter10', difficulty: 1, examples: ['Buy daily items at grocery store.'] },
  { id: 'place8', english: 'Boutique', vietnamese: 'Cửa hàng thời trang', pronunciation: 'cua hang thoi trang', category: 'place', chapter: 'chapter10', difficulty: 2, examples: ['Browse clothes at boutique.'] },
  { id: 'place9', english: 'Pharmacy', vietnamese: 'Hiệu thuốc', pronunciation: 'hieu thuoc', category: 'place', chapter: 'chapter10', difficulty: 1, examples: ['Buy medicine at pharmacy.'] },
  { id: 'place10', english: 'Bookstore', vietnamese: 'Hiệu sách', pronunciation: 'hieu sach', category: 'place', chapter: 'chapter10', difficulty: 1, examples: ['Browse books at bookstore.'] },
  { id: 'place11', english: 'Electronics store', vietnamese: 'Cửa hàng điện tử', pronunciation: 'cua hang dien tu', category: 'place', chapter: 'chapter10', difficulty: 1, examples: ['Compare prices at electronics store.'] },
  { id: 'place12', english: 'Toy store', vietnamese: 'Cửa hàng đồ chơi', pronunciation: 'cua hang do choi', category: 'place', chapter: 'chapter10', difficulty: 1, examples: ['Kids love toy store.'] },
  { id: 'place13', english: 'Hardware store', vietnamese: 'Cửa hàng phần cứng', pronunciation: 'cua hang phan cung', category: 'place', chapter: 'chapter10', difficulty: 1, examples: ['Buy tools at hardware store.'] },
  { id: 'place14', english: 'Bakery', vietnamese: 'Tiệm bánh', pronunciation: 'tiem banh', category: 'place', chapter: 'chapter10', difficulty: 1, examples: ['Fresh bread from bakery.'] },
  { id: 'place15', english: 'Butcher shop', vietnamese: 'Cửa hàng thịt', pronunciation: 'cua hang thit', category: 'place', chapter: 'chapter10', difficulty: 1, examples: ['Buy meat at butcher shop.'] },
  { id: 'place16', english: 'Gas station', vietnamese: 'Trạm xăng', pronunciation: 'tram xang', category: 'place', chapter: 'chapter10', difficulty: 1, examples: ['Fill tank at gas station.'] },
  { id: 'place17', english: 'Bank', vietnamese: 'Ngân hàng', pronunciation: 'ngan hang', category: 'place', chapter: 'chapter10', difficulty: 1, examples: ['Open account at bank.'] },
  { id: 'place18', english: 'Restaurant', vietnamese: 'Nhà hàng', pronunciation: 'nha hang', category: 'place', chapter: 'chapter10', difficulty: 1, examples: ['Eat dinner at restaurant.'] },
  { id: 'place19', english: 'Cafe', vietnamese: 'Quán cà phê', pronunciation: 'quan ca phe', category: 'place', chapter: 'chapter10', difficulty: 1, examples: ['Work at quiet cafe.'] },
  { id: 'place20', english: 'Food court', vietnamese: 'Khu ẩm thực', pronunciation: 'khu am thuc', category: 'place', chapter: 'chapter10', difficulty: 1, examples: ['Many options at food court.'] },
  { id: 'place21', english: 'Outlet', vietnamese: 'Cửa hàng giảm giá', pronunciation: 'cua hang giam gia', category: 'place', chapter: 'chapter10', difficulty: 1, examples: ['Shop brand items at outlet.'] },
  { id: 'place22', english: 'Warehouse', vietnamese: 'Kho hàng', pronunciation: 'kho hang', category: 'place', chapter: 'chapter10', difficulty: 1, examples: ['Buy bulk items at warehouse.'] },
  { id: 'place23', english: 'Kiosk', vietnamese: 'Gian hàng', pronunciation: 'gian hang', category: 'place', chapter: 'chapter10', difficulty: 1, examples: ['Buy snacks from kiosk.'] },
  { id: 'place24', english: 'Counter', vietnamese: 'Quầy', pronunciation: 'quay', category: 'place', chapter: 'chapter10', difficulty: 1, examples: ['Pay at checkout counter.'] },
  { id: 'place25', english: 'Cashier', vietnamese: 'Thu ngân', pronunciation: 'thu ngan', category: 'place', chapter: 'chapter10', difficulty: 1, examples: ['Cashier scans items.'] },

  // Shopping Actions (25 words)
  { id: 'action1', english: 'Buy', vietnamese: 'Mua', pronunciation: 'mua', category: 'action', chapter: 'chapter10', difficulty: 1, examples: ['Buy fresh groceries today.'] },
  { id: 'action2', english: 'Purchase', vietnamese: 'Mua', pronunciation: 'mua', category: 'action', chapter: 'chapter10', difficulty: 1, examples: ['Purchase online for convenience.'] },
  { id: 'action3', english: 'Sell', vietnamese: 'Bán', pronunciation: 'ban', category: 'action', chapter: 'chapter10', difficulty: 1, examples: ['Sell old furniture.'] },
  { id: 'action4', english: 'Browse', vietnamese: 'Duyệt', pronunciation: 'duyet', category: 'action', chapter: 'chapter10', difficulty: 1, examples: ['Browse items before deciding.'] },
  { id: 'action5', english: 'Compare', vietnamese: 'So sánh', pronunciation: 'so sanh', category: 'action', chapter: 'chapter10', difficulty: 1, examples: ['Compare prices carefully.'] },
  { id: 'action6', english: 'Choose', vietnamese: 'Chọn', pronunciation: 'chon', category: 'action', chapter: 'chapter10', difficulty: 1, examples: ['Choose best quality item.'] },
  { id: 'action7', english: 'Select', vietnamese: 'Lựa chọn', pronunciation: 'lua chon', category: 'action', chapter: 'chapter10', difficulty: 1, examples: ['Select size and color.'] },
  { id: 'action8', english: 'Try on', vietnamese: 'Thử', pronunciation: 'thu', category: 'action', chapter: 'chapter10', difficulty: 1, examples: ['Try on clothes before buying.'] },
  { id: 'action9', english: 'Return', vietnamese: 'Trả lại', pronunciation: 'tra lai', category: 'action', chapter: 'chapter10', difficulty: 1, examples: ['Return defective product.'] },
  { id: 'action10', english: 'Exchange', vietnamese: 'Đổi', pronunciation: 'doi', category: 'action', chapter: 'chapter10', difficulty: 1, examples: ['Exchange for different size.'] },
  { id: 'action11', english: 'Pay', vietnamese: 'Trả tiền', pronunciation: 'tra tien', category: 'action', chapter: 'chapter10', difficulty: 1, examples: ['Pay at checkout counter.'] },
  { id: 'action12', english: 'Checkout', vietnamese: 'Thanh toán', pronunciation: 'thanh toan', category: 'action', chapter: 'chapter10', difficulty: 1, examples: ['Checkout takes few minutes.'] },
  { id: 'action13', english: 'Order', vietnamese: 'Đặt hàng', pronunciation: 'dat hang', category: 'action', chapter: 'chapter10', difficulty: 1, examples: ['Order food for delivery.'] },
  { id: 'action14', english: 'Deliver', vietnamese: 'Giao hàng', pronunciation: 'giao hang', category: 'action', chapter: 'chapter10', difficulty: 1, examples: ['Deliver package today.'] },
  { id: 'action15', english: 'Ship', vietnamese: 'Vận chuyển', pronunciation: 'van chuyen', category: 'action', chapter: 'chapter10', difficulty: 1, examples: ['Ship items nationwide.'] },
  { id: 'action16', english: 'Pick up', vietnamese: 'Lấy hàng', pronunciation: 'lay hang', category: 'action', chapter: 'chapter10', difficulty: 1, examples: ['Pick up order at store.'] },
  { id: 'action17', english: 'Reserve', vietnamese: 'Đặt trước', pronunciation: 'dat truoc', category: 'action', chapter: 'chapter10', difficulty: 1, examples: ['Reserve item for tomorrow.'] },
  { id: 'action18', english: 'Wait', vietnamese: 'Chờ', pronunciation: 'cho', category: 'action', chapter: 'chapter10', difficulty: 1, examples: ['Wait in line patiently.'] },
  { id: 'action19', english: 'Queue', vietnamese: 'Xếp hàng', pronunciation: 'xep hang', category: 'action', chapter: 'chapter10', difficulty: 1, examples: ['Queue at checkout counter.'] },
  { id: 'action20', english: 'Bargain', vietnamese: 'Mặc cả', pronunciation: 'mac ca', category: 'action', chapter: 'chapter10', difficulty: 1, examples: ['Bargain for better price.'] },
  { id: 'action21', english: 'Negotiate', vietnamese: 'Thương lượng', pronunciation: 'thuong luong', category: 'action', chapter: 'chapter10', difficulty: 2, examples: ['Negotiate contract terms.'] },
  { id: 'action22', english: 'Wrap', vietnamese: 'Gói', pronunciation: 'goi', category: 'action', chapter: 'chapter10', difficulty: 1, examples: ['Wrap gift beautifully.'] },
  { id: 'action23', english: 'Package', vietnamese: 'Đóng gói', pronunciation: 'dong goi', category: 'action', chapter: 'chapter10', difficulty: 1, examples: ['Package items carefully.'] },
  { id: 'action24', english: 'Scan', vietnamese: 'Quét mã', pronunciation: 'quet ma', category: 'action', chapter: 'chapter10', difficulty: 1, examples: ['Scan barcode for price.'] },
  { id: 'action25', english: 'Weigh', vietnamese: 'Cân', pronunciation: 'can', category: 'action', chapter: 'chapter10', difficulty: 1, examples: ['Weigh vegetables at scale.'] },

  // Shopping Items & Terms (25 words)
  { id: 'item1', english: 'Product', vietnamese: 'Sản phẩm', pronunciation: 'san pham', category: 'item', chapter: 'chapter10', difficulty: 1, examples: ['Quality product lasts longer.'] },
  { id: 'item2', english: 'Item', vietnamese: 'Món hàng', pronunciation: 'mon hang', category: 'item', chapter: 'chapter10', difficulty: 1, examples: ['Check each item carefully.'] },
  { id: 'item3', english: 'Goods', vietnamese: 'Hàng hóa', pronunciation: 'hang hoa', category: 'item', chapter: 'chapter10', difficulty: 1, examples: ['Import goods from abroad.'] },
  { id: 'item4', english: 'Merchandise', vietnamese: 'Hàng hóa', pronunciation: 'hang hoa', category: 'item', chapter: 'chapter10', difficulty: 2, examples: ['Display merchandise attractively.'] },
  { id: 'item5', english: 'Brand', vietnamese: 'Thương hiệu', pronunciation: 'thuong hieu', category: 'item', chapter: 'chapter10', difficulty: 1, examples: ['Trust this brand quality.'] },
  { id: 'item6', english: 'Label', vietnamese: 'Nhãn', pronunciation: 'nhan', category: 'item', chapter: 'chapter10', difficulty: 1, examples: ['Read product label carefully.'] },
  { id: 'item7', english: 'Size', vietnamese: 'Kích cỡ', pronunciation: 'kich co', category: 'item', chapter: 'chapter10', difficulty: 1, examples: ['Choose correct clothing size.'] },
  { id: 'item8', english: 'Color', vietnamese: 'Màu sắc', pronunciation: 'mau sac', category: 'item', chapter: 'chapter10', difficulty: 1, examples: ['Prefer dark color clothes.'] },
  { id: 'item9', english: 'Quality', vietnamese: 'Chất lượng', pronunciation: 'chat luong', category: 'item', chapter: 'chapter10', difficulty: 1, examples: ['High quality worth paying.'] },
  { id: 'item10', english: 'Quantity', vietnamese: 'Số lượng', pronunciation: 'so luong', category: 'item', chapter: 'chapter10', difficulty: 1, examples: ['Order large quantity.'] },
  { id: 'item11', english: 'Stock', vietnamese: 'Hàng tồn kho', pronunciation: 'hang ton kho', category: 'item', chapter: 'chapter10', difficulty: 1, examples: ['Check stock availability.'] },
  { id: 'item12', english: 'Inventory', vietnamese: 'Kiểm kê', pronunciation: 'kiem ke', category: 'item', chapter: 'chapter10', difficulty: 2, examples: ['Monthly inventory count.'] },
  { id: 'item13', english: 'Catalog', vietnamese: 'Danh mục', pronunciation: 'danh muc', category: 'item', chapter: 'chapter10', difficulty: 1, examples: ['Browse product catalog.'] },
  { id: 'item14', english: 'Sample', vietnamese: 'Mẫu', pronunciation: 'mau', category: 'item', chapter: 'chapter10', difficulty: 1, examples: ['Try free sample first.'] },
  { id: 'item15', english: 'Warranty', vietnamese: 'Bảo hành', pronunciation: 'bao hanh', category: 'item', chapter: 'chapter10', difficulty: 1, examples: ['One year warranty included.'] },
  { id: 'item16', english: 'Guarantee', vietnamese: 'Đảm bảo', pronunciation: 'dam bao', category: 'item', chapter: 'chapter10', difficulty: 1, examples: ['Money back guarantee.'] },
  { id: 'item17', english: 'Expiry date', vietnamese: 'Ngày hết hạn', pronunciation: 'ngay het han', category: 'item', chapter: 'chapter10', difficulty: 1, examples: ['Check expiry date carefully.'] },
  { id: 'item18', english: 'Barcode', vietnamese: 'Mã vạch', pronunciation: 'ma vach', category: 'item', chapter: 'chapter10', difficulty: 1, examples: ['Scan barcode for price.'] },
  { id: 'item19', english: 'Package', vietnamese: 'Gói hàng', pronunciation: 'goi hang', category: 'item', chapter: 'chapter10', difficulty: 1, examples: ['Receive package safely.'] },
  { id: 'item20', english: 'Bag', vietnamese: 'Túi', pronunciation: 'tui', category: 'item', chapter: 'chapter10', difficulty: 1, examples: ['Carry items in bag.'] },
  { id: 'item21', english: 'Basket', vietnamese: 'Giỏ', pronunciation: 'gio', category: 'item', chapter: 'chapter10', difficulty: 1, examples: ['Put groceries in basket.'] },
  { id: 'item22', english: 'Cart', vietnamese: 'Xe đẩy', pronunciation: 'xe day', category: 'item', chapter: 'chapter10', difficulty: 1, examples: ['Push shopping cart.'] },
  { id: 'item23', english: 'List', vietnamese: 'Danh sách', pronunciation: 'danh sach', category: 'item', chapter: 'chapter10', difficulty: 1, examples: ['Make shopping list.'] },
  { id: 'item24', english: 'Coupon', vietnamese: 'Phiếu giảm giá', pronunciation: 'phieu giam gia', category: 'item', chapter: 'chapter10', difficulty: 1, examples: ['Use coupon for discount.'] },
  { id: 'item25', english: 'Gift card', vietnamese: 'Thẻ quà tặng', pronunciation: 'the qua tang', category: 'item', chapter: 'chapter10', difficulty: 1, examples: ['Buy gift card for friend.'] }
]
