// Chapter 21: Household Items (100 Essential Words)
// Words related to furniture, appliances, household objects, and home essentials

import { LanguageWord } from './chapter01-basic-everyday'

export const chapter21Words: LanguageWord[] = [
  // Furniture & Room Items (25 words)
  { id: 'furniture1', english: 'Furniture', vietnamese: 'Đồ nội thất', pronunciation: 'do noi that', category: 'furniture', chapter: 'chapter21', difficulty: 1, examples: ['Furniture arranged nicely.'] },
  { id: 'furniture2', english: 'Chair', vietnamese: 'Ghế', pronunciation: 'ghe', category: 'furniture', chapter: 'chapter21', difficulty: 1, examples: ['Chair very comfortable.'] },
  { id: 'furniture3', english: 'Table', vietnamese: 'Bàn', pronunciation: 'ban', category: 'furniture', chapter: 'chapter21', difficulty: 1, examples: ['Table holds books.'] },
  { id: 'furniture4', english: 'Sofa', vietnamese: 'Ghế sofa', pronunciation: 'ghe sofa', category: 'furniture', chapter: 'chapter21', difficulty: 1, examples: ['Sofa soft comfortable.'] },
  { id: 'furniture5', english: 'Bed', vietnamese: 'Giường', pronunciation: 'giuong', category: 'furniture', chapter: 'chapter21', difficulty: 1, examples: ['Bed sleeps peacefully.'] },
  { id: 'furniture6', english: 'Mattress', vietnamese: 'Nệm', pronunciation: 'nem', category: 'furniture', chapter: 'chapter21', difficulty: 1, examples: ['Mattress supports well.'] },
  { id: 'furniture7', english: 'Pillow', vietnamese: 'Gối', pronunciation: 'goi', category: 'furniture', chapter: 'chapter21', difficulty: 1, examples: ['Pillow soft fluffy.'] },
  { id: 'furniture8', english: 'Blanket', vietnamese: 'Chăn', pronunciation: 'chan', category: 'furniture', chapter: 'chapter21', difficulty: 1, examples: ['Blanket keeps warm.'] },
  { id: 'furniture9', english: 'Sheet', vietnamese: 'Ga giường', pronunciation: 'ga giuong', category: 'furniture', chapter: 'chapter21', difficulty: 1, examples: ['Clean sheets fresh.'] },
  { id: 'furniture10', english: 'Dresser', vietnamese: 'Tủ quần áo', pronunciation: 'tu quan ao', category: 'furniture', chapter: 'chapter21', difficulty: 1, examples: ['Dresser stores clothes.'] },
  { id: 'furniture11', english: 'Wardrobe', vietnamese: 'Tủ đựng quần áo', pronunciation: 'tu dung quan ao', category: 'furniture', chapter: 'chapter21', difficulty: 1, examples: ['Wardrobe organized neatly.'] },
  { id: 'furniture12', english: 'Bookshelf', vietnamese: 'Kệ sách', pronunciation: 'ke sach', category: 'furniture', chapter: 'chapter21', difficulty: 1, examples: ['Bookshelf full books.'] },
  { id: 'furniture13', english: 'Desk', vietnamese: 'Bàn làm việc', pronunciation: 'ban lam viec', category: 'furniture', chapter: 'chapter21', difficulty: 1, examples: ['Desk workspace organized.'] },
  { id: 'furniture14', english: 'Cabinet', vietnamese: 'Tủ', pronunciation: 'tu', category: 'furniture', chapter: 'chapter21', difficulty: 1, examples: ['Cabinet stores dishes.'] },
  { id: 'furniture15', english: 'Shelf', vietnamese: 'Kệ', pronunciation: 'ke', category: 'furniture', chapter: 'chapter21', difficulty: 1, examples: ['Shelf displays items.'] },
  { id: 'furniture16', english: 'Mirror', vietnamese: 'Gương', pronunciation: 'guong', category: 'furniture', chapter: 'chapter21', difficulty: 1, examples: ['Mirror reflects clearly.'] },
  { id: 'furniture17', english: 'Lamp', vietnamese: 'Đèn', pronunciation: 'den', category: 'furniture', chapter: 'chapter21', difficulty: 1, examples: ['Lamp provides light.'] },
  { id: 'furniture18', english: 'Curtain', vietnamese: 'Rèm cửa', pronunciation: 'rem cua', category: 'furniture', chapter: 'chapter21', difficulty: 1, examples: ['Curtain blocks sunlight.'] },
  { id: 'furniture19', english: 'Carpet', vietnamese: 'Thảm', pronunciation: 'tham', category: 'furniture', chapter: 'chapter21', difficulty: 1, examples: ['Carpet covers floor.'] },
  { id: 'furniture20', english: 'Rug', vietnamese: 'Thảm nhỏ', pronunciation: 'tham nho', category: 'furniture', chapter: 'chapter21', difficulty: 1, examples: ['Rug decorates room.'] },
  { id: 'furniture21', english: 'Clock', vietnamese: 'Đồng hồ', pronunciation: 'dong ho', category: 'furniture', chapter: 'chapter21', difficulty: 1, examples: ['Clock shows time.'] },
  { id: 'furniture22', english: 'Picture frame', vietnamese: 'Khung ảnh', pronunciation: 'khung anh', category: 'furniture', chapter: 'chapter21', difficulty: 1, examples: ['Picture frame holds memories.'] },
  { id: 'furniture23', english: 'Vase', vietnamese: 'Lọ hoa', pronunciation: 'lo hoa', category: 'furniture', chapter: 'chapter21', difficulty: 1, examples: ['Vase holds flowers.'] },
  { id: 'furniture24', english: 'Cushion', vietnamese: 'Đệm', pronunciation: 'dem', category: 'furniture', chapter: 'chapter21', difficulty: 1, examples: ['Cushion adds comfort.'] },
  { id: 'furniture25', english: 'Ottoman', vietnamese: 'Ghế đẩu', pronunciation: 'ghe dau', category: 'furniture', chapter: 'chapter21', difficulty: 2, examples: ['Ottoman rests feet.'] },

  // Kitchen Appliances & Items (25 words)
  { id: 'kitchen1', english: 'Kitchen', vietnamese: 'Nhà bếp', pronunciation: 'nha bep', category: 'kitchen', chapter: 'chapter21', difficulty: 1, examples: ['Kitchen cooks delicious.'] },
  { id: 'kitchen2', english: 'Refrigerator', vietnamese: 'Tủ lạnh', pronunciation: 'tu lanh', category: 'kitchen', chapter: 'chapter21', difficulty: 1, examples: ['Refrigerator keeps cold.'] },
  { id: 'kitchen3', english: 'Stove', vietnamese: 'Bếp', pronunciation: 'bep', category: 'kitchen', chapter: 'chapter21', difficulty: 1, examples: ['Stove cooks food.'] },
  { id: 'kitchen4', english: 'Oven', vietnamese: 'Lò nướng', pronunciation: 'lo nuong', category: 'kitchen', chapter: 'chapter21', difficulty: 1, examples: ['Oven bakes bread.'] },
  { id: 'kitchen5', english: 'Microwave', vietnamese: 'Lò vi sóng', pronunciation: 'lo vi song', category: 'kitchen', chapter: 'chapter21', difficulty: 1, examples: ['Microwave heats quickly.'] },
  { id: 'kitchen6', english: 'Dishwasher', vietnamese: 'Máy rửa bát', pronunciation: 'may rua bat', category: 'kitchen', chapter: 'chapter21', difficulty: 1, examples: ['Dishwasher cleans efficiently.'] },
  { id: 'kitchen7', english: 'Sink', vietnamese: 'Bồn rửa', pronunciation: 'bon rua', category: 'kitchen', chapter: 'chapter21', difficulty: 1, examples: ['Sink washes dishes.'] },
  { id: 'kitchen8', english: 'Faucet', vietnamese: 'Vòi nước', pronunciation: 'voi nuoc', category: 'kitchen', chapter: 'chapter21', difficulty: 1, examples: ['Faucet provides water.'] },
  { id: 'kitchen9', english: 'Counter', vietnamese: 'Mặt bàn', pronunciation: 'mat ban', category: 'kitchen', chapter: 'chapter21', difficulty: 1, examples: ['Counter workspace clean.'] },
  { id: 'kitchen10', english: 'Pot', vietnamese: 'Nồi', pronunciation: 'noi', category: 'kitchen', chapter: 'chapter21', difficulty: 1, examples: ['Pot boils water.'] },
  { id: 'kitchen11', english: 'Pan', vietnamese: 'Chảo', pronunciation: 'chao', category: 'kitchen', chapter: 'chapter21', difficulty: 1, examples: ['Pan fries eggs.'] },
  { id: 'kitchen12', english: 'Plate', vietnamese: 'Đĩa', pronunciation: 'dia', category: 'kitchen', chapter: 'chapter21', difficulty: 1, examples: ['Plate holds food.'] },
  { id: 'kitchen13', english: 'Bowl', vietnamese: 'Bát', pronunciation: 'bat', category: 'kitchen', chapter: 'chapter21', difficulty: 1, examples: ['Bowl contains soup.'] },
  { id: 'kitchen14', english: 'Cup', vietnamese: 'Cốc', pronunciation: 'coc', category: 'kitchen', chapter: 'chapter21', difficulty: 1, examples: ['Cup holds coffee.'] },
  { id: 'kitchen15', english: 'Glass', vietnamese: 'Ly', pronunciation: 'ly', category: 'kitchen', chapter: 'chapter21', difficulty: 1, examples: ['Glass transparent clear.'] },
  { id: 'kitchen16', english: 'Fork', vietnamese: 'Nĩa', pronunciation: 'nia', category: 'kitchen', chapter: 'chapter21', difficulty: 1, examples: ['Fork picks food.'] },
  { id: 'kitchen17', english: 'Knife', vietnamese: 'Dao', pronunciation: 'dao', category: 'kitchen', chapter: 'chapter21', difficulty: 1, examples: ['Knife cuts sharp.'] },
  { id: 'kitchen18', english: 'Spoon', vietnamese: 'Thìa', pronunciation: 'thia', category: 'kitchen', chapter: 'chapter21', difficulty: 1, examples: ['Spoon stirs soup.'] },
  { id: 'kitchen19', english: 'Chopsticks', vietnamese: 'Đũa', pronunciation: 'dua', category: 'kitchen', chapter: 'chapter21', difficulty: 1, examples: ['Chopsticks eat rice.'] },
  { id: 'kitchen20', english: 'Kettle', vietnamese: 'Ấm đun nước', pronunciation: 'am dun nuoc', category: 'kitchen', chapter: 'chapter21', difficulty: 1, examples: ['Kettle boils tea.'] },
  { id: 'kitchen21', english: 'Toaster', vietnamese: 'Máy nướng bánh', pronunciation: 'may nuong banh', category: 'kitchen', chapter: 'chapter21', difficulty: 1, examples: ['Toaster browns bread.'] },
  { id: 'kitchen22', english: 'Blender', vietnamese: 'Máy xay', pronunciation: 'may xay', category: 'kitchen', chapter: 'chapter21', difficulty: 1, examples: ['Blender makes smoothies.'] },
  { id: 'kitchen23', english: 'Can opener', vietnamese: 'Dụng cụ mở hộp', pronunciation: 'dung cu mo hop', category: 'kitchen', chapter: 'chapter21', difficulty: 1, examples: ['Can opener opens cans.'] },
  { id: 'kitchen24', english: 'Cutting board', vietnamese: 'Thớt', pronunciation: 'thot', category: 'kitchen', chapter: 'chapter21', difficulty: 1, examples: ['Cutting board protects counter.'] },
  { id: 'kitchen25', english: 'Garbage can', vietnamese: 'Thùng rác', pronunciation: 'thung rac', category: 'kitchen', chapter: 'chapter21', difficulty: 1, examples: ['Garbage can collects waste.'] },

  // Bathroom Items (25 words)
  { id: 'bathroom1', english: 'Bathroom', vietnamese: 'Phòng tắm', pronunciation: 'phong tam', category: 'bathroom', chapter: 'chapter21', difficulty: 1, examples: ['Bathroom clean private.'] },
  { id: 'bathroom2', english: 'Toilet', vietnamese: 'Bồn cầu', pronunciation: 'bon cau', category: 'bathroom', chapter: 'chapter21', difficulty: 1, examples: ['Toilet paper available.'] },
  { id: 'bathroom3', english: 'Bathtub', vietnamese: 'Bồn tắm', pronunciation: 'bon tam', category: 'bathroom', chapter: 'chapter21', difficulty: 1, examples: ['Bathtub relaxing warm.'] },
  { id: 'bathroom4', english: 'Shower', vietnamese: 'Vòi sen', pronunciation: 'voi sen', category: 'bathroom', chapter: 'chapter21', difficulty: 1, examples: ['Shower refreshing clean.'] },
  { id: 'bathroom5', english: 'Towel', vietnamese: 'Khăn tắm', pronunciation: 'khan tam', category: 'bathroom', chapter: 'chapter21', difficulty: 1, examples: ['Towel dries body.'] },
  { id: 'bathroom6', english: 'Soap', vietnamese: 'Xà phòng', pronunciation: 'xa phong', category: 'bathroom', chapter: 'chapter21', difficulty: 1, examples: ['Soap cleans hands.'] },
  { id: 'bathroom7', english: 'Shampoo', vietnamese: 'Dầu gội', pronunciation: 'dau goi', category: 'bathroom', chapter: 'chapter21', difficulty: 1, examples: ['Shampoo cleans hair.'] },
  { id: 'bathroom8', english: 'Toothbrush', vietnamese: 'Bàn chải đánh răng', pronunciation: 'ban chai danh rang', category: 'bathroom', chapter: 'chapter21', difficulty: 1, examples: ['Toothbrush cleans teeth.'] },
  { id: 'bathroom9', english: 'Toothpaste', vietnamese: 'Kem đánh răng', pronunciation: 'kem danh rang', category: 'bathroom', chapter: 'chapter21', difficulty: 1, examples: ['Toothpaste prevents cavities.'] },
  { id: 'bathroom10', english: 'Razor', vietnamese: 'Dao cạo', pronunciation: 'dao cao', category: 'bathroom', chapter: 'chapter21', difficulty: 1, examples: ['Razor shaves smoothly.'] },
  { id: 'bathroom11', english: 'Hairbrush', vietnamese: 'Lược', pronunciation: 'luoc', category: 'bathroom', chapter: 'chapter21', difficulty: 1, examples: ['Hairbrush styles hair.'] },
  { id: 'bathroom12', english: 'Comb', vietnamese: 'Lược nhỏ', pronunciation: 'luoc nho', category: 'bathroom', chapter: 'chapter21', difficulty: 1, examples: ['Comb arranges hair.'] },
  { id: 'bathroom13', english: 'Hairdryer', vietnamese: 'Máy sấy tóc', pronunciation: 'may say toc', category: 'bathroom', chapter: 'chapter21', difficulty: 1, examples: ['Hairdryer dries quickly.'] },
  { id: 'bathroom14', english: 'Mirror', vietnamese: 'Gương', pronunciation: 'guong', category: 'bathroom', chapter: 'chapter21', difficulty: 1, examples: ['Mirror reflects image.'] },
  { id: 'bathroom15', english: 'Scale', vietnamese: 'Cân', pronunciation: 'can', category: 'bathroom', chapter: 'chapter21', difficulty: 1, examples: ['Scale measures weight.'] },
  { id: 'bathroom16', english: 'Medicine cabinet', vietnamese: 'Tủ thuốc', pronunciation: 'tu thuoc', category: 'bathroom', chapter: 'chapter21', difficulty: 1, examples: ['Medicine cabinet stores pills.'] },
  { id: 'bathroom17', english: 'Toilet paper', vietnamese: 'Giấy vệ sinh', pronunciation: 'giay ve sinh', category: 'bathroom', chapter: 'chapter21', difficulty: 1, examples: ['Toilet paper essential.'] },
  { id: 'bathroom18', english: 'Tissue', vietnamese: 'Khăn giấy', pronunciation: 'khan giay', category: 'bathroom', chapter: 'chapter21', difficulty: 1, examples: ['Tissue soft gentle.'] },
  { id: 'bathroom19', english: 'Lotion', vietnamese: 'Kem dưỡng da', pronunciation: 'kem duong da', category: 'bathroom', chapter: 'chapter21', difficulty: 1, examples: ['Lotion moisturizes skin.'] },
  { id: 'bathroom20', english: 'Perfume', vietnamese: 'Nước hoa', pronunciation: 'nuoc hoa', category: 'bathroom', chapter: 'chapter21', difficulty: 1, examples: ['Perfume smells pleasant.'] },
  { id: 'bathroom21', english: 'Deodorant', vietnamese: 'Lăn khử mùi', pronunciation: 'lan khu mui', category: 'bathroom', chapter: 'chapter21', difficulty: 1, examples: ['Deodorant prevents odor.'] },
  { id: 'bathroom22', english: 'Makeup', vietnamese: 'Trang điểm', pronunciation: 'trang diem', category: 'bathroom', chapter: 'chapter21', difficulty: 1, examples: ['Makeup enhances beauty.'] },
  { id: 'bathroom23', english: 'Lipstick', vietnamese: 'Son môi', pronunciation: 'son moi', category: 'bathroom', chapter: 'chapter21', difficulty: 1, examples: ['Lipstick colors lips.'] },
  { id: 'bathroom24', english: 'Nail clipper', vietnamese: 'Kéo cắt móng', pronunciation: 'keo cat mong', category: 'bathroom', chapter: 'chapter21', difficulty: 1, examples: ['Nail clipper trims nails.'] },
  { id: 'bathroom25', english: 'Cotton swab', vietnamese: 'Tăm bông', pronunciation: 'tam bong', category: 'bathroom', chapter: 'chapter21', difficulty: 1, examples: ['Cotton swab cleans ears.'] },

  // Cleaning & Household Tools (25 words)
  { id: 'cleaning1', english: 'Cleaning', vietnamese: 'Dọn dẹp', pronunciation: 'don dep', category: 'cleaning', chapter: 'chapter21', difficulty: 1, examples: ['Cleaning keeps tidy.'] },
  { id: 'cleaning2', english: 'Vacuum cleaner', vietnamese: 'Máy hút bụi', pronunciation: 'may hut bui', category: 'cleaning', chapter: 'chapter21', difficulty: 1, examples: ['Vacuum cleaner removes dust.'] },
  { id: 'cleaning3', english: 'Broom', vietnamese: 'Chổi', pronunciation: 'choi', category: 'cleaning', chapter: 'chapter21', difficulty: 1, examples: ['Broom sweeps floor.'] },
  { id: 'cleaning4', english: 'Mop', vietnamese: 'Cây lau nhà', pronunciation: 'cay lau nha', category: 'cleaning', chapter: 'chapter21', difficulty: 1, examples: ['Mop cleans thoroughly.'] },
  { id: 'cleaning5', english: 'Bucket', vietnamese: 'Xô', pronunciation: 'xo', category: 'cleaning', chapter: 'chapter21', difficulty: 1, examples: ['Bucket holds water.'] },
  { id: 'cleaning6', english: 'Sponge', vietnamese: 'Miếng xốp', pronunciation: 'mieng xop', category: 'cleaning', chapter: 'chapter21', difficulty: 1, examples: ['Sponge absorbs liquid.'] },
  { id: 'cleaning7', english: 'Cloth', vietnamese: 'Khăn lau', pronunciation: 'khan lau', category: 'cleaning', chapter: 'chapter21', difficulty: 1, examples: ['Cloth wipes surfaces.'] },
  { id: 'cleaning8', english: 'Detergent', vietnamese: 'Chất tẩy rửa', pronunciation: 'chat tay rua', category: 'cleaning', chapter: 'chapter21', difficulty: 1, examples: ['Detergent removes stains.'] },
  { id: 'cleaning9', english: 'Bleach', vietnamese: 'Thuốc tẩy', pronunciation: 'thuoc tay', category: 'cleaning', chapter: 'chapter21', difficulty: 1, examples: ['Bleach whitens clothes.'] },
  { id: 'cleaning10', english: 'Washing machine', vietnamese: 'Máy giặt', pronunciation: 'may giat', category: 'cleaning', chapter: 'chapter21', difficulty: 1, examples: ['Washing machine cleans clothes.'] },
  { id: 'cleaning11', english: 'Dryer', vietnamese: 'Máy sấy', pronunciation: 'may say', category: 'cleaning', chapter: 'chapter21', difficulty: 1, examples: ['Dryer removes moisture.'] },
  { id: 'cleaning12', english: 'Iron', vietnamese: 'Bàn ủi', pronunciation: 'ban ui', category: 'cleaning', chapter: 'chapter21', difficulty: 1, examples: ['Iron smooths wrinkles.'] },
  { id: 'cleaning13', english: 'Ironing board', vietnamese: 'Bàn để ủi', pronunciation: 'ban de ui', category: 'cleaning', chapter: 'chapter21', difficulty: 1, examples: ['Ironing board stable surface.'] },
  { id: 'cleaning14', english: 'Hanger', vietnamese: 'Móc treo', pronunciation: 'moc treo', category: 'cleaning', chapter: 'chapter21', difficulty: 1, examples: ['Hanger holds clothes.'] },
  { id: 'cleaning15', english: 'Laundry basket', vietnamese: 'Rổ đựng quần áo', pronunciation: 'ro dung quan ao', category: 'cleaning', chapter: 'chapter21', difficulty: 1, examples: ['Laundry basket collects clothes.'] },
  { id: 'cleaning16', english: 'Dustpan', vietnamese: 'Hốt rác', pronunciation: 'hot rac', category: 'cleaning', chapter: 'chapter21', difficulty: 1, examples: ['Dustpan collects debris.'] },
  { id: 'cleaning17', english: 'Trash bag', vietnamese: 'Túi rác', pronunciation: 'tui rac', category: 'cleaning', chapter: 'chapter21', difficulty: 1, examples: ['Trash bag holds garbage.'] },
  { id: 'cleaning18', english: 'Rubber gloves', vietnamese: 'Găng tay cao su', pronunciation: 'gang tay cao su', category: 'cleaning', chapter: 'chapter21', difficulty: 1, examples: ['Rubber gloves protect hands.'] },
  { id: 'cleaning19', english: 'Scrub brush', vietnamese: 'Bàn chải cọ', pronunciation: 'ban chai co', category: 'cleaning', chapter: 'chapter21', difficulty: 1, examples: ['Scrub brush removes dirt.'] },
  { id: 'cleaning20', english: 'Duster', vietnamese: 'Chổi lông', pronunciation: 'choi long', category: 'cleaning', chapter: 'chapter21', difficulty: 1, examples: ['Duster removes dust.'] },
  { id: 'cleaning21', english: 'Air freshener', vietnamese: 'Chất làm thơm', pronunciation: 'chat lam thom', category: 'cleaning', chapter: 'chapter21', difficulty: 1, examples: ['Air freshener smells nice.'] },
  { id: 'cleaning22', english: 'Disinfectant', vietnamese: 'Chất khử trùng', pronunciation: 'chat khu trung', category: 'cleaning', chapter: 'chapter21', difficulty: 2, examples: ['Disinfectant kills germs.'] },
  { id: 'cleaning23', english: 'Polish', vietnamese: 'Chất đánh bóng', pronunciation: 'chat danh bong', category: 'cleaning', chapter: 'chapter21', difficulty: 1, examples: ['Polish shines surfaces.'] },
  { id: 'cleaning24', english: 'Window cleaner', vietnamese: 'Chất lau kính', pronunciation: 'chat lau kinh', category: 'cleaning', chapter: 'chapter21', difficulty: 1, examples: ['Window cleaner clears glass.'] },
  { id: 'cleaning25', english: 'Paper towel', vietnamese: 'Khăn giấy', pronunciation: 'khan giay', category: 'cleaning', chapter: 'chapter21', difficulty: 1, examples: ['Paper towel absorbs spills.'] }
]
