// Chapter 6: Work & Career (100 Essential Words)
// Words related to jobs, workplace, business, and professional life

import { LanguageWord } from './chapter01-basic-everyday'

export const chapter06Words: LanguageWord[] = [
  // Jobs & Professions (30 words)
  { id: 'work1', english: 'Job', vietnamese: 'Công việc', pronunciation: 'cong viec', category: 'profession', chapter: 'chapter06', difficulty: 1, examples: ['I have a good job.'] },
  { id: 'work2', english: 'Work', vietnamese: 'Làm việc', pronunciation: 'lam viec', category: 'profession', chapter: 'chapter06', difficulty: 1, examples: ['I work in an office.'] },
  { id: 'work3', english: 'Career', vietnamese: 'Sự nghiệp', pronunciation: 'su nghiep', category: 'profession', chapter: 'chapter06', difficulty: 1, examples: ['She has a successful career.'] },
  { id: 'work4', english: 'Teacher', vietnamese: 'Giáo viên', pronunciation: 'giao vien', category: 'profession', chapter: 'chapter06', difficulty: 1, examples: ['My teacher is very kind.'] },
  { id: 'work5', english: 'Doctor', vietnamese: 'Bác sĩ', pronunciation: 'bac si', category: 'profession', chapter: 'chapter06', difficulty: 1, examples: ['The doctor examined me.'] },
  { id: 'work6', english: 'Nurse', vietnamese: 'Y tá', pronunciation: 'y ta', category: 'profession', chapter: 'chapter06', difficulty: 1, examples: ['The nurse helped patients.'] },
  { id: 'work7', english: 'Engineer', vietnamese: 'Kỹ sư', pronunciation: 'ky su', category: 'profession', chapter: 'chapter06', difficulty: 1, examples: ['He is a software engineer.'] },
  { id: 'work8', english: 'Lawyer', vietnamese: 'Luật sư', pronunciation: 'luat su', category: 'profession', chapter: 'chapter06', difficulty: 1, examples: ['The lawyer defended him.'] },
  { id: 'work9', english: 'Police officer', vietnamese: 'Cảnh sát', pronunciation: 'canh sat', category: 'profession', chapter: 'chapter06', difficulty: 1, examples: ['The police officer helped me.'] },
  { id: 'work10', english: 'Firefighter', vietnamese: 'Lính cứu hỏa', pronunciation: 'linh cuu hoa', category: 'profession', chapter: 'chapter06', difficulty: 1, examples: ['Firefighters saved the house.'] },
  { id: 'work11', english: 'Chef', vietnamese: 'Đầu bếp', pronunciation: 'dau bep', category: 'profession', chapter: 'chapter06', difficulty: 1, examples: ['The chef cooked delicious food.'] },
  { id: 'work12', english: 'Waiter', vietnamese: 'Phục vụ bàn', pronunciation: 'phuc vu ban', category: 'profession', chapter: 'chapter06', difficulty: 1, examples: ['The waiter brought our order.'] },
  { id: 'work13', english: 'Driver', vietnamese: 'Tài xế', pronunciation: 'tai xe', category: 'profession', chapter: 'chapter06', difficulty: 1, examples: ['The taxi driver was friendly.'] },
  { id: 'work14', english: 'Pilot', vietnamese: 'Phi công', pronunciation: 'phi cong', category: 'profession', chapter: 'chapter06', difficulty: 1, examples: ['The pilot flew the plane.'] },
  { id: 'work15', english: 'Mechanic', vietnamese: 'Thợ máy', pronunciation: 'tho may', category: 'profession', chapter: 'chapter06', difficulty: 1, examples: ['The mechanic fixed my car.'] },
  { id: 'work16', english: 'Electrician', vietnamese: 'Thợ điện', pronunciation: 'tho dien', category: 'profession', chapter: 'chapter06', difficulty: 1, examples: ['Call the electrician for help.'] },
  { id: 'work17', english: 'Plumber', vietnamese: 'Thợ sửa ống nước', pronunciation: 'tho sua ong nuoc', category: 'profession', chapter: 'chapter06', difficulty: 1, examples: ['The plumber fixed the leak.'] },
  { id: 'work18', english: 'Carpenter', vietnamese: 'Thợ mộc', pronunciation: 'tho moc', category: 'profession', chapter: 'chapter06', difficulty: 1, examples: ['The carpenter built a table.'] },
  { id: 'work19', english: 'Artist', vietnamese: 'Nghệ sĩ', pronunciation: 'nghe si', category: 'profession', chapter: 'chapter06', difficulty: 1, examples: ['The artist painted beautifully.'] },
  { id: 'work20', english: 'Musician', vietnamese: 'Nhạc sĩ', pronunciation: 'nhac si', category: 'profession', chapter: 'chapter06', difficulty: 1, examples: ['The musician played guitar.'] },
  { id: 'work21', english: 'Actor', vietnamese: 'Diễn viên', pronunciation: 'dien vien', category: 'profession', chapter: 'chapter06', difficulty: 1, examples: ['The actor performed well.'] },
  { id: 'work22', english: 'Farmer', vietnamese: 'Nông dân', pronunciation: 'nong dan', category: 'profession', chapter: 'chapter06', difficulty: 1, examples: ['The farmer grows vegetables.'] },
  { id: 'work23', english: 'Soldier', vietnamese: 'Người lính', pronunciation: 'nguoi linh', category: 'profession', chapter: 'chapter06', difficulty: 1, examples: ['The soldier served his country.'] },
  { id: 'work24', english: 'Manager', vietnamese: 'Quản lý', pronunciation: 'quan ly', category: 'profession', chapter: 'chapter06', difficulty: 1, examples: ['The manager called a meeting.'] },
  { id: 'work25', english: 'Secretary', vietnamese: 'Thư ký', pronunciation: 'thu ky', category: 'profession', chapter: 'chapter06', difficulty: 1, examples: ['The secretary answered the phone.'] },
  { id: 'work26', english: 'Accountant', vietnamese: 'Kế toán', pronunciation: 'ke toan', category: 'profession', chapter: 'chapter06', difficulty: 1, examples: ['The accountant handles finances.'] },
  { id: 'work27', english: 'Pharmacist', vietnamese: 'Dược sĩ', pronunciation: 'duoc si', category: 'profession', chapter: 'chapter06', difficulty: 1, examples: ['The pharmacist gave medicine.'] },
  { id: 'work28', english: 'Dentist', vietnamese: 'Nha sĩ', pronunciation: 'nha si', category: 'profession', chapter: 'chapter06', difficulty: 1, examples: ['Visit the dentist regularly.'] },
  { id: 'work29', english: 'Scientist', vietnamese: 'Nhà khoa học', pronunciation: 'nha khoa hoc', category: 'profession', chapter: 'chapter06', difficulty: 1, examples: ['The scientist made a discovery.'] },
  { id: 'work30', english: 'Programmer', vietnamese: 'Lập trình viên', pronunciation: 'lap trinh vien', category: 'profession', chapter: 'chapter06', difficulty: 1, examples: ['The programmer wrote code.'] },

  // Workplace Terms (25 words)
  { id: 'workplace1', english: 'Office', vietnamese: 'Văn phòng', pronunciation: 'van phong', category: 'workplace', chapter: 'chapter06', difficulty: 1, examples: ['I work in an office building.'] },
  { id: 'workplace2', english: 'Company', vietnamese: 'Công ty', pronunciation: 'cong ty', category: 'workplace', chapter: 'chapter06', difficulty: 1, examples: ['Our company is growing.'] },
  { id: 'workplace3', english: 'Business', vietnamese: 'Kinh doanh', pronunciation: 'kinh doanh', category: 'workplace', chapter: 'chapter06', difficulty: 1, examples: ['He owns a small business.'] },
  { id: 'workplace4', english: 'Factory', vietnamese: 'Nhà máy', pronunciation: 'nha may', category: 'workplace', chapter: 'chapter06', difficulty: 1, examples: ['The factory produces cars.'] },
  { id: 'workplace5', english: 'Store', vietnamese: 'Cửa hàng', pronunciation: 'cua hang', category: 'workplace', chapter: 'chapter06', difficulty: 1, examples: ['I bought food at the store.'] },
  { id: 'workplace6', english: 'Shop', vietnamese: 'Tiệm', pronunciation: 'tiem', category: 'workplace', chapter: 'chapter06', difficulty: 1, examples: ['The coffee shop is busy.'] },
  { id: 'workplace7', english: 'Restaurant', vietnamese: 'Nhà hàng', pronunciation: 'nha hang', category: 'workplace', chapter: 'chapter06', difficulty: 1, examples: ['We ate at a nice restaurant.'] },
  { id: 'workplace8', english: 'Hospital', vietnamese: 'Bệnh viện', pronunciation: 'benh vien', category: 'workplace', chapter: 'chapter06', difficulty: 1, examples: ['She works at the hospital.'] },
  { id: 'workplace9', english: 'School', vietnamese: 'Trường học', pronunciation: 'truong hoc', category: 'workplace', chapter: 'chapter06', difficulty: 1, examples: ['Children go to school daily.'] },
  { id: 'workplace10', english: 'University', vietnamese: 'Đại học', pronunciation: 'dai hoc', category: 'workplace', chapter: 'chapter06', difficulty: 1, examples: ['He studies at university.'] },
  { id: 'workplace11', english: 'Bank', vietnamese: 'Ngân hàng', pronunciation: 'ngan hang', category: 'workplace', chapter: 'chapter06', difficulty: 1, examples: ['I went to the bank.'] },
  { id: 'workplace12', english: 'Post office', vietnamese: 'Bưu điện', pronunciation: 'buu dien', category: 'workplace', chapter: 'chapter06', difficulty: 1, examples: ['Send mail at post office.'] },
  { id: 'workplace13', english: 'Police station', vietnamese: 'Đồn cảnh sát', pronunciation: 'don canh sat', category: 'workplace', chapter: 'chapter06', difficulty: 1, examples: ['Report crime at police station.'] },
  { id: 'workplace14', english: 'Fire station', vietnamese: 'Trạm cứu hỏa', pronunciation: 'tram cuu hoa', category: 'workplace', chapter: 'chapter06', difficulty: 1, examples: ['Fire trucks at fire station.'] },
  { id: 'workplace15', english: 'Library', vietnamese: 'Thư viện', pronunciation: 'thu vien', category: 'workplace', chapter: 'chapter06', difficulty: 1, examples: ['Study quietly in library.'] },
  { id: 'workplace16', english: 'Museum', vietnamese: 'Bảo tàng', pronunciation: 'bao tang', category: 'workplace', chapter: 'chapter06', difficulty: 1, examples: ['Visit art museum today.'] },
  { id: 'workplace17', english: 'Hotel', vietnamese: 'Khách sạn', pronunciation: 'khach san', category: 'workplace', chapter: 'chapter06', difficulty: 1, examples: ['Stay at nice hotel.'] },
  { id: 'workplace18', english: 'Farm', vietnamese: 'Nông trại', pronunciation: 'nong trai', category: 'workplace', chapter: 'chapter06', difficulty: 1, examples: ['Animals live on farm.'] },
  { id: 'workplace19', english: 'Market', vietnamese: 'Chợ', pronunciation: 'cho', category: 'workplace', chapter: 'chapter06', difficulty: 1, examples: ['Buy fresh food at market.'] },
  { id: 'workplace20', english: 'Supermarket', vietnamese: 'Siêu thị', pronunciation: 'sieu thi', category: 'workplace', chapter: 'chapter06', difficulty: 1, examples: ['Shop at big supermarket.'] },
  { id: 'workplace21', english: 'Mall', vietnamese: 'Trung tâm thương mại', pronunciation: 'trung tam thuong mai', category: 'workplace', chapter: 'chapter06', difficulty: 1, examples: ['Many stores in mall.'] },
  { id: 'workplace22', english: 'Gym', vietnamese: 'Phòng tập', pronunciation: 'phong tap', category: 'workplace', chapter: 'chapter06', difficulty: 1, examples: ['Exercise at gym daily.'] },
  { id: 'workplace23', english: 'Salon', vietnamese: 'Tiệm làm tóc', pronunciation: 'tiem lam toc', category: 'workplace', chapter: 'chapter06', difficulty: 1, examples: ['Cut hair at salon.'] },
  { id: 'workplace24', english: 'Garage', vietnamese: 'Ga ra sửa xe', pronunciation: 'ga ra sua xe', category: 'workplace', chapter: 'chapter06', difficulty: 1, examples: ['Fix car at garage.'] },
  { id: 'workplace25', english: 'Construction site', vietnamese: 'Công trường xây dựng', pronunciation: 'cong truong xay dung', category: 'workplace', chapter: 'chapter06', difficulty: 2, examples: ['Workers at construction site.'] },

  // Work Actions & Activities (25 words)
  { id: 'action1', english: 'Work', vietnamese: 'Làm việc', pronunciation: 'lam viec', category: 'action', chapter: 'chapter06', difficulty: 1, examples: ['I work eight hours daily.'] },
  { id: 'action2', english: 'Start', vietnamese: 'Bắt đầu', pronunciation: 'bat dau', category: 'action', chapter: 'chapter06', difficulty: 1, examples: ['Start work at 9 AM.'] },
  { id: 'action3', english: 'Finish', vietnamese: 'Kết thúc', pronunciation: 'ket thuc', category: 'action', chapter: 'chapter06', difficulty: 1, examples: ['Finish work at 5 PM.'] },
  { id: 'action4', english: 'Hire', vietnamese: 'Thuê', pronunciation: 'thue', category: 'action', chapter: 'chapter06', difficulty: 1, examples: ['Company will hire new staff.'] },
  { id: 'action5', english: 'Fire', vietnamese: 'Sa thải', pronunciation: 'sa thai', category: 'action', chapter: 'chapter06', difficulty: 1, examples: ['Boss fired lazy worker.'] },
  { id: 'action6', english: 'Resign', vietnamese: 'Từ chức', pronunciation: 'tu chuc', category: 'action', chapter: 'chapter06', difficulty: 1, examples: ['She resigned from job.'] },
  { id: 'action7', english: 'Retire', vietnamese: 'Nghỉ hưu', pronunciation: 'nghi huu', category: 'action', chapter: 'chapter06', difficulty: 1, examples: ['He retired at 65.'] },
  { id: 'action8', english: 'Apply', vietnamese: 'Ứng tuyển', pronunciation: 'ung tuyen', category: 'action', chapter: 'chapter06', difficulty: 1, examples: ['Apply for new job.'] },
  { id: 'action9', english: 'Interview', vietnamese: 'Phỏng vấn', pronunciation: 'phong van', category: 'action', chapter: 'chapter06', difficulty: 1, examples: ['Job interview went well.'] },
  { id: 'action10', english: 'Train', vietnamese: 'Đào tạo', pronunciation: 'dao tao', category: 'action', chapter: 'chapter06', difficulty: 1, examples: ['Train new employees well.'] },
  { id: 'action11', english: 'Learn', vietnamese: 'Học', pronunciation: 'hoc', category: 'action', chapter: 'chapter06', difficulty: 1, examples: ['Learn new skills daily.'] },
  { id: 'action12', english: 'Teach', vietnamese: 'Dạy', pronunciation: 'day', category: 'action', chapter: 'chapter06', difficulty: 1, examples: ['Teach students math.'] },
  { id: 'action13', english: 'Manage', vietnamese: 'Quản lý', pronunciation: 'quan ly', category: 'action', chapter: 'chapter06', difficulty: 1, examples: ['Manage team of five.'] },
  { id: 'action14', english: 'Lead', vietnamese: 'Lãnh đạo', pronunciation: 'lanh dao', category: 'action', chapter: 'chapter06', difficulty: 1, examples: ['Lead project successfully.'] },
  { id: 'action15', english: 'Follow', vietnamese: 'Theo dõi', pronunciation: 'theo doi', category: 'action', chapter: 'chapter06', difficulty: 1, examples: ['Follow company rules.'] },
  { id: 'action16', english: 'Plan', vietnamese: 'Lập kế hoạch', pronunciation: 'lap ke hoach', category: 'action', chapter: 'chapter06', difficulty: 1, examples: ['Plan next week schedule.'] },
  { id: 'action17', english: 'Organize', vietnamese: 'Tổ chức', pronunciation: 'to chuc', category: 'action', chapter: 'chapter06', difficulty: 1, examples: ['Organize office files.'] },
  { id: 'action18', english: 'Communicate', vietnamese: 'Giao tiếp', pronunciation: 'giao tiep', category: 'action', chapter: 'chapter06', difficulty: 1, examples: ['Communicate with clients.'] },
  { id: 'action19', english: 'Present', vietnamese: 'Trình bày', pronunciation: 'trinh bay', category: 'action', chapter: 'chapter06', difficulty: 1, examples: ['Present new ideas.'] },
  { id: 'action20', english: 'Sell', vietnamese: 'Bán', pronunciation: 'ban', category: 'action', chapter: 'chapter06', difficulty: 1, examples: ['Sell products to customers.'] },
  { id: 'action21', english: 'Buy', vietnamese: 'Mua', pronunciation: 'mua', category: 'action', chapter: 'chapter06', difficulty: 1, examples: ['Buy office supplies.'] },
  { id: 'action22', english: 'Serve', vietnamese: 'Phục vụ', pronunciation: 'phuc vu', category: 'action', chapter: 'chapter06', difficulty: 1, examples: ['Serve customers well.'] },
  { id: 'action23', english: 'Help', vietnamese: 'Giúp đỡ', pronunciation: 'giup do', category: 'action', chapter: 'chapter06', difficulty: 1, examples: ['Help colleagues finish tasks.'] },
  { id: 'action24', english: 'Cooperate', vietnamese: 'Hợp tác', pronunciation: 'hop tac', category: 'action', chapter: 'chapter06', difficulty: 1, examples: ['Cooperate with team members.'] },
  { id: 'action25', english: 'Complete', vietnamese: 'Hoàn thành', pronunciation: 'hoan thanh', category: 'action', chapter: 'chapter06', difficulty: 1, examples: ['Complete project on time.'] },

  // Work Items & Equipment (20 words)
  { id: 'equipment1', english: 'Computer', vietnamese: 'Máy tính', pronunciation: 'may tinh', category: 'equipment', chapter: 'chapter06', difficulty: 1, examples: ['Use computer for work.'] },
  { id: 'equipment2', english: 'Phone', vietnamese: 'Điện thoại', pronunciation: 'dien thoai', category: 'equipment', chapter: 'chapter06', difficulty: 1, examples: ['Answer office phone.'] },
  { id: 'equipment3', english: 'Desk', vietnamese: 'Bàn làm việc', pronunciation: 'ban lam viec', category: 'equipment', chapter: 'chapter06', difficulty: 1, examples: ['Sit at clean desk.'] },
  { id: 'equipment4', english: 'Chair', vietnamese: 'Ghế', pronunciation: 'ghe', category: 'equipment', chapter: 'chapter06', difficulty: 1, examples: ['Comfortable office chair.'] },
  { id: 'equipment5', english: 'Paper', vietnamese: 'Giấy', pronunciation: 'giay', category: 'equipment', chapter: 'chapter06', difficulty: 1, examples: ['Print on white paper.'] },
  { id: 'equipment6', english: 'Pen', vietnamese: 'Bút', pronunciation: 'but', category: 'equipment', chapter: 'chapter06', difficulty: 1, examples: ['Write with blue pen.'] },
  { id: 'equipment7', english: 'Pencil', vietnamese: 'Bút chì', pronunciation: 'but chi', category: 'equipment', chapter: 'chapter06', difficulty: 1, examples: ['Draw with sharp pencil.'] },
  { id: 'equipment8', english: 'Notebook', vietnamese: 'Sổ tay', pronunciation: 'so tay', category: 'equipment', chapter: 'chapter06', difficulty: 1, examples: ['Take notes in notebook.'] },
  { id: 'equipment9', english: 'File', vietnamese: 'Hồ sơ', pronunciation: 'ho so', category: 'equipment', chapter: 'chapter06', difficulty: 1, examples: ['Organize important files.'] },
  { id: 'equipment10', english: 'Folder', vietnamese: 'Thư mục', pronunciation: 'thu muc', category: 'equipment', chapter: 'chapter06', difficulty: 1, examples: ['Put papers in folder.'] },
  { id: 'equipment11', english: 'Calendar', vietnamese: 'Lịch', pronunciation: 'lich', category: 'equipment', chapter: 'chapter06', difficulty: 1, examples: ['Check calendar for meetings.'] },
  { id: 'equipment12', english: 'Clock', vietnamese: 'Đồng hồ', pronunciation: 'dong ho', category: 'equipment', chapter: 'chapter06', difficulty: 1, examples: ['Check time on clock.'] },
  { id: 'equipment13', english: 'Printer', vietnamese: 'Máy in', pronunciation: 'may in', category: 'equipment', chapter: 'chapter06', difficulty: 1, examples: ['Print documents on printer.'] },
  { id: 'equipment14', english: 'Scanner', vietnamese: 'Máy quét', pronunciation: 'may quet', category: 'equipment', chapter: 'chapter06', difficulty: 1, examples: ['Scan papers with scanner.'] },
  { id: 'equipment15', english: 'Photocopier', vietnamese: 'Máy photocopy', pronunciation: 'may photocopy', category: 'equipment', chapter: 'chapter06', difficulty: 1, examples: ['Make copies on photocopier.'] },
  { id: 'equipment16', english: 'Fax machine', vietnamese: 'Máy fax', pronunciation: 'may fax', category: 'equipment', chapter: 'chapter06', difficulty: 1, examples: ['Send documents by fax machine.'] },
  { id: 'equipment17', english: 'Calculator', vietnamese: 'Máy tính', pronunciation: 'may tinh', category: 'equipment', chapter: 'chapter06', difficulty: 1, examples: ['Calculate numbers with calculator.'] },
  { id: 'equipment18', english: 'Stapler', vietnamese: 'Máy bấm kim', pronunciation: 'may bam kim', category: 'equipment', chapter: 'chapter06', difficulty: 1, examples: ['Staple papers together.'] },
  { id: 'equipment19', english: 'Shredder', vietnamese: 'Máy hủy tài liệu', pronunciation: 'may huy tai lieu', category: 'equipment', chapter: 'chapter06', difficulty: 2, examples: ['Destroy confidential papers.'] },
  { id: 'equipment20', english: 'Briefcase', vietnamese: 'Cặp công sở', pronunciation: 'cap cong so', category: 'equipment', chapter: 'chapter06', difficulty: 1, examples: ['Carry documents in briefcase.'] }
]
