// Chapter 28: Science & Nature (100 Essential Words)
// Words related to science, nature, environment, and natural phenomena

import { LanguageWord } from './chapter01-basic-everyday'

export const chapter28Words: LanguageWord[] = [
  // Basic Science (25 words)
  { id: 'science1', english: 'Science', vietnamese: 'Khoa học', pronunciation: 'khoa hoc', category: 'science', chapter: 'chapter28', difficulty: 1, examples: ['Science explains nature.'] },
  { id: 'science2', english: 'Biology', vietnamese: 'Sinh học', pronunciation: 'sinh hoc', category: 'science', chapter: 'chapter28', difficulty: 1, examples: ['Biology studies life.'] },
  { id: 'science3', english: 'Chemistry', vietnamese: 'Hóa học', pronunciation: 'hoa hoc', category: 'science', chapter: 'chapter28', difficulty: 1, examples: ['Chemistry studies matter.'] },
  { id: 'science4', english: 'Physics', vietnamese: 'Vật lý', pronunciation: 'vat ly', category: 'science', chapter: 'chapter28', difficulty: 1, examples: ['Physics studies motion.'] },
  { id: 'science5', english: 'Mathematics', vietnamese: 'Toán học', pronunciation: 'toan hoc', category: 'science', chapter: 'chapter28', difficulty: 1, examples: ['Mathematics uses numbers.'] },
  { id: 'science6', english: 'Geography', vietnamese: 'Địa lý', pronunciation: 'dia ly', category: 'science', chapter: 'chapter28', difficulty: 1, examples: ['Geography studies Earth.'] },
  { id: 'science7', english: 'Astronomy', vietnamese: 'Thiên văn học', pronunciation: 'thien van hoc', category: 'science', chapter: 'chapter28', difficulty: 1, examples: ['Astronomy studies space.'] },
  { id: 'science8', english: 'Geology', vietnamese: 'Địa chất học', pronunciation: 'dia chat hoc', category: 'science', chapter: 'chapter28', difficulty: 1, examples: ['Geology studies rocks.'] },
  { id: 'science9', english: 'Experiment', vietnamese: 'Thí nghiệm', pronunciation: 'thi nghiem', category: 'science', chapter: 'chapter28', difficulty: 1, examples: ['Experiment tests ideas.'] },
  { id: 'science10', english: 'Research', vietnamese: 'Nghiên cứu', pronunciation: 'nghien cuu', category: 'science', chapter: 'chapter28', difficulty: 1, examples: ['Research finds answers.'] },
  { id: 'science11', english: 'Discovery', vietnamese: 'Khám phá', pronunciation: 'kham pha', category: 'science', chapter: 'chapter28', difficulty: 1, examples: ['Discovery new knowledge.'] },
  { id: 'science12', english: 'Theory', vietnamese: 'Lý thuyết', pronunciation: 'ly thuyet', category: 'science', chapter: 'chapter28', difficulty: 1, examples: ['Theory explains facts.'] },
  { id: 'science13', english: 'Hypothesis', vietnamese: 'Giả thuyết', pronunciation: 'gia thuyet', category: 'science', chapter: 'chapter28', difficulty: 2, examples: ['Hypothesis educated guess.'] },
  { id: 'science14', english: 'Laboratory', vietnamese: 'Phòng thí nghiệm', pronunciation: 'phong thi nghiem', category: 'science', chapter: 'chapter28', difficulty: 1, examples: ['Laboratory research place.'] },
  { id: 'science15', english: 'Microscope', vietnamese: 'Kính hiển vi', pronunciation: 'kinh hien vi', category: 'science', chapter: 'chapter28', difficulty: 1, examples: ['Microscope magnifies objects.'] },
  { id: 'science16', english: 'Telescope', vietnamese: 'Kính thiên văn', pronunciation: 'kinh thien van', category: 'science', chapter: 'chapter28', difficulty: 1, examples: ['Telescope views stars.'] },
  { id: 'science17', english: 'Formula', vietnamese: 'Công thức', pronunciation: 'cong thuc', category: 'science', chapter: 'chapter28', difficulty: 1, examples: ['Formula mathematical rule.'] },
  { id: 'science18', english: 'Equation', vietnamese: 'Phương trình', pronunciation: 'phuong trinh', category: 'science', chapter: 'chapter28', difficulty: 1, examples: ['Equation mathematical statement.'] },
  { id: 'science19', english: 'Data', vietnamese: 'Dữ liệu', pronunciation: 'du lieu', category: 'science', chapter: 'chapter28', difficulty: 1, examples: ['Data information collected.'] },
  { id: 'science20', english: 'Evidence', vietnamese: 'Bằng chứng', pronunciation: 'bang chung', category: 'science', chapter: 'chapter28', difficulty: 1, examples: ['Evidence supports claims.'] },
  { id: 'science21', english: 'Conclusion', vietnamese: 'Kết luận', pronunciation: 'ket luan', category: 'science', chapter: 'chapter28', difficulty: 1, examples: ['Conclusion final result.'] },
  { id: 'science22', english: 'Analysis', vietnamese: 'Phân tích', pronunciation: 'phan tich', category: 'science', chapter: 'chapter28', difficulty: 1, examples: ['Analysis examines data.'] },
  { id: 'science23', english: 'Measurement', vietnamese: 'Đo lường', pronunciation: 'do luong', category: 'science', chapter: 'chapter28', difficulty: 1, examples: ['Measurement quantifies properties.'] },
  { id: 'science24', english: 'Observation', vietnamese: 'Quan sát', pronunciation: 'quan sat', category: 'science', chapter: 'chapter28', difficulty: 1, examples: ['Observation careful watching.'] },
  { id: 'science25', english: 'Classification', vietnamese: 'Phân loại', pronunciation: 'phan loai', category: 'science', chapter: 'chapter28', difficulty: 1, examples: ['Classification organizes groups.'] },

  // Nature & Environment (25 words)
  { id: 'nature1', english: 'Nature', vietnamese: 'Thiên nhiên', pronunciation: 'thien nhien', category: 'nature', chapter: 'chapter28', difficulty: 1, examples: ['Nature beautiful creation.'] },
  { id: 'nature2', english: 'Environment', vietnamese: 'Môi trường', pronunciation: 'moi truong', category: 'nature', chapter: 'chapter28', difficulty: 1, examples: ['Environment surrounds us.'] },
  { id: 'nature3', english: 'Ecosystem', vietnamese: 'Hệ sinh thái', pronunciation: 'he sinh thai', category: 'nature', chapter: 'chapter28', difficulty: 2, examples: ['Ecosystem balanced community.'] },
  { id: 'nature4', english: 'Forest', vietnamese: 'Rừng', pronunciation: 'rung', category: 'nature', chapter: 'chapter28', difficulty: 1, examples: ['Forest many trees.'] },
  { id: 'nature5', english: 'Ocean', vietnamese: 'Đại dương', pronunciation: 'dai duong', category: 'nature', chapter: 'chapter28', difficulty: 1, examples: ['Ocean vast water.'] },
  { id: 'nature6', english: 'Mountain', vietnamese: 'Núi', pronunciation: 'nui', category: 'nature', chapter: 'chapter28', difficulty: 1, examples: ['Mountain high land.'] },
  { id: 'nature7', english: 'River', vietnamese: 'Sông', pronunciation: 'song', category: 'nature', chapter: 'chapter28', difficulty: 1, examples: ['River flowing water.'] },
  { id: 'nature8', english: 'Lake', vietnamese: 'Hồ', pronunciation: 'ho', category: 'nature', chapter: 'chapter28', difficulty: 1, examples: ['Lake still water.'] },
  { id: 'nature9', english: 'Desert', vietnamese: 'Sa mạc', pronunciation: 'sa mac', category: 'nature', chapter: 'chapter28', difficulty: 1, examples: ['Desert dry land.'] },
  { id: 'nature10', english: 'Jungle', vietnamese: 'Rừng rậm', pronunciation: 'rung ram', category: 'nature', chapter: 'chapter28', difficulty: 1, examples: ['Jungle dense forest.'] },
  { id: 'nature11', english: 'Wildlife', vietnamese: 'Động vật hoang dã', pronunciation: 'dong vat hoang da', category: 'nature', chapter: 'chapter28', difficulty: 1, examples: ['Wildlife natural animals.'] },
  { id: 'nature12', english: 'Habitat', vietnamese: 'Môi trường sống', pronunciation: 'moi truong song', category: 'nature', chapter: 'chapter28', difficulty: 1, examples: ['Habitat animal home.'] },
  { id: 'nature13', english: 'Species', vietnamese: 'Loài', pronunciation: 'loai', category: 'nature', chapter: 'chapter28', difficulty: 1, examples: ['Species group organisms.'] },
  { id: 'nature14', english: 'Extinct', vietnamese: 'Tuyệt chủng', pronunciation: 'tuyet chung', category: 'nature', chapter: 'chapter28', difficulty: 1, examples: ['Extinct no longer exists.'] },
  { id: 'nature15', english: 'Endangered', vietnamese: 'Có nguy cơ tuyệt chủng', pronunciation: 'co nguy co tuyet chung', category: 'nature', chapter: 'chapter28', difficulty: 2, examples: ['Endangered species risk.'] },
  { id: 'nature16', english: 'Conservation', vietnamese: 'Bảo tồn', pronunciation: 'bao ton', category: 'nature', chapter: 'chapter28', difficulty: 1, examples: ['Conservation protects nature.'] },
  { id: 'nature17', english: 'Pollution', vietnamese: 'Ô nhiễm', pronunciation: 'o nhiem', category: 'nature', chapter: 'chapter28', difficulty: 1, examples: ['Pollution harms environment.'] },
  { id: 'nature18', english: 'Recycling', vietnamese: 'Tái chế', pronunciation: 'tai che', category: 'nature', chapter: 'chapter28', difficulty: 1, examples: ['Recycling reuses materials.'] },
  { id: 'nature19', english: 'Climate', vietnamese: 'Khí hậu', pronunciation: 'khi hau', category: 'nature', chapter: 'chapter28', difficulty: 1, examples: ['Climate weather patterns.'] },
  { id: 'nature20', english: 'Global warming', vietnamese: 'Nóng lên toàn cầu', pronunciation: 'nong len toan cau', category: 'nature', chapter: 'chapter28', difficulty: 2, examples: ['Global warming Earth heats.'] },
  { id: 'nature21', english: 'Renewable', vietnamese: 'Tái tạo', pronunciation: 'tai tao', category: 'nature', chapter: 'chapter28', difficulty: 1, examples: ['Renewable energy source.'] },
  { id: 'nature22', english: 'Sustainable', vietnamese: 'Bền vững', pronunciation: 'ben vung', category: 'nature', chapter: 'chapter28', difficulty: 1, examples: ['Sustainable long-term practice.'] },
  { id: 'nature23', english: 'Biodiversity', vietnamese: 'Đa dạng sinh học', pronunciation: 'da dang sinh hoc', category: 'nature', chapter: 'chapter28', difficulty: 2, examples: ['Biodiversity variety life.'] },
  { id: 'nature24', english: 'Natural resources', vietnamese: 'Tài nguyên thiên nhiên', pronunciation: 'tai nguyen thien nhien', category: 'nature', chapter: 'chapter28', difficulty: 2, examples: ['Natural resources Earth materials.'] },
  { id: 'nature25', english: 'Carbon footprint', vietnamese: 'Dấu chân carbon', pronunciation: 'dau chan carbon', category: 'nature', chapter: 'chapter28', difficulty: 2, examples: ['Carbon footprint environmental impact.'] },

  // Space & Universe (25 words)
  { id: 'space1', english: 'Space', vietnamese: 'Không gian', pronunciation: 'khong gian', category: 'space', chapter: 'chapter28', difficulty: 1, examples: ['Space vast emptiness.'] },
  { id: 'space2', english: 'Universe', vietnamese: 'Vũ trụ', pronunciation: 'vu tru', category: 'space', chapter: 'chapter28', difficulty: 1, examples: ['Universe everything exists.'] },
  { id: 'space3', english: 'Galaxy', vietnamese: 'Thiên hà', pronunciation: 'thien ha', category: 'space', chapter: 'chapter28', difficulty: 1, examples: ['Galaxy star system.'] },
  { id: 'space4', english: 'Star', vietnamese: 'Ngôi sao', pronunciation: 'ngoi sao', category: 'space', chapter: 'chapter28', difficulty: 1, examples: ['Star shines bright.'] },
  { id: 'space5', english: 'Planet', vietnamese: 'Hành tinh', pronunciation: 'hanh tinh', category: 'space', chapter: 'chapter28', difficulty: 1, examples: ['Planet orbits star.'] },
  { id: 'space6', english: 'Moon', vietnamese: 'Mặt trăng', pronunciation: 'mat trang', category: 'space', chapter: 'chapter28', difficulty: 1, examples: ['Moon orbits Earth.'] },
  { id: 'space7', english: 'Sun', vietnamese: 'Mặt trời', pronunciation: 'mat troi', category: 'space', chapter: 'chapter28', difficulty: 1, examples: ['Sun center solar system.'] },
  { id: 'space8', english: 'Earth', vietnamese: 'Trái đất', pronunciation: 'trai dat', category: 'space', chapter: 'chapter28', difficulty: 1, examples: ['Earth our planet.'] },
  { id: 'space9', english: 'Solar system', vietnamese: 'Hệ mặt trời', pronunciation: 'he mat troi', category: 'space', chapter: 'chapter28', difficulty: 1, examples: ['Solar system sun planets.'] },
  { id: 'space10', english: 'Orbit', vietnamese: 'Quỹ đạo', pronunciation: 'quy dao', category: 'space', chapter: 'chapter28', difficulty: 1, examples: ['Orbit circular path.'] },
  { id: 'space11', english: 'Satellite', vietnamese: 'Vệ tinh', pronunciation: 've tinh', category: 'space', chapter: 'chapter28', difficulty: 1, examples: ['Satellite orbits Earth.'] },
  { id: 'space12', english: 'Rocket', vietnamese: 'Tên lửa', pronunciation: 'ten lua', category: 'space', chapter: 'chapter28', difficulty: 1, examples: ['Rocket launches spacecraft.'] },
  { id: 'space13', english: 'Astronaut', vietnamese: 'Phi hành gia', pronunciation: 'phi hanh gia', category: 'space', chapter: 'chapter28', difficulty: 1, examples: ['Astronaut travels space.'] },
  { id: 'space14', english: 'Spacecraft', vietnamese: 'Tàu vũ trụ', pronunciation: 'tau vu tru', category: 'space', chapter: 'chapter28', difficulty: 1, examples: ['Spacecraft explores space.'] },
  { id: 'space15', english: 'Gravity', vietnamese: 'Trọng lực', pronunciation: 'trong luc', category: 'space', chapter: 'chapter28', difficulty: 1, examples: ['Gravity pulls objects.'] },
  { id: 'space16', english: 'Atmosphere', vietnamese: 'Khí quyển', pronunciation: 'khi quyen', category: 'space', chapter: 'chapter28', difficulty: 1, examples: ['Atmosphere air layer.'] },
  { id: 'space17', english: 'Meteor', vietnamese: 'Sao băng', pronunciation: 'sao bang', category: 'space', chapter: 'chapter28', difficulty: 1, examples: ['Meteor falling star.'] },
  { id: 'space18', english: 'Comet', vietnamese: 'Sao chổi', pronunciation: 'sao choi', category: 'space', chapter: 'chapter28', difficulty: 1, examples: ['Comet ice rock.'] },
  { id: 'space19', english: 'Asteroid', vietnamese: 'Tiểu hành tinh', pronunciation: 'tieu hanh tinh', category: 'space', chapter: 'chapter28', difficulty: 1, examples: ['Asteroid space rock.'] },
  { id: 'space20', english: 'Black hole', vietnamese: 'Hố đen', pronunciation: 'ho den', category: 'space', chapter: 'chapter28', difficulty: 1, examples: ['Black hole dense space.'] },
  { id: 'space21', english: 'Light year', vietnamese: 'Năm ánh sáng', pronunciation: 'nam anh sang', category: 'space', chapter: 'chapter28', difficulty: 2, examples: ['Light year distance unit.'] },
  { id: 'space22', english: 'Constellation', vietnamese: 'Chòm sao', pronunciation: 'chom sao', category: 'space', chapter: 'chapter28', difficulty: 1, examples: ['Constellation star pattern.'] },
  { id: 'space23', english: 'Eclipse', vietnamese: 'Nhật thực', pronunciation: 'nhat thuc', category: 'space', chapter: 'chapter28', difficulty: 1, examples: ['Eclipse moon blocks sun.'] },
  { id: 'space24', english: 'Space station', vietnamese: 'Trạm vũ trụ', pronunciation: 'tram vu tru', category: 'space', chapter: 'chapter28', difficulty: 1, examples: ['Space station orbits Earth.'] },
  { id: 'space25', english: 'Mission', vietnamese: 'Nhiệm vụ', pronunciation: 'nhiem vu', category: 'space', chapter: 'chapter28', difficulty: 1, examples: ['Mission space exploration.'] },

  // Elements & Matter (25 words)
  { id: 'matter1', english: 'Matter', vietnamese: 'Vật chất', pronunciation: 'vat chat', category: 'matter', chapter: 'chapter28', difficulty: 1, examples: ['Matter has mass.'] },
  { id: 'matter2', english: 'Element', vietnamese: 'Nguyên tố', pronunciation: 'nguyen to', category: 'matter', chapter: 'chapter28', difficulty: 1, examples: ['Element basic substance.'] },
  { id: 'matter3', english: 'Atom', vietnamese: 'Nguyên tử', pronunciation: 'nguyen tu', category: 'matter', chapter: 'chapter28', difficulty: 1, examples: ['Atom smallest unit.'] },
  { id: 'matter4', english: 'Molecule', vietnamese: 'Phân tử', pronunciation: 'phan tu', category: 'matter', chapter: 'chapter28', difficulty: 1, examples: ['Molecule atoms combined.'] },
  { id: 'matter5', english: 'Compound', vietnamese: 'Hợp chất', pronunciation: 'hop chat', category: 'matter', chapter: 'chapter28', difficulty: 1, examples: ['Compound elements combined.'] },
  { id: 'matter6', english: 'Mixture', vietnamese: 'Hỗn hợp', pronunciation: 'hon hop', category: 'matter', chapter: 'chapter28', difficulty: 1, examples: ['Mixture substances combined.'] },
  { id: 'matter7', english: 'Solid', vietnamese: 'Chất rắn', pronunciation: 'chat ran', category: 'matter', chapter: 'chapter28', difficulty: 1, examples: ['Solid fixed shape.'] },
  { id: 'matter8', english: 'Liquid', vietnamese: 'Chất lỏng', pronunciation: 'chat long', category: 'matter', chapter: 'chapter28', difficulty: 1, examples: ['Liquid flows freely.'] },
  { id: 'matter9', english: 'Gas', vietnamese: 'Chất khí', pronunciation: 'chat khi', category: 'matter', chapter: 'chapter28', difficulty: 1, examples: ['Gas fills container.'] },
  { id: 'matter10', english: 'Plasma', vietnamese: 'Plasma', pronunciation: 'plasma', category: 'matter', chapter: 'chapter28', difficulty: 2, examples: ['Plasma ionized gas.'] },
  { id: 'matter11', english: 'Density', vietnamese: 'Mật độ', pronunciation: 'mat do', category: 'matter', chapter: 'chapter28', difficulty: 1, examples: ['Density mass volume.'] },
  { id: 'matter12', english: 'Volume', vietnamese: 'Thể tích', pronunciation: 'the tich', category: 'matter', chapter: 'chapter28', difficulty: 1, examples: ['Volume space occupied.'] },
  { id: 'matter13', english: 'Mass', vietnamese: 'Khối lượng', pronunciation: 'khoi luong', category: 'matter', chapter: 'chapter28', difficulty: 1, examples: ['Mass amount matter.'] },
  { id: 'matter14', english: 'Weight', vietnamese: 'Trọng lượng', pronunciation: 'trong luong', category: 'matter', chapter: 'chapter28', difficulty: 1, examples: ['Weight gravity force.'] },
  { id: 'matter15', english: 'Energy', vietnamese: 'Năng lượng', pronunciation: 'nang luong', category: 'matter', chapter: 'chapter28', difficulty: 1, examples: ['Energy ability work.'] },
  { id: 'matter16', english: 'Force', vietnamese: 'Lực', pronunciation: 'luc', category: 'matter', chapter: 'chapter28', difficulty: 1, examples: ['Force pushes pulls.'] },
  { id: 'matter17', english: 'Motion', vietnamese: 'Chuyển động', pronunciation: 'chuyen dong', category: 'matter', chapter: 'chapter28', difficulty: 1, examples: ['Motion position change.'] },
  { id: 'matter18', english: 'Speed', vietnamese: 'Tốc độ', pronunciation: 'toc do', category: 'matter', chapter: 'chapter28', difficulty: 1, examples: ['Speed distance time.'] },
  { id: 'matter19', english: 'Velocity', vietnamese: 'Vận tốc', pronunciation: 'van toc', category: 'matter', chapter: 'chapter28', difficulty: 1, examples: ['Velocity speed direction.'] },
  { id: 'matter20', english: 'Acceleration', vietnamese: 'Gia tốc', pronunciation: 'gia toc', category: 'matter', chapter: 'chapter28', difficulty: 1, examples: ['Acceleration speed change.'] },
  { id: 'matter21', english: 'Temperature', vietnamese: 'Nhiệt độ', pronunciation: 'nhiet do', category: 'matter', chapter: 'chapter28', difficulty: 1, examples: ['Temperature heat measure.'] },
  { id: 'matter22', english: 'Pressure', vietnamese: 'Áp suất', pronunciation: 'ap suat', category: 'matter', chapter: 'chapter28', difficulty: 1, examples: ['Pressure force area.'] },
  { id: 'matter23', english: 'Electricity', vietnamese: 'Điện', pronunciation: 'dien', category: 'matter', chapter: 'chapter28', difficulty: 1, examples: ['Electricity energy form.'] },
  { id: 'matter24', english: 'Magnetism', vietnamese: 'Từ tính', pronunciation: 'tu tinh', category: 'matter', chapter: 'chapter28', difficulty: 1, examples: ['Magnetism attractive force.'] },
  { id: 'matter25', english: 'Radiation', vietnamese: 'Bức xạ', pronunciation: 'buc xa', category: 'matter', chapter: 'chapter28', difficulty: 1, examples: ['Radiation energy emission.'] }
]
