// Chapter 30: Advanced Essential Vocabulary (100 Words)
// Advanced but essential words for daily communication and understanding

import { LanguageWord } from './chapter01-basic-everyday'

export const chapter30Words: LanguageWord[] = [
  // Abstract Concepts (25 words)
  { id: 'abstract1', english: 'Idea', vietnamese: 'Ý tưởng', pronunciation: 'y tuong', category: 'abstract', chapter: 'chapter30', difficulty: 1, examples: ['Idea creative thought.'] },
  { id: 'abstract2', english: 'Concept', vietnamese: 'Khái niệm', pronunciation: 'khai niem', category: 'abstract', chapter: 'chapter30', difficulty: 1, examples: ['Concept general idea.'] },
  { id: 'abstract3', english: 'Opinion', vietnamese: 'Ý kiến', pronunciation: 'y kien', category: 'abstract', chapter: 'chapter30', difficulty: 1, examples: ['Opinion personal view.'] },
  { id: 'abstract4', english: 'Belief', vietnamese: 'Niềm tin', pronunciation: 'niem tin', category: 'abstract', chapter: 'chapter30', difficulty: 1, examples: ['Belief strong feeling.'] },
  { id: 'abstract5', english: 'Truth', vietnamese: 'Sự thật', pronunciation: 'su that', category: 'abstract', chapter: 'chapter30', difficulty: 1, examples: ['Truth honest facts.'] },
  { id: 'abstract6', english: 'Lie', vietnamese: 'Lời nói dối', pronunciation: 'loi noi doi', category: 'abstract', chapter: 'chapter30', difficulty: 1, examples: ['Lie false statement.'] },
  { id: 'abstract7', english: 'Fact', vietnamese: 'Sự kiện', pronunciation: 'su kien', category: 'abstract', chapter: 'chapter30', difficulty: 1, examples: ['Fact proven truth.'] },
  { id: 'abstract8', english: 'Reality', vietnamese: 'Thực tế', pronunciation: 'thuc te', category: 'abstract', chapter: 'chapter30', difficulty: 1, examples: ['Reality actual situation.'] },
  { id: 'abstract9', english: 'Dream', vietnamese: 'Giấc mơ', pronunciation: 'giac mo', category: 'abstract', chapter: 'chapter30', difficulty: 1, examples: ['Dream sleep vision.'] },
  { id: 'abstract10', english: 'Hope', vietnamese: 'Hy vọng', pronunciation: 'hy vong', category: 'abstract', chapter: 'chapter30', difficulty: 1, examples: ['Hope positive expectation.'] },
  { id: 'abstract11', english: 'Fear', vietnamese: 'Nỗi sợ', pronunciation: 'noi so', category: 'abstract', chapter: 'chapter30', difficulty: 1, examples: ['Fear worry feeling.'] },
  { id: 'abstract12', english: 'Courage', vietnamese: 'Lòng dũng cảm', pronunciation: 'long dung cam', category: 'abstract', chapter: 'chapter30', difficulty: 1, examples: ['Courage brave spirit.'] },
  { id: 'abstract13', english: 'Wisdom', vietnamese: 'Trí khôn', pronunciation: 'tri khon', category: 'abstract', chapter: 'chapter30', difficulty: 1, examples: ['Wisdom deep knowledge.'] },
  { id: 'abstract14', english: 'Knowledge', vietnamese: 'Kiến thức', pronunciation: 'kien thuc', category: 'abstract', chapter: 'chapter30', difficulty: 1, examples: ['Knowledge learned information.'] },
  { id: 'abstract15', english: 'Experience', vietnamese: 'Kinh nghiệm', pronunciation: 'kinh nghiem', category: 'abstract', chapter: 'chapter30', difficulty: 1, examples: ['Experience life lessons.'] },
  { id: 'abstract16', english: 'Skill', vietnamese: 'Kỹ năng', pronunciation: 'ky nang', category: 'abstract', chapter: 'chapter30', difficulty: 1, examples: ['Skill learned ability.'] },
  { id: 'abstract17', english: 'Talent', vietnamese: 'Tài năng', pronunciation: 'tai nang', category: 'abstract', chapter: 'chapter30', difficulty: 1, examples: ['Talent natural ability.'] },
  { id: 'abstract18', english: 'Ability', vietnamese: 'Khả năng', pronunciation: 'kha nang', category: 'abstract', chapter: 'chapter30', difficulty: 1, examples: ['Ability power to do.'] },
  { id: 'abstract19', english: 'Opportunity', vietnamese: 'Cơ hội', pronunciation: 'co hoi', category: 'abstract', chapter: 'chapter30', difficulty: 1, examples: ['Opportunity good chance.'] },
  { id: 'abstract20', english: 'Challenge', vietnamese: 'Thách thức', pronunciation: 'thach thuc', category: 'abstract', chapter: 'chapter30', difficulty: 1, examples: ['Challenge difficult task.'] },
  { id: 'abstract21', english: 'Success', vietnamese: 'Thành công', pronunciation: 'thanh cong', category: 'abstract', chapter: 'chapter30', difficulty: 1, examples: ['Success achievement goal.'] },
  { id: 'abstract22', english: 'Failure', vietnamese: 'Thất bại', pronunciation: 'that bai', category: 'abstract', chapter: 'chapter30', difficulty: 1, examples: ['Failure learning experience.'] },
  { id: 'abstract23', english: 'Progress', vietnamese: 'Tiến bộ', pronunciation: 'tien bo', category: 'abstract', chapter: 'chapter30', difficulty: 1, examples: ['Progress forward movement.'] },
  { id: 'abstract24', english: 'Change', vietnamese: 'Thay đổi', pronunciation: 'thay doi', category: 'abstract', chapter: 'chapter30', difficulty: 1, examples: ['Change becomes different.'] },
  { id: 'abstract25', english: 'Development', vietnamese: 'Phát triển', pronunciation: 'phat trien', category: 'abstract', chapter: 'chapter30', difficulty: 1, examples: ['Development growth process.'] },

  // Actions & Processes (25 words)
  { id: 'action1', english: 'Create', vietnamese: 'Tạo ra', pronunciation: 'tao ra', category: 'action', chapter: 'chapter30', difficulty: 1, examples: ['Create something new.'] },
  { id: 'action2', english: 'Destroy', vietnamese: 'Phá hủy', pronunciation: 'pha huy', category: 'action', chapter: 'chapter30', difficulty: 1, examples: ['Destroy break down.'] },
  { id: 'action3', english: 'Build', vietnamese: 'Xây dựng', pronunciation: 'xay dung', category: 'action', chapter: 'chapter30', difficulty: 1, examples: ['Build construct something.'] },
  { id: 'action4', english: 'Improve', vietnamese: 'Cải thiện', pronunciation: 'cai thien', category: 'action', chapter: 'chapter30', difficulty: 1, examples: ['Improve make better.'] },
  { id: 'action5', english: 'Increase', vietnamese: 'Tăng', pronunciation: 'tang', category: 'action', chapter: 'chapter30', difficulty: 1, examples: ['Increase make more.'] },
  { id: 'action6', english: 'Decrease', vietnamese: 'Giảm', pronunciation: 'giam', category: 'action', chapter: 'chapter30', difficulty: 1, examples: ['Decrease make less.'] },
  { id: 'action7', english: 'Compare', vietnamese: 'So sánh', pronunciation: 'so sanh', category: 'action', chapter: 'chapter30', difficulty: 1, examples: ['Compare find differences.'] },
  { id: 'action8', english: 'Decide', vietnamese: 'Quyết định', pronunciation: 'quyet dinh', category: 'action', chapter: 'chapter30', difficulty: 1, examples: ['Decide make choice.'] },
  { id: 'action9', english: 'Choose', vietnamese: 'Chọn', pronunciation: 'chon', category: 'action', chapter: 'chapter30', difficulty: 1, examples: ['Choose select option.'] },
  { id: 'action10', english: 'Solve', vietnamese: 'Giải quyết', pronunciation: 'giai quyet', category: 'action', chapter: 'chapter30', difficulty: 1, examples: ['Solve find answer.'] },
  { id: 'action11', english: 'Explain', vietnamese: 'Giải thích', pronunciation: 'giai thich', category: 'action', chapter: 'chapter30', difficulty: 1, examples: ['Explain make clear.'] },
  { id: 'action12', english: 'Describe', vietnamese: 'Mô tả', pronunciation: 'mo ta', category: 'action', chapter: 'chapter30', difficulty: 1, examples: ['Describe tell details.'] },
  { id: 'action13', english: 'Discuss', vietnamese: 'Thảo luận', pronunciation: 'thao luan', category: 'action', chapter: 'chapter30', difficulty: 1, examples: ['Discuss talk about.'] },
  { id: 'action14', english: 'Argue', vietnamese: 'Tranh luận', pronunciation: 'tranh luan', category: 'action', chapter: 'action', difficulty: 1, examples: ['Argue disagree strongly.'] },
  { id: 'action15', english: 'Agree', vietnamese: 'Đồng ý', pronunciation: 'dong y', category: 'action', chapter: 'chapter30', difficulty: 1, examples: ['Agree have same opinion.'] },
  { id: 'action16', english: 'Disagree', vietnamese: 'Không đồng ý', pronunciation: 'khong dong y', category: 'action', chapter: 'chapter30', difficulty: 1, examples: ['Disagree different opinion.'] },
  { id: 'action17', english: 'Accept', vietnamese: 'Chấp nhận', pronunciation: 'chap nhan', category: 'action', chapter: 'chapter30', difficulty: 1, examples: ['Accept say yes.'] },
  { id: 'action18', english: 'Refuse', vietnamese: 'Từ chối', pronunciation: 'tu choi', category: 'action', chapter: 'chapter30', difficulty: 1, examples: ['Refuse say no.'] },
  { id: 'action19', english: 'Suggest', vietnamese: 'Gợi ý', pronunciation: 'goi y', category: 'action', chapter: 'chapter30', difficulty: 1, examples: ['Suggest offer idea.'] },
  { id: 'action20', english: 'Recommend', vietnamese: 'Khuyến nghị', pronunciation: 'khuyen nghi', category: 'action', chapter: 'chapter30', difficulty: 1, examples: ['Recommend advise choice.'] },
  { id: 'action21', english: 'Organize', vietnamese: 'Tổ chức', pronunciation: 'to chuc', category: 'action', chapter: 'chapter30', difficulty: 1, examples: ['Organize arrange order.'] },
  { id: 'action22', english: 'Plan', vietnamese: 'Lên kế hoạch', pronunciation: 'len ke hoach', category: 'action', chapter: 'chapter30', difficulty: 1, examples: ['Plan prepare ahead.'] },
  { id: 'action23', english: 'Manage', vietnamese: 'Quản lý', pronunciation: 'quan ly', category: 'action', chapter: 'chapter30', difficulty: 1, examples: ['Manage control resources.'] },
  { id: 'action24', english: 'Control', vietnamese: 'Kiểm soát', pronunciation: 'kiem soat', category: 'action', chapter: 'chapter30', difficulty: 1, examples: ['Control direct actions.'] },
  { id: 'action25', english: 'Influence', vietnamese: 'Ảnh hưởng', pronunciation: 'anh huong', category: 'action', chapter: 'chapter30', difficulty: 1, examples: ['Influence affect others.'] },

  // Descriptions & Qualities (25 words)
  { id: 'quality1', english: 'Important', vietnamese: 'Quan trọng', pronunciation: 'quan trong', category: 'quality', chapter: 'chapter30', difficulty: 1, examples: ['Important very significant.'] },
  { id: 'quality2', english: 'Necessary', vietnamese: 'Cần thiết', pronunciation: 'can thiet', category: 'quality', chapter: 'chapter30', difficulty: 1, examples: ['Necessary must have.'] },
  { id: 'quality3', english: 'Useful', vietnamese: 'Hữu ích', pronunciation: 'huu ich', category: 'quality', chapter: 'chapter30', difficulty: 1, examples: ['Useful helps purposes.'] },
  { id: 'quality4', english: 'Effective', vietnamese: 'Hiệu quả', pronunciation: 'hieu qua', category: 'quality', chapter: 'chapter30', difficulty: 1, examples: ['Effective works well.'] },
  { id: 'quality5', english: 'Efficient', vietnamese: 'Hiệu suất cao', pronunciation: 'hieu suat cao', category: 'quality', chapter: 'chapter30', difficulty: 2, examples: ['Efficient saves resources.'] },
  { id: 'quality6', english: 'Convenient', vietnamese: 'Tiện lợi', pronunciation: 'tien loi', category: 'quality', chapter: 'chapter30', difficulty: 1, examples: ['Convenient easy access.'] },
  { id: 'quality7', english: 'Comfortable', vietnamese: 'Thoải mái', pronunciation: 'thoai mai', category: 'quality', chapter: 'chapter30', difficulty: 1, examples: ['Comfortable feels good.'] },
  { id: 'quality8', english: 'Pleasant', vietnamese: 'Dễ chịu', pronunciation: 'de chiu', category: 'quality', chapter: 'chapter30', difficulty: 1, examples: ['Pleasant enjoyable experience.'] },
  { id: 'quality9', english: 'Interesting', vietnamese: 'Thú vị', pronunciation: 'thu vi', category: 'quality', chapter: 'chapter30', difficulty: 1, examples: ['Interesting catches attention.'] },
  { id: 'quality10', english: 'Boring', vietnamese: 'Nhàm chán', pronunciation: 'nham chan', category: 'quality', chapter: 'chapter30', difficulty: 1, examples: ['Boring not interesting.'] },
  { id: 'quality11', english: 'Exciting', vietnamese: 'Thú vị', pronunciation: 'thu vi', category: 'quality', chapter: 'chapter30', difficulty: 1, examples: ['Exciting creates enthusiasm.'] },
  { id: 'quality12', english: 'Surprising', vietnamese: 'Ngạc nhiên', pronunciation: 'ngac nhien', category: 'quality', chapter: 'chapter30', difficulty: 1, examples: ['Surprising unexpected event.'] },
  { id: 'quality13', english: 'Amazing', vietnamese: 'Tuyệt vời', pronunciation: 'tuyet voi', category: 'quality', chapter: 'chapter30', difficulty: 1, examples: ['Amazing incredibly good.'] },
  { id: 'quality14', english: 'Wonderful', vietnamese: 'Tuyệt diệu', pronunciation: 'tuyet dieu', category: 'quality', chapter: 'chapter30', difficulty: 1, examples: ['Wonderful very beautiful.'] },
  { id: 'quality15', english: 'Perfect', vietnamese: 'Hoàn hảo', pronunciation: 'hoan hao', category: 'quality', chapter: 'chapter30', difficulty: 1, examples: ['Perfect without flaws.'] },
  { id: 'quality16', english: 'Terrible', vietnamese: 'Khủng khiếp', pronunciation: 'khung khiep', category: 'quality', chapter: 'chapter30', difficulty: 1, examples: ['Terrible very bad.'] },
  { id: 'quality17', english: 'Awful', vietnamese: 'Tệ hại', pronunciation: 'te hai', category: 'quality', chapter: 'chapter30', difficulty: 1, examples: ['Awful extremely bad.'] },
  { id: 'quality18', english: 'Serious', vietnamese: 'Nghiêm trọng', pronunciation: 'nghiem trong', category: 'quality', chapter: 'chapter30', difficulty: 1, examples: ['Serious important matter.'] },
  { id: 'quality19', english: 'Careful', vietnamese: 'Cẩn thận', pronunciation: 'can than', category: 'quality', chapter: 'chapter30', difficulty: 1, examples: ['Careful pays attention.'] },
  { id: 'quality20', english: 'Careless', vietnamese: 'Bất cẩn', pronunciation: 'bat can', category: 'quality', chapter: 'chapter30', difficulty: 1, examples: ['Careless not careful.'] },
  { id: 'quality21', english: 'Responsible', vietnamese: 'Có trách nhiệm', pronunciation: 'co trach nhiem', category: 'quality', chapter: 'chapter30', difficulty: 2, examples: ['Responsible takes care.'] },
  { id: 'quality22', english: 'Reliable', vietnamese: 'Đáng tin cậy', pronunciation: 'dang tin cay', category: 'quality', chapter: 'chapter30', difficulty: 1, examples: ['Reliable can trust.'] },
  { id: 'quality23', english: 'Honest', vietnamese: 'Trung thực', pronunciation: 'trung thuc', category: 'quality', chapter: 'chapter30', difficulty: 1, examples: ['Honest tells truth.'] },
  { id: 'quality24', english: 'Fair', vietnamese: 'Công bằng', pronunciation: 'cong bang', category: 'quality', chapter: 'chapter30', difficulty: 1, examples: ['Fair treats equally.'] },
  { id: 'quality25', english: 'Unfair', vietnamese: 'Không công bằng', pronunciation: 'khong cong bang', category: 'quality', chapter: 'chapter30', difficulty: 2, examples: ['Unfair not equal treatment.'] },

  // Problem & Solution Words (25 words)
  { id: 'problem1', english: 'Problem', vietnamese: 'Vấn đề', pronunciation: 'van de', category: 'problem', chapter: 'chapter30', difficulty: 1, examples: ['Problem needs solution.'] },
  { id: 'problem2', english: 'Solution', vietnamese: 'Giải pháp', pronunciation: 'giai phap', category: 'problem', chapter: 'chapter30', difficulty: 1, examples: ['Solution fixes problem.'] },
  { id: 'problem3', english: 'Issue', vietnamese: 'Vấn đề', pronunciation: 'van de', category: 'problem', chapter: 'chapter30', difficulty: 1, examples: ['Issue important topic.'] },
  { id: 'problem4', english: 'Difficulty', vietnamese: 'Khó khăn', pronunciation: 'kho khan', category: 'problem', chapter: 'chapter30', difficulty: 1, examples: ['Difficulty hard situation.'] },
  { id: 'problem5', english: 'Trouble', vietnamese: 'Rắc rối', pronunciation: 'rac roi', category: 'problem', chapter: 'chapter30', difficulty: 1, examples: ['Trouble causes problems.'] },
  { id: 'problem6', english: 'Mistake', vietnamese: 'Lỗi', pronunciation: 'loi', category: 'problem', chapter: 'chapter30', difficulty: 1, examples: ['Mistake wrong action.'] },
  { id: 'problem7', english: 'Error', vietnamese: 'Sai lầm', pronunciation: 'sai lam', category: 'problem', chapter: 'chapter30', difficulty: 1, examples: ['Error incorrect information.'] },
  { id: 'problem8', english: 'Fix', vietnamese: 'Sửa chữa', pronunciation: 'sua chua', category: 'problem', chapter: 'chapter30', difficulty: 1, examples: ['Fix repair broken.'] },
  { id: 'problem9', english: 'Repair', vietnamese: 'Sửa chữa', pronunciation: 'sua chua', category: 'problem', chapter: 'chapter30', difficulty: 1, examples: ['Repair restore function.'] },
  { id: 'problem10', english: 'Help', vietnamese: 'Giúp đỡ', pronunciation: 'giup do', category: 'problem', chapter: 'chapter30', difficulty: 1, examples: ['Help assist others.'] },
  { id: 'problem11', english: 'Support', vietnamese: 'Hỗ trợ', pronunciation: 'ho tro', category: 'problem', chapter: 'chapter30', difficulty: 1, examples: ['Support provide assistance.'] },
  { id: 'problem12', english: 'Advice', vietnamese: 'Lời khuyên', pronunciation: 'loi khuyen', category: 'problem', chapter: 'chapter30', difficulty: 1, examples: ['Advice helpful suggestion.'] },
  { id: 'problem13', english: 'Guide', vietnamese: 'Hướng dẫn', pronunciation: 'huong dan', category: 'problem', chapter: 'chapter30', difficulty: 1, examples: ['Guide show direction.'] },
  { id: 'problem14', english: 'Instruction', vietnamese: 'Hướng dẫn', pronunciation: 'huong dan', category: 'problem', chapter: 'chapter30', difficulty: 1, examples: ['Instruction tells how.'] },
  { id: 'problem15', english: 'Method', vietnamese: 'Phương pháp', pronunciation: 'phuong phap', category: 'problem', chapter: 'chapter30', difficulty: 1, examples: ['Method way doing.'] },
  { id: 'problem16', english: 'Way', vietnamese: 'Cách', pronunciation: 'cach', category: 'problem', chapter: 'chapter30', difficulty: 1, examples: ['Way method approach.'] },
  { id: 'problem17', english: 'Approach', vietnamese: 'Cách tiếp cận', pronunciation: 'cach tiep can', category: 'problem', chapter: 'chapter30', difficulty: 2, examples: ['Approach strategy method.'] },
  { id: 'problem18', english: 'Strategy', vietnamese: 'Chiến lược', pronunciation: 'chien luoc', category: 'problem', chapter: 'chapter30', difficulty: 1, examples: ['Strategy planned approach.'] },
  { id: 'problem19', english: 'Goal', vietnamese: 'Mục tiêu', pronunciation: 'muc tieu', category: 'problem', chapter: 'chapter30', difficulty: 1, examples: ['Goal target objective.'] },
  { id: 'problem20', english: 'Purpose', vietnamese: 'Mục đích', pronunciation: 'muc dich', category: 'problem', chapter: 'chapter30', difficulty: 1, examples: ['Purpose reason doing.'] },
  { id: 'problem21', english: 'Result', vietnamese: 'Kết quả', pronunciation: 'ket qua', category: 'problem', chapter: 'chapter30', difficulty: 1, examples: ['Result outcome effect.'] },
  { id: 'problem22', english: 'Consequence', vietnamese: 'Hậu quả', pronunciation: 'hau qua', category: 'problem', chapter: 'chapter30', difficulty: 1, examples: ['Consequence action result.'] },
  { id: 'problem23', english: 'Effect', vietnamese: 'Tác động', pronunciation: 'tac dong', category: 'problem', chapter: 'chapter30', difficulty: 1, examples: ['Effect change caused.'] },
  { id: 'problem24', english: 'Cause', vietnamese: 'Nguyên nhân', pronunciation: 'nguyen nhan', category: 'problem', chapter: 'chapter30', difficulty: 1, examples: ['Cause reason why.'] },
  { id: 'problem25', english: 'Reason', vietnamese: 'Lý do', pronunciation: 'ly do', category: 'problem', chapter: 'chapter30', difficulty: 1, examples: ['Reason explanation why.'] }
]
