// Chapter 7: Health & Body (100 Essential Words)
// Words related to body parts, health, medical terms, and wellness

import { LanguageWord } from './chapter01-basic-everyday'

export const chapter07Words: LanguageWord[] = [
  // Body Parts (30 words)
  { id: 'body1', english: 'Body', vietnamese: 'Cơ thể', pronunciation: 'co the', category: 'body', chapter: 'chapter07', difficulty: 1, examples: ['Take care of your body.'] },
  { id: 'body2', english: 'Head', vietnamese: 'Đầu', pronunciation: 'dau', category: 'body', chapter: 'chapter07', difficulty: 1, examples: ['My head hurts today.'] },
  { id: 'body3', english: 'Hair', vietnamese: 'Tóc', pronunciation: 'toc', category: 'body', chapter: 'chapter07', difficulty: 1, examples: ['She has beautiful long hair.'] },
  { id: 'body4', english: 'Face', vietnamese: 'Mặt', pronunciation: 'mat', category: 'body', chapter: 'chapter07', difficulty: 1, examples: ['Wash your face daily.'] },
  { id: 'body5', english: 'Eye', vietnamese: 'Mắt', pronunciation: 'mat', category: 'body', chapter: 'chapter07', difficulty: 1, examples: ['She has brown eyes.'] },
  { id: 'body6', english: 'Nose', vietnamese: 'Mũi', pronunciation: 'mui', category: 'body', chapter: 'chapter07', difficulty: 1, examples: ['Cover your nose when sneezing.'] },
  { id: 'body7', english: 'Mouth', vietnamese: 'Miệng', pronunciation: 'mieng', category: 'body', chapter: 'chapter07', difficulty: 1, examples: ['Open your mouth wide.'] },
  { id: 'body8', english: 'Teeth', vietnamese: 'Răng', pronunciation: 'rang', category: 'body', chapter: 'chapter07', difficulty: 1, examples: ['Brush your teeth twice daily.'] },
  { id: 'body9', english: 'Tongue', vietnamese: 'Lưỡi', pronunciation: 'luoi', category: 'body', chapter: 'chapter07', difficulty: 1, examples: ['Stick out your tongue.'] },
  { id: 'body10', english: 'Ear', vietnamese: 'Tai', pronunciation: 'tai', category: 'body', chapter: 'chapter07', difficulty: 1, examples: ['Listen with both ears.'] },
  { id: 'body11', english: 'Neck', vietnamese: 'Cổ', pronunciation: 'co', category: 'body', chapter: 'chapter07', difficulty: 1, examples: ['Turn your neck slowly.'] },
  { id: 'body12', english: 'Shoulder', vietnamese: 'Vai', pronunciation: 'vai', category: 'body', chapter: 'chapter07', difficulty: 1, examples: ['Relax your shoulders.'] },
  { id: 'body13', english: 'Arm', vietnamese: 'Cánh tay', pronunciation: 'canh tay', category: 'body', chapter: 'chapter07', difficulty: 1, examples: ['Raise your arms up.'] },
  { id: 'body14', english: 'Hand', vietnamese: 'Bàn tay', pronunciation: 'ban tay', category: 'body', chapter: 'chapter07', difficulty: 1, examples: ['Wash your hands frequently.'] },
  { id: 'body15', english: 'Finger', vietnamese: 'Ngón tay', pronunciation: 'ngon tay', category: 'body', chapter: 'chapter07', difficulty: 1, examples: ['Point with your finger.'] },
  { id: 'body16', english: 'Chest', vietnamese: 'Ngực', pronunciation: 'nguc', category: 'body', chapter: 'chapter07', difficulty: 1, examples: ['Take deep breaths in chest.'] },
  { id: 'body17', english: 'Back', vietnamese: 'Lưng', pronunciation: 'lung', category: 'body', chapter: 'chapter07', difficulty: 1, examples: ['My back is sore.'] },
  { id: 'body18', english: 'Stomach', vietnamese: 'Bụng', pronunciation: 'bung', category: 'body', chapter: 'chapter07', difficulty: 1, examples: ['My stomach is full.'] },
  { id: 'body19', english: 'Waist', vietnamese: 'Eo', pronunciation: 'eo', category: 'body', chapter: 'chapter07', difficulty: 1, examples: ['Measure your waist size.'] },
  { id: 'body20', english: 'Hip', vietnamese: 'Hông', pronunciation: 'hong', category: 'body', chapter: 'chapter07', difficulty: 1, examples: ['Move your hips when dancing.'] },
  { id: 'body21', english: 'Leg', vietnamese: 'Chân', pronunciation: 'chan', category: 'body', chapter: 'chapter07', difficulty: 1, examples: ['Exercise your legs daily.'] },
  { id: 'body22', english: 'Knee', vietnamese: 'Đầu gối', pronunciation: 'dau goi', category: 'body', chapter: 'chapter07', difficulty: 1, examples: ['Bend your knee slowly.'] },
  { id: 'body23', english: 'Foot', vietnamese: 'Bàn chân', pronunciation: 'ban chan', category: 'body', chapter: 'chapter07', difficulty: 1, examples: ['Keep your feet clean.'] },
  { id: 'body24', english: 'Toe', vietnamese: 'Ngón chân', pronunciation: 'ngon chan', category: 'body', chapter: 'chapter07', difficulty: 1, examples: ['Wiggle your toes.'] },
  { id: 'body25', english: 'Skin', vietnamese: 'Da', pronunciation: 'da', category: 'body', chapter: 'chapter07', difficulty: 1, examples: ['Protect your skin from sun.'] },
  { id: 'body26', english: 'Bone', vietnamese: 'Xương', pronunciation: 'xuong', category: 'body', chapter: 'chapter07', difficulty: 1, examples: ['Calcium strengthens bones.'] },
  { id: 'body27', english: 'Muscle', vietnamese: 'Cơ bắp', pronunciation: 'co bap', category: 'body', chapter: 'chapter07', difficulty: 1, examples: ['Exercise builds muscle.'] },
  { id: 'body28', english: 'Blood', vietnamese: 'Máu', pronunciation: 'mau', category: 'body', chapter: 'chapter07', difficulty: 1, examples: ['Donate blood to help others.'] },
  { id: 'body29', english: 'Heart', vietnamese: 'Tim', pronunciation: 'tim', category: 'body', chapter: 'chapter07', difficulty: 1, examples: ['Heart pumps blood through body.'] },
  { id: 'body30', english: 'Brain', vietnamese: 'Não', pronunciation: 'nao', category: 'body', chapter: 'chapter07', difficulty: 1, examples: ['Use your brain to think.'] },

  // Health Conditions & Symptoms (25 words)
  { id: 'health1', english: 'Health', vietnamese: 'Sức khỏe', pronunciation: 'suc khoe', category: 'health', chapter: 'chapter07', difficulty: 1, examples: ['Good health is important.'] },
  { id: 'health2', english: 'Sick', vietnamese: 'Ốm', pronunciation: 'om', category: 'health', chapter: 'chapter07', difficulty: 1, examples: ['I feel sick today.'] },
  { id: 'health3', english: 'Healthy', vietnamese: 'Khỏe mạnh', pronunciation: 'khoe manh', category: 'health', chapter: 'chapter07', difficulty: 1, examples: ['Eat healthy food daily.'] },
  { id: 'health4', english: 'Pain', vietnamese: 'Đau', pronunciation: 'dau', category: 'health', chapter: 'chapter07', difficulty: 1, examples: ['The pain is getting worse.'] },
  { id: 'health5', english: 'Hurt', vietnamese: 'Bị thương', pronunciation: 'bi thuong', category: 'health', chapter: 'chapter07', difficulty: 1, examples: ['My leg hurts badly.'] },
  { id: 'health6', english: 'Fever', vietnamese: 'Sốt', pronunciation: 'sot', category: 'health', chapter: 'chapter07', difficulty: 1, examples: ['He has high fever.'] },
  { id: 'health7', english: 'Cough', vietnamese: 'Ho', pronunciation: 'ho', category: 'health', chapter: 'chapter07', difficulty: 1, examples: ['Cover mouth when coughing.'] },
  { id: 'health8', english: 'Cold', vietnamese: 'Cảm lạnh', pronunciation: 'cam lanh', category: 'health', chapter: 'chapter07', difficulty: 1, examples: ['I caught a cold.'] },
  { id: 'health9', english: 'Flu', vietnamese: 'Cúm', pronunciation: 'cum', category: 'health', chapter: 'chapter07', difficulty: 1, examples: ['Get flu vaccine yearly.'] },
  { id: 'health10', english: 'Headache', vietnamese: 'Đau đầu', pronunciation: 'dau dau', category: 'health', chapter: 'chapter07', difficulty: 1, examples: ['I have terrible headache.'] },
  { id: 'health11', english: 'Toothache', vietnamese: 'Đau răng', pronunciation: 'dau rang', category: 'health', chapter: 'chapter07', difficulty: 1, examples: ['Toothache keeps me awake.'] },
  { id: 'health12', english: 'Stomachache', vietnamese: 'Đau bụng', pronunciation: 'dau bung', category: 'health', chapter: 'chapter07', difficulty: 1, examples: ['Spicy food causes stomachache.'] },
  { id: 'health13', english: 'Backache', vietnamese: 'Đau lưng', pronunciation: 'dau lung', category: 'health', chapter: 'chapter07', difficulty: 1, examples: ['Sitting causes backache.'] },
  { id: 'health14', english: 'Sore throat', vietnamese: 'Đau họng', pronunciation: 'dau hong', category: 'health', chapter: 'chapter07', difficulty: 1, examples: ['Drink warm tea for sore throat.'] },
  { id: 'health15', english: 'Dizzy', vietnamese: 'Chóng mặt', pronunciation: 'chong mat', category: 'health', chapter: 'chapter07', difficulty: 1, examples: ['I feel dizzy standing up.'] },
  { id: 'health16', english: 'Tired', vietnamese: 'Mệt', pronunciation: 'met', category: 'health', chapter: 'chapter07', difficulty: 1, examples: ['I am very tired today.'] },
  { id: 'health17', english: 'Weak', vietnamese: 'Yếu', pronunciation: 'yeu', category: 'health', chapter: 'chapter07', difficulty: 1, examples: ['Feel weak after illness.'] },
  { id: 'health18', english: 'Nauseous', vietnamese: 'Buồn nôn', pronunciation: 'buon non', category: 'health', chapter: 'chapter07', difficulty: 1, examples: ['Motion makes me nauseous.'] },
  { id: 'health19', english: 'Allergic', vietnamese: 'Dị ứng', pronunciation: 'di ung', category: 'health', chapter: 'chapter07', difficulty: 1, examples: ['I am allergic to nuts.'] },
  { id: 'health20', english: 'Infection', vietnamese: 'Nhiễm trùng', pronunciation: 'nhiem trung', category: 'health', chapter: 'chapter07', difficulty: 2, examples: ['Clean wound to prevent infection.'] },
  { id: 'health21', english: 'Injury', vietnamese: 'Chấn thương', pronunciation: 'chan thuong', category: 'health', chapter: 'chapter07', difficulty: 1, examples: ['Sports injury needs treatment.'] },
  { id: 'health22', english: 'Broken', vietnamese: 'Gãy', pronunciation: 'gay', category: 'health', chapter: 'chapter07', difficulty: 1, examples: ['Broken arm in cast.'] },
  { id: 'health23', english: 'Bruise', vietnamese: 'Bầm tím', pronunciation: 'bam tim', category: 'health', chapter: 'chapter07', difficulty: 1, examples: ['Ice helps reduce bruise.'] },
  { id: 'health24', english: 'Cut', vietnamese: 'Vết cắt', pronunciation: 'vet cat', category: 'health', chapter: 'chapter07', difficulty: 1, examples: ['Clean cut with antiseptic.'] },
  { id: 'health25', english: 'Burn', vietnamese: 'Bỏng', pronunciation: 'bong', category: 'health', chapter: 'chapter07', difficulty: 1, examples: ['Cool water helps burn.'] },

  // Medical Terms & Treatment (25 words)
  { id: 'medical1', english: 'Doctor', vietnamese: 'Bác sĩ', pronunciation: 'bac si', category: 'medical', chapter: 'chapter07', difficulty: 1, examples: ['Visit doctor for checkup.'] },
  { id: 'medical2', english: 'Nurse', vietnamese: 'Y tá', pronunciation: 'y ta', category: 'medical', chapter: 'chapter07', difficulty: 1, examples: ['Nurse checked blood pressure.'] },
  { id: 'medical3', english: 'Hospital', vietnamese: 'Bệnh viện', pronunciation: 'benh vien', category: 'medical', chapter: 'chapter07', difficulty: 1, examples: ['Emergency room at hospital.'] },
  { id: 'medical4', english: 'Clinic', vietnamese: 'Phòng khám', pronunciation: 'phong kham', category: 'medical', chapter: 'chapter07', difficulty: 1, examples: ['Small clinic near home.'] },
  { id: 'medical5', english: 'Medicine', vietnamese: 'Thuốc', pronunciation: 'thuoc', category: 'medical', chapter: 'chapter07', difficulty: 1, examples: ['Take medicine as prescribed.'] },
  { id: 'medical6', english: 'Pill', vietnamese: 'Viên thuốc', pronunciation: 'vien thuoc', category: 'medical', chapter: 'chapter07', difficulty: 1, examples: ['Swallow pill with water.'] },
  { id: 'medical7', english: 'Injection', vietnamese: 'Tiêm', pronunciation: 'tiem', category: 'medical', chapter: 'chapter07', difficulty: 1, examples: ['Vaccine injection prevents disease.'] },
  { id: 'medical8', english: 'Surgery', vietnamese: 'Phẫu thuật', pronunciation: 'phau thuat', category: 'medical', chapter: 'chapter07', difficulty: 2, examples: ['Surgery went successfully.'] },
  { id: 'medical9', english: 'Treatment', vietnamese: 'Điều trị', pronunciation: 'dieu tri', category: 'medical', chapter: 'chapter07', difficulty: 1, examples: ['Treatment takes several weeks.'] },
  { id: 'medical10', english: 'Cure', vietnamese: 'Chữa khỏi', pronunciation: 'chua khoi', category: 'medical', chapter: 'chapter07', difficulty: 1, examples: ['Medicine will cure illness.'] },
  { id: 'medical11', english: 'Heal', vietnamese: 'Lành', pronunciation: 'lanh', category: 'medical', chapter: 'chapter07', difficulty: 1, examples: ['Wound will heal slowly.'] },
  { id: 'medical12', english: 'Recovery', vietnamese: 'Hồi phục', pronunciation: 'hoi phuc', category: 'medical', chapter: 'chapter07', difficulty: 1, examples: ['Recovery takes time.'] },
  { id: 'medical13', english: 'Checkup', vietnamese: 'Khám sức khỏe', pronunciation: 'kham suc khoe', category: 'medical', chapter: 'chapter07', difficulty: 1, examples: ['Annual checkup important.'] },
  { id: 'medical14', english: 'X-ray', vietnamese: 'Chụp X-quang', pronunciation: 'chup X-quang', category: 'medical', chapter: 'chapter07', difficulty: 1, examples: ['X-ray shows broken bone.'] },
  { id: 'medical15', english: 'Test', vietnamese: 'Xét nghiệm', pronunciation: 'xet nghiem', category: 'medical', chapter: 'chapter07', difficulty: 1, examples: ['Blood test results normal.'] },
  { id: 'medical16', english: 'Diagnosis', vietnamese: 'Chẩn đoán', pronunciation: 'chan doan', category: 'medical', chapter: 'chapter07', difficulty: 2, examples: ['Doctor made accurate diagnosis.'] },
  { id: 'medical17', english: 'Prescription', vietnamese: 'Đơn thuốc', pronunciation: 'don thuoc', category: 'medical', chapter: 'chapter07', difficulty: 1, examples: ['Fill prescription at pharmacy.'] },
  { id: 'medical18', english: 'Bandage', vietnamese: 'Băng', pronunciation: 'bang', category: 'medical', chapter: 'chapter07', difficulty: 1, examples: ['Change bandage daily.'] },
  { id: 'medical19', english: 'Cast', vietnamese: 'Bột', pronunciation: 'bot', category: 'medical', chapter: 'chapter07', difficulty: 1, examples: ['Leg in cast for weeks.'] },
  { id: 'medical20', english: 'Crutches', vietnamese: 'Nạng', pronunciation: 'nang', category: 'medical', chapter: 'chapter07', difficulty: 1, examples: ['Walk with crutches carefully.'] },
  { id: 'medical21', english: 'Wheelchair', vietnamese: 'Xe lăn', pronunciation: 'xe lan', category: 'medical', chapter: 'chapter07', difficulty: 1, examples: ['Temporary wheelchair use.'] },
  { id: 'medical22', english: 'Thermometer', vietnamese: 'Nhiệt kế', pronunciation: 'nhiet ke', category: 'medical', chapter: 'chapter07', difficulty: 1, examples: ['Check temperature with thermometer.'] },
  { id: 'medical23', english: 'Stethoscope', vietnamese: 'Ống nghe', pronunciation: 'ong nghe', category: 'medical', chapter: 'chapter07', difficulty: 2, examples: ['Doctor uses stethoscope.'] },
  { id: 'medical24', english: 'Ambulance', vietnamese: 'Xe cứu thương', pronunciation: 'xe cuu thuong', category: 'medical', chapter: 'chapter07', difficulty: 1, examples: ['Call ambulance for emergency.'] },
  { id: 'medical25', english: 'Emergency', vietnamese: 'Cấp cứu', pronunciation: 'cap cuu', category: 'medical', chapter: 'chapter07', difficulty: 1, examples: ['Rush to emergency room.'] },

  // Health Actions & Wellness (20 words)
  { id: 'wellness1', english: 'Exercise', vietnamese: 'Tập thể dục', pronunciation: 'tap the duc', category: 'wellness', chapter: 'chapter07', difficulty: 1, examples: ['Exercise keeps you healthy.'] },
  { id: 'wellness2', english: 'Diet', vietnamese: 'Chế độ ăn', pronunciation: 'che do an', category: 'wellness', chapter: 'chapter07', difficulty: 1, examples: ['Healthy diet prevents disease.'] },
  { id: 'wellness3', english: 'Sleep', vietnamese: 'Ngủ', pronunciation: 'ngu', category: 'wellness', chapter: 'chapter07', difficulty: 1, examples: ['Get enough sleep nightly.'] },
  { id: 'wellness4', english: 'Rest', vietnamese: 'Nghỉ ngơi', pronunciation: 'nghi ngoi', category: 'wellness', chapter: 'chapter07', difficulty: 1, examples: ['Rest when feeling tired.'] },
  { id: 'wellness5', english: 'Relax', vietnamese: 'Thư giãn', pronunciation: 'thu gian', category: 'wellness', chapter: 'chapter07', difficulty: 1, examples: ['Relax after hard work.'] },
  { id: 'wellness6', english: 'Breathe', vietnamese: 'Thở', pronunciation: 'tho', category: 'wellness', chapter: 'chapter07', difficulty: 1, examples: ['Breathe deeply and slowly.'] },
  { id: 'wellness7', english: 'Stretch', vietnamese: 'Duỗi', pronunciation: 'duoi', category: 'wellness', chapter: 'chapter07', difficulty: 1, examples: ['Stretch muscles before exercise.'] },
  { id: 'wellness8', english: 'Walk', vietnamese: 'Đi bộ', pronunciation: 'di bo', category: 'wellness', chapter: 'chapter07', difficulty: 1, examples: ['Walk daily for fitness.'] },
  { id: 'wellness9', english: 'Run', vietnamese: 'Chạy', pronunciation: 'chay', category: 'wellness', chapter: 'chapter07', difficulty: 1, examples: ['Run in park mornings.'] },
  { id: 'wellness10', english: 'Swim', vietnamese: 'Bơi', pronunciation: 'boi', category: 'wellness', chapter: 'chapter07', difficulty: 1, examples: ['Swimming is great exercise.'] },
  { id: 'wellness11', english: 'Meditate', vietnamese: 'Thiền', pronunciation: 'thien', category: 'wellness', chapter: 'chapter07', difficulty: 1, examples: ['Meditate to reduce stress.'] },
  { id: 'wellness12', english: 'Massage', vietnamese: 'Massage', pronunciation: 'massage', category: 'wellness', chapter: 'chapter07', difficulty: 1, examples: ['Massage relieves muscle tension.'] },
  { id: 'wellness13', english: 'Vitamin', vietnamese: 'Vitamin', pronunciation: 'vitamin', category: 'wellness', chapter: 'chapter07', difficulty: 1, examples: ['Take vitamin supplements daily.'] },
  { id: 'wellness14', english: 'Nutrition', vietnamese: 'Dinh dưỡng', pronunciation: 'dinh duong', category: 'wellness', chapter: 'chapter07', difficulty: 1, examples: ['Good nutrition essential.'] },
  { id: 'wellness15', english: 'Hygiene', vietnamese: 'Vệ sinh', pronunciation: 've sinh', category: 'wellness', chapter: 'chapter07', difficulty: 1, examples: ['Personal hygiene prevents illness.'] },
  { id: 'wellness16', english: 'Wash', vietnamese: 'Rửa', pronunciation: 'rua', category: 'wellness', chapter: 'chapter07', difficulty: 1, examples: ['Wash hands before eating.'] },
  { id: 'wellness17', english: 'Brush', vietnamese: 'Đánh', pronunciation: 'danh', category: 'wellness', chapter: 'chapter07', difficulty: 1, examples: ['Brush teeth after meals.'] },
  { id: 'wellness18', english: 'Shower', vietnamese: 'Tắm', pronunciation: 'tam', category: 'wellness', chapter: 'chapter07', difficulty: 1, examples: ['Take shower daily.'] },
  { id: 'wellness19', english: 'Immunity', vietnamese: 'Miễn dịch', pronunciation: 'mien dich', category: 'wellness', chapter: 'chapter07', difficulty: 2, examples: ['Strong immunity fights disease.'] },
  { id: 'wellness20', english: 'Prevention', vietnamese: 'Phòng ngừa', pronunciation: 'phong ngua', category: 'wellness', chapter: 'chapter07', difficulty: 1, examples: ['Prevention better than cure.'] }
]
