// Chapter 4: House & Home (100 Essential Words)
// Words related to housing, rooms, furniture, and household items

import { LanguageWord } from './chapter01-basic-everyday'

export const chapter04Words: LanguageWord[] = [
  // House & Building (20 words)
  { id: 'house1', english: 'House', vietnamese: 'Nhà', pronunciation: 'nha', category: 'building', chapter: 'chapter04', difficulty: 1, examples: ['My house is small.'] },
  { id: 'house2', english: 'Home', vietnamese: 'Nhà', pronunciation: 'nha', category: 'building', chapter: 'chapter04', difficulty: 1, examples: ['Home sweet home.'] },
  { id: 'house3', english: 'Apartment', vietnamese: 'Căn hộ', pronunciation: 'can ho', category: 'building', chapter: 'chapter04', difficulty: 1, examples: ['I live in an apartment.'] },
  { id: 'house4', english: 'Building', vietnamese: 'Tòa nhà', pronunciation: 'toa nha', category: 'building', chapter: 'chapter04', difficulty: 1, examples: ['Tall building in the city.'] },
  { id: 'house5', english: 'Room', vietnamese: 'Phòng', pronunciation: 'phong', category: 'building', chapter: 'chapter04', difficulty: 1, examples: ['Each room has a purpose.'] },
  { id: 'house6', english: 'Floor', vietnamese: 'Tầng', pronunciation: 'tang', category: 'building', chapter: 'chapter04', difficulty: 1, examples: ['I live on the third floor.'] },
  { id: 'house7', english: 'Roof', vietnamese: 'Mái nhà', pronunciation: 'mai nha', category: 'building', chapter: 'chapter04', difficulty: 1, examples: ['Red roof on old houses.'] },
  { id: 'house8', english: 'Wall', vietnamese: 'Tường', pronunciation: 'tuong', category: 'building', chapter: 'chapter04', difficulty: 1, examples: ['Paint the wall white.'] },
  { id: 'house9', english: 'Door', vietnamese: 'Cửa', pronunciation: 'cua', category: 'building', chapter: 'chapter04', difficulty: 1, examples: ['Open the door please.'] },
  { id: 'house10', english: 'Window', vietnamese: 'Cửa sổ', pronunciation: 'cua so', category: 'building', chapter: 'chapter04', difficulty: 1, examples: ['Look through the window.'] },
  { id: 'house11', english: 'Stairs', vietnamese: 'Cầu thang', pronunciation: 'cau thang', category: 'building', chapter: 'chapter04', difficulty: 1, examples: ['Walk up the stairs.'] },
  { id: 'house12', english: 'Elevator', vietnamese: 'Thang máy', pronunciation: 'thang may', category: 'building', chapter: 'chapter04', difficulty: 1, examples: ['Take the elevator to floor 5.'] },
  { id: 'house13', english: 'Balcony', vietnamese: 'Ban công', pronunciation: 'ban cong', category: 'building', chapter: 'chapter04', difficulty: 1, examples: ['Drink coffee on the balcony.'] },
  { id: 'house14', english: 'Garden', vietnamese: 'Vườn', pronunciation: 'vuon', category: 'building', chapter: 'chapter04', difficulty: 1, examples: ['Beautiful garden with flowers.'] },
  { id: 'house15', english: 'Yard', vietnamese: 'Sân', pronunciation: 'san', category: 'building', chapter: 'chapter04', difficulty: 1, examples: ['Children play in the yard.'] },
  { id: 'house16', english: 'Garage', vietnamese: 'Ga ra', pronunciation: 'ga ra', category: 'building', chapter: 'chapter04', difficulty: 1, examples: ['Park car in the garage.'] },
  { id: 'house17', english: 'Fence', vietnamese: 'Hàng rào', pronunciation: 'hang rao', category: 'building', chapter: 'chapter04', difficulty: 1, examples: ['High fence around the house.'] },
  { id: 'house18', english: 'Gate', vietnamese: 'Cổng', pronunciation: 'cong', category: 'building', chapter: 'chapter04', difficulty: 1, examples: ['Close the gate after entering.'] },
  { id: 'house19', english: 'Basement', vietnamese: 'Tầng hầm', pronunciation: 'tang ham', category: 'building', chapter: 'chapter04', difficulty: 1, examples: ['Store things in the basement.'] },
  { id: 'house20', english: 'Attic', vietnamese: 'Gác mái', pronunciation: 'gac mai', category: 'building', chapter: 'chapter04', difficulty: 1, examples: ['Old furniture in the attic.'] },

  // Rooms (15 words)
  { id: 'room1', english: 'Living room', vietnamese: 'Phòng khách', pronunciation: 'phong khach', category: 'room', chapter: 'chapter04', difficulty: 1, examples: ['Watch TV in living room.'] },
  { id: 'room2', english: 'Bedroom', vietnamese: 'Phòng ngủ', pronunciation: 'phong ngu', category: 'room', chapter: 'chapter04', difficulty: 1, examples: ['Sleep in the bedroom.'] },
  { id: 'room3', english: 'Kitchen', vietnamese: 'Nhà bếp', pronunciation: 'nha bep', category: 'room', chapter: 'chapter04', difficulty: 1, examples: ['Cook dinner in kitchen.'] },
  { id: 'room4', english: 'Bathroom', vietnamese: 'Phòng tắm', pronunciation: 'phong tam', category: 'room', chapter: 'chapter04', difficulty: 1, examples: ['Clean bathroom daily.'] },
  { id: 'room5', english: 'Dining room', vietnamese: 'Phòng ăn', pronunciation: 'phong an', category: 'room', chapter: 'chapter04', difficulty: 1, examples: ['Family eats in dining room.'] },
  { id: 'room6', english: 'Study room', vietnamese: 'Phòng học', pronunciation: 'phong hoc', category: 'room', chapter: 'chapter04', difficulty: 1, examples: ['Study quietly in study room.'] },
  { id: 'room7', english: 'Office', vietnamese: 'Văn phòng', pronunciation: 'van phong', category: 'room', chapter: 'chapter04', difficulty: 1, examples: ['Work from home office.'] },
  { id: 'room8', english: 'Guest room', vietnamese: 'Phòng khách', pronunciation: 'phong khach', category: 'room', chapter: 'chapter04', difficulty: 1, examples: ['Visitors stay in guest room.'] },
  { id: 'room9', english: 'Laundry room', vietnamese: 'Phòng giặt', pronunciation: 'phong giat', category: 'room', chapter: 'chapter04', difficulty: 1, examples: ['Wash clothes in laundry room.'] },
  { id: 'room10', english: 'Storage room', vietnamese: 'Phòng chứa đồ', pronunciation: 'phong chua do', category: 'room', chapter: 'chapter04', difficulty: 1, examples: ['Keep boxes in storage room.'] },
  { id: 'room11', english: 'Closet', vietnamese: 'Tủ quần áo', pronunciation: 'tu quan ao', category: 'room', chapter: 'chapter04', difficulty: 1, examples: ['Hang clothes in closet.'] },
  { id: 'room12', english: 'Hallway', vietnamese: 'Hành lang', pronunciation: 'hanh lang', category: 'room', chapter: 'chapter04', difficulty: 1, examples: ['Long hallway connects rooms.'] },
  { id: 'room13', english: 'Entrance', vietnamese: 'Lối vào', pronunciation: 'loi vao', category: 'room', chapter: 'chapter04', difficulty: 1, examples: ['Welcome guests at entrance.'] },
  { id: 'room14', english: 'Porch', vietnamese: 'Hiên nhà', pronunciation: 'hien nha', category: 'room', chapter: 'chapter04', difficulty: 1, examples: ['Sit on porch in evening.'] },
  { id: 'room15', english: 'Terrace', vietnamese: 'Sân thượng', pronunciation: 'san thuong', category: 'room', chapter: 'chapter04', difficulty: 1, examples: ['BBQ party on terrace.'] },

  // Furniture (25 words)
  { id: 'furniture1', english: 'Furniture', vietnamese: 'Đồ nội thất', pronunciation: 'do noi that', category: 'furniture', chapter: 'chapter04', difficulty: 1, examples: ['Buy new furniture for home.'] },
  { id: 'furniture2', english: 'Chair', vietnamese: 'Ghế', pronunciation: 'ghe', category: 'furniture', chapter: 'chapter04', difficulty: 1, examples: ['Comfortable chair for reading.'] },
  { id: 'furniture3', english: 'Table', vietnamese: 'Bàn', pronunciation: 'ban', category: 'furniture', chapter: 'chapter04', difficulty: 1, examples: ['Wooden table in dining room.'] },
  { id: 'furniture4', english: 'Sofa', vietnamese: 'Ghế sofa', pronunciation: 'ghe sofa', category: 'furniture', chapter: 'chapter04', difficulty: 1, examples: ['Relax on the sofa.'] },
  { id: 'furniture5', english: 'Bed', vietnamese: 'Giường', pronunciation: 'giuong', category: 'furniture', chapter: 'chapter04', difficulty: 1, examples: ['Sleep on a soft bed.'] },
  { id: 'furniture6', english: 'Desk', vietnamese: 'Bàn làm việc', pronunciation: 'ban lam viec', category: 'furniture', chapter: 'chapter04', difficulty: 1, examples: ['Study at the desk.'] },
  { id: 'furniture7', english: 'Bookshelf', vietnamese: 'Kệ sách', pronunciation: 'ke sach', category: 'furniture', chapter: 'chapter04', difficulty: 1, examples: ['Books on the bookshelf.'] },
  { id: 'furniture8', english: 'Wardrobe', vietnamese: 'Tủ quần áo', pronunciation: 'tu quan ao', category: 'furniture', chapter: 'chapter04', difficulty: 1, examples: ['Clothes in the wardrobe.'] },
  { id: 'furniture9', english: 'Dresser', vietnamese: 'Tủ trang điểm', pronunciation: 'tu trang diem', category: 'furniture', chapter: 'chapter04', difficulty: 1, examples: ['Mirror on the dresser.'] },
  { id: 'furniture10', english: 'Cabinet', vietnamese: 'Tủ', pronunciation: 'tu', category: 'furniture', chapter: 'chapter04', difficulty: 1, examples: ['Store dishes in cabinet.'] },
  { id: 'furniture11', english: 'Drawer', vietnamese: 'Ngăn kéo', pronunciation: 'ngan keo', category: 'furniture', chapter: 'chapter04', difficulty: 1, examples: ['Keys in the drawer.'] },
  { id: 'furniture12', english: 'Shelf', vietnamese: 'Kệ', pronunciation: 'ke', category: 'furniture', chapter: 'chapter04', difficulty: 1, examples: ['Books on the shelf.'] },
  { id: 'furniture13', english: 'Couch', vietnamese: 'Ghế dài', pronunciation: 'ghe dai', category: 'furniture', chapter: 'chapter04', difficulty: 1, examples: ['Nap on the couch.'] },
  { id: 'furniture14', english: 'Armchair', vietnamese: 'Ghế bành', pronunciation: 'ghe banh', category: 'furniture', chapter: 'chapter04', difficulty: 1, examples: ['Read in the armchair.'] },
  { id: 'furniture15', english: 'Stool', vietnamese: 'Ghế đẩu', pronunciation: 'ghe dau', category: 'furniture', chapter: 'chapter04', difficulty: 1, examples: ['Sit on a tall stool.'] },
  { id: 'furniture16', english: 'Bench', vietnamese: 'Ghế dài', pronunciation: 'ghe dai', category: 'furniture', chapter: 'chapter04', difficulty: 1, examples: ['Garden bench under tree.'] },
  { id: 'furniture17', english: 'Coffee table', vietnamese: 'Bàn cà phê', pronunciation: 'ban ca phe', category: 'furniture', chapter: 'chapter04', difficulty: 1, examples: ['Magazine on coffee table.'] },
  { id: 'furniture18', english: 'Dining table', vietnamese: 'Bàn ăn', pronunciation: 'ban an', category: 'furniture', chapter: 'chapter04', difficulty: 1, examples: ['Family dinner at dining table.'] },
  { id: 'furniture19', english: 'Nightstand', vietnamese: 'Tủ đầu giường', pronunciation: 'tu dau giuong', category: 'furniture', chapter: 'chapter04', difficulty: 1, examples: ['Lamp on the nightstand.'] },
  { id: 'furniture20', english: 'Mirror', vietnamese: 'Gương', pronunciation: 'guong', category: 'furniture', chapter: 'chapter04', difficulty: 1, examples: ['Look in the mirror.'] },
  { id: 'furniture21', english: 'Curtain', vietnamese: 'Rèm cửa', pronunciation: 'rem cua', category: 'furniture', chapter: 'chapter04', difficulty: 1, examples: ['Close curtains at night.'] },
  { id: 'furniture22', english: 'Carpet', vietnamese: 'Thảm', pronunciation: 'tham', category: 'furniture', chapter: 'chapter04', difficulty: 1, examples: ['Soft carpet in living room.'] },
  { id: 'furniture23', english: 'Rug', vietnamese: 'Thảm nhỏ', pronunciation: 'tham nho', category: 'furniture', chapter: 'chapter04', difficulty: 1, examples: ['Beautiful rug on floor.'] },
  { id: 'furniture24', english: 'Lamp', vietnamese: 'Đèn', pronunciation: 'den', category: 'furniture', chapter: 'chapter04', difficulty: 1, examples: ['Turn on the lamp.'] },
  { id: 'furniture25', english: 'Picture', vietnamese: 'Tranh', pronunciation: 'tranh', category: 'furniture', chapter: 'chapter04', difficulty: 1, examples: ['Family picture on wall.'] },

  // Appliances & Electronics (20 words)
  { id: 'appliance1', english: 'Television', vietnamese: 'Tivi', pronunciation: 'tivi', category: 'appliance', chapter: 'chapter04', difficulty: 1, examples: ['Watch news on television.'] },
  { id: 'appliance2', english: 'Refrigerator', vietnamese: 'Tủ lạnh', pronunciation: 'tu lanh', category: 'appliance', chapter: 'chapter04', difficulty: 1, examples: ['Keep food cold in refrigerator.'] },
  { id: 'appliance3', english: 'Washing machine', vietnamese: 'Máy giặt', pronunciation: 'may giat', category: 'appliance', chapter: 'chapter04', difficulty: 1, examples: ['Wash clothes in washing machine.'] },
  { id: 'appliance4', english: 'Microwave', vietnamese: 'Lò vi sóng', pronunciation: 'lo vi song', category: 'appliance', chapter: 'chapter04', difficulty: 1, examples: ['Heat food in microwave.'] },
  { id: 'appliance5', english: 'Oven', vietnamese: 'Lò nướng', pronunciation: 'lo nuong', category: 'appliance', chapter: 'chapter04', difficulty: 1, examples: ['Bake cake in oven.'] },
  { id: 'appliance6', english: 'Stove', vietnamese: 'Bếp', pronunciation: 'bep', category: 'appliance', chapter: 'chapter04', difficulty: 1, examples: ['Cook on the stove.'] },
  { id: 'appliance7', english: 'Dishwasher', vietnamese: 'Máy rửa bát', pronunciation: 'may rua bat', category: 'appliance', chapter: 'chapter04', difficulty: 1, examples: ['Clean dishes in dishwasher.'] },
  { id: 'appliance8', english: 'Air conditioner', vietnamese: 'Máy lạnh', pronunciation: 'may lanh', category: 'appliance', chapter: 'chapter04', difficulty: 1, examples: ['Cool room with air conditioner.'] },
  { id: 'appliance9', english: 'Fan', vietnamese: 'Quạt', pronunciation: 'quat', category: 'appliance', chapter: 'chapter04', difficulty: 1, examples: ['Electric fan for hot weather.'] },
  { id: 'appliance10', english: 'Heater', vietnamese: 'Máy sưởi', pronunciation: 'may suoi', category: 'appliance', chapter: 'chapter04', difficulty: 1, examples: ['Use heater in winter.'] },
  { id: 'appliance11', english: 'Computer', vietnamese: 'Máy tính', pronunciation: 'may tinh', category: 'appliance', chapter: 'chapter04', difficulty: 1, examples: ['Work on computer daily.'] },
  { id: 'appliance12', english: 'Phone', vietnamese: 'Điện thoại', pronunciation: 'dien thoai', category: 'appliance', chapter: 'chapter04', difficulty: 1, examples: ['Call friends on phone.'] },
  { id: 'appliance13', english: 'Radio', vietnamese: 'Đài phát thanh', pronunciation: 'dai phat thanh', category: 'appliance', chapter: 'chapter04', difficulty: 1, examples: ['Listen to music on radio.'] },
  { id: 'appliance14', english: 'Speaker', vietnamese: 'Loa', pronunciation: 'loa', category: 'appliance', chapter: 'chapter04', difficulty: 1, examples: ['Play music through speaker.'] },
  { id: 'appliance15', english: 'Vacuum cleaner', vietnamese: 'Máy hút bụi', pronunciation: 'may hut bui', category: 'appliance', chapter: 'chapter04', difficulty: 1, examples: ['Clean carpet with vacuum cleaner.'] },
  { id: 'appliance16', english: 'Iron', vietnamese: 'Bàn là', pronunciation: 'ban la', category: 'appliance', chapter: 'chapter04', difficulty: 1, examples: ['Iron wrinkled clothes.'] },
  { id: 'appliance17', english: 'Hair dryer', vietnamese: 'Máy sấy tóc', pronunciation: 'may say toc', category: 'appliance', chapter: 'chapter04', difficulty: 1, examples: ['Dry hair with hair dryer.'] },
  { id: 'appliance18', english: 'Toaster', vietnamese: 'Máy nướng bánh', pronunciation: 'may nuong banh', category: 'appliance', chapter: 'chapter04', difficulty: 1, examples: ['Make toast with toaster.'] },
  { id: 'appliance19', english: 'Blender', vietnamese: 'Máy xay', pronunciation: 'may xay', category: 'appliance', chapter: 'chapter04', difficulty: 1, examples: ['Make smoothie with blender.'] },
  { id: 'appliance20', english: 'Coffee maker', vietnamese: 'Máy pha cà phê', pronunciation: 'may pha ca phe', category: 'appliance', chapter: 'chapter04', difficulty: 1, examples: ['Brew coffee with coffee maker.'] },

  // Household Items (20 words)
  { id: 'household1', english: 'Pillow', vietnamese: 'Gối', pronunciation: 'goi', category: 'household', chapter: 'chapter04', difficulty: 1, examples: ['Soft pillow for sleeping.'] },
  { id: 'household2', english: 'Blanket', vietnamese: 'Chăn', pronunciation: 'chan', category: 'household', chapter: 'chapter04', difficulty: 1, examples: ['Warm blanket in winter.'] },
  { id: 'household3', english: 'Sheet', vietnamese: 'Ga trải giường', pronunciation: 'ga trai giuong', category: 'household', chapter: 'chapter04', difficulty: 1, examples: ['Clean white sheets.'] },
  { id: 'household4', english: 'Towel', vietnamese: 'Khăn tắm', pronunciation: 'khan tam', category: 'household', chapter: 'chapter04', difficulty: 1, examples: ['Dry with clean towel.'] },
  { id: 'household5', english: 'Soap', vietnamese: 'Xà phòng', pronunciation: 'xa phong', category: 'household', chapter: 'chapter04', difficulty: 1, examples: ['Wash hands with soap.'] },
  { id: 'household6', english: 'Shampoo', vietnamese: 'Dầu gội', pronunciation: 'dau goi', category: 'household', chapter: 'chapter04', difficulty: 1, examples: ['Wash hair with shampoo.'] },
  { id: 'household7', english: 'Toothbrush', vietnamese: 'Bàn chải đánh răng', pronunciation: 'ban chai danh rang', category: 'household', chapter: 'chapter04', difficulty: 1, examples: ['Brush teeth with toothbrush.'] },
  { id: 'household8', english: 'Toothpaste', vietnamese: 'Kem đánh răng', pronunciation: 'kem danh rang', category: 'household', chapter: 'chapter04', difficulty: 1, examples: ['Use toothpaste for clean teeth.'] },
  { id: 'household9', english: 'Tissue', vietnamese: 'Khăn giấy', pronunciation: 'khan giay', category: 'household', chapter: 'chapter04', difficulty: 1, examples: ['Wipe nose with tissue.'] },
  { id: 'household10', english: 'Toilet paper', vietnamese: 'Giấy vệ sinh', pronunciation: 'giay ve sinh', category: 'household', chapter: 'chapter04', difficulty: 1, examples: ['Buy toilet paper for bathroom.'] },
  { id: 'household11', english: 'Candle', vietnamese: 'Nến', pronunciation: 'nen', category: 'household', chapter: 'chapter04', difficulty: 1, examples: ['Light candle for dinner.'] },
  { id: 'household12', english: 'Clock', vietnamese: 'Đồng hồ', pronunciation: 'dong ho', category: 'household', chapter: 'chapter04', difficulty: 1, examples: ['Check time on clock.'] },
  { id: 'household13', english: 'Calendar', vietnamese: 'Lịch', pronunciation: 'lich', category: 'household', chapter: 'chapter04', difficulty: 1, examples: ['Mark date on calendar.'] },
  { id: 'household14', english: 'Trash can', vietnamese: 'Thùng rác', pronunciation: 'thung rac', category: 'household', chapter: 'chapter04', difficulty: 1, examples: ['Throw garbage in trash can.'] },
  { id: 'household15', english: 'Bucket', vietnamese: 'Xô', pronunciation: 'xo', category: 'household', chapter: 'chapter04', difficulty: 1, examples: ['Carry water in bucket.'] },
  { id: 'household16', english: 'Broom', vietnamese: 'Chổi', pronunciation: 'choi', category: 'household', chapter: 'chapter04', difficulty: 1, examples: ['Sweep floor with broom.'] },
  { id: 'household17', english: 'Mop', vietnamese: 'Cây lau nhà', pronunciation: 'cay lau nha', category: 'household', chapter: 'chapter04', difficulty: 1, examples: ['Clean floor with mop.'] },
  { id: 'household18', english: 'Detergent', vietnamese: 'Bột giặt', pronunciation: 'bot giat', category: 'household', chapter: 'chapter04', difficulty: 1, examples: ['Use detergent for washing.'] },
  { id: 'household19', english: 'Key', vietnamese: 'Chìa khóa', pronunciation: 'chia khoa', category: 'household', chapter: 'chapter04', difficulty: 1, examples: ['Open door with key.'] },
  { id: 'household20', english: 'Lock', vietnamese: 'Ổ khóa', pronunciation: 'o khoa', category: 'household', chapter: 'chapter04', difficulty: 1, examples: ['Secure door with lock.'] }
]
