// Chapter 8: Education & Learning (100 Essential Words)
// Words related to school, studying, knowledge, and educational activities

import { LanguageWord } from './chapter01-basic-everyday'

export const chapter08Words: LanguageWord[] = [
  // School & Educational Institutions (20 words)
  { id: 'education1', english: 'School', vietnamese: 'Trường học', pronunciation: 'truong hoc', category: 'institution', chapter: 'chapter08', difficulty: 1, examples: ['Children go to school daily.'] },
  { id: 'education2', english: 'University', vietnamese: 'Đại học', pronunciation: 'dai hoc', category: 'institution', chapter: 'chapter08', difficulty: 1, examples: ['Study at famous university.'] },
  { id: 'education3', english: 'College', vietnamese: 'Cao đẳng', pronunciation: 'cao dang', category: 'institution', chapter: 'chapter08', difficulty: 1, examples: ['Community college near home.'] },
  { id: 'education4', english: 'Kindergarten', vietnamese: 'Mẫu giáo', pronunciation: 'mau giao', category: 'institution', chapter: 'chapter08', difficulty: 1, examples: ['Children start kindergarten early.'] },
  { id: 'education5', english: 'Elementary school', vietnamese: 'Trường tiểu học', pronunciation: 'truong tieu hoc', category: 'institution', chapter: 'chapter08', difficulty: 1, examples: ['Elementary school teaches basics.'] },
  { id: 'education6', english: 'Middle school', vietnamese: 'Trường trung học cơ sở', pronunciation: 'truong trung hoc co so', category: 'institution', chapter: 'chapter08', difficulty: 1, examples: ['Middle school prepares students.'] },
  { id: 'education7', english: 'High school', vietnamese: 'Trường trung học phổ thông', pronunciation: 'truong trung hoc pho thong', category: 'institution', chapter: 'chapter08', difficulty: 1, examples: ['Graduate from high school.'] },
  { id: 'education8', english: 'Library', vietnamese: 'Thư viện', pronunciation: 'thu vien', category: 'institution', chapter: 'chapter08', difficulty: 1, examples: ['Study quietly in library.'] },
  { id: 'education9', english: 'Classroom', vietnamese: 'Phòng học', pronunciation: 'phong hoc', category: 'institution', chapter: 'chapter08', difficulty: 1, examples: ['Students sit in classroom.'] },
  { id: 'education10', english: 'Laboratory', vietnamese: 'Phòng thí nghiệm', pronunciation: 'phong thi nghiem', category: 'institution', chapter: 'chapter08', difficulty: 1, examples: ['Conduct experiments in laboratory.'] },
  { id: 'education11', english: 'Cafeteria', vietnamese: 'Căng tin', pronunciation: 'cang tin', category: 'institution', chapter: 'chapter08', difficulty: 1, examples: ['Eat lunch in cafeteria.'] },
  { id: 'education12', english: 'Playground', vietnamese: 'Sân chơi', pronunciation: 'san choi', category: 'institution', chapter: 'chapter08', difficulty: 1, examples: ['Children play on playground.'] },
  { id: 'education13', english: 'Auditorium', vietnamese: 'Hội trường', pronunciation: 'hoi truong', category: 'institution', chapter: 'chapter08', difficulty: 1, examples: ['Assembly in school auditorium.'] },
  { id: 'education14', english: 'Gym', vietnamese: 'Phòng tập thể dục', pronunciation: 'phong tap the duc', category: 'institution', chapter: 'chapter08', difficulty: 1, examples: ['Physical education in gym.'] },
  { id: 'education15', english: 'Office', vietnamese: 'Văn phòng', pronunciation: 'van phong', category: 'institution', chapter: 'chapter08', difficulty: 1, examples: ['Principal works in office.'] },
  { id: 'education16', english: 'Dormitory', vietnamese: 'Ký túc xá', pronunciation: 'ky tuc xa', category: 'institution', chapter: 'chapter08', difficulty: 1, examples: ['Students live in dormitory.'] },
  { id: 'education17', english: 'Campus', vietnamese: 'Khuôn viên', pronunciation: 'khuon vien', category: 'institution', chapter: 'chapter08', difficulty: 1, examples: ['Beautiful university campus.'] },
  { id: 'education18', english: 'Academy', vietnamese: 'Học viện', pronunciation: 'hoc vien', category: 'institution', chapter: 'chapter08', difficulty: 1, examples: ['Military academy trains officers.'] },
  { id: 'education19', english: 'Institute', vietnamese: 'Viện', pronunciation: 'vien', category: 'institution', chapter: 'chapter08', difficulty: 1, examples: ['Research institute studies science.'] },
  { id: 'education20', english: 'Nursery school', vietnamese: 'Nhà trẻ', pronunciation: 'nha tre', category: 'institution', chapter: 'chapter08', difficulty: 1, examples: ['Toddlers attend nursery school.'] },

  // People in Education (15 words)
  { id: 'people1', english: 'Student', vietnamese: 'Học sinh', pronunciation: 'hoc sinh', category: 'people', chapter: 'chapter08', difficulty: 1, examples: ['Students study hard.'] },
  { id: 'people2', english: 'Teacher', vietnamese: 'Giáo viên', pronunciation: 'giao vien', category: 'people', chapter: 'chapter08', difficulty: 1, examples: ['Teacher explains lesson clearly.'] },
  { id: 'people3', english: 'Professor', vietnamese: 'Giáo sư', pronunciation: 'giao su', category: 'people', chapter: 'chapter08', difficulty: 1, examples: ['Professor teaches university course.'] },
  { id: 'people4', english: 'Principal', vietnamese: 'Hiệu trưởng', pronunciation: 'hieu truong', category: 'people', chapter: 'chapter08', difficulty: 1, examples: ['Principal manages school.'] },
  { id: 'people5', english: 'Dean', vietnamese: 'Trưởng khoa', pronunciation: 'truong khoa', category: 'people', chapter: 'chapter08', difficulty: 1, examples: ['Dean oversees department.'] },
  { id: 'people6', english: 'Tutor', vietnamese: 'Gia sư', pronunciation: 'gia su', category: 'people', chapter: 'chapter08', difficulty: 1, examples: ['Tutor helps with homework.'] },
  { id: 'people7', english: 'Classmate', vietnamese: 'Bạn cùng lớp', pronunciation: 'ban cung lop', category: 'people', chapter: 'chapter08', difficulty: 1, examples: ['Help classmate with project.'] },
  { id: 'people8', english: 'Roommate', vietnamese: 'Bạn cùng phòng', pronunciation: 'ban cung phong', category: 'people', chapter: 'chapter08', difficulty: 1, examples: ['Live with friendly roommate.'] },
  { id: 'people9', english: 'Graduate', vietnamese: 'Sinh viên tốt nghiệp', pronunciation: 'sinh vien tot nghiep', category: 'people', chapter: 'chapter08', difficulty: 1, examples: ['Recent graduate seeks job.'] },
  { id: 'people10', english: 'Freshman', vietnamese: 'Sinh viên năm nhất', pronunciation: 'sinh vien nam nhat', category: 'people', chapter: 'chapter08', difficulty: 1, examples: ['Freshman adjusts to college.'] },
  { id: 'people11', english: 'Senior', vietnamese: 'Sinh viên cuối khóa', pronunciation: 'sinh vien cuoi khoa', category: 'people', chapter: 'chapter08', difficulty: 1, examples: ['Senior prepares for graduation.'] },
  { id: 'people12', english: 'Counselor', vietnamese: 'Cố vấn', pronunciation: 'co van', category: 'people', chapter: 'chapter08', difficulty: 1, examples: ['Counselor provides guidance.'] },
  { id: 'people13', english: 'Librarian', vietnamese: 'Thủ thư', pronunciation: 'thu thu', category: 'people', chapter: 'chapter08', difficulty: 1, examples: ['Librarian helps find books.'] },
  { id: 'people14', english: 'Coach', vietnamese: 'Huấn luyện viên', pronunciation: 'huan luyen vien', category: 'people', chapter: 'chapter08', difficulty: 1, examples: ['Coach trains school team.'] },
  { id: 'people15', english: 'Janitor', vietnamese: 'Người dọn dẹp', pronunciation: 'nguoi don dep', category: 'people', chapter: 'chapter08', difficulty: 1, examples: ['Janitor keeps school clean.'] },

  // Learning Activities & Actions (25 words)
  { id: 'activity1', english: 'Learn', vietnamese: 'Học', pronunciation: 'hoc', category: 'activity', chapter: 'chapter08', difficulty: 1, examples: ['Learn something new daily.'] },
  { id: 'activity2', english: 'Study', vietnamese: 'Học bài', pronunciation: 'hoc bai', category: 'activity', chapter: 'chapter08', difficulty: 1, examples: ['Study hard for exam.'] },
  { id: 'activity3', english: 'Teach', vietnamese: 'Dạy', pronunciation: 'day', category: 'activity', chapter: 'chapter08', difficulty: 1, examples: ['Teacher teaches math.'] },
  { id: 'activity4', english: 'Read', vietnamese: 'Đọc', pronunciation: 'doc', category: 'activity', chapter: 'chapter08', difficulty: 1, examples: ['Read textbook carefully.'] },
  { id: 'activity5', english: 'Write', vietnamese: 'Viết', pronunciation: 'viet', category: 'activity', chapter: 'chapter08', difficulty: 1, examples: ['Write essay on topic.'] },
  { id: 'activity6', english: 'Listen', vietnamese: 'Nghe', pronunciation: 'nghe', category: 'activity', chapter: 'chapter08', difficulty: 1, examples: ['Listen to teacher carefully.'] },
  { id: 'activity7', english: 'Speak', vietnamese: 'Nói', pronunciation: 'noi', category: 'activity', chapter: 'chapter08', difficulty: 1, examples: ['Speak clearly in presentation.'] },
  { id: 'activity8', english: 'Practice', vietnamese: 'Luyện tập', pronunciation: 'luyen tap', category: 'activity', chapter: 'chapter08', difficulty: 1, examples: ['Practice piano daily.'] },
  { id: 'activity9', english: 'Memorize', vietnamese: 'Ghi nhớ', pronunciation: 'ghi nho', category: 'activity', chapter: 'chapter08', difficulty: 1, examples: ['Memorize vocabulary words.'] },
  { id: 'activity10', english: 'Review', vietnamese: 'Ôn tập', pronunciation: 'on tap', category: 'activity', chapter: 'chapter08', difficulty: 1, examples: ['Review notes before test.'] },
  { id: 'activity11', english: 'Research', vietnamese: 'Nghiên cứu', pronunciation: 'nghien cuu', category: 'activity', chapter: 'chapter08', difficulty: 1, examples: ['Research topic thoroughly.'] },
  { id: 'activity12', english: 'Discuss', vietnamese: 'Thảo luận', pronunciation: 'thao luan', category: 'activity', chapter: 'chapter08', difficulty: 1, examples: ['Discuss ideas with group.'] },
  { id: 'activity13', english: 'Explain', vietnamese: 'Giải thích', pronunciation: 'giai thich', category: 'activity', chapter: 'chapter08', difficulty: 1, examples: ['Explain answer step by step.'] },
  { id: 'activity14', english: 'Understand', vietnamese: 'Hiểu', pronunciation: 'hieu', category: 'activity', chapter: 'chapter08', difficulty: 1, examples: ['Understand lesson completely.'] },
  { id: 'activity15', english: 'Answer', vietnamese: 'Trả lời', pronunciation: 'tra loi', category: 'activity', chapter: 'chapter08', difficulty: 1, examples: ['Answer question correctly.'] },
  { id: 'activity16', english: 'Question', vietnamese: 'Hỏi', pronunciation: 'hoi', category: 'activity', chapter: 'chapter08', difficulty: 1, examples: ['Ask question when confused.'] },
  { id: 'activity17', english: 'Calculate', vietnamese: 'Tính toán', pronunciation: 'tinh toan', category: 'activity', chapter: 'chapter08', difficulty: 1, examples: ['Calculate math problem.'] },
  { id: 'activity18', english: 'Solve', vietnamese: 'Giải', pronunciation: 'giai', category: 'activity', chapter: 'chapter08', difficulty: 1, examples: ['Solve difficult equation.'] },
  { id: 'activity19', english: 'Analyze', vietnamese: 'Phân tích', pronunciation: 'phan tich', category: 'activity', chapter: 'chapter08', difficulty: 1, examples: ['Analyze data carefully.'] },
  { id: 'activity20', english: 'Compare', vietnamese: 'So sánh', pronunciation: 'so sanh', category: 'activity', chapter: 'chapter08', difficulty: 1, examples: ['Compare different methods.'] },
  { id: 'activity21', english: 'Experiment', vietnamese: 'Thí nghiệm', pronunciation: 'thi nghiem', category: 'activity', chapter: 'chapter08', difficulty: 1, examples: ['Conduct science experiment.'] },
  { id: 'activity22', english: 'Present', vietnamese: 'Trình bày', pronunciation: 'trinh bay', category: 'activity', chapter: 'chapter08', difficulty: 1, examples: ['Present project to class.'] },
  { id: 'activity23', english: 'Draw', vietnamese: 'Vẽ', pronunciation: 've', category: 'activity', chapter: 'chapter08', difficulty: 1, examples: ['Draw diagram in notebook.'] },
  { id: 'activity24', english: 'Copy', vietnamese: 'Sao chép', pronunciation: 'sao chep', category: 'activity', chapter: 'chapter08', difficulty: 1, examples: ['Copy notes from board.'] },
  { id: 'activity25', english: 'Translate', vietnamese: 'Dịch', pronunciation: 'dich', category: 'activity', chapter: 'chapter08', difficulty: 1, examples: ['Translate text to English.'] },

  // Subjects & Academic Areas (20 words)
  { id: 'subject1', english: 'Math', vietnamese: 'Toán', pronunciation: 'toan', category: 'subject', chapter: 'chapter08', difficulty: 1, examples: ['Math class at 10 AM.'] },
  { id: 'subject2', english: 'Science', vietnamese: 'Khoa học', pronunciation: 'khoa hoc', category: 'subject', chapter: 'chapter08', difficulty: 1, examples: ['Science explains natural world.'] },
  { id: 'subject3', english: 'English', vietnamese: 'Tiếng Anh', pronunciation: 'tieng anh', category: 'subject', chapter: 'chapter08', difficulty: 1, examples: ['Practice English daily.'] },
  { id: 'subject4', english: 'History', vietnamese: 'Lịch sử', pronunciation: 'lich su', category: 'subject', chapter: 'chapter08', difficulty: 1, examples: ['History teaches about past.'] },
  { id: 'subject5', english: 'Geography', vietnamese: 'Địa lý', pronunciation: 'dia ly', category: 'subject', chapter: 'chapter08', difficulty: 1, examples: ['Geography studies places.'] },
  { id: 'subject6', english: 'Biology', vietnamese: 'Sinh học', pronunciation: 'sinh hoc', category: 'subject', chapter: 'chapter08', difficulty: 1, examples: ['Biology studies living things.'] },
  { id: 'subject7', english: 'Chemistry', vietnamese: 'Hóa học', pronunciation: 'hoa hoc', category: 'subject', chapter: 'chapter08', difficulty: 1, examples: ['Chemistry experiments interesting.'] },
  { id: 'subject8', english: 'Physics', vietnamese: 'Vật lý', pronunciation: 'vat ly', category: 'subject', chapter: 'chapter08', difficulty: 1, examples: ['Physics explains motion.'] },
  { id: 'subject9', english: 'Art', vietnamese: 'Mỹ thuật', pronunciation: 'my thuat', category: 'subject', chapter: 'chapter08', difficulty: 1, examples: ['Art class develops creativity.'] },
  { id: 'subject10', english: 'Music', vietnamese: 'Âm nhạc', pronunciation: 'am nhac', category: 'subject', chapter: 'chapter08', difficulty: 1, examples: ['Music lessons on Friday.'] },
  { id: 'subject11', english: 'Physical education', vietnamese: 'Thể dục', pronunciation: 'the duc', category: 'subject', chapter: 'chapter08', difficulty: 1, examples: ['Physical education builds fitness.'] },
  { id: 'subject12', english: 'Literature', vietnamese: 'Văn học', pronunciation: 'van hoc', category: 'subject', chapter: 'chapter08', difficulty: 1, examples: ['Literature explores stories.'] },
  { id: 'subject13', english: 'Computer science', vietnamese: 'Tin học', pronunciation: 'tin hoc', category: 'subject', chapter: 'chapter08', difficulty: 1, examples: ['Computer science teaches programming.'] },
  { id: 'subject14', english: 'Economics', vietnamese: 'Kinh tế học', pronunciation: 'kinh te hoc', category: 'subject', chapter: 'chapter08', difficulty: 1, examples: ['Economics studies money.'] },
  { id: 'subject15', english: 'Psychology', vietnamese: 'Tâm lý học', pronunciation: 'tam ly hoc', category: 'subject', chapter: 'chapter08', difficulty: 1, examples: ['Psychology studies mind.'] },
  { id: 'subject16', english: 'Philosophy', vietnamese: 'Triết học', pronunciation: 'triet hoc', category: 'subject', chapter: 'chapter08', difficulty: 1, examples: ['Philosophy asks deep questions.'] },
  { id: 'subject17', english: 'Language', vietnamese: 'Ngôn ngữ', pronunciation: 'ngon ngu', category: 'subject', chapter: 'chapter08', difficulty: 1, examples: ['Learn foreign language.'] },
  { id: 'subject18', english: 'Engineering', vietnamese: 'Kỹ thuật', pronunciation: 'ky thuat', category: 'subject', chapter: 'chapter08', difficulty: 1, examples: ['Engineering solves problems.'] },
  { id: 'subject19', english: 'Medicine', vietnamese: 'Y học', pronunciation: 'y hoc', category: 'subject', chapter: 'chapter08', difficulty: 1, examples: ['Medicine helps heal people.'] },
  { id: 'subject20', english: 'Law', vietnamese: 'Luật', pronunciation: 'luat', category: 'subject', chapter: 'chapter08', difficulty: 1, examples: ['Law governs society.'] },

  // School Supplies & Materials (20 words)
  { id: 'supply1', english: 'Book', vietnamese: 'Sách', pronunciation: 'sach', category: 'supply', chapter: 'chapter08', difficulty: 1, examples: ['Read textbook for homework.'] },
  { id: 'supply2', english: 'Notebook', vietnamese: 'Vở', pronunciation: 'vo', category: 'supply', chapter: 'chapter08', difficulty: 1, examples: ['Write notes in notebook.'] },
  { id: 'supply3', english: 'Pen', vietnamese: 'Bút', pronunciation: 'but', category: 'supply', chapter: 'chapter08', difficulty: 1, examples: ['Write with blue pen.'] },
  { id: 'supply4', english: 'Pencil', vietnamese: 'Bút chì', pronunciation: 'but chi', category: 'supply', chapter: 'chapter08', difficulty: 1, examples: ['Draw with sharp pencil.'] },
  { id: 'supply5', english: 'Eraser', vietnamese: 'Tẩy', pronunciation: 'tay', category: 'supply', chapter: 'chapter08', difficulty: 1, examples: ['Erase mistake with eraser.'] },
  { id: 'supply6', english: 'Ruler', vietnamese: 'Thước', pronunciation: 'thuoc', category: 'supply', chapter: 'chapter08', difficulty: 1, examples: ['Measure with plastic ruler.'] },
  { id: 'supply7', english: 'Calculator', vietnamese: 'Máy tính', pronunciation: 'may tinh', category: 'supply', chapter: 'chapter08', difficulty: 1, examples: ['Use calculator for math.'] },
  { id: 'supply8', english: 'Paper', vietnamese: 'Giấy', pronunciation: 'giay', category: 'supply', chapter: 'chapter08', difficulty: 1, examples: ['Write essay on paper.'] },
  { id: 'supply9', english: 'Folder', vietnamese: 'Bìa kẹp', pronunciation: 'bia kep', category: 'supply', chapter: 'chapter08', difficulty: 1, examples: ['Organize papers in folder.'] },
  { id: 'supply10', english: 'Backpack', vietnamese: 'Cặp sách', pronunciation: 'cap sach', category: 'supply', chapter: 'chapter08', difficulty: 1, examples: ['Carry books in backpack.'] },
  { id: 'supply11', english: 'Computer', vietnamese: 'Máy tính', pronunciation: 'may tinh', category: 'supply', chapter: 'chapter08', difficulty: 1, examples: ['Type report on computer.'] },
  { id: 'supply12', english: 'Tablet', vietnamese: 'Máy tính bảng', pronunciation: 'may tinh bang', category: 'supply', chapter: 'chapter08', difficulty: 1, examples: ['Read e-books on tablet.'] },
  { id: 'supply13', english: 'Highlighter', vietnamese: 'Bút dạ quang', pronunciation: 'but da quang', category: 'supply', chapter: 'chapter08', difficulty: 1, examples: ['Mark important text.'] },
  { id: 'supply14', english: 'Stapler', vietnamese: 'Dập ghim', pronunciation: 'dap ghim', category: 'supply', chapter: 'chapter08', difficulty: 1, examples: ['Staple pages together.'] },
  { id: 'supply15', english: 'Scissors', vietnamese: 'Kéo', pronunciation: 'keo', category: 'supply', chapter: 'chapter08', difficulty: 1, examples: ['Cut paper with scissors.'] },
  { id: 'supply16', english: 'Glue', vietnamese: 'Keo dán', pronunciation: 'keo dan', category: 'supply', chapter: 'chapter08', difficulty: 1, examples: ['Glue pictures in album.'] },
  { id: 'supply17', english: 'Marker', vietnamese: 'Bút lông', pronunciation: 'but long', category: 'supply', chapter: 'chapter08', difficulty: 1, examples: ['Draw with colored markers.'] },
  { id: 'supply18', english: 'Whiteboard', vietnamese: 'Bảng trắng', pronunciation: 'bang trang', category: 'supply', chapter: 'chapter08', difficulty: 1, examples: ['Write on classroom whiteboard.'] },
  { id: 'supply19', english: 'Projector', vietnamese: 'Máy chiếu', pronunciation: 'may chieu', category: 'supply', chapter: 'chapter08', difficulty: 1, examples: ['Present slides on projector.'] },
  { id: 'supply20', english: 'Dictionary', vietnamese: 'Từ điển', pronunciation: 'tu dien', category: 'supply', chapter: 'chapter08', difficulty: 1, examples: ['Look up words in dictionary.'] }
]
