// Chapter 26: Weather & Seasons (100 Essential Words)
// Words related to weather conditions, seasons, climate, and natural phenomena

import { LanguageWord } from './chapter01-basic-everyday'

export const chapter26Words: LanguageWord[] = [
  // Weather Conditions (25 words)
  { id: 'weather1', english: 'Weather', vietnamese: 'Thời tiết', pronunciation: 'thoi tiet', category: 'weather', chapter: 'chapter26', difficulty: 1, examples: ['Weather today sunny.'] },
  { id: 'weather2', english: 'Sunny', vietnamese: 'Nắng', pronunciation: 'nang', category: 'weather', chapter: 'chapter26', difficulty: 1, examples: ['Sunny day beautiful.'] },
  { id: 'weather3', english: 'Cloudy', vietnamese: 'Có mây', pronunciation: 'co may', category: 'weather', chapter: 'chapter26', difficulty: 1, examples: ['Cloudy sky gray.'] },
  { id: 'weather4', english: 'Rainy', vietnamese: 'Mưa', pronunciation: 'mua', category: 'weather', chapter: 'chapter26', difficulty: 1, examples: ['Rainy season wet.'] },
  { id: 'weather5', english: 'Stormy', vietnamese: 'Bão', pronunciation: 'bao', category: 'weather', chapter: 'chapter26', difficulty: 1, examples: ['Stormy night dangerous.'] },
  { id: 'weather6', english: 'Windy', vietnamese: 'Có gió', pronunciation: 'co gio', category: 'weather', chapter: 'chapter26', difficulty: 1, examples: ['Windy day cool.'] },
  { id: 'weather7', english: 'Snowy', vietnamese: 'Có tuyết', pronunciation: 'co tuyet', category: 'weather', chapter: 'chapter26', difficulty: 1, examples: ['Snowy mountains white.'] },
  { id: 'weather8', english: 'Foggy', vietnamese: 'Có sương mù', pronunciation: 'co suong mu', category: 'weather', chapter: 'chapter26', difficulty: 1, examples: ['Foggy morning mysterious.'] },
  { id: 'weather9', english: 'Clear', vietnamese: 'Quang đãng', pronunciation: 'quang dang', category: 'weather', chapter: 'chapter26', difficulty: 1, examples: ['Clear sky blue.'] },
  { id: 'weather10', english: 'Overcast', vietnamese: 'U ám', pronunciation: 'u am', category: 'weather', chapter: 'chapter26', difficulty: 2, examples: ['Overcast day gloomy.'] },
  { id: 'weather11', english: 'Drizzle', vietnamese: 'Mưa phùn', pronunciation: 'mua phun', category: 'weather', chapter: 'chapter26', difficulty: 1, examples: ['Drizzle light rain.'] },
  { id: 'weather12', english: 'Shower', vietnamese: 'Mưa rào', pronunciation: 'mua rao', category: 'weather', chapter: 'chapter26', difficulty: 1, examples: ['Shower brief rain.'] },
  { id: 'weather13', english: 'Downpour', vietnamese: 'Mưa to', pronunciation: 'mua to', category: 'weather', chapter: 'chapter26', difficulty: 1, examples: ['Downpour heavy rain.'] },
  { id: 'weather14', english: 'Thunder', vietnamese: 'Sấm', pronunciation: 'sam', category: 'weather', chapter: 'chapter26', difficulty: 1, examples: ['Thunder loud noise.'] },
  { id: 'weather15', english: 'Lightning', vietnamese: 'Chớp', pronunciation: 'chop', category: 'weather', chapter: 'chapter26', difficulty: 1, examples: ['Lightning bright flash.'] },
  { id: 'weather16', english: 'Hail', vietnamese: 'Mưa đá', pronunciation: 'mua da', category: 'weather', chapter: 'chapter26', difficulty: 1, examples: ['Hail damages crops.'] },
  { id: 'weather17', english: 'Frost', vietnamese: 'Sương giá', pronunciation: 'suong gia', category: 'weather', chapter: 'chapter26', difficulty: 1, examples: ['Frost covers ground.'] },
  { id: 'weather18', english: 'Ice', vietnamese: 'Băng', pronunciation: 'bang', category: 'weather', chapter: 'chapter26', difficulty: 1, examples: ['Ice slippery surface.'] },
  { id: 'weather19', english: 'Humid', vietnamese: 'Ẩm ướt', pronunciation: 'am uot', category: 'weather', chapter: 'chapter26', difficulty: 1, examples: ['Humid air sticky.'] },
  { id: 'weather20', english: 'Dry', vietnamese: 'Khô', pronunciation: 'kho', category: 'weather', chapter: 'chapter26', difficulty: 1, examples: ['Dry season dusty.'] },
  { id: 'weather21', english: 'Mild', vietnamese: 'Ôn hòa', pronunciation: 'on hoa', category: 'weather', chapter: 'chapter26', difficulty: 1, examples: ['Mild temperature comfortable.'] },
  { id: 'weather22', english: 'Severe', vietnamese: 'Khắc nghiệt', pronunciation: 'khac nghiet', category: 'weather', chapter: 'chapter26', difficulty: 1, examples: ['Severe weather warning.'] },
  { id: 'weather23', english: 'Breeze', vietnamese: 'Gió nhẹ', pronunciation: 'gio nhe', category: 'weather', chapter: 'chapter26', difficulty: 1, examples: ['Breeze feels refreshing.'] },
  { id: 'weather24', english: 'Gale', vietnamese: 'Gió mạnh', pronunciation: 'gio manh', category: 'weather', chapter: 'chapter26', difficulty: 2, examples: ['Gale force winds.'] },
  { id: 'weather25', english: 'Hurricane', vietnamese: 'Bão lớn', pronunciation: 'bao lon', category: 'weather', chapter: 'chapter26', difficulty: 1, examples: ['Hurricane destroys buildings.'] },

  // Seasons & Time (25 words)
  { id: 'seasons1', english: 'Season', vietnamese: 'Mùa', pronunciation: 'mua', category: 'seasons', chapter: 'chapter26', difficulty: 1, examples: ['Season changes gradually.'] },
  { id: 'seasons2', english: 'Spring', vietnamese: 'Mùa xuân', pronunciation: 'mua xuan', category: 'seasons', chapter: 'chapter26', difficulty: 1, examples: ['Spring flowers bloom.'] },
  { id: 'seasons3', english: 'Summer', vietnamese: 'Mùa hè', pronunciation: 'mua he', category: 'seasons', chapter: 'chapter26', difficulty: 1, examples: ['Summer very hot.'] },
  { id: 'seasons4', english: 'Autumn', vietnamese: 'Mùa thu', pronunciation: 'mua thu', category: 'seasons', chapter: 'chapter26', difficulty: 1, examples: ['Autumn leaves fall.'] },
  { id: 'seasons5', english: 'Fall', vietnamese: 'Mùa thu', pronunciation: 'mua thu', category: 'seasons', chapter: 'chapter26', difficulty: 1, examples: ['Fall colors beautiful.'] },
  { id: 'seasons6', english: 'Winter', vietnamese: 'Mùa đông', pronunciation: 'mua dong', category: 'seasons', chapter: 'chapter26', difficulty: 1, examples: ['Winter snow white.'] },
  { id: 'seasons7', english: 'January', vietnamese: 'Tháng một', pronunciation: 'thang mot', category: 'seasons', chapter: 'chapter26', difficulty: 1, examples: ['January cold month.'] },
  { id: 'seasons8', english: 'February', vietnamese: 'Tháng hai', pronunciation: 'thang hai', category: 'seasons', chapter: 'chapter26', difficulty: 1, examples: ['February shortest month.'] },
  { id: 'seasons9', english: 'March', vietnamese: 'Tháng ba', pronunciation: 'thang ba', category: 'seasons', chapter: 'chapter26', difficulty: 1, examples: ['March windy month.'] },
  { id: 'seasons10', english: 'April', vietnamese: 'Tháng tư', pronunciation: 'thang tu', category: 'seasons', chapter: 'chapter26', difficulty: 1, examples: ['April spring showers.'] },
  { id: 'seasons11', english: 'May', vietnamese: 'Tháng năm', pronunciation: 'thang nam', category: 'seasons', chapter: 'chapter26', difficulty: 1, examples: ['May flowers beautiful.'] },
  { id: 'seasons12', english: 'June', vietnamese: 'Tháng sáu', pronunciation: 'thang sau', category: 'seasons', chapter: 'chapter26', difficulty: 1, examples: ['June summer begins.'] },
  { id: 'seasons13', english: 'July', vietnamese: 'Tháng bảy', pronunciation: 'thang bay', category: 'seasons', chapter: 'chapter26', difficulty: 1, examples: ['July hottest month.'] },
  { id: 'seasons14', english: 'August', vietnamese: 'Tháng tám', pronunciation: 'thang tam', category: 'seasons', chapter: 'chapter26', difficulty: 1, examples: ['August very humid.'] },
  { id: 'seasons15', english: 'September', vietnamese: 'Tháng chín', pronunciation: 'thang chin', category: 'seasons', chapter: 'chapter26', difficulty: 1, examples: ['September school starts.'] },
  { id: 'seasons16', english: 'October', vietnamese: 'Tháng mười', pronunciation: 'thang muoi', category: 'seasons', chapter: 'chapter26', difficulty: 1, examples: ['October autumn colors.'] },
  { id: 'seasons17', english: 'November', vietnamese: 'Tháng mười một', pronunciation: 'thang muoi mot', category: 'seasons', chapter: 'chapter26', difficulty: 1, examples: ['November cooler weather.'] },
  { id: 'seasons18', english: 'December', vietnamese: 'Tháng mười hai', pronunciation: 'thang muoi hai', category: 'seasons', chapter: 'chapter26', difficulty: 1, examples: ['December winter holidays.'] },
  { id: 'seasons19', english: 'Month', vietnamese: 'Tháng', pronunciation: 'thang', category: 'seasons', chapter: 'chapter26', difficulty: 1, examples: ['Month thirty days.'] },
  { id: 'seasons20', english: 'Year', vietnamese: 'Năm', pronunciation: 'nam', category: 'seasons', chapter: 'chapter26', difficulty: 1, examples: ['Year twelve months.'] },
  { id: 'seasons21', english: 'Equinox', vietnamese: 'Xuân phân', pronunciation: 'xuan phan', category: 'seasons', chapter: 'chapter26', difficulty: 2, examples: ['Equinox equal day night.'] },
  { id: 'seasons22', english: 'Solstice', vietnamese: 'Chí', pronunciation: 'chi', category: 'seasons', chapter: 'chapter26', difficulty: 2, examples: ['Solstice longest day.'] },
  { id: 'seasons23', english: 'Climate', vietnamese: 'Khí hậu', pronunciation: 'khi hau', category: 'seasons', chapter: 'chapter26', difficulty: 1, examples: ['Climate affects lifestyle.'] },
  { id: 'seasons24', english: 'Tropical', vietnamese: 'Nhiệt đới', pronunciation: 'nhiet doi', category: 'seasons', chapter: 'chapter26', difficulty: 1, examples: ['Tropical climate hot.'] },
  { id: 'seasons25', english: 'Temperate', vietnamese: 'Ôn đới', pronunciation: 'on doi', category: 'seasons', chapter: 'chapter26', difficulty: 2, examples: ['Temperate zone mild.'] },

  // Temperature & Measurements (25 words)
  { id: 'temperature1', english: 'Temperature', vietnamese: 'Nhiệt độ', pronunciation: 'nhiet do', category: 'temperature', chapter: 'chapter26', difficulty: 1, examples: ['Temperature rises noon.'] },
  { id: 'temperature2', english: 'Hot', vietnamese: 'Nóng', pronunciation: 'nong', category: 'temperature', chapter: 'chapter26', difficulty: 1, examples: ['Hot summer day.'] },
  { id: 'temperature3', english: 'Cold', vietnamese: 'Lạnh', pronunciation: 'lanh', category: 'temperature', chapter: 'chapter26', difficulty: 1, examples: ['Cold winter night.'] },
  { id: 'temperature4', english: 'Warm', vietnamese: 'Ấm', pronunciation: 'am', category: 'temperature', chapter: 'chapter26', difficulty: 1, examples: ['Warm spring weather.'] },
  { id: 'temperature5', english: 'Cool', vietnamese: 'Mát', pronunciation: 'mat', category: 'temperature', chapter: 'chapter26', difficulty: 1, examples: ['Cool evening breeze.'] },
  { id: 'temperature6', english: 'Freezing', vietnamese: 'Đóng băng', pronunciation: 'dong bang', category: 'temperature', chapter: 'chapter26', difficulty: 1, examples: ['Freezing water ice.'] },
  { id: 'temperature7', english: 'Boiling', vietnamese: 'Sôi', pronunciation: 'soi', category: 'temperature', chapter: 'chapter26', difficulty: 1, examples: ['Boiling water steam.'] },
  { id: 'temperature8', english: 'Degree', vietnamese: 'Độ', pronunciation: 'do', category: 'temperature', chapter: 'chapter26', difficulty: 1, examples: ['Twenty degrees celsius.'] },
  { id: 'temperature9', english: 'Celsius', vietnamese: 'Độ C', pronunciation: 'do c', category: 'temperature', chapter: 'chapter26', difficulty: 1, examples: ['Celsius metric scale.'] },
  { id: 'temperature10', english: 'Fahrenheit', vietnamese: 'Độ F', pronunciation: 'do f', category: 'temperature', chapter: 'chapter26', difficulty: 1, examples: ['Fahrenheit imperial scale.'] },
  { id: 'temperature11', english: 'Thermometer', vietnamese: 'Nhiệt kế', pronunciation: 'nhiet ke', category: 'temperature', chapter: 'chapter26', difficulty: 1, examples: ['Thermometer measures temperature.'] },
  { id: 'temperature12', english: 'Rising', vietnamese: 'Tăng', pronunciation: 'tang', category: 'temperature', chapter: 'chapter26', difficulty: 1, examples: ['Temperature rising gradually.'] },
  { id: 'temperature13', english: 'Falling', vietnamese: 'Giảm', pronunciation: 'giam', category: 'temperature', chapter: 'chapter26', difficulty: 1, examples: ['Temperature falling rapidly.'] },
  { id: 'temperature14', english: 'High', vietnamese: 'Cao', pronunciation: 'cao', category: 'temperature', chapter: 'chapter26', difficulty: 1, examples: ['High temperature summer.'] },
  { id: 'temperature15', english: 'Low', vietnamese: 'Thấp', pronunciation: 'thap', category: 'temperature', chapter: 'chapter26', difficulty: 1, examples: ['Low temperature winter.'] },
  { id: 'temperature16', english: 'Maximum', vietnamese: 'Tối đa', pronunciation: 'toi da', category: 'temperature', chapter: 'chapter26', difficulty: 1, examples: ['Maximum temperature today.'] },
  { id: 'temperature17', english: 'Minimum', vietnamese: 'Tối thiểu', pronunciation: 'toi thieu', category: 'temperature', chapter: 'chapter26', difficulty: 1, examples: ['Minimum temperature tonight.'] },
  { id: 'temperature18', english: 'Average', vietnamese: 'Trung bình', pronunciation: 'trung binh', category: 'temperature', chapter: 'chapter26', difficulty: 1, examples: ['Average temperature month.'] },
  { id: 'temperature19', english: 'Humidity', vietnamese: 'Độ ẩm', pronunciation: 'do am', category: 'temperature', chapter: 'chapter26', difficulty: 1, examples: ['Humidity makes uncomfortable.'] },
  { id: 'temperature20', english: 'Pressure', vietnamese: 'Áp suất', pronunciation: 'ap suat', category: 'temperature', chapter: 'chapter26', difficulty: 1, examples: ['Air pressure changes.'] },
  { id: 'temperature21', english: 'Barometer', vietnamese: 'Phong vũ biểu', pronunciation: 'phong vu bieu', category: 'temperature', chapter: 'chapter26', difficulty: 2, examples: ['Barometer measures pressure.'] },
  { id: 'temperature22', english: 'Forecast', vietnamese: 'Dự báo', pronunciation: 'du bao', category: 'temperature', chapter: 'chapter26', difficulty: 1, examples: ['Weather forecast tomorrow.'] },
  { id: 'temperature23', english: 'Prediction', vietnamese: 'Dự đoán', pronunciation: 'du doan', category: 'temperature', chapter: 'chapter26', difficulty: 1, examples: ['Prediction rain tonight.'] },
  { id: 'temperature24', english: 'Report', vietnamese: 'Báo cáo', pronunciation: 'bao cao', category: 'temperature', chapter: 'chapter26', difficulty: 1, examples: ['Weather report accurate.'] },
  { id: 'temperature25', english: 'Warning', vietnamese: 'Cảnh báo', pronunciation: 'canh bao', category: 'temperature', chapter: 'chapter26', difficulty: 1, examples: ['Storm warning issued.'] },

  // Natural Phenomena (25 words)
  { id: 'phenomena1', english: 'Sun', vietnamese: 'Mặt trời', pronunciation: 'mat troi', category: 'phenomena', chapter: 'chapter26', difficulty: 1, examples: ['Sun shines brightly.'] },
  { id: 'phenomena2', english: 'Moon', vietnamese: 'Mặt trăng', pronunciation: 'mat trang', category: 'phenomena', chapter: 'chapter26', difficulty: 1, examples: ['Moon lights night.'] },
  { id: 'phenomena3', english: 'Stars', vietnamese: 'Sao', pronunciation: 'sao', category: 'phenomena', chapter: 'chapter26', difficulty: 1, examples: ['Stars twinkle sky.'] },
  { id: 'phenomena4', english: 'Cloud', vietnamese: 'Mây', pronunciation: 'may', category: 'phenomena', chapter: 'chapter26', difficulty: 1, examples: ['Cloud blocks sun.'] },
  { id: 'phenomena5', english: 'Sky', vietnamese: 'Bầu trời', pronunciation: 'bau troi', category: 'phenomena', chapter: 'chapter26', difficulty: 1, examples: ['Sky blue clear.'] },
  { id: 'phenomena6', english: 'Horizon', vietnamese: 'Đường chân trời', pronunciation: 'duong chan troi', category: 'phenomena', chapter: 'chapter26', difficulty: 1, examples: ['Horizon line distant.'] },
  { id: 'phenomena7', english: 'Sunrise', vietnamese: 'Bình minh', pronunciation: 'binh minh', category: 'phenomena', chapter: 'chapter26', difficulty: 1, examples: ['Sunrise beautiful morning.'] },
  { id: 'phenomena8', english: 'Sunset', vietnamese: 'Hoàng hôn', pronunciation: 'hoang hon', category: 'phenomena', chapter: 'chapter26', difficulty: 1, examples: ['Sunset colorful evening.'] },
  { id: 'phenomena9', english: 'Dawn', vietnamese: 'Rạng đông', pronunciation: 'rang dong', category: 'phenomena', chapter: 'chapter26', difficulty: 1, examples: ['Dawn early light.'] },
  { id: 'phenomena10', english: 'Dusk', vietnamese: 'Chạng vạng', pronunciation: 'chang vang', category: 'phenomena', chapter: 'chapter26', difficulty: 1, examples: ['Dusk twilight time.'] },
  { id: 'phenomena11', english: 'Rainbow', vietnamese: 'Cầu vồng', pronunciation: 'cau vong', category: 'phenomena', chapter: 'chapter26', difficulty: 1, examples: ['Rainbow after rain.'] },
  { id: 'phenomena12', english: 'Eclipse', vietnamese: 'Nhật thực', pronunciation: 'nhat thuc', category: 'phenomena', chapter: 'chapter26', difficulty: 2, examples: ['Eclipse rare event.'] },
  { id: 'phenomena13', english: 'Aurora', vietnamese: 'Cực quang', pronunciation: 'cuc quang', category: 'phenomena', chapter: 'chapter26', difficulty: 2, examples: ['Aurora northern lights.'] },
  { id: 'phenomena14', english: 'Meteor', vietnamese: 'Sao băng', pronunciation: 'sao bang', category: 'phenomena', chapter: 'chapter26', difficulty: 2, examples: ['Meteor shooting star.'] },
  { id: 'phenomena15', english: 'Comet', vietnamese: 'Sao chổi', pronunciation: 'sao choi', category: 'phenomena', chapter: 'chapter26', difficulty: 2, examples: ['Comet long tail.'] },
  { id: 'phenomena16', english: 'Wind', vietnamese: 'Gió', pronunciation: 'gio', category: 'phenomena', chapter: 'chapter26', difficulty: 1, examples: ['Wind blows leaves.'] },
  { id: 'phenomena17', english: 'Rain', vietnamese: 'Mưa', pronunciation: 'mua', category: 'phenomena', chapter: 'chapter26', difficulty: 1, examples: ['Rain waters plants.'] },
  { id: 'phenomena18', english: 'Snow', vietnamese: 'Tuyết', pronunciation: 'tuyet', category: 'phenomena', chapter: 'chapter26', difficulty: 1, examples: ['Snow covers ground.'] },
  { id: 'phenomena19', english: 'Mist', vietnamese: 'Sương mù', pronunciation: 'suong mu', category: 'phenomena', chapter: 'chapter26', difficulty: 1, examples: ['Mist morning fog.'] },
  { id: 'phenomena20', english: 'Dew', vietnamese: 'Sương', pronunciation: 'suong', category: 'phenomena', chapter: 'chapter26', difficulty: 1, examples: ['Dew morning drops.'] },
  { id: 'phenomena21', english: 'Tide', vietnamese: 'Thủy triều', pronunciation: 'thuy trieu', category: 'phenomena', chapter: 'chapter26', difficulty: 1, examples: ['Tide ocean movement.'] },
  { id: 'phenomena22', english: 'Wave', vietnamese: 'Sóng', pronunciation: 'song', category: 'phenomena', chapter: 'chapter26', difficulty: 1, examples: ['Wave crashes shore.'] },
  { id: 'phenomena23', english: 'Flood', vietnamese: 'Lũ lụt', pronunciation: 'lu lut', category: 'phenomena', chapter: 'chapter26', difficulty: 1, examples: ['Flood damages homes.'] },
  { id: 'phenomena24', english: 'Drought', vietnamese: 'Hạn hán', pronunciation: 'han han', category: 'phenomena', chapter: 'chapter26', difficulty: 1, examples: ['Drought no rain.'] },
  { id: 'phenomena25', english: 'Earthquake', vietnamese: 'Động đất', pronunciation: 'dong dat', category: 'phenomena', chapter: 'chapter26', difficulty: 1, examples: ['Earthquake shakes ground.'] }
]
