// Chapter 27: Sports & Fitness (100 Essential Words)
// Words related to sports, exercise, fitness, and physical activities

import { LanguageWord } from './chapter01-basic-everyday'

export const chapter27Words: LanguageWord[] = [
  // Ball Sports (25 words)
  { id: 'ball1', english: 'Sport', vietnamese: 'Thể thao', pronunciation: 'the thao', category: 'ball', chapter: 'chapter27', difficulty: 1, examples: ['Sport keeps healthy.'] },
  { id: 'ball2', english: 'Football', vietnamese: 'Bóng đá', pronunciation: 'bong da', category: 'ball', chapter: 'chapter27', difficulty: 1, examples: ['Football popular worldwide.'] },
  { id: 'ball3', english: 'Soccer', vietnamese: 'Bóng đá', pronunciation: 'bong da', category: 'ball', chapter: 'chapter27', difficulty: 1, examples: ['Soccer world cup.'] },
  { id: 'ball4', english: 'Basketball', vietnamese: 'Bóng rổ', pronunciation: 'bong ro', category: 'ball', chapter: 'chapter27', difficulty: 1, examples: ['Basketball tall players.'] },
  { id: 'ball5', english: 'Baseball', vietnamese: 'Bóng chày', pronunciation: 'bong chay', category: 'ball', chapter: 'chapter27', difficulty: 1, examples: ['Baseball American sport.'] },
  { id: 'ball6', english: 'Tennis', vietnamese: 'Quần vợt', pronunciation: 'quan vot', category: 'ball', chapter: 'chapter27', difficulty: 1, examples: ['Tennis racket sport.'] },
  { id: 'ball7', english: 'Volleyball', vietnamese: 'Bóng chuyền', pronunciation: 'bong chuyen', category: 'ball', chapter: 'chapter27', difficulty: 1, examples: ['Volleyball team sport.'] },
  { id: 'ball8', english: 'Badminton', vietnamese: 'Cầu lông', pronunciation: 'cau long', category: 'ball', chapter: 'chapter27', difficulty: 1, examples: ['Badminton shuttlecock game.'] },
  { id: 'ball9', english: 'Table tennis', vietnamese: 'Bóng bàn', pronunciation: 'bong ban', category: 'ball', chapter: 'chapter27', difficulty: 1, examples: ['Table tennis ping pong.'] },
  { id: 'ball10', english: 'Golf', vietnamese: 'Golf', pronunciation: 'golf', category: 'ball', chapter: 'chapter27', difficulty: 1, examples: ['Golf precision sport.'] },
  { id: 'ball11', english: 'Rugby', vietnamese: 'Bóng bầu dục', pronunciation: 'bong bau duc', category: 'ball', chapter: 'chapter27', difficulty: 1, examples: ['Rugby physical sport.'] },
  { id: 'ball12', english: 'Cricket', vietnamese: 'Crikê', pronunciation: 'crike', category: 'ball', chapter: 'chapter27', difficulty: 1, examples: ['Cricket British sport.'] },
  { id: 'ball13', english: 'Bowling', vietnamese: 'Bowling', pronunciation: 'bowling', category: 'ball', chapter: 'chapter27', difficulty: 1, examples: ['Bowling strike score.'] },
  { id: 'ball14', english: 'Ball', vietnamese: 'Bóng', pronunciation: 'bong', category: 'ball', chapter: 'chapter27', difficulty: 1, examples: ['Ball round object.'] },
  { id: 'ball15', english: 'Goal', vietnamese: 'Bàn thắng', pronunciation: 'ban thang', category: 'ball', chapter: 'chapter27', difficulty: 1, examples: ['Goal scores point.'] },
  { id: 'ball16', english: 'Field', vietnamese: 'Sân', pronunciation: 'san', category: 'ball', chapter: 'chapter27', difficulty: 1, examples: ['Field grass surface.'] },
  { id: 'ball17', english: 'Court', vietnamese: 'Sân bóng', pronunciation: 'san bong', category: 'ball', chapter: 'chapter27', difficulty: 1, examples: ['Court basketball area.'] },
  { id: 'ball18', english: 'Net', vietnamese: 'Lưới', pronunciation: 'luoi', category: 'ball', chapter: 'chapter27', difficulty: 1, examples: ['Net catches ball.'] },
  { id: 'ball19', english: 'Racket', vietnamese: 'Vợt', pronunciation: 'vot', category: 'ball', chapter: 'chapter27', difficulty: 1, examples: ['Racket hits ball.'] },
  { id: 'ball20', english: 'Bat', vietnamese: 'Gậy', pronunciation: 'gay', category: 'ball', chapter: 'chapter27', difficulty: 1, examples: ['Bat hits baseball.'] },
  { id: 'ball21', english: 'Club', vietnamese: 'Gậy golf', pronunciation: 'gay golf', category: 'ball', chapter: 'chapter27', difficulty: 1, examples: ['Club golf equipment.'] },
  { id: 'ball22', english: 'Score', vietnamese: 'Điểm số', pronunciation: 'diem so', category: 'ball', chapter: 'chapter27', difficulty: 1, examples: ['Score wins game.'] },
  { id: 'ball23', english: 'Team', vietnamese: 'Đội', pronunciation: 'doi', category: 'ball', chapter: 'chapter27', difficulty: 1, examples: ['Team works together.'] },
  { id: 'ball24', english: 'Player', vietnamese: 'Người chơi', pronunciation: 'nguoi choi', category: 'ball', chapter: 'chapter27', difficulty: 1, examples: ['Player skilled athlete.'] },
  { id: 'ball25', english: 'Match', vietnamese: 'Trận đấu', pronunciation: 'tran dau', category: 'ball', chapter: 'chapter27', difficulty: 1, examples: ['Match exciting competition.'] },

  // Water & Individual Sports (25 words)
  { id: 'water1', english: 'Swimming', vietnamese: 'Bơi lội', pronunciation: 'boi loi', category: 'water', chapter: 'chapter27', difficulty: 1, examples: ['Swimming good exercise.'] },
  { id: 'water2', english: 'Diving', vietnamese: 'Lặn', pronunciation: 'lan', category: 'water', chapter: 'chapter27', difficulty: 1, examples: ['Diving underwater activity.'] },
  { id: 'water3', english: 'Surfing', vietnamese: 'Lướt sóng', pronunciation: 'luot song', category: 'water', chapter: 'chapter27', difficulty: 1, examples: ['Surfing ocean sport.'] },
  { id: 'water4', english: 'Sailing', vietnamese: 'Đi thuyền buồm', pronunciation: 'di thuyen buom', category: 'water', chapter: 'chapter27', difficulty: 1, examples: ['Sailing wind power.'] },
  { id: 'water5', english: 'Rowing', vietnamese: 'Chèo thuyền', pronunciation: 'cheo thuyen', category: 'water', chapter: 'chapter27', difficulty: 1, examples: ['Rowing arm exercise.'] },
  { id: 'water6', english: 'Fishing', vietnamese: 'Câu cá', pronunciation: 'cau ca', category: 'water', chapter: 'chapter27', difficulty: 1, examples: ['Fishing relaxing hobby.'] },
  { id: 'water7', english: 'Pool', vietnamese: 'Bể bơi', pronunciation: 'be boi', category: 'water', chapter: 'chapter27', difficulty: 1, examples: ['Pool swimming facility.'] },
  { id: 'water8', english: 'Running', vietnamese: 'Chạy bộ', pronunciation: 'chay bo', category: 'water', chapter: 'chapter27', difficulty: 1, examples: ['Running cardio exercise.'] },
  { id: 'water9', english: 'Jogging', vietnamese: 'Chạy bộ nhẹ', pronunciation: 'chay bo nhe', category: 'water', chapter: 'chapter27', difficulty: 1, examples: ['Jogging morning routine.'] },
  { id: 'water10', english: 'Walking', vietnamese: 'Đi bộ', pronunciation: 'di bo', category: 'water', chapter: 'chapter27', difficulty: 1, examples: ['Walking daily exercise.'] },
  { id: 'water11', english: 'Hiking', vietnamese: 'Đi bộ đường dài', pronunciation: 'di bo duong dai', category: 'water', chapter: 'chapter27', difficulty: 1, examples: ['Hiking mountain trails.'] },
  { id: 'water12', english: 'Climbing', vietnamese: 'Leo núi', pronunciation: 'leo nui', category: 'water', chapter: 'chapter27', difficulty: 1, examples: ['Climbing requires strength.'] },
  { id: 'water13', english: 'Cycling', vietnamese: 'Đạp xe', pronunciation: 'dap xe', category: 'water', chapter: 'chapter27', difficulty: 1, examples: ['Cycling leg exercise.'] },
  { id: 'water14', english: 'Skating', vietnamese: 'Trượt băng', pronunciation: 'truot bang', category: 'water', chapter: 'chapter27', difficulty: 1, examples: ['Skating ice sport.'] },
  { id: 'water15', english: 'Skiing', vietnamese: 'Trượt tuyết', pronunciation: 'truot tuyet', category: 'water', chapter: 'chapter27', difficulty: 1, examples: ['Skiing winter sport.'] },
  { id: 'water16', english: 'Snowboarding', vietnamese: 'Trượt tuyết ván', pronunciation: 'truot tuyet van', category: 'water', chapter: 'chapter27', difficulty: 2, examples: ['Snowboarding extreme sport.'] },
  { id: 'water17', english: 'Track', vietnamese: 'Đường chạy', pronunciation: 'duong chay', category: 'water', chapter: 'chapter27', difficulty: 1, examples: ['Track athletic field.'] },
  { id: 'water18', english: 'Marathon', vietnamese: 'Chạy marathon', pronunciation: 'chay marathon', category: 'water', chapter: 'chapter27', difficulty: 1, examples: ['Marathon long distance.'] },
  { id: 'water19', english: 'Sprint', vietnamese: 'Chạy nước rút', pronunciation: 'chay nuoc rut', category: 'water', chapter: 'chapter27', difficulty: 1, examples: ['Sprint short distance.'] },
  { id: 'water20', english: 'Jump', vietnamese: 'Nhảy', pronunciation: 'nhay', category: 'water', chapter: 'chapter27', difficulty: 1, examples: ['Jump high athletics.'] },
  { id: 'water21', english: 'Throw', vietnamese: 'Ném', pronunciation: 'nem', category: 'water', chapter: 'chapter27', difficulty: 1, examples: ['Throw javelin far.'] },
  { id: 'water22', english: 'Race', vietnamese: 'Cuộc đua', pronunciation: 'cuoc dua', category: 'water', chapter: 'chapter27', difficulty: 1, examples: ['Race competitive event.'] },
  { id: 'water23', english: 'Competition', vietnamese: 'Cuộc thi', pronunciation: 'cuoc thi', category: 'water', chapter: 'chapter27', difficulty: 1, examples: ['Competition tests skills.'] },
  { id: 'water24', english: 'Tournament', vietnamese: 'Giải đấu', pronunciation: 'giai dau', category: 'water', chapter: 'chapter27', difficulty: 1, examples: ['Tournament championship event.'] },
  { id: 'water25', english: 'Championship', vietnamese: 'Vô địch', pronunciation: 'vo dich', category: 'water', chapter: 'chapter27', difficulty: 1, examples: ['Championship title prize.'] },

  // Fitness & Exercise (25 words)
  { id: 'fitness1', english: 'Fitness', vietnamese: 'Thể dục', pronunciation: 'the duc', category: 'fitness', chapter: 'chapter27', difficulty: 1, examples: ['Fitness improves health.'] },
  { id: 'fitness2', english: 'Exercise', vietnamese: 'Tập thể dục', pronunciation: 'tap the duc', category: 'fitness', chapter: 'chapter27', difficulty: 1, examples: ['Exercise daily routine.'] },
  { id: 'fitness3', english: 'Workout', vietnamese: 'Tập luyện', pronunciation: 'tap luyen', category: 'fitness', chapter: 'chapter27', difficulty: 1, examples: ['Workout muscle building.'] },
  { id: 'fitness4', english: 'Training', vietnamese: 'Huấn luyện', pronunciation: 'huan luyen', category: 'fitness', chapter: 'chapter27', difficulty: 1, examples: ['Training improves performance.'] },
  { id: 'fitness5', english: 'Gym', vietnamese: 'Phòng tập', pronunciation: 'phong tap', category: 'fitness', chapter: 'chapter27', difficulty: 1, examples: ['Gym fitness facility.'] },
  { id: 'fitness6', english: 'Weightlifting', vietnamese: 'Cử tạ', pronunciation: 'cu ta', category: 'fitness', chapter: 'chapter27', difficulty: 1, examples: ['Weightlifting builds strength.'] },
  { id: 'fitness7', english: 'Yoga', vietnamese: 'Yoga', pronunciation: 'yoga', category: 'fitness', chapter: 'chapter27', difficulty: 1, examples: ['Yoga flexibility exercise.'] },
  { id: 'fitness8', english: 'Pilates', vietnamese: 'Pilates', pronunciation: 'pilates', category: 'fitness', chapter: 'chapter27', difficulty: 1, examples: ['Pilates core strength.'] },
  { id: 'fitness9', english: 'Aerobics', vietnamese: 'Thể dục nhịp điệu', pronunciation: 'the duc nhip dieu', category: 'fitness', chapter: 'chapter27', difficulty: 1, examples: ['Aerobics cardio workout.'] },
  { id: 'fitness10', english: 'Stretching', vietnamese: 'Duỗi cơ', pronunciation: 'duoi co', category: 'fitness', chapter: 'chapter27', difficulty: 1, examples: ['Stretching prevents injury.'] },
  { id: 'fitness11', english: 'Strength', vietnamese: 'Sức mạnh', pronunciation: 'suc manh', category: 'fitness', chapter: 'chapter27', difficulty: 1, examples: ['Strength training important.'] },
  { id: 'fitness12', english: 'Endurance', vietnamese: 'Sức bền', pronunciation: 'suc ben', category: 'fitness', chapter: 'chapter27', difficulty: 1, examples: ['Endurance long activity.'] },
  { id: 'fitness13', english: 'Flexibility', vietnamese: 'Sự dẻo dai', pronunciation: 'su deo dai', category: 'fitness', chapter: 'chapter27', difficulty: 1, examples: ['Flexibility prevents stiffness.'] },
  { id: 'fitness14', english: 'Balance', vietnamese: 'Thăng bằng', pronunciation: 'thang bang', category: 'fitness', chapter: 'chapter27', difficulty: 1, examples: ['Balance coordination skill.'] },
  { id: 'fitness15', english: 'Cardio', vietnamese: 'Tim mạch', pronunciation: 'tim mach', category: 'fitness', chapter: 'chapter27', difficulty: 1, examples: ['Cardio heart exercise.'] },
  { id: 'fitness16', english: 'Muscle', vietnamese: 'Cơ bắp', pronunciation: 'co bap', category: 'fitness', chapter: 'chapter27', difficulty: 1, examples: ['Muscle body strength.'] },
  { id: 'fitness17', english: 'Calories', vietnamese: 'Calo', pronunciation: 'calo', category: 'fitness', chapter: 'chapter27', difficulty: 1, examples: ['Calories energy units.'] },
  { id: 'fitness18', english: 'Diet', vietnamese: 'Chế độ ăn', pronunciation: 'che do an', category: 'fitness', chapter: 'chapter27', difficulty: 1, examples: ['Diet affects fitness.'] },
  { id: 'fitness19', english: 'Nutrition', vietnamese: 'Dinh dưỡng', pronunciation: 'dinh duong', category: 'fitness', chapter: 'chapter27', difficulty: 1, examples: ['Nutrition supports health.'] },
  { id: 'fitness20', english: 'Protein', vietnamese: 'Chất đạm', pronunciation: 'chat dam', category: 'fitness', chapter: 'chapter27', difficulty: 1, examples: ['Protein builds muscle.'] },
  { id: 'fitness21', english: 'Vitamins', vietnamese: 'Vitamin', pronunciation: 'vitamin', category: 'fitness', chapter: 'chapter27', difficulty: 1, examples: ['Vitamins boost immunity.'] },
  { id: 'fitness22', english: 'Hydration', vietnamese: 'Cung cấp nước', pronunciation: 'cung cap nuoc', category: 'fitness', chapter: 'chapter27', difficulty: 2, examples: ['Hydration prevents dehydration.'] },
  { id: 'fitness23', english: 'Recovery', vietnamese: 'Phục hồi', pronunciation: 'phuc hoi', category: 'fitness', chapter: 'chapter27', difficulty: 1, examples: ['Recovery rest period.'] },
  { id: 'fitness24', english: 'Injury', vietnamese: 'Chấn thương', pronunciation: 'chan thuong', category: 'fitness', chapter: 'chapter27', difficulty: 1, examples: ['Injury requires treatment.'] },
  { id: 'fitness25', english: 'Warm-up', vietnamese: 'Khởi động', pronunciation: 'khoi dong', category: 'fitness', chapter: 'chapter27', difficulty: 1, examples: ['Warm-up prevents injury.'] },

  // Competition & Achievement (25 words)
  { id: 'competition1', english: 'Athlete', vietnamese: 'Vận động viên', pronunciation: 'van dong vien', category: 'competition', chapter: 'chapter27', difficulty: 1, examples: ['Athlete trains daily.'] },
  { id: 'competition2', english: 'Coach', vietnamese: 'Huấn luyện viên', pronunciation: 'huan luyen vien', category: 'competition', chapter: 'chapter27', difficulty: 1, examples: ['Coach guides athletes.'] },
  { id: 'competition3', english: 'Trainer', vietnamese: 'Người đào tạo', pronunciation: 'nguoi dao tao', category: 'competition', chapter: 'chapter27', difficulty: 1, examples: ['Trainer develops skills.'] },
  { id: 'competition4', english: 'Captain', vietnamese: 'Đội trưởng', pronunciation: 'doi truong', category: 'competition', chapter: 'chapter27', difficulty: 1, examples: ['Captain leads team.'] },
  { id: 'competition5', english: 'Referee', vietnamese: 'Trọng tài', pronunciation: 'trong tai', category: 'competition', chapter: 'chapter27', difficulty: 1, examples: ['Referee enforces rules.'] },
  { id: 'competition6', english: 'Judge', vietnamese: 'Giám khảo', pronunciation: 'giam khao', category: 'competition', chapter: 'chapter27', difficulty: 1, examples: ['Judge scores performance.'] },
  { id: 'competition7', english: 'Spectator', vietnamese: 'Khán giả', pronunciation: 'khan gia', category: 'competition', chapter: 'chapter27', difficulty: 1, examples: ['Spectator watches game.'] },
  { id: 'competition8', english: 'Fan', vietnamese: 'Người hâm mộ', pronunciation: 'nguoi ham mo', category: 'competition', chapter: 'chapter27', difficulty: 1, examples: ['Fan supports team.'] },
  { id: 'competition9', english: 'Stadium', vietnamese: 'Sân vận động', pronunciation: 'san van dong', category: 'competition', chapter: 'chapter27', difficulty: 1, examples: ['Stadium holds thousands.'] },
  { id: 'competition10', english: 'Arena', vietnamese: 'Đấu trường', pronunciation: 'dau truong', category: 'competition', chapter: 'chapter27', difficulty: 1, examples: ['Arena indoor venue.'] },
  { id: 'competition11', english: 'Victory', vietnamese: 'Chiến thắng', pronunciation: 'chien thang', category: 'competition', chapter: 'chapter27', difficulty: 1, examples: ['Victory hard earned.'] },
  { id: 'competition12', english: 'Defeat', vietnamese: 'Thất bại', pronunciation: 'that bai', category: 'competition', chapter: 'chapter27', difficulty: 1, examples: ['Defeat teaches lessons.'] },
  { id: 'competition13', english: 'Win', vietnamese: 'Thắng', pronunciation: 'thang', category: 'competition', chapter: 'chapter27', difficulty: 1, examples: ['Win brings joy.'] },
  { id: 'competition14', english: 'Lose', vietnamese: 'Thua', pronunciation: 'thua', category: 'competition', chapter: 'chapter27', difficulty: 1, examples: ['Lose motivates improvement.'] },
  { id: 'competition15', english: 'Draw', vietnamese: 'Hòa', pronunciation: 'hoa', category: 'competition', chapter: 'chapter27', difficulty: 1, examples: ['Draw equal result.'] },
  { id: 'competition16', english: 'Medal', vietnamese: 'Huy chương', pronunciation: 'huy chuong', category: 'competition', chapter: 'chapter27', difficulty: 1, examples: ['Medal achievement reward.'] },
  { id: 'competition17', english: 'Trophy', vietnamese: 'Cúp', pronunciation: 'cup', category: 'competition', chapter: 'chapter27', difficulty: 1, examples: ['Trophy victory symbol.'] },
  { id: 'competition18', english: 'Prize', vietnamese: 'Giải thưởng', pronunciation: 'giai thuong', category: 'competition', chapter: 'chapter27', difficulty: 1, examples: ['Prize motivates effort.'] },
  { id: 'competition19', english: 'Record', vietnamese: 'Kỷ lục', pronunciation: 'ky luc', category: 'competition', chapter: 'chapter27', difficulty: 1, examples: ['Record breaking performance.'] },
  { id: 'competition20', english: 'Champion', vietnamese: 'Nhà vô địch', pronunciation: 'nha vo dich', category: 'competition', chapter: 'chapter27', difficulty: 1, examples: ['Champion best performer.'] },
  { id: 'competition21', english: 'Opponent', vietnamese: 'Đối thủ', pronunciation: 'doi thu', category: 'competition', chapter: 'chapter27', difficulty: 1, examples: ['Opponent challenges skills.'] },
  { id: 'competition22', english: 'Rival', vietnamese: 'Đối thủ cạnh tranh', pronunciation: 'doi thu canh tranh', category: 'competition', chapter: 'chapter27', difficulty: 1, examples: ['Rival competitive relationship.'] },
  { id: 'competition23', english: 'Teamwork', vietnamese: 'Làm việc nhóm', pronunciation: 'lam viec nhom', category: 'competition', chapter: 'chapter27', difficulty: 1, examples: ['Teamwork achieves goals.'] },
  { id: 'competition24', english: 'Fair play', vietnamese: 'Chơi công bằng', pronunciation: 'choi cong bang', category: 'competition', chapter: 'chapter27', difficulty: 1, examples: ['Fair play sportsmanship.'] },
  { id: 'competition25', english: 'Olympics', vietnamese: 'Thế vận hội', pronunciation: 'the van hoi', category: 'competition', chapter: 'chapter27', difficulty: 1, examples: ['Olympics global competition.'] }
]
