// Chapter 12: Weather & Nature (100 Essential Words)
// Words related to weather conditions, natural phenomena, and the environment

import { LanguageWord } from './chapter01-basic-everyday'

export const chapter12Words: LanguageWord[] = [
  // Weather Conditions (25 words)
  { id: 'weather1', english: 'Weather', vietnamese: 'Thời tiết', pronunciation: 'thoi tiet', category: 'weather', chapter: 'chapter12', difficulty: 1, examples: ['Check weather forecast daily.'] },
  { id: 'weather2', english: 'Sunny', vietnamese: 'Nắng', pronunciation: 'nang', category: 'weather', chapter: 'chapter12', difficulty: 1, examples: ['Today is sunny day.'] },
  { id: 'weather3', english: 'Cloudy', vietnamese: 'Có mây', pronunciation: 'co may', category: 'weather', chapter: 'chapter12', difficulty: 1, examples: ['Sky looks cloudy.'] },
  { id: 'weather4', english: 'Rainy', vietnamese: 'Mưa', pronunciation: 'mua', category: 'weather', chapter: 'chapter12', difficulty: 1, examples: ['Rainy season starts soon.'] },
  { id: 'weather5', english: 'Snowy', vietnamese: 'Tuyết', pronunciation: 'tuyet', category: 'weather', chapter: 'chapter12', difficulty: 1, examples: ['Snowy weather is beautiful.'] },
  { id: 'weather6', english: 'Windy', vietnamese: 'Gió', pronunciation: 'gio', category: 'weather', chapter: 'chapter12', difficulty: 1, examples: ['Very windy today.'] },
  { id: 'weather7', english: 'Hot', vietnamese: 'Nóng', pronunciation: 'nong', category: 'weather', chapter: 'chapter12', difficulty: 1, examples: ['Summer is very hot.'] },
  { id: 'weather8', english: 'Cold', vietnamese: 'Lạnh', pronunciation: 'lanh', category: 'weather', chapter: 'chapter12', difficulty: 1, examples: ['Winter is cold season.'] },
  { id: 'weather9', english: 'Warm', vietnamese: 'Ấm', pronunciation: 'am', category: 'weather', chapter: 'chapter12', difficulty: 1, examples: ['Spring brings warm weather.'] },
  { id: 'weather10', english: 'Cool', vietnamese: 'Mát', pronunciation: 'mat', category: 'weather', chapter: 'chapter12', difficulty: 1, examples: ['Evening feels cool.'] },
  { id: 'weather11', english: 'Humid', vietnamese: 'Ẩm ướt', pronunciation: 'am uot', category: 'weather', chapter: 'chapter12', difficulty: 1, examples: ['Tropical weather is humid.'] },
  { id: 'weather12', english: 'Dry', vietnamese: 'Khô', pronunciation: 'kho', category: 'weather', chapter: 'chapter12', difficulty: 1, examples: ['Desert climate is dry.'] },
  { id: 'weather13', english: 'Foggy', vietnamese: 'Sương mù', pronunciation: 'suong mu', category: 'weather', chapter: 'chapter12', difficulty: 1, examples: ['Morning is often foggy.'] },
  { id: 'weather14', english: 'Clear', vietnamese: 'Quang đãng', pronunciation: 'quang dang', category: 'weather', chapter: 'chapter12', difficulty: 1, examples: ['Clear sky tonight.'] },
  { id: 'weather15', english: 'Stormy', vietnamese: 'Bão', pronunciation: 'bao', category: 'weather', chapter: 'chapter12', difficulty: 1, examples: ['Stormy weather is dangerous.'] },
  { id: 'weather16', english: 'Thunder', vietnamese: 'Sấm', pronunciation: 'sam', category: 'weather', chapter: 'chapter12', difficulty: 1, examples: ['Loud thunder scares cats.'] },
  { id: 'weather17', english: 'Lightning', vietnamese: 'Chớp', pronunciation: 'chop', category: 'weather', chapter: 'chapter12', difficulty: 1, examples: ['Lightning lights up sky.'] },
  { id: 'weather18', english: 'Rainbow', vietnamese: 'Cầu vồng', pronunciation: 'cau vong', category: 'weather', chapter: 'chapter12', difficulty: 1, examples: ['Rainbow after rain.'] },
  { id: 'weather19', english: 'Frost', vietnamese: 'Sương giá', pronunciation: 'suong gia', category: 'weather', chapter: 'chapter12', difficulty: 1, examples: ['Frost covers grass.'] },
  { id: 'weather20', english: 'Hail', vietnamese: 'Mưa đá', pronunciation: 'mua da', category: 'weather', chapter: 'chapter12', difficulty: 1, examples: ['Hail damages crops.'] },
  { id: 'weather21', english: 'Drizzle', vietnamese: 'Mưa phùn', pronunciation: 'mua phun', category: 'weather', chapter: 'chapter12', difficulty: 1, examples: ['Light drizzle all day.'] },
  { id: 'weather22', english: 'Shower', vietnamese: 'Cơn mưa', pronunciation: 'con mua', category: 'weather', chapter: 'chapter12', difficulty: 1, examples: ['Brief shower in afternoon.'] },
  { id: 'weather23', english: 'Downpour', vietnamese: 'Mưa to', pronunciation: 'mua to', category: 'weather', chapter: 'chapter12', difficulty: 1, examples: ['Heavy downpour floods streets.'] },
  { id: 'weather24', english: 'Breeze', vietnamese: 'Gió nhẹ', pronunciation: 'gio nhe', category: 'weather', chapter: 'chapter12', difficulty: 1, examples: ['Gentle breeze feels nice.'] },
  { id: 'weather25', english: 'Hurricane', vietnamese: 'Bão lớn', pronunciation: 'bao lon', category: 'weather', chapter: 'chapter12', difficulty: 1, examples: ['Hurricane brings destruction.'] },

  // Natural Elements (25 words)
  { id: 'nature1', english: 'Sun', vietnamese: 'Mặt trời', pronunciation: 'mat troi', category: 'nature', chapter: 'chapter12', difficulty: 1, examples: ['Sun rises in east.'] },
  { id: 'nature2', english: 'Moon', vietnamese: 'Mặt trăng', pronunciation: 'mat trang', category: 'nature', chapter: 'chapter12', difficulty: 1, examples: ['Full moon is bright.'] },
  { id: 'nature3', english: 'Star', vietnamese: 'Ngôi sao', pronunciation: 'ngoi sao', category: 'nature', chapter: 'chapter12', difficulty: 1, examples: ['Stars shine at night.'] },
  { id: 'nature4', english: 'Cloud', vietnamese: 'Đám mây', pronunciation: 'dam may', category: 'nature', chapter: 'chapter12', difficulty: 1, examples: ['White clouds float.'] },
  { id: 'nature5', english: 'Sky', vietnamese: 'Bầu trời', pronunciation: 'bau troi', category: 'nature', chapter: 'chapter12', difficulty: 1, examples: ['Blue sky looks beautiful.'] },
  { id: 'nature6', english: 'Air', vietnamese: 'Không khí', pronunciation: 'khong khi', category: 'nature', chapter: 'chapter12', difficulty: 1, examples: ['Fresh air in mountains.'] },
  { id: 'nature7', english: 'Wind', vietnamese: 'Gió', pronunciation: 'gio', category: 'nature', chapter: 'chapter12', difficulty: 1, examples: ['Strong wind blows.'] },
  { id: 'nature8', english: 'Rain', vietnamese: 'Mưa', pronunciation: 'mua', category: 'nature', chapter: 'chapter12', difficulty: 1, examples: ['Rain waters plants.'] },
  { id: 'nature9', english: 'Snow', vietnamese: 'Tuyết', pronunciation: 'tuyet', category: 'nature', chapter: 'chapter12', difficulty: 1, examples: ['Snow covers mountains.'] },
  { id: 'nature10', english: 'Ice', vietnamese: 'Băng', pronunciation: 'bang', category: 'nature', chapter: 'chapter12', difficulty: 1, examples: ['Ice forms in winter.'] },
  { id: 'nature11', english: 'Water', vietnamese: 'Nước', pronunciation: 'nuoc', category: 'nature', chapter: 'chapter12', difficulty: 1, examples: ['Clean water is essential.'] },
  { id: 'nature12', english: 'Fire', vietnamese: 'Lửa', pronunciation: 'lua', category: 'nature', chapter: 'chapter12', difficulty: 1, examples: ['Fire provides warmth.'] },
  { id: 'nature13', english: 'Earth', vietnamese: 'Đất', pronunciation: 'dat', category: 'nature', chapter: 'chapter12', difficulty: 1, examples: ['Rich earth grows crops.'] },
  { id: 'nature14', english: 'Rock', vietnamese: 'Đá', pronunciation: 'da', category: 'nature', chapter: 'chapter12', difficulty: 1, examples: ['Climb on big rock.'] },
  { id: 'nature15', english: 'Sand', vietnamese: 'Cát', pronunciation: 'cat', category: 'nature', chapter: 'chapter12', difficulty: 1, examples: ['Sand feels warm.'] },
  { id: 'nature16', english: 'Mud', vietnamese: 'Bùn', pronunciation: 'bun', category: 'nature', chapter: 'chapter12', difficulty: 1, examples: ['Rain creates mud.'] },
  { id: 'nature17', english: 'Dust', vietnamese: 'Bụi', pronunciation: 'bui', category: 'nature', chapter: 'chapter12', difficulty: 1, examples: ['Wind blows dust.'] },
  { id: 'nature18', english: 'Stone', vietnamese: 'Đá', pronunciation: 'da', category: 'nature', chapter: 'chapter12', difficulty: 1, examples: ['Smooth stone in river.'] },
  { id: 'nature19', english: 'Mountain', vietnamese: 'Núi', pronunciation: 'nui', category: 'nature', chapter: 'chapter12', difficulty: 1, examples: ['Tall mountain peak.'] },
  { id: 'nature20', english: 'Hill', vietnamese: 'Đồi', pronunciation: 'doi', category: 'nature', chapter: 'chapter12', difficulty: 1, examples: ['Rolling green hills.'] },
  { id: 'nature21', english: 'Valley', vietnamese: 'Thung lũng', pronunciation: 'thung lung', category: 'nature', chapter: 'chapter12', difficulty: 1, examples: ['Deep valley below.'] },
  { id: 'nature22', english: 'River', vietnamese: 'Sông', pronunciation: 'song', category: 'nature', chapter: 'chapter12', difficulty: 1, examples: ['River flows to sea.'] },
  { id: 'nature23', english: 'Lake', vietnamese: 'Hồ', pronunciation: 'ho', category: 'nature', chapter: 'chapter12', difficulty: 1, examples: ['Clear lake water.'] },
  { id: 'nature24', english: 'Ocean', vietnamese: 'Đại dương', pronunciation: 'dai duong', category: 'nature', chapter: 'chapter12', difficulty: 1, examples: ['Ocean waves crash.'] },
  { id: 'nature25', english: 'Sea', vietnamese: 'Biển', pronunciation: 'bien', category: 'nature', chapter: 'chapter12', difficulty: 1, examples: ['Blue sea stretches far.'] },

  // Plants & Trees (25 words)
  { id: 'plant1', english: 'Tree', vietnamese: 'Cây', pronunciation: 'cay', category: 'plant', chapter: 'chapter12', difficulty: 1, examples: ['Old tree provides shade.'] },
  { id: 'plant2', english: 'Flower', vietnamese: 'Hoa', pronunciation: 'hoa', category: 'plant', chapter: 'chapter12', difficulty: 1, examples: ['Beautiful flower blooms.'] },
  { id: 'plant3', english: 'Grass', vietnamese: 'Cỏ', pronunciation: 'co', category: 'plant', chapter: 'chapter12', difficulty: 1, examples: ['Green grass grows.'] },
  { id: 'plant4', english: 'Leaf', vietnamese: 'Lá', pronunciation: 'la', category: 'plant', chapter: 'chapter12', difficulty: 1, examples: ['Autumn leaves fall.'] },
  { id: 'plant5', english: 'Branch', vietnamese: 'Cành', pronunciation: 'canh', category: 'plant', chapter: 'chapter12', difficulty: 1, examples: ['Bird sits on branch.'] },
  { id: 'plant6', english: 'Root', vietnamese: 'Rễ', pronunciation: 're', category: 'plant', chapter: 'chapter12', difficulty: 1, examples: ['Strong roots anchor tree.'] },
  { id: 'plant7', english: 'Trunk', vietnamese: 'Thân cây', pronunciation: 'than cay', category: 'plant', chapter: 'chapter12', difficulty: 1, examples: ['Thick tree trunk.'] },
  { id: 'plant8', english: 'Seed', vietnamese: 'Hạt giống', pronunciation: 'hat giong', category: 'plant', chapter: 'chapter12', difficulty: 1, examples: ['Plant seeds in spring.'] },
  { id: 'plant9', english: 'Fruit', vietnamese: 'Trái cây', pronunciation: 'trai cay', category: 'plant', chapter: 'chapter12', difficulty: 1, examples: ['Fresh fruit tastes good.'] },
  { id: 'plant10', english: 'Vegetable', vietnamese: 'Rau', pronunciation: 'rau', category: 'plant', chapter: 'chapter12', difficulty: 1, examples: ['Eat vegetables daily.'] },
  { id: 'plant11', english: 'Bush', vietnamese: 'Bụi cây', pronunciation: 'bui cay', category: 'plant', chapter: 'chapter12', difficulty: 1, examples: ['Rose bush has thorns.'] },
  { id: 'plant12', english: 'Vine', vietnamese: 'Dây leo', pronunciation: 'day leo', category: 'plant', chapter: 'chapter12', difficulty: 1, examples: ['Grape vine grows tall.'] },
  { id: 'plant13', english: 'Moss', vietnamese: 'Rêu', pronunciation: 'reu', category: 'plant', chapter: 'chapter12', difficulty: 1, examples: ['Green moss on rocks.'] },
  { id: 'plant14', english: 'Fern', vietnamese: 'Dương xỉ', pronunciation: 'duong xi', category: 'plant', chapter: 'chapter12', difficulty: 2, examples: ['Fern grows in shade.'] },
  { id: 'plant15', english: 'Pine', vietnamese: 'Thông', pronunciation: 'thong', category: 'plant', chapter: 'chapter12', difficulty: 1, examples: ['Pine tree stays green.'] },
  { id: 'plant16', english: 'Oak', vietnamese: 'Sồi', pronunciation: 'soi', category: 'plant', chapter: 'chapter12', difficulty: 1, examples: ['Strong oak tree.'] },
  { id: 'plant17', english: 'Palm', vietnamese: 'Cọ', pronunciation: 'co', category: 'plant', chapter: 'chapter12', difficulty: 1, examples: ['Palm tree on beach.'] },
  { id: 'plant18', english: 'Bamboo', vietnamese: 'Tre', pronunciation: 'tre', category: 'plant', chapter: 'chapter12', difficulty: 1, examples: ['Bamboo grows quickly.'] },
  { id: 'plant19', english: 'Cactus', vietnamese: 'Xương rồng', pronunciation: 'xuong rong', category: 'plant', chapter: 'chapter12', difficulty: 1, examples: ['Cactus needs little water.'] },
  { id: 'plant20', english: 'Rose', vietnamese: 'Hoa hồng', pronunciation: 'hoa hong', category: 'plant', chapter: 'chapter12', difficulty: 1, examples: ['Red rose smells sweet.'] },
  { id: 'plant21', english: 'Sunflower', vietnamese: 'Hướng dương', pronunciation: 'huong duong', category: 'plant', chapter: 'chapter12', difficulty: 1, examples: ['Sunflower follows sun.'] },
  { id: 'plant22', english: 'Tulip', vietnamese: 'Hoa tulip', pronunciation: 'hoa tulip', category: 'plant', chapter: 'chapter12', difficulty: 1, examples: ['Colorful tulip garden.'] },
  { id: 'plant23', english: 'Lily', vietnamese: 'Hoa lily', pronunciation: 'hoa lily', category: 'plant', chapter: 'chapter12', difficulty: 1, examples: ['White lily blooms.'] },
  { id: 'plant24', english: 'Daisy', vietnamese: 'Hoa cúc', pronunciation: 'hoa cuc', category: 'plant', chapter: 'chapter12', difficulty: 1, examples: ['Simple daisy flower.'] },
  { id: 'plant25', english: 'Orchid', vietnamese: 'Hoa lan', pronunciation: 'hoa lan', category: 'plant', chapter: 'chapter12', difficulty: 1, examples: ['Exotic orchid blooms.'] },

  // Animals & Environment (25 words)
  { id: 'animal1', english: 'Bird', vietnamese: 'Chim', pronunciation: 'chim', category: 'animal', chapter: 'chapter12', difficulty: 1, examples: ['Bird sings beautifully.'] },
  { id: 'animal2', english: 'Fish', vietnamese: 'Cá', pronunciation: 'ca', category: 'animal', chapter: 'chapter12', difficulty: 1, examples: ['Fish swim in river.'] },
  { id: 'animal3', english: 'Butterfly', vietnamese: 'Bướm', pronunciation: 'buom', category: 'animal', chapter: 'chapter12', difficulty: 1, examples: ['Colorful butterfly flies.'] },
  { id: 'animal4', english: 'Bee', vietnamese: 'Ong', pronunciation: 'ong', category: 'animal', chapter: 'chapter12', difficulty: 1, examples: ['Bee collects nectar.'] },
  { id: 'animal5', english: 'Ant', vietnamese: 'Kiến', pronunciation: 'kien', category: 'animal', chapter: 'chapter12', difficulty: 1, examples: ['Ant works hard.'] },
  { id: 'animal6', english: 'Spider', vietnamese: 'Nhện', pronunciation: 'nhen', category: 'animal', chapter: 'chapter12', difficulty: 1, examples: ['Spider builds web.'] },
  { id: 'animal7', english: 'Frog', vietnamese: 'Ếch', pronunciation: 'ech', category: 'animal', chapter: 'chapter12', difficulty: 1, examples: ['Frog jumps in pond.'] },
  { id: 'animal8', english: 'Snake', vietnamese: 'Rắn', pronunciation: 'ran', category: 'animal', chapter: 'chapter12', difficulty: 1, examples: ['Snake slithers silently.'] },
  { id: 'animal9', english: 'Lizard', vietnamese: 'Thằn lằn', pronunciation: 'than lan', category: 'animal', chapter: 'chapter12', difficulty: 1, examples: ['Lizard basks in sun.'] },
  { id: 'animal10', english: 'Turtle', vietnamese: 'Rùa', pronunciation: 'rua', category: 'animal', chapter: 'chapter12', difficulty: 1, examples: ['Turtle moves slowly.'] },
  { id: 'animal11', english: 'Rabbit', vietnamese: 'Thỏ', pronunciation: 'tho', category: 'animal', chapter: 'chapter12', difficulty: 1, examples: ['Rabbit hops quickly.'] },
  { id: 'animal12', english: 'Squirrel', vietnamese: 'Sóc', pronunciation: 'soc', category: 'animal', chapter: 'chapter12', difficulty: 1, examples: ['Squirrel gathers nuts.'] },
  { id: 'animal13', english: 'Deer', vietnamese: 'Hươu', pronunciation: 'huou', category: 'animal', chapter: 'chapter12', difficulty: 1, examples: ['Deer runs gracefully.'] },
  { id: 'animal14', english: 'Bear', vietnamese: 'Gấu', pronunciation: 'gau', category: 'animal', chapter: 'chapter12', difficulty: 1, examples: ['Bear hibernates in winter.'] },
  { id: 'animal15', english: 'Wolf', vietnamese: 'Sói', pronunciation: 'soi', category: 'animal', chapter: 'chapter12', difficulty: 1, examples: ['Wolf howls at moon.'] },
  { id: 'animal16', english: 'Fox', vietnamese: 'Cáo', pronunciation: 'cao', category: 'animal', chapter: 'chapter12', difficulty: 1, examples: ['Fox is very clever.'] },
  { id: 'animal17', english: 'Eagle', vietnamese: 'Đại bàng', pronunciation: 'dai bang', category: 'animal', chapter: 'chapter12', difficulty: 1, examples: ['Eagle soars high.'] },
  { id: 'animal18', english: 'Owl', vietnamese: 'Cú', pronunciation: 'cu', category: 'animal', chapter: 'chapter12', difficulty: 1, examples: ['Owl hunts at night.'] },
  { id: 'animal19', english: 'Dolphin', vietnamese: 'Cá heo', pronunciation: 'ca heo', category: 'animal', chapter: 'chapter12', difficulty: 1, examples: ['Dolphin is intelligent.'] },
  { id: 'animal20', english: 'Whale', vietnamese: 'Cá voi', pronunciation: 'ca voi', category: 'animal', chapter: 'chapter12', difficulty: 1, examples: ['Whale is largest mammal.'] },
  { id: 'animal21', english: 'Forest', vietnamese: 'Rừng', pronunciation: 'rung', category: 'environment', chapter: 'chapter12', difficulty: 1, examples: ['Dense forest has wildlife.'] },
  { id: 'animal22', english: 'Desert', vietnamese: 'Sa mạc', pronunciation: 'sa mac', category: 'environment', chapter: 'chapter12', difficulty: 1, examples: ['Desert is very dry.'] },
  { id: 'animal23', english: 'Beach', vietnamese: 'Bãi biển', pronunciation: 'bai bien', category: 'environment', chapter: 'chapter12', difficulty: 1, examples: ['Sandy beach feels warm.'] },
  { id: 'animal24', english: 'Island', vietnamese: 'Đảo', pronunciation: 'dao', category: 'environment', chapter: 'chapter12', difficulty: 1, examples: ['Tropical island paradise.'] },
  { id: 'animal25', english: 'Cave', vietnamese: 'Hang động', pronunciation: 'hang dong', category: 'environment', chapter: 'chapter12', difficulty: 1, examples: ['Dark cave is mysterious.'] }
]
