// Chapter 19: Work & Professions (100 Essential Words)
// Words related to work, careers, professions, and workplace terminology

import { LanguageWord } from './chapter01-basic-everyday'

export const chapter19Words: LanguageWord[] = [
  // General Work Terms (25 words)
  { id: 'work1', english: 'Work', vietnamese: 'Công việc', pronunciation: 'cong viec', category: 'work', chapter: 'chapter19', difficulty: 1, examples: ['Work starts eight.'] },
  { id: 'work2', english: 'Job', vietnamese: 'Nghề nghiệp', pronunciation: 'nghe nghiep', category: 'work', chapter: 'chapter19', difficulty: 1, examples: ['Job security important.'] },
  { id: 'work3', english: 'Career', vietnamese: 'Sự nghiệp', pronunciation: 'su nghiep', category: 'work', chapter: 'chapter19', difficulty: 1, examples: ['Career development crucial.'] },
  { id: 'work4', english: 'Profession', vietnamese: 'Nghề', pronunciation: 'nghe', category: 'work', chapter: 'chapter19', difficulty: 1, examples: ['Teaching noble profession.'] },
  { id: 'work5', english: 'Occupation', vietnamese: 'Nghề nghiệp', pronunciation: 'nghe nghiep', category: 'work', chapter: 'chapter19', difficulty: 1, examples: ['Occupation requires skills.'] },
  { id: 'work6', english: 'Employee', vietnamese: 'Nhân viên', pronunciation: 'nhan vien', category: 'work', chapter: 'chapter19', difficulty: 1, examples: ['Employee works diligently.'] },
  { id: 'work7', english: 'Employer', vietnamese: 'Nhà tuyển dụng', pronunciation: 'nha tuyen dung', category: 'work', chapter: 'chapter19', difficulty: 1, examples: ['Employer provides benefits.'] },
  { id: 'work8', english: 'Boss', vietnamese: 'Sếp', pronunciation: 'sep', category: 'work', chapter: 'chapter19', difficulty: 1, examples: ['Boss meeting today.'] },
  { id: 'work9', english: 'Manager', vietnamese: 'Quản lý', pronunciation: 'quan ly', category: 'work', chapter: 'chapter19', difficulty: 1, examples: ['Manager supervises team.'] },
  { id: 'work10', english: 'Supervisor', vietnamese: 'Giám sát viên', pronunciation: 'giam sat vien', category: 'work', chapter: 'chapter19', difficulty: 1, examples: ['Supervisor checks quality.'] },
  { id: 'work11', english: 'Director', vietnamese: 'Giám đốc', pronunciation: 'giam doc', category: 'work', chapter: 'chapter19', difficulty: 1, examples: ['Director makes decisions.'] },
  { id: 'work12', english: 'Executive', vietnamese: 'Điều hành', pronunciation: 'dieu hanh', category: 'work', chapter: 'chapter19', difficulty: 2, examples: ['Executive level position.'] },
  { id: 'work13', english: 'Assistant', vietnamese: 'Trợ lý', pronunciation: 'tro ly', category: 'work', chapter: 'chapter19', difficulty: 1, examples: ['Assistant helps daily.'] },
  { id: 'work14', english: 'Secretary', vietnamese: 'Thư ký', pronunciation: 'thu ky', category: 'work', chapter: 'chapter19', difficulty: 1, examples: ['Secretary schedules meetings.'] },
  { id: 'work15', english: 'Intern', vietnamese: 'Thực tập sinh', pronunciation: 'thuc tap sinh', category: 'work', chapter: 'chapter19', difficulty: 1, examples: ['Intern learns skills.'] },
  { id: 'work16', english: 'Trainee', vietnamese: 'Người tập sự', pronunciation: 'nguoi tap su', category: 'work', chapter: 'chapter19', difficulty: 1, examples: ['Trainee program comprehensive.'] },
  { id: 'work17', english: 'Colleague', vietnamese: 'Đồng nghiệp', pronunciation: 'dong nghiep', category: 'work', chapter: 'chapter19', difficulty: 1, examples: ['Colleague very helpful.'] },
  { id: 'work18', english: 'Coworker', vietnamese: 'Đồng nghiệp', pronunciation: 'dong nghiep', category: 'work', chapter: 'chapter19', difficulty: 1, examples: ['Coworker shares office.'] },
  { id: 'work19', english: 'Team', vietnamese: 'Đội', pronunciation: 'doi', category: 'work', chapter: 'chapter19', difficulty: 1, examples: ['Team works together.'] },
  { id: 'work20', english: 'Staff', vietnamese: 'Nhân viên', pronunciation: 'nhan vien', category: 'work', chapter: 'chapter19', difficulty: 1, examples: ['Staff meeting monthly.'] },
  { id: 'work21', english: 'Worker', vietnamese: 'Công nhân', pronunciation: 'cong nhan', category: 'work', chapter: 'chapter19', difficulty: 1, examples: ['Factory worker skilled.'] },
  { id: 'work22', english: 'Labor', vietnamese: 'Lao động', pronunciation: 'lao dong', category: 'work', chapter: 'chapter19', difficulty: 1, examples: ['Manual labor physical.'] },
  { id: 'work23', english: 'Employment', vietnamese: 'Việc làm', pronunciation: 'viec lam', category: 'work', chapter: 'chapter19', difficulty: 1, examples: ['Employment rate rising.'] },
  { id: 'work24', english: 'Unemployment', vietnamese: 'Thất nghiệp', pronunciation: 'that nghiep', category: 'work', chapter: 'chapter19', difficulty: 1, examples: ['Unemployment benefits temporary.'] },
  { id: 'work25', english: 'Freelancer', vietnamese: 'Làm việc tự do', pronunciation: 'lam viec tu do', category: 'work', chapter: 'chapter19', difficulty: 1, examples: ['Freelancer flexible schedule.'] },

  // Healthcare & Education (25 words)
  { id: 'healthcare1', english: 'Doctor', vietnamese: 'Bác sĩ', pronunciation: 'bac si', category: 'healthcare', chapter: 'chapter19', difficulty: 1, examples: ['Doctor examines patients.'] },
  { id: 'healthcare2', english: 'Nurse', vietnamese: 'Y tá', pronunciation: 'y ta', category: 'healthcare', chapter: 'chapter19', difficulty: 1, examples: ['Nurse cares compassionately.'] },
  { id: 'healthcare3', english: 'Surgeon', vietnamese: 'Bác sĩ phẫu thuật', pronunciation: 'bac si phau thuat', category: 'healthcare', chapter: 'chapter19', difficulty: 2, examples: ['Surgeon operates skillfully.'] },
  { id: 'healthcare4', english: 'Dentist', vietnamese: 'Nha sĩ', pronunciation: 'nha si', category: 'healthcare', chapter: 'chapter19', difficulty: 1, examples: ['Dentist cleans teeth.'] },
  { id: 'healthcare5', english: 'Pharmacist', vietnamese: 'Dược sĩ', pronunciation: 'duoc si', category: 'healthcare', chapter: 'chapter19', difficulty: 1, examples: ['Pharmacist dispenses medicine.'] },
  { id: 'healthcare6', english: 'Therapist', vietnamese: 'Chuyên gia trị liệu', pronunciation: 'chuyen gia tri lieu', category: 'healthcare', chapter: 'chapter19', difficulty: 2, examples: ['Therapist helps recovery.'] },
  { id: 'healthcare7', english: 'Psychologist', vietnamese: 'Nhà tâm lý học', pronunciation: 'nha tam ly hoc', category: 'healthcare', chapter: 'chapter19', difficulty: 2, examples: ['Psychologist counsels patients.'] },
  { id: 'healthcare8', english: 'Veterinarian', vietnamese: 'Bác sĩ thú y', pronunciation: 'bac si thu y', category: 'healthcare', chapter: 'chapter19', difficulty: 2, examples: ['Veterinarian treats animals.'] },
  { id: 'healthcare9', english: 'Teacher', vietnamese: 'Giáo viên', pronunciation: 'giao vien', category: 'healthcare', chapter: 'chapter19', difficulty: 1, examples: ['Teacher educates children.'] },
  { id: 'healthcare10', english: 'Professor', vietnamese: 'Giáo sư', pronunciation: 'giao su', category: 'healthcare', chapter: 'chapter19', difficulty: 1, examples: ['Professor conducts research.'] },
  { id: 'healthcare11', english: 'Instructor', vietnamese: 'Người hướng dẫn', pronunciation: 'nguoi huong dan', category: 'healthcare', chapter: 'chapter19', difficulty: 1, examples: ['Instructor explains clearly.'] },
  { id: 'healthcare12', english: 'Tutor', vietnamese: 'Gia sư', pronunciation: 'gia su', category: 'healthcare', chapter: 'chapter19', difficulty: 1, examples: ['Tutor helps homework.'] },
  { id: 'healthcare13', english: 'Principal', vietnamese: 'Hiệu trưởng', pronunciation: 'hieu truong', category: 'healthcare', chapter: 'chapter19', difficulty: 1, examples: ['Principal leads school.'] },
  { id: 'healthcare14', english: 'Librarian', vietnamese: 'Thủ thư', pronunciation: 'thu thu', category: 'healthcare', chapter: 'chapter19', difficulty: 1, examples: ['Librarian organizes books.'] },
  { id: 'healthcare15', english: 'Counselor', vietnamese: 'Cố vấn', pronunciation: 'co van', category: 'healthcare', chapter: 'chapter19', difficulty: 1, examples: ['Counselor provides guidance.'] },
  { id: 'healthcare16', english: 'Coach', vietnamese: 'Huấn luyện viên', pronunciation: 'huan luyen vien', category: 'healthcare', chapter: 'chapter19', difficulty: 1, examples: ['Coach trains athletes.'] },
  { id: 'healthcare17', english: 'Trainer', vietnamese: 'Người đào tạo', pronunciation: 'nguoi dao tao', category: 'healthcare', chapter: 'chapter19', difficulty: 1, examples: ['Trainer develops skills.'] },
  { id: 'healthcare18', english: 'Researcher', vietnamese: 'Nhà nghiên cứu', pronunciation: 'nha nghien cuu', category: 'healthcare', chapter: 'chapter19', difficulty: 2, examples: ['Researcher discovers facts.'] },
  { id: 'healthcare19', english: 'Scientist', vietnamese: 'Nhà khoa học', pronunciation: 'nha khoa hoc', category: 'healthcare', chapter: 'chapter19', difficulty: 1, examples: ['Scientist studies nature.'] },
  { id: 'healthcare20', english: 'Biologist', vietnamese: 'Nhà sinh vật học', pronunciation: 'nha sinh vat hoc', category: 'healthcare', chapter: 'chapter19', difficulty: 2, examples: ['Biologist studies life.'] },
  { id: 'healthcare21', english: 'Chemist', vietnamese: 'Nhà hóa học', pronunciation: 'nha hoa hoc', category: 'healthcare', chapter: 'chapter19', difficulty: 2, examples: ['Chemist analyzes compounds.'] },
  { id: 'healthcare22', english: 'Physicist', vietnamese: 'Nhà vật lý', pronunciation: 'nha vat ly', category: 'healthcare', chapter: 'chapter19', difficulty: 2, examples: ['Physicist studies matter.'] },
  { id: 'healthcare23', english: 'Mathematician', vietnamese: 'Nhà toán học', pronunciation: 'nha toan hoc', category: 'healthcare', chapter: 'chapter19', difficulty: 2, examples: ['Mathematician solves equations.'] },
  { id: 'healthcare24', english: 'Paramedic', vietnamese: 'Nhân viên cấp cứu', pronunciation: 'nhan vien cap cuu', category: 'healthcare', chapter: 'chapter19', difficulty: 2, examples: ['Paramedic saves lives.'] },
  { id: 'healthcare25', english: 'Social worker', vietnamese: 'Nhân viên xã hội', pronunciation: 'nhan vien xa hoi', category: 'healthcare', chapter: 'chapter19', difficulty: 2, examples: ['Social worker helps community.'] },

  // Business & Technology (25 words)
  { id: 'business1', english: 'Businessman', vietnamese: 'Doanh nhân', pronunciation: 'doanh nhan', category: 'business', chapter: 'chapter19', difficulty: 1, examples: ['Businessman successful entrepreneur.'] },
  { id: 'business2', english: 'Entrepreneur', vietnamese: 'Doanh nhân', pronunciation: 'doanh nhan', category: 'business', chapter: 'chapter19', difficulty: 2, examples: ['Entrepreneur starts companies.'] },
  { id: 'business3', english: 'Accountant', vietnamese: 'Kế toán', pronunciation: 'ke toan', category: 'business', chapter: 'chapter19', difficulty: 1, examples: ['Accountant manages finances.'] },
  { id: 'business4', english: 'Banker', vietnamese: 'Nhân viên ngân hàng', pronunciation: 'nhan vien ngan hang', category: 'business', chapter: 'chapter19', difficulty: 1, examples: ['Banker handles loans.'] },
  { id: 'business5', english: 'Investor', vietnamese: 'Nhà đầu tư', pronunciation: 'nha dau tu', category: 'business', chapter: 'chapter19', difficulty: 1, examples: ['Investor evaluates opportunities.'] },
  { id: 'business6', english: 'Consultant', vietnamese: 'Cố vấn', pronunciation: 'co van', category: 'business', chapter: 'chapter19', difficulty: 1, examples: ['Consultant provides expertise.'] },
  { id: 'business7', english: 'Analyst', vietnamese: 'Nhà phân tích', pronunciation: 'nha phan tich', category: 'business', chapter: 'chapter19', difficulty: 1, examples: ['Analyst studies data.'] },
  { id: 'business8', english: 'Sales representative', vietnamese: 'Đại diện bán hàng', pronunciation: 'dai dien ban hang', category: 'business', chapter: 'chapter19', difficulty: 1, examples: ['Sales representative meets clients.'] },
  { id: 'business9', english: 'Marketing manager', vietnamese: 'Quản lý tiếp thị', pronunciation: 'quan ly tiep thi', category: 'business', chapter: 'chapter19', difficulty: 2, examples: ['Marketing manager plans campaigns.'] },
  { id: 'business10', english: 'Customer service', vietnamese: 'Dịch vụ khách hàng', pronunciation: 'dich vu khach hang', category: 'business', chapter: 'chapter19', difficulty: 1, examples: ['Customer service helpful.'] },
  { id: 'business11', english: 'Programmer', vietnamese: 'Lập trình viên', pronunciation: 'lap trinh vien', category: 'business', chapter: 'chapter19', difficulty: 1, examples: ['Programmer writes code.'] },
  { id: 'business12', english: 'Developer', vietnamese: 'Nhà phát triển', pronunciation: 'nha phat trien', category: 'business', chapter: 'chapter19', difficulty: 1, examples: ['Developer creates software.'] },
  { id: 'business13', english: 'Engineer', vietnamese: 'Kỹ sư', pronunciation: 'ky su', category: 'business', chapter: 'chapter19', difficulty: 1, examples: ['Engineer designs systems.'] },
  { id: 'business14', english: 'Technician', vietnamese: 'Kỹ thuật viên', pronunciation: 'ky thuat vien', category: 'business', chapter: 'chapter19', difficulty: 1, examples: ['Technician repairs equipment.'] },
  { id: 'business15', english: 'Architect', vietnamese: 'Kiến trúc sư', pronunciation: 'kien truc su', category: 'business', chapter: 'chapter19', difficulty: 1, examples: ['Architect designs buildings.'] },
  { id: 'business16', english: 'Designer', vietnamese: 'Nhà thiết kế', pronunciation: 'nha thiet ke', category: 'business', chapter: 'chapter19', difficulty: 1, examples: ['Designer creates graphics.'] },
  { id: 'business17', english: 'Artist', vietnamese: 'Nghệ sĩ', pronunciation: 'nghe si', category: 'business', chapter: 'chapter19', difficulty: 1, examples: ['Artist paints beautifully.'] },
  { id: 'business18', english: 'Photographer', vietnamese: 'Nhiếp ảnh gia', pronunciation: 'nhiep anh gia', category: 'business', chapter: 'chapter19', difficulty: 1, examples: ['Photographer captures moments.'] },
  { id: 'business19', english: 'Writer', vietnamese: 'Nhà văn', pronunciation: 'nha van', category: 'business', chapter: 'chapter19', difficulty: 1, examples: ['Writer publishes books.'] },
  { id: 'business20', english: 'Journalist', vietnamese: 'Nhà báo', pronunciation: 'nha bao', category: 'business', chapter: 'chapter19', difficulty: 1, examples: ['Journalist reports news.'] },
  { id: 'business21', english: 'Editor', vietnamese: 'Biên tập viên', pronunciation: 'bien tap vien', category: 'business', chapter: 'chapter19', difficulty: 1, examples: ['Editor reviews articles.'] },
  { id: 'business22', english: 'Publisher', vietnamese: 'Nhà xuất bản', pronunciation: 'nha xuat ban', category: 'business', chapter: 'chapter19', difficulty: 2, examples: ['Publisher prints books.'] },
  { id: 'business23', english: 'Translator', vietnamese: 'Dịch giả', pronunciation: 'dich gia', category: 'business', chapter: 'chapter19', difficulty: 1, examples: ['Translator converts languages.'] },
  { id: 'business24', english: 'Interpreter', vietnamese: 'Thông dịch viên', pronunciation: 'thong dich vien', category: 'business', chapter: 'chapter19', difficulty: 2, examples: ['Interpreter facilitates communication.'] },
  { id: 'business25', english: 'Administrator', vietnamese: 'Quản trị viên', pronunciation: 'quan tri vien', category: 'business', chapter: 'chapter19', difficulty: 1, examples: ['Administrator manages systems.'] },

  // Service & Trade (25 words)
  { id: 'service1', english: 'Chef', vietnamese: 'Đầu bếp', pronunciation: 'dau bep', category: 'service', chapter: 'chapter19', difficulty: 1, examples: ['Chef cooks delicious.'] },
  { id: 'service2', english: 'Waiter', vietnamese: 'Phục vụ bàn', pronunciation: 'phuc vu ban', category: 'service', chapter: 'chapter19', difficulty: 1, examples: ['Waiter serves food.'] },
  { id: 'service3', english: 'Waitress', vietnamese: 'Nữ phục vụ', pronunciation: 'nu phuc vu', category: 'service', chapter: 'chapter19', difficulty: 1, examples: ['Waitress takes orders.'] },
  { id: 'service4', english: 'Bartender', vietnamese: 'Pha chế', pronunciation: 'pha che', category: 'service', chapter: 'chapter19', difficulty: 1, examples: ['Bartender mixes drinks.'] },
  { id: 'service5', english: 'Cashier', vietnamese: 'Thu ngân', pronunciation: 'thu ngan', category: 'service', chapter: 'chapter19', difficulty: 1, examples: ['Cashier handles payments.'] },
  { id: 'service6', english: 'Salesperson', vietnamese: 'Nhân viên bán hàng', pronunciation: 'nhan vien ban hang', category: 'service', chapter: 'chapter19', difficulty: 1, examples: ['Salesperson helps customers.'] },
  { id: 'service7', english: 'Receptionist', vietnamese: 'Lễ tân', pronunciation: 'le tan', category: 'service', chapter: 'chapter19', difficulty: 1, examples: ['Receptionist greets visitors.'] },
  { id: 'service8', english: 'Security guard', vietnamese: 'Bảo vệ', pronunciation: 'bao ve', category: 'service', chapter: 'chapter19', difficulty: 1, examples: ['Security guard protects.'] },
  { id: 'service9', english: 'Cleaner', vietnamese: 'Người dọn dẹp', pronunciation: 'nguoi don dep', category: 'service', chapter: 'chapter19', difficulty: 1, examples: ['Cleaner maintains hygiene.'] },
  { id: 'service10', english: 'Janitor', vietnamese: 'Người gác cổng', pronunciation: 'nguoi gac cong', category: 'service', chapter: 'chapter19', difficulty: 1, examples: ['Janitor cleans building.'] },
  { id: 'service11', english: 'Hairdresser', vietnamese: 'Thợ cắt tóc', pronunciation: 'tho cat toc', category: 'service', chapter: 'chapter19', difficulty: 1, examples: ['Hairdresser styles hair.'] },
  { id: 'service12', english: 'Barber', vietnamese: 'Thợ cạo', pronunciation: 'tho cao', category: 'service', chapter: 'chapter19', difficulty: 1, examples: ['Barber cuts hair.'] },
  { id: 'service13', english: 'Mechanic', vietnamese: 'Thợ máy', pronunciation: 'tho may', category: 'service', chapter: 'chapter19', difficulty: 1, examples: ['Mechanic repairs cars.'] },
  { id: 'service14', english: 'Electrician', vietnamese: 'Thợ điện', pronunciation: 'tho dien', category: 'service', chapter: 'chapter19', difficulty: 1, examples: ['Electrician fixes wiring.'] },
  { id: 'service15', english: 'Plumber', vietnamese: 'Thợ sửa ống nước', pronunciation: 'tho sua ong nuoc', category: 'service', chapter: 'chapter19', difficulty: 1, examples: ['Plumber repairs pipes.'] },
  { id: 'service16', english: 'Carpenter', vietnamese: 'Thợ mộc', pronunciation: 'tho moc', category: 'service', chapter: 'chapter19', difficulty: 1, examples: ['Carpenter builds furniture.'] },
  { id: 'service17', english: 'Painter', vietnamese: 'Thợ sơn', pronunciation: 'tho son', category: 'service', chapter: 'chapter19', difficulty: 1, examples: ['Painter decorates walls.'] },
  { id: 'service18', english: 'Driver', vietnamese: 'Tài xế', pronunciation: 'tai xe', category: 'service', chapter: 'chapter19', difficulty: 1, examples: ['Driver transports safely.'] },
  { id: 'service19', english: 'Pilot', vietnamese: 'Phi công', pronunciation: 'phi cong', category: 'service', chapter: 'chapter19', difficulty: 1, examples: ['Pilot flies aircraft.'] },
  { id: 'service20', english: 'Flight attendant', vietnamese: 'Tiếp viên hàng không', pronunciation: 'tiep vien hang khong', category: 'service', chapter: 'chapter19', difficulty: 2, examples: ['Flight attendant serves passengers.'] },
  { id: 'service21', english: 'Police officer', vietnamese: 'Cảnh sát', pronunciation: 'canh sat', category: 'service', chapter: 'chapter19', difficulty: 1, examples: ['Police officer maintains order.'] },
  { id: 'service22', english: 'Firefighter', vietnamese: 'Lính cứu hỏa', pronunciation: 'linh cuu hoa', category: 'service', chapter: 'chapter19', difficulty: 1, examples: ['Firefighter saves lives.'] },
  { id: 'service23', english: 'Soldier', vietnamese: 'Lính', pronunciation: 'linh', category: 'service', chapter: 'chapter19', difficulty: 1, examples: ['Soldier defends country.'] },
  { id: 'service24', english: 'Postman', vietnamese: 'Người đưa thư', pronunciation: 'nguoi dua thu', category: 'service', chapter: 'chapter19', difficulty: 1, examples: ['Postman delivers mail.'] },
  { id: 'service25', english: 'Farmer', vietnamese: 'Nông dân', pronunciation: 'nong dan', category: 'service', chapter: 'chapter19', difficulty: 1, examples: ['Farmer grows crops.'] }
]
