// Chapter 22: Numbers & Mathematics (100 Essential Words)
// Words related to numbers, counting, mathematics, and calculations

import { LanguageWord } from './chapter01-basic-everyday'

export const chapter22Words: LanguageWord[] = [
  // Basic Numbers (25 words)
  { id: 'numbers1', english: 'Number', vietnamese: 'Số', pronunciation: 'so', category: 'numbers', chapter: 'chapter22', difficulty: 1, examples: ['Number sequence order.'] },
  { id: 'numbers2', english: 'Zero', vietnamese: 'Số không', pronunciation: 'so khong', category: 'numbers', chapter: 'chapter22', difficulty: 1, examples: ['Zero means nothing.'] },
  { id: 'numbers3', english: 'One', vietnamese: 'Một', pronunciation: 'mot', category: 'numbers', chapter: 'chapter22', difficulty: 1, examples: ['One apple red.'] },
  { id: 'numbers4', english: 'Two', vietnamese: 'Hai', pronunciation: 'hai', category: 'numbers', chapter: 'chapter22', difficulty: 1, examples: ['Two eyes see.'] },
  { id: 'numbers5', english: 'Three', vietnamese: 'Ba', pronunciation: 'ba', category: 'numbers', chapter: 'chapter22', difficulty: 1, examples: ['Three wheels bicycle.'] },
  { id: 'numbers6', english: 'Four', vietnamese: 'Bốn', pronunciation: 'bon', category: 'numbers', chapter: 'chapter22', difficulty: 1, examples: ['Four legs table.'] },
  { id: 'numbers7', english: 'Five', vietnamese: 'Năm', pronunciation: 'nam', category: 'numbers', chapter: 'chapter22', difficulty: 1, examples: ['Five fingers hand.'] },
  { id: 'numbers8', english: 'Six', vietnamese: 'Sáu', pronunciation: 'sau', category: 'numbers', chapter: 'chapter22', difficulty: 1, examples: ['Six days week.'] },
  { id: 'numbers9', english: 'Seven', vietnamese: 'Bảy', pronunciation: 'bay', category: 'numbers', chapter: 'chapter22', difficulty: 1, examples: ['Seven colors rainbow.'] },
  { id: 'numbers10', english: 'Eight', vietnamese: 'Tám', pronunciation: 'tam', category: 'numbers', chapter: 'chapter22', difficulty: 1, examples: ['Eight hours work.'] },
  { id: 'numbers11', english: 'Nine', vietnamese: 'Chín', pronunciation: 'chin', category: 'numbers', chapter: 'chapter22', difficulty: 1, examples: ['Nine months pregnancy.'] },
  { id: 'numbers12', english: 'Ten', vietnamese: 'Mười', pronunciation: 'muoi', category: 'numbers', chapter: 'chapter22', difficulty: 1, examples: ['Ten toes feet.'] },
  { id: 'numbers13', english: 'Eleven', vietnamese: 'Mười một', pronunciation: 'muoi mot', category: 'numbers', chapter: 'chapter22', difficulty: 1, examples: ['Eleven players team.'] },
  { id: 'numbers14', english: 'Twelve', vietnamese: 'Mười hai', pronunciation: 'muoi hai', category: 'numbers', chapter: 'chapter22', difficulty: 1, examples: ['Twelve months year.'] },
  { id: 'numbers15', english: 'Twenty', vietnamese: 'Hai mười', pronunciation: 'hai muoi', category: 'numbers', chapter: 'chapter22', difficulty: 1, examples: ['Twenty years old.'] },
  { id: 'numbers16', english: 'Thirty', vietnamese: 'Ba mười', pronunciation: 'ba muoi', category: 'numbers', chapter: 'chapter22', difficulty: 1, examples: ['Thirty days month.'] },
  { id: 'numbers17', english: 'Fifty', vietnamese: 'Năm mười', pronunciation: 'nam muoi', category: 'numbers', chapter: 'chapter22', difficulty: 1, examples: ['Fifty states America.'] },
  { id: 'numbers18', english: 'Hundred', vietnamese: 'Một trăm', pronunciation: 'mot tram', category: 'numbers', chapter: 'chapter22', difficulty: 1, examples: ['Hundred percent complete.'] },
  { id: 'numbers19', english: 'Thousand', vietnamese: 'Một nghìn', pronunciation: 'mot nghin', category: 'numbers', chapter: 'chapter22', difficulty: 1, examples: ['Thousand dollars expensive.'] },
  { id: 'numbers20', english: 'Million', vietnamese: 'Một triệu', pronunciation: 'mot trieu', category: 'numbers', chapter: 'chapter22', difficulty: 1, examples: ['Million people city.'] },
  { id: 'numbers21', english: 'First', vietnamese: 'Thứ nhất', pronunciation: 'thu nhat', category: 'numbers', chapter: 'chapter22', difficulty: 1, examples: ['First place winner.'] },
  { id: 'numbers22', english: 'Second', vietnamese: 'Thứ hai', pronunciation: 'thu hai', category: 'numbers', chapter: 'chapter22', difficulty: 1, examples: ['Second chance opportunity.'] },
  { id: 'numbers23', english: 'Third', vietnamese: 'Thứ ba', pronunciation: 'thu ba', category: 'numbers', chapter: 'chapter22', difficulty: 1, examples: ['Third time lucky.'] },
  { id: 'numbers24', english: 'Last', vietnamese: 'Cuối cùng', pronunciation: 'cuoi cung', category: 'numbers', chapter: 'chapter22', difficulty: 1, examples: ['Last person line.'] },
  { id: 'numbers25', english: 'Half', vietnamese: 'Một nửa', pronunciation: 'mot nua', category: 'numbers', chapter: 'chapter22', difficulty: 1, examples: ['Half apple eaten.'] },

  // Mathematical Operations (25 words)
  { id: 'math1', english: 'Mathematics', vietnamese: 'Toán học', pronunciation: 'toan hoc', category: 'math', chapter: 'chapter22', difficulty: 1, examples: ['Mathematics logical subject.'] },
  { id: 'math2', english: 'Addition', vietnamese: 'Phép cộng', pronunciation: 'phep cong', category: 'math', chapter: 'chapter22', difficulty: 1, examples: ['Addition increases total.'] },
  { id: 'math3', english: 'Subtraction', vietnamese: 'Phép trừ', pronunciation: 'phep tru', category: 'math', chapter: 'chapter22', difficulty: 1, examples: ['Subtraction decreases amount.'] },
  { id: 'math4', english: 'Multiplication', vietnamese: 'Phép nhân', pronunciation: 'phep nhan', category: 'math', chapter: 'chapter22', difficulty: 1, examples: ['Multiplication repeated addition.'] },
  { id: 'math5', english: 'Division', vietnamese: 'Phép chia', pronunciation: 'phep chia', category: 'math', chapter: 'chapter22', difficulty: 1, examples: ['Division splits equally.'] },
  { id: 'math6', english: 'Plus', vietnamese: 'Cộng', pronunciation: 'cong', category: 'math', chapter: 'chapter22', difficulty: 1, examples: ['Two plus three.'] },
  { id: 'math7', english: 'Minus', vietnamese: 'Trừ', pronunciation: 'tru', category: 'math', chapter: 'chapter22', difficulty: 1, examples: ['Five minus two.'] },
  { id: 'math8', english: 'Times', vietnamese: 'Nhân', pronunciation: 'nhan', category: 'math', chapter: 'chapter22', difficulty: 1, examples: ['Three times four.'] },
  { id: 'math9', english: 'Divided by', vietnamese: 'Chia cho', pronunciation: 'chia cho', category: 'math', chapter: 'chapter22', difficulty: 1, examples: ['Ten divided two.'] },
  { id: 'math10', english: 'Equals', vietnamese: 'Bằng', pronunciation: 'bang', category: 'math', chapter: 'chapter22', difficulty: 1, examples: ['Two plus two equals.'] },
  { id: 'math11', english: 'Sum', vietnamese: 'Tổng', pronunciation: 'tong', category: 'math', chapter: 'chapter22', difficulty: 1, examples: ['Sum all numbers.'] },
  { id: 'math12', english: 'Difference', vietnamese: 'Hiệu', pronunciation: 'hieu', category: 'math', chapter: 'chapter22', difficulty: 1, examples: ['Difference between numbers.'] },
  { id: 'math13', english: 'Product', vietnamese: 'Tích', pronunciation: 'tich', category: 'math', chapter: 'chapter22', difficulty: 1, examples: ['Product two numbers.'] },
  { id: 'math14', english: 'Quotient', vietnamese: 'Thương', pronunciation: 'thuong', category: 'math', chapter: 'chapter22', difficulty: 2, examples: ['Quotient division result.'] },
  { id: 'math15', english: 'Remainder', vietnamese: 'Số dư', pronunciation: 'so du', category: 'math', chapter: 'chapter22', difficulty: 1, examples: ['Remainder after division.'] },
  { id: 'math16', english: 'Fraction', vietnamese: 'Phân số', pronunciation: 'phan so', category: 'math', chapter: 'chapter22', difficulty: 1, examples: ['Fraction part whole.'] },
  { id: 'math17', english: 'Decimal', vietnamese: 'Số thập phân', pronunciation: 'so thap phan', category: 'math', chapter: 'chapter22', difficulty: 1, examples: ['Decimal point separates.'] },
  { id: 'math18', english: 'Percentage', vietnamese: 'Phần trăm', pronunciation: 'phan tram', category: 'math', chapter: 'chapter22', difficulty: 1, examples: ['Percentage out hundred.'] },
  { id: 'math19', english: 'Average', vietnamese: 'Trung bình', pronunciation: 'trung binh', category: 'math', chapter: 'chapter22', difficulty: 1, examples: ['Average middle value.'] },
  { id: 'math20', english: 'Total', vietnamese: 'Tổng cộng', pronunciation: 'tong cong', category: 'math', chapter: 'chapter22', difficulty: 1, examples: ['Total cost expensive.'] },
  { id: 'math21', english: 'Calculate', vietnamese: 'Tính toán', pronunciation: 'tinh toan', category: 'math', chapter: 'chapter22', difficulty: 1, examples: ['Calculate final answer.'] },
  { id: 'math22', english: 'Solve', vietnamese: 'Giải', pronunciation: 'giai', category: 'math', chapter: 'chapter22', difficulty: 1, examples: ['Solve math problem.'] },
  { id: 'math23', english: 'Formula', vietnamese: 'Công thức', pronunciation: 'cong thuc', category: 'math', chapter: 'chapter22', difficulty: 1, examples: ['Formula solves equations.'] },
  { id: 'math24', english: 'Equation', vietnamese: 'Phương trình', pronunciation: 'phuong trinh', category: 'math', chapter: 'chapter22', difficulty: 2, examples: ['Equation mathematical statement.'] },
  { id: 'math25', english: 'Problem', vietnamese: 'Bài toán', pronunciation: 'bai toan', category: 'math', chapter: 'chapter22', difficulty: 1, examples: ['Problem requires solution.'] },

  // Measurement & Quantities (25 words)
  { id: 'measurement1', english: 'Measurement', vietnamese: 'Đo lường', pronunciation: 'do luong', category: 'measurement', chapter: 'chapter22', difficulty: 1, examples: ['Measurement accurate important.'] },
  { id: 'measurement2', english: 'Length', vietnamese: 'Chiều dài', pronunciation: 'chieu dai', category: 'measurement', chapter: 'chapter22', difficulty: 1, examples: ['Length measures distance.'] },
  { id: 'measurement3', english: 'Width', vietnamese: 'Chiều rộng', pronunciation: 'chieu rong', category: 'measurement', chapter: 'chapter22', difficulty: 1, examples: ['Width measures across.'] },
  { id: 'measurement4', english: 'Height', vietnamese: 'Chiều cao', pronunciation: 'chieu cao', category: 'measurement', chapter: 'chapter22', difficulty: 1, examples: ['Height measures tall.'] },
  { id: 'measurement5', english: 'Weight', vietnamese: 'Cân nặng', pronunciation: 'can nang', category: 'measurement', chapter: 'chapter22', difficulty: 1, examples: ['Weight measures heaviness.'] },
  { id: 'measurement6', english: 'Area', vietnamese: 'Diện tích', pronunciation: 'dien tich', category: 'measurement', chapter: 'chapter22', difficulty: 1, examples: ['Area measures surface.'] },
  { id: 'measurement7', english: 'Volume', vietnamese: 'Thể tích', pronunciation: 'the tich', category: 'measurement', chapter: 'chapter22', difficulty: 1, examples: ['Volume measures space.'] },
  { id: 'measurement8', english: 'Distance', vietnamese: 'Khoảng cách', pronunciation: 'khoang cach', category: 'measurement', chapter: 'chapter22', difficulty: 1, examples: ['Distance between points.'] },
  { id: 'measurement9', english: 'Speed', vietnamese: 'Tốc độ', pronunciation: 'toc do', category: 'measurement', chapter: 'chapter22', difficulty: 1, examples: ['Speed measures velocity.'] },
  { id: 'measurement10', english: 'Temperature', vietnamese: 'Nhiệt độ', pronunciation: 'nhiet do', category: 'measurement', chapter: 'chapter22', difficulty: 1, examples: ['Temperature measures heat.'] },
  { id: 'measurement11', english: 'Meter', vietnamese: 'Mét', pronunciation: 'met', category: 'measurement', chapter: 'chapter22', difficulty: 1, examples: ['Meter unit length.'] },
  { id: 'measurement12', english: 'Centimeter', vietnamese: 'Xăng-ti-mét', pronunciation: 'xang-ti-met', category: 'measurement', chapter: 'chapter22', difficulty: 1, examples: ['Centimeter small measure.'] },
  { id: 'measurement13', english: 'Kilometer', vietnamese: 'Ki-lô-mét', pronunciation: 'ki-lo-met', category: 'measurement', chapter: 'chapter22', difficulty: 1, examples: ['Kilometer long distance.'] },
  { id: 'measurement14', english: 'Gram', vietnamese: 'Gam', pronunciation: 'gam', category: 'measurement', chapter: 'chapter22', difficulty: 1, examples: ['Gram unit weight.'] },
  { id: 'measurement15', english: 'Kilogram', vietnamese: 'Ki-lô-gam', pronunciation: 'ki-lo-gam', category: 'measurement', chapter: 'chapter22', difficulty: 1, examples: ['Kilogram heavy weight.'] },
  { id: 'measurement16', english: 'Liter', vietnamese: 'Lít', pronunciation: 'lit', category: 'measurement', chapter: 'chapter22', difficulty: 1, examples: ['Liter unit volume.'] },
  { id: 'measurement17', english: 'Inch', vietnamese: 'Inch', pronunciation: 'inch', category: 'measurement', chapter: 'chapter22', difficulty: 1, examples: ['Inch English measure.'] },
  { id: 'measurement18', english: 'Foot', vietnamese: 'Foot', pronunciation: 'foot', category: 'measurement', chapter: 'chapter22', difficulty: 1, examples: ['Foot twelve inches.'] },
  { id: 'measurement19', english: 'Pound', vietnamese: 'Pound', pronunciation: 'pound', category: 'measurement', chapter: 'chapter22', difficulty: 1, examples: ['Pound weight unit.'] },
  { id: 'measurement20', english: 'Gallon', vietnamese: 'Gallon', pronunciation: 'gallon', category: 'measurement', chapter: 'chapter22', difficulty: 1, examples: ['Gallon liquid measure.'] },
  { id: 'measurement21', english: 'Degree', vietnamese: 'Độ', pronunciation: 'do', category: 'measurement', chapter: 'chapter22', difficulty: 1, examples: ['Degree temperature unit.'] },
  { id: 'measurement22', english: 'Scale', vietnamese: 'Thang đo', pronunciation: 'thang do', category: 'measurement', chapter: 'chapter22', difficulty: 1, examples: ['Scale measures weight.'] },
  { id: 'measurement23', english: 'Ruler', vietnamese: 'Thước kẻ', pronunciation: 'thuoc ke', category: 'measurement', chapter: 'chapter22', difficulty: 1, examples: ['Ruler measures length.'] },
  { id: 'measurement24', english: 'Calculator', vietnamese: 'Máy tính', pronunciation: 'may tinh', category: 'measurement', chapter: 'chapter22', difficulty: 1, examples: ['Calculator computes numbers.'] },
  { id: 'measurement25', english: 'Counter', vietnamese: 'Bộ đếm', pronunciation: 'bo dem', category: 'measurement', chapter: 'chapter22', difficulty: 1, examples: ['Counter tracks numbers.'] },

  // Money & Financial Terms (25 words)
  { id: 'money1', english: 'Money', vietnamese: 'Tiền', pronunciation: 'tien', category: 'money', chapter: 'chapter22', difficulty: 1, examples: ['Money buys things.'] },
  { id: 'money2', english: 'Cash', vietnamese: 'Tiền mặt', pronunciation: 'tien mat', category: 'money', chapter: 'chapter22', difficulty: 1, examples: ['Cash payment immediate.'] },
  { id: 'money3', english: 'Coin', vietnamese: 'Đồng xu', pronunciation: 'dong xu', category: 'money', chapter: 'chapter22', difficulty: 1, examples: ['Coin metal money.'] },
  { id: 'money4', english: 'Bill', vietnamese: 'Tờ tiền', pronunciation: 'to tien', category: 'money', chapter: 'chapter22', difficulty: 1, examples: ['Bill paper money.'] },
  { id: 'money5', english: 'Dollar', vietnamese: 'Đô-la', pronunciation: 'do-la', category: 'money', chapter: 'chapter22', difficulty: 1, examples: ['Dollar American currency.'] },
  { id: 'money6', english: 'Cent', vietnamese: 'Xu', pronunciation: 'xu', category: 'money', chapter: 'chapter22', difficulty: 1, examples: ['Cent small coin.'] },
  { id: 'money7', english: 'Price', vietnamese: 'Giá', pronunciation: 'gia', category: 'money', chapter: 'chapter22', difficulty: 1, examples: ['Price too expensive.'] },
  { id: 'money8', english: 'Cost', vietnamese: 'Chi phí', pronunciation: 'chi phi', category: 'money', chapter: 'chapter22', difficulty: 1, examples: ['Cost includes tax.'] },
  { id: 'money9', english: 'Expensive', vietnamese: 'Đắt', pronunciation: 'dat', category: 'money', chapter: 'chapter22', difficulty: 1, examples: ['Car very expensive.'] },
  { id: 'money10', english: 'Cheap', vietnamese: 'Rẻ', pronunciation: 're', category: 'money', chapter: 'chapter22', difficulty: 1, examples: ['Food relatively cheap.'] },
  { id: 'money11', english: 'Free', vietnamese: 'Miễn phí', pronunciation: 'mien phi', category: 'money', chapter: 'chapter22', difficulty: 1, examples: ['Water bottle free.'] },
  { id: 'money12', english: 'Discount', vietnamese: 'Giảm giá', pronunciation: 'giam gia', category: 'money', chapter: 'chapter22', difficulty: 1, examples: ['Discount saves money.'] },
  { id: 'money13', english: 'Sale', vietnamese: 'Giảm giá', pronunciation: 'giam gia', category: 'money', chapter: 'chapter22', difficulty: 1, examples: ['Sale prices lower.'] },
  { id: 'money14', english: 'Tax', vietnamese: 'Thuế', pronunciation: 'thue', category: 'money', chapter: 'chapter22', difficulty: 1, examples: ['Tax government collects.'] },
  { id: 'money15', english: 'Change', vietnamese: 'Tiền thối', pronunciation: 'tien thoi', category: 'money', chapter: 'chapter22', difficulty: 1, examples: ['Change returned customer.'] },
  { id: 'money16', english: 'Receipt', vietnamese: 'Hóa đơn', pronunciation: 'hoa don', category: 'money', chapter: 'chapter22', difficulty: 1, examples: ['Receipt proves purchase.'] },
  { id: 'money17', english: 'Bank', vietnamese: 'Ngân hàng', pronunciation: 'ngan hang', category: 'money', chapter: 'chapter22', difficulty: 1, examples: ['Bank stores money.'] },
  { id: 'money18', english: 'Account', vietnamese: 'Tài khoản', pronunciation: 'tai khoan', category: 'money', chapter: 'chapter22', difficulty: 1, examples: ['Account holds funds.'] },
  { id: 'money19', english: 'Deposit', vietnamese: 'Gửi tiền', pronunciation: 'gui tien', category: 'money', chapter: 'chapter22', difficulty: 1, examples: ['Deposit money bank.'] },
  { id: 'money20', english: 'Withdraw', vietnamese: 'Rút tiền', pronunciation: 'rut tien', category: 'money', chapter: 'chapter22', difficulty: 1, examples: ['Withdraw cash ATM.'] },
  { id: 'money21', english: 'Credit card', vietnamese: 'Thẻ tín dụng', pronunciation: 'the tin dung', category: 'money', chapter: 'chapter22', difficulty: 1, examples: ['Credit card convenient.'] },
  { id: 'money22', english: 'Loan', vietnamese: 'Vay', pronunciation: 'vay', category: 'money', chapter: 'chapter22', difficulty: 1, examples: ['Loan helps purchase.'] },
  { id: 'money23', english: 'Interest', vietnamese: 'Lãi suất', pronunciation: 'lai suat', category: 'money', chapter: 'chapter22', difficulty: 1, examples: ['Interest earns money.'] },
  { id: 'money24', english: 'Budget', vietnamese: 'Ngân sách', pronunciation: 'ngan sach', category: 'money', chapter: 'chapter22', difficulty: 1, examples: ['Budget plans spending.'] },
  { id: 'money25', english: 'Savings', vietnamese: 'Tiết kiệm', pronunciation: 'tiet kiem', category: 'money', chapter: 'chapter22', difficulty: 1, examples: ['Savings secure future.'] }
]
