// Chapter 20: Relationships & Social Life (100 Essential Words)
// Words related to family, friends, relationships, and social interactions

import { LanguageWord } from './chapter01-basic-everyday'

export const chapter20Words: LanguageWord[] = [
  // Family Relationships (25 words)
  { id: 'family1', english: 'Family', vietnamese: 'Gia đình', pronunciation: 'gia dinh', category: 'family', chapter: 'chapter20', difficulty: 1, examples: ['Family dinner together.'] },
  { id: 'family2', english: 'Parents', vietnamese: 'Bố mẹ', pronunciation: 'bo me', category: 'family', chapter: 'chapter20', difficulty: 1, examples: ['Parents love children.'] },
  { id: 'family3', english: 'Father', vietnamese: 'Bố', pronunciation: 'bo', category: 'family', chapter: 'chapter20', difficulty: 1, examples: ['Father works hard.'] },
  { id: 'family4', english: 'Mother', vietnamese: 'Mẹ', pronunciation: 'me', category: 'family', chapter: 'chapter20', difficulty: 1, examples: ['Mother cooks delicious.'] },
  { id: 'family5', english: 'Son', vietnamese: 'Con trai', pronunciation: 'con trai', category: 'family', chapter: 'chapter20', difficulty: 1, examples: ['Son plays football.'] },
  { id: 'family6', english: 'Daughter', vietnamese: 'Con gái', pronunciation: 'con gai', category: 'family', chapter: 'chapter20', difficulty: 1, examples: ['Daughter studies hard.'] },
  { id: 'family7', english: 'Brother', vietnamese: 'Anh/Em trai', pronunciation: 'anh/em trai', category: 'family', chapter: 'chapter20', difficulty: 1, examples: ['Brother helps sister.'] },
  { id: 'family8', english: 'Sister', vietnamese: 'Chị/Em gái', pronunciation: 'chi/em gai', category: 'family', chapter: 'chapter20', difficulty: 1, examples: ['Sister shares room.'] },
  { id: 'family9', english: 'Grandfather', vietnamese: 'Ông', pronunciation: 'ong', category: 'family', chapter: 'chapter20', difficulty: 1, examples: ['Grandfather tells stories.'] },
  { id: 'family10', english: 'Grandmother', vietnamese: 'Bà', pronunciation: 'ba', category: 'family', chapter: 'chapter20', difficulty: 1, examples: ['Grandmother bakes cookies.'] },
  { id: 'family11', english: 'Uncle', vietnamese: 'Chú/Bác', pronunciation: 'chu/bac', category: 'family', chapter: 'chapter20', difficulty: 1, examples: ['Uncle visits weekends.'] },
  { id: 'family12', english: 'Aunt', vietnamese: 'Cô/Dì', pronunciation: 'co/di', category: 'family', chapter: 'chapter20', difficulty: 1, examples: ['Aunt brings gifts.'] },
  { id: 'family13', english: 'Cousin', vietnamese: 'Anh/Chị/Em họ', pronunciation: 'anh/chi/em ho', category: 'family', chapter: 'chapter20', difficulty: 1, examples: ['Cousin same age.'] },
  { id: 'family14', english: 'Nephew', vietnamese: 'Cháu trai', pronunciation: 'chau trai', category: 'family', chapter: 'chapter20', difficulty: 1, examples: ['Nephew very smart.'] },
  { id: 'family15', english: 'Niece', vietnamese: 'Cháu gái', pronunciation: 'chau gai', category: 'family', chapter: 'chapter20', difficulty: 1, examples: ['Niece loves dancing.'] },
  { id: 'family16', english: 'Husband', vietnamese: 'Chồng', pronunciation: 'chong', category: 'family', chapter: 'chapter20', difficulty: 1, examples: ['Husband caring person.'] },
  { id: 'family17', english: 'Wife', vietnamese: 'Vợ', pronunciation: 'vo', category: 'family', chapter: 'chapter20', difficulty: 1, examples: ['Wife supportive always.'] },
  { id: 'family18', english: 'Spouse', vietnamese: 'Vợ/Chồng', pronunciation: 'vo/chong', category: 'family', chapter: 'chapter20', difficulty: 1, examples: ['Spouse best friend.'] },
  { id: 'family19', english: 'Relative', vietnamese: 'Họ hàng', pronunciation: 'ho hang', category: 'family', chapter: 'chapter20', difficulty: 1, examples: ['Relative visits holidays.'] },
  { id: 'family20', english: 'In-laws', vietnamese: 'Họ hàng nhà chồng/vợ', pronunciation: 'ho hang nha chong/vo', category: 'family', chapter: 'chapter20', difficulty: 2, examples: ['In-laws very kind.'] },
  { id: 'family21', english: 'Stepfather', vietnamese: 'Bố dượng', pronunciation: 'bo duong', category: 'family', chapter: 'chapter20', difficulty: 2, examples: ['Stepfather treats well.'] },
  { id: 'family22', english: 'Stepmother', vietnamese: 'Mẹ kế', pronunciation: 'me ke', category: 'family', chapter: 'chapter20', difficulty: 2, examples: ['Stepmother loves family.'] },
  { id: 'family23', english: 'Twins', vietnamese: 'Sinh đôi', pronunciation: 'sinh doi', category: 'family', chapter: 'chapter20', difficulty: 1, examples: ['Twins look identical.'] },
  { id: 'family24', english: 'Baby', vietnamese: 'Em bé', pronunciation: 'em be', category: 'family', chapter: 'chapter20', difficulty: 1, examples: ['Baby sleeps peacefully.'] },
  { id: 'family25', english: 'Child', vietnamese: 'Trẻ con', pronunciation: 'tre con', category: 'family', chapter: 'chapter20', difficulty: 1, examples: ['Child plays happily.'] },

  // Friends & Social Connections (25 words)
  { id: 'friends1', english: 'Friend', vietnamese: 'Bạn', pronunciation: 'ban', category: 'friends', chapter: 'chapter20', difficulty: 1, examples: ['Friend always loyal.'] },
  { id: 'friends2', english: 'Best friend', vietnamese: 'Bạn thân', pronunciation: 'ban than', category: 'friends', chapter: 'chapter20', difficulty: 1, examples: ['Best friend understands.'] },
  { id: 'friends3', english: 'Friendship', vietnamese: 'Tình bạn', pronunciation: 'tinh ban', category: 'friends', chapter: 'chapter20', difficulty: 1, examples: ['Friendship lasts forever.'] },
  { id: 'friends4', english: 'Buddy', vietnamese: 'Bạn bè', pronunciation: 'ban be', category: 'friends', chapter: 'chapter20', difficulty: 1, examples: ['Buddy helps always.'] },
  { id: 'friends5', english: 'Pal', vietnamese: 'Bạn thân', pronunciation: 'ban than', category: 'friends', chapter: 'chapter20', difficulty: 1, examples: ['Childhood pal visits.'] },
  { id: 'friends6', english: 'Companion', vietnamese: 'Bạn đồng hành', pronunciation: 'ban dong hanh', category: 'friends', chapter: 'chapter20', difficulty: 2, examples: ['Travel companion fun.'] },
  { id: 'friends7', english: 'Acquaintance', vietnamese: 'Người quen', pronunciation: 'nguoi quen', category: 'friends', chapter: 'chapter20', difficulty: 2, examples: ['Acquaintance from work.'] },
  { id: 'friends8', english: 'Classmate', vietnamese: 'Bạn cùng lớp', pronunciation: 'ban cung lop', category: 'friends', chapter: 'chapter20', difficulty: 1, examples: ['Classmate studies together.'] },
  { id: 'friends9', english: 'Teammate', vietnamese: 'Đồng đội', pronunciation: 'dong doi', category: 'friends', chapter: 'chapter20', difficulty: 1, examples: ['Teammate works cooperatively.'] },
  { id: 'friends10', english: 'Roommate', vietnamese: 'Bạn cùng phòng', pronunciation: 'ban cung phong', category: 'friends', chapter: 'chapter20', difficulty: 1, examples: ['Roommate shares expenses.'] },
  { id: 'friends11', english: 'Neighbor', vietnamese: 'Hàng xóm', pronunciation: 'hang xom', category: 'friends', chapter: 'chapter20', difficulty: 1, examples: ['Neighbor very friendly.'] },
  { id: 'friends12', english: 'Stranger', vietnamese: 'Người lạ', pronunciation: 'nguoi la', category: 'friends', chapter: 'chapter20', difficulty: 1, examples: ['Stranger asks directions.'] },
  { id: 'friends13', english: 'Guest', vietnamese: 'Khách', pronunciation: 'khach', category: 'friends', chapter: 'chapter20', difficulty: 1, examples: ['Guest arrives tonight.'] },
  { id: 'friends14', english: 'Host', vietnamese: 'Chủ nhà', pronunciation: 'chu nha', category: 'friends', chapter: 'chapter20', difficulty: 1, examples: ['Host welcomes warmly.'] },
  { id: 'friends15', english: 'Visitor', vietnamese: 'Khách thăm', pronunciation: 'khach tham', category: 'friends', chapter: 'chapter20', difficulty: 1, examples: ['Visitor stays weekend.'] },
  { id: 'friends16', english: 'Group', vietnamese: 'Nhóm', pronunciation: 'nhom', category: 'friends', chapter: 'chapter20', difficulty: 1, examples: ['Group meets regularly.'] },
  { id: 'friends17', english: 'Circle', vietnamese: 'Vòng tròn', pronunciation: 'vong tron', category: 'friends', chapter: 'chapter20', difficulty: 1, examples: ['Circle of friends.'] },
  { id: 'friends18', english: 'Community', vietnamese: 'Cộng đồng', pronunciation: 'cong dong', category: 'friends', chapter: 'chapter20', difficulty: 1, examples: ['Community supports each.'] },
  { id: 'friends19', english: 'Society', vietnamese: 'Xã hội', pronunciation: 'xa hoi', category: 'friends', chapter: 'chapter20', difficulty: 1, examples: ['Society changes constantly.'] },
  { id: 'friends20', english: 'Network', vietnamese: 'Mạng lưới', pronunciation: 'mang luoi', category: 'friends', chapter: 'chapter20', difficulty: 1, examples: ['Professional network grows.'] },
  { id: 'friends21', english: 'Contact', vietnamese: 'Liên lạc', pronunciation: 'lien lac', category: 'friends', chapter: 'chapter20', difficulty: 1, examples: ['Contact information updated.'] },
  { id: 'friends22', english: 'Connection', vietnamese: 'Kết nối', pronunciation: 'ket noi', category: 'friends', chapter: 'chapter20', difficulty: 1, examples: ['Connection strengthens relationship.'] },
  { id: 'friends23', english: 'Partner', vietnamese: 'Đối tác', pronunciation: 'doi tac', category: 'friends', chapter: 'chapter20', difficulty: 1, examples: ['Business partner reliable.'] },
  { id: 'friends24', english: 'Ally', vietnamese: 'Đồng minh', pronunciation: 'dong minh', category: 'friends', chapter: 'chapter20', difficulty: 2, examples: ['Ally supports cause.'] },
  { id: 'friends25', english: 'Mentor', vietnamese: 'Người cố vấn', pronunciation: 'nguoi co van', category: 'friends', chapter: 'chapter20', difficulty: 2, examples: ['Mentor guides career.'] },

  // Romantic Relationships (25 words)
  { id: 'romantic1', english: 'Love', vietnamese: 'Tình yêu', pronunciation: 'tinh yeu', category: 'romantic', chapter: 'chapter20', difficulty: 1, examples: ['Love conquers all.'] },
  { id: 'romantic2', english: 'Romance', vietnamese: 'Tình lãng mạn', pronunciation: 'tinh lang man', category: 'romantic', chapter: 'chapter20', difficulty: 1, examples: ['Romance brings happiness.'] },
  { id: 'romantic3', english: 'Boyfriend', vietnamese: 'Bạn trai', pronunciation: 'ban trai', category: 'romantic', chapter: 'chapter20', difficulty: 1, examples: ['Boyfriend very thoughtful.'] },
  { id: 'romantic4', english: 'Girlfriend', vietnamese: 'Bạn gái', pronunciation: 'ban gai', category: 'romantic', chapter: 'chapter20', difficulty: 1, examples: ['Girlfriend studies medicine.'] },
  { id: 'romantic5', english: 'Dating', vietnamese: 'Hẹn hò', pronunciation: 'hen ho', category: 'romantic', chapter: 'chapter20', difficulty: 1, examples: ['Dating requires patience.'] },
  { id: 'romantic6', english: 'Relationship', vietnamese: 'Mối quan hệ', pronunciation: 'moi quan he', category: 'romantic', chapter: 'chapter20', difficulty: 1, examples: ['Relationship needs trust.'] },
  { id: 'romantic7', english: 'Couple', vietnamese: 'Cặp đôi', pronunciation: 'cap doi', category: 'romantic', chapter: 'chapter20', difficulty: 1, examples: ['Couple walks together.'] },
  { id: 'romantic8', english: 'Engagement', vietnamese: 'Đính hôn', pronunciation: 'dinh hon', category: 'romantic', chapter: 'chapter20', difficulty: 1, examples: ['Engagement party celebration.'] },
  { id: 'romantic9', english: 'Fiancé', vietnamese: 'Chồng chưa cưới', pronunciation: 'chong chua cuoi', category: 'romantic', chapter: 'chapter20', difficulty: 2, examples: ['Fiancé plans wedding.'] },
  { id: 'romantic10', english: 'Fiancée', vietnamese: 'Vợ chưa cưới', pronunciation: 'vo chua cuoi', category: 'romantic', chapter: 'chapter20', difficulty: 2, examples: ['Fiancée chooses dress.'] },
  { id: 'romantic11', english: 'Marriage', vietnamese: 'Hôn nhân', pronunciation: 'hon nhan', category: 'romantic', chapter: 'chapter20', difficulty: 1, examples: ['Marriage requires commitment.'] },
  { id: 'romantic12', english: 'Wedding', vietnamese: 'Đám cưới', pronunciation: 'dam cuoi', category: 'romantic', chapter: 'chapter20', difficulty: 1, examples: ['Wedding ceremony beautiful.'] },
  { id: 'romantic13', english: 'Honeymoon', vietnamese: 'Tuần trăng mật', pronunciation: 'tuan trang mat', category: 'romantic', chapter: 'chapter20', difficulty: 2, examples: ['Honeymoon trip romantic.'] },
  { id: 'romantic14', english: 'Anniversary', vietnamese: 'Kỷ niệm', pronunciation: 'ky niem', category: 'romantic', chapter: 'chapter20', difficulty: 1, examples: ['Anniversary dinner special.'] },
  { id: 'romantic15', english: 'Valentine', vietnamese: 'Lễ tình nhân', pronunciation: 'le tinh nhan', category: 'romantic', chapter: 'chapter20', difficulty: 1, examples: ['Valentine Day romantic.'] },
  { id: 'romantic16', english: 'Kiss', vietnamese: 'Hôn', pronunciation: 'hon', category: 'romantic', chapter: 'chapter20', difficulty: 1, examples: ['Kiss shows affection.'] },
  { id: 'romantic17', english: 'Hug', vietnamese: 'Ôm', pronunciation: 'om', category: 'romantic', chapter: 'chapter20', difficulty: 1, examples: ['Hug comforts sadness.'] },
  { id: 'romantic18', english: 'Crush', vietnamese: 'Người thầm thích', pronunciation: 'nguoi tham thich', category: 'romantic', chapter: 'chapter20', difficulty: 1, examples: ['Crush makes nervous.'] },
  { id: 'romantic19', english: 'Attraction', vietnamese: 'Sự hấp dẫn', pronunciation: 'su hap dan', category: 'romantic', chapter: 'chapter20', difficulty: 2, examples: ['Attraction grows slowly.'] },
  { id: 'romantic20', english: 'Affection', vietnamese: 'Tình cảm', pronunciation: 'tinh cam', category: 'romantic', chapter: 'chapter20', difficulty: 1, examples: ['Affection shows care.'] },
  { id: 'romantic21', english: 'Devotion', vietnamese: 'Sự tận tâm', pronunciation: 'su tan tam', category: 'romantic', chapter: 'chapter20', difficulty: 2, examples: ['Devotion proves love.'] },
  { id: 'romantic22', english: 'Commitment', vietnamese: 'Cam kết', pronunciation: 'cam ket', category: 'romantic', chapter: 'chapter20', difficulty: 1, examples: ['Commitment strengthens bond.'] },
  { id: 'romantic23', english: 'Loyalty', vietnamese: 'Lòng trung thành', pronunciation: 'long trung thanh', category: 'romantic', chapter: 'chapter20', difficulty: 2, examples: ['Loyalty builds trust.'] },
  { id: 'romantic24', english: 'Passion', vietnamese: 'Đam mê', pronunciation: 'dam me', category: 'romantic', chapter: 'chapter20', difficulty: 1, examples: ['Passion drives relationship.'] },
  { id: 'romantic25', english: 'Intimacy', vietnamese: 'Sự thân mật', pronunciation: 'su than mat', category: 'romantic', chapter: 'chapter20', difficulty: 2, examples: ['Intimacy deepens connection.'] },

  // Social Activities & Events (25 words)
  { id: 'social1', english: 'Party', vietnamese: 'Tiệc', pronunciation: 'tiec', category: 'social', chapter: 'chapter20', difficulty: 1, examples: ['Party celebrates birthday.'] },
  { id: 'social2', english: 'Celebration', vietnamese: 'Lễ kỷ niệm', pronunciation: 'le ky niem', category: 'social', chapter: 'chapter20', difficulty: 1, examples: ['Celebration brings joy.'] },
  { id: 'social3', english: 'Event', vietnamese: 'Sự kiện', pronunciation: 'su kien', category: 'social', chapter: 'chapter20', difficulty: 1, examples: ['Event well organized.'] },
  { id: 'social4', english: 'Gathering', vietnamese: 'Tụ tập', pronunciation: 'tu tap', category: 'social', chapter: 'chapter20', difficulty: 1, examples: ['Family gathering warm.'] },
  { id: 'social5', english: 'Meeting', vietnamese: 'Cuộc họp', pronunciation: 'cuoc hop', category: 'social', chapter: 'chapter20', difficulty: 1, examples: ['Meeting starts promptly.'] },
  { id: 'social6', english: 'Reunion', vietnamese: 'Tái ngộ', pronunciation: 'tai ngo', category: 'social', chapter: 'chapter20', difficulty: 1, examples: ['Class reunion exciting.'] },
  { id: 'social7', english: 'Get-together', vietnamese: 'Tụ tập', pronunciation: 'tu tap', category: 'social', chapter: 'chapter20', difficulty: 1, examples: ['Get-together informal fun.'] },
  { id: 'social8', english: 'Hangout', vietnamese: 'Tụ tập chơi', pronunciation: 'tu tap choi', category: 'social', chapter: 'chapter20', difficulty: 1, examples: ['Weekend hangout relaxing.'] },
  { id: 'social9', english: 'Date', vietnamese: 'Hẹn hò', pronunciation: 'hen ho', category: 'social', chapter: 'chapter20', difficulty: 1, examples: ['First date nervous.'] },
  { id: 'social10', english: 'Appointment', vietnamese: 'Cuộc hẹn', pronunciation: 'cuoc hen', category: 'social', chapter: 'chapter20', difficulty: 1, examples: ['Doctor appointment scheduled.'] },
  { id: 'social11', english: 'Invitation', vietnamese: 'Lời mời', pronunciation: 'loi moi', category: 'social', chapter: 'chapter20', difficulty: 1, examples: ['Invitation arrives today.'] },
  { id: 'social12', english: 'Visit', vietnamese: 'Thăm', pronunciation: 'tham', category: 'social', chapter: 'chapter20', difficulty: 1, examples: ['Visit grandmother Sunday.'] },
  { id: 'social13', english: 'Chat', vietnamese: 'Trò chuyện', pronunciation: 'tro chuyen', category: 'social', chapter: 'chapter20', difficulty: 1, examples: ['Chat over coffee.'] },
  { id: 'social14', english: 'Conversation', vietnamese: 'Cuộc trò chuyện', pronunciation: 'cuoc tro chuyen', category: 'social', chapter: 'chapter20', difficulty: 1, examples: ['Conversation flows naturally.'] },
  { id: 'social15', english: 'Discussion', vietnamese: 'Thảo luận', pronunciation: 'thao luan', category: 'social', chapter: 'chapter20', difficulty: 1, examples: ['Discussion very productive.'] },
  { id: 'social16', english: 'Introduction', vietnamese: 'Giới thiệu', pronunciation: 'gioi thieu', category: 'social', chapter: 'chapter20', difficulty: 1, examples: ['Introduction creates connections.'] },
  { id: 'social17', english: 'Greeting', vietnamese: 'Chào hỏi', pronunciation: 'chao hoi', category: 'social', chapter: 'chapter20', difficulty: 1, examples: ['Greeting shows politeness.'] },
  { id: 'social18', english: 'Farewell', vietnamese: 'Chào tạm biệt', pronunciation: 'chao tam biet', category: 'social', chapter: 'chapter20', difficulty: 1, examples: ['Farewell party emotional.'] },
  { id: 'social19', english: 'Communication', vietnamese: 'Giao tiếp', pronunciation: 'giao tiep', category: 'social', chapter: 'chapter20', difficulty: 1, examples: ['Communication improves relationships.'] },
  { id: 'social20', english: 'Interaction', vietnamese: 'Tương tác', pronunciation: 'tuong tac', category: 'social', chapter: 'chapter20', difficulty: 1, examples: ['Social interaction important.'] },
  { id: 'social21', english: 'Cooperation', vietnamese: 'Hợp tác', pronunciation: 'hop tac', category: 'social', chapter: 'chapter20', difficulty: 1, examples: ['Cooperation achieves goals.'] },
  { id: 'social22', english: 'Collaboration', vietnamese: 'Cộng tác', pronunciation: 'cong tac', category: 'social', chapter: 'chapter20', difficulty: 2, examples: ['Collaboration produces results.'] },
  { id: 'social23', english: 'Support', vietnamese: 'Hỗ trợ', pronunciation: 'ho tro', category: 'social', chapter: 'chapter20', difficulty: 1, examples: ['Friends support always.'] },
  { id: 'social24', english: 'Help', vietnamese: 'Giúp đỡ', pronunciation: 'giup do', category: 'social', chapter: 'chapter20', difficulty: 1, examples: ['Help arrives timely.'] },
  { id: 'social25', english: 'Care', vietnamese: 'Quan tâm', pronunciation: 'quan tam', category: 'social', chapter: 'chapter20', difficulty: 1, examples: ['Care shows kindness.'] }
]
