// Chapter 5: Transportation (100 Essential Words)
// Words related to vehicles, travel, and transportation

import { LanguageWord } from './chapter01-basic-everyday'

export const chapter05Words: LanguageWord[] = [
  // Vehicles (30 words)
  { id: 'transport1', english: 'Car', vietnamese: 'Xe ô tô', pronunciation: 'xe o to', category: 'vehicle', chapter: 'chapter05', difficulty: 1, examples: ['Drive a red car.'] },
  { id: 'transport2', english: 'Bus', vietnamese: 'Xe buýt', pronunciation: 'xe buyt', category: 'vehicle', chapter: 'chapter05', difficulty: 1, examples: ['Take bus to work.'] },
  { id: 'transport3', english: 'Train', vietnamese: 'Tàu hỏa', pronunciation: 'tau hoa', category: 'vehicle', chapter: 'chapter05', difficulty: 1, examples: ['Fast train to the city.'] },
  { id: 'transport4', english: 'Plane', vietnamese: 'Máy bay', pronunciation: 'may bay', category: 'vehicle', chapter: 'chapter05', difficulty: 1, examples: ['Fly on a plane.'] },
  { id: 'transport5', english: 'Boat', vietnamese: 'Thuyền', pronunciation: 'thuyen', category: 'vehicle', chapter: 'chapter05', difficulty: 1, examples: ['Sail on a boat.'] },
  { id: 'transport6', english: 'Bicycle', vietnamese: 'Xe đạp', pronunciation: 'xe dap', category: 'vehicle', chapter: 'chapter05', difficulty: 1, examples: ['Ride bicycle to school.'] },
  { id: 'transport7', english: 'Motorcycle', vietnamese: 'Xe máy', pronunciation: 'xe may', category: 'vehicle', chapter: 'chapter05', difficulty: 1, examples: ['Fast motorcycle on road.'] },
  { id: 'transport8', english: 'Truck', vietnamese: 'Xe tải', pronunciation: 'xe tai', category: 'vehicle', chapter: 'chapter05', difficulty: 1, examples: ['Big truck carries goods.'] },
  { id: 'transport9', english: 'Taxi', vietnamese: 'Taxi', pronunciation: 'taxi', category: 'vehicle', chapter: 'chapter05', difficulty: 1, examples: ['Call a taxi home.'] },
  { id: 'transport10', english: 'Subway', vietnamese: 'Tàu điện ngầm', pronunciation: 'tau dien ngam', category: 'vehicle', chapter: 'chapter05', difficulty: 1, examples: ['Take subway underground.'] },
  { id: 'transport11', english: 'Helicopter', vietnamese: 'Trực thăng', pronunciation: 'truc thang', category: 'vehicle', chapter: 'chapter05', difficulty: 1, examples: ['Helicopter in the sky.'] },
  { id: 'transport12', english: 'Van', vietnamese: 'Xe van', pronunciation: 'xe van', category: 'vehicle', chapter: 'chapter05', difficulty: 1, examples: ['Family trip in van.'] },
  { id: 'transport13', english: 'Scooter', vietnamese: 'Xe scooter', pronunciation: 'xe scooter', category: 'vehicle', chapter: 'chapter05', difficulty: 1, examples: ['Electric scooter for short trips.'] },
  { id: 'transport14', english: 'Ambulance', vietnamese: 'Xe cứu thương', pronunciation: 'xe cuu thuong', category: 'vehicle', chapter: 'chapter05', difficulty: 1, examples: ['Emergency ambulance service.'] },
  { id: 'transport15', english: 'Fire truck', vietnamese: 'Xe cứu hỏa', pronunciation: 'xe cuu hoa', category: 'vehicle', chapter: 'chapter05', difficulty: 1, examples: ['Fire truck puts out fires.'] },
  { id: 'transport16', english: 'Police car', vietnamese: 'Xe cảnh sát', pronunciation: 'xe canh sat', category: 'vehicle', chapter: 'chapter05', difficulty: 1, examples: ['Police car patrols streets.'] },
  { id: 'transport17', english: 'Tram', vietnamese: 'Xe điện', pronunciation: 'xe dien', category: 'vehicle', chapter: 'chapter05', difficulty: 1, examples: ['Old tram in the city.'] },
  { id: 'transport18', english: 'Cable car', vietnamese: 'Cáp treo', pronunciation: 'cap treo', category: 'vehicle', chapter: 'chapter05', difficulty: 1, examples: ['Cable car up the mountain.'] },
  { id: 'transport19', english: 'Ferry', vietnamese: 'Phà', pronunciation: 'pha', category: 'vehicle', chapter: 'chapter05', difficulty: 1, examples: ['Ferry crosses the river.'] },
  { id: 'transport20', english: 'Cruise ship', vietnamese: 'Tàu du lịch', pronunciation: 'tau du lich', category: 'vehicle', chapter: 'chapter05', difficulty: 1, examples: ['Vacation on cruise ship.'] },
  { id: 'transport21', english: 'Rocket', vietnamese: 'Tên lửa', pronunciation: 'ten lua', category: 'vehicle', chapter: 'chapter05', difficulty: 2, examples: ['Rocket flies to space.'] },
  { id: 'transport22', english: 'Skateboard', vietnamese: 'Ván trượt', pronunciation: 'van truot', category: 'vehicle', chapter: 'chapter05', difficulty: 1, examples: ['Kids play with skateboard.'] },
  { id: 'transport23', english: 'Roller skates', vietnamese: 'Giày trượt patin', pronunciation: 'giay truot patin', category: 'vehicle', chapter: 'chapter05', difficulty: 1, examples: ['Fun with roller skates.'] },
  { id: 'transport24', english: 'Golf cart', vietnamese: 'Xe golf', pronunciation: 'xe golf', category: 'vehicle', chapter: 'chapter05', difficulty: 1, examples: ['Drive golf cart on course.'] },
  { id: 'transport25', english: 'Rickshaw', vietnamese: 'Xe kéo', pronunciation: 'xe keo', category: 'vehicle', chapter: 'chapter05', difficulty: 1, examples: ['Traditional rickshaw ride.'] },
  { id: 'transport26', english: 'Jeep', vietnamese: 'Xe jeep', pronunciation: 'xe jeep', category: 'vehicle', chapter: 'chapter05', difficulty: 1, examples: ['Off-road adventure in jeep.'] },
  { id: 'transport27', english: 'Limousine', vietnamese: 'Xe limousine', pronunciation: 'xe limousine', category: 'vehicle', chapter: 'chapter05', difficulty: 1, examples: ['Wedding in white limousine.'] },
  { id: 'transport28', english: 'Snowmobile', vietnamese: 'Xe trượt tuyết', pronunciation: 'xe truot tuyet', category: 'vehicle', chapter: 'chapter05', difficulty: 2, examples: ['Snowmobile in winter.'] },
  { id: 'transport29', english: 'ATV', vietnamese: 'Xe địa hình', pronunciation: 'xe dia hinh', category: 'vehicle', chapter: 'chapter05', difficulty: 2, examples: ['ATV for rough terrain.'] },
  { id: 'transport30', english: 'Segway', vietnamese: 'Xe Segway', pronunciation: 'xe segway', category: 'vehicle', chapter: 'chapter05', difficulty: 2, examples: ['Tour city on Segway.'] },

  // Transportation Actions (20 words)
  { id: 'action1', english: 'Drive', vietnamese: 'Lái xe', pronunciation: 'lai xe', category: 'action', chapter: 'chapter05', difficulty: 1, examples: ['Drive carefully on roads.'] },
  { id: 'action2', english: 'Ride', vietnamese: 'Đi', pronunciation: 'di', category: 'action', chapter: 'chapter05', difficulty: 1, examples: ['Ride the bus to work.'] },
  { id: 'action3', english: 'Walk', vietnamese: 'Đi bộ', pronunciation: 'di bo', category: 'action', chapter: 'chapter05', difficulty: 1, examples: ['Walk to the store.'] },
  { id: 'action4', english: 'Run', vietnamese: 'Chạy', pronunciation: 'chay', category: 'action', chapter: 'chapter05', difficulty: 1, examples: ['Run to catch the bus.'] },
  { id: 'action5', english: 'Fly', vietnamese: 'Bay', pronunciation: 'bay', category: 'action', chapter: 'chapter05', difficulty: 1, examples: ['Fly to another country.'] },
  { id: 'action6', english: 'Sail', vietnamese: 'Đi thuyền', pronunciation: 'di thuyen', category: 'action', chapter: 'chapter05', difficulty: 1, examples: ['Sail across the ocean.'] },
  { id: 'action7', english: 'Travel', vietnamese: 'Du lịch', pronunciation: 'du lich', category: 'action', chapter: 'chapter05', difficulty: 1, examples: ['Travel around the world.'] },
  { id: 'action8', english: 'Stop', vietnamese: 'Dừng', pronunciation: 'dung', category: 'action', chapter: 'chapter05', difficulty: 1, examples: ['Stop at red light.'] },
  { id: 'action9', english: 'Go', vietnamese: 'Đi', pronunciation: 'di', category: 'action', chapter: 'chapter05', difficulty: 1, examples: ['Go to the station.'] },
  { id: 'action10', english: 'Turn', vietnamese: 'Rẽ', pronunciation: 're', category: 'action', chapter: 'chapter05', difficulty: 1, examples: ['Turn left at corner.'] },
  { id: 'action11', english: 'Park', vietnamese: 'Đậu xe', pronunciation: 'dau xe', category: 'action', chapter: 'chapter05', difficulty: 1, examples: ['Park car in garage.'] },
  { id: 'action12', english: 'Speed up', vietnamese: 'Tăng tốc', pronunciation: 'tang toc', category: 'action', chapter: 'chapter05', difficulty: 1, examples: ['Speed up on highway.'] },
  { id: 'action13', english: 'Slow down', vietnamese: 'Chậm lại', pronunciation: 'cham lai', category: 'action', chapter: 'chapter05', difficulty: 1, examples: ['Slow down near school.'] },
  { id: 'action14', english: 'Brake', vietnamese: 'Phanh', pronunciation: 'phanh', category: 'action', chapter: 'chapter05', difficulty: 1, examples: ['Brake at the intersection.'] },
  { id: 'action15', english: 'Reverse', vietnamese: 'Lùi', pronunciation: 'lui', category: 'action', chapter: 'chapter05', difficulty: 1, examples: ['Reverse out of driveway.'] },
  { id: 'action16', english: 'Overtake', vietnamese: 'Vượt', pronunciation: 'vuot', category: 'action', chapter: 'chapter05', difficulty: 2, examples: ['Overtake slow vehicle.'] },
  { id: 'action17', english: 'Follow', vietnamese: 'Theo', pronunciation: 'theo', category: 'action', chapter: 'chapter05', difficulty: 1, examples: ['Follow the GPS directions.'] },
  { id: 'action18', english: 'Navigate', vietnamese: 'Điều hướng', pronunciation: 'dieu huong', category: 'action', chapter: 'chapter05', difficulty: 2, examples: ['Navigate through traffic.'] },
  { id: 'action19', english: 'Honk', vietnamese: 'Bấm còi', pronunciation: 'bam coi', category: 'action', chapter: 'chapter05', difficulty: 1, examples: ['Honk horn at intersection.'] },
  { id: 'action20', english: 'Signal', vietnamese: 'Báo hiệu', pronunciation: 'bao hieu', category: 'action', chapter: 'chapter05', difficulty: 1, examples: ['Signal before turning.'] },

  // Places & Infrastructure (25 words)
  { id: 'place1', english: 'Station', vietnamese: 'Ga', pronunciation: 'ga', category: 'place', chapter: 'chapter05', difficulty: 1, examples: ['Wait at train station.'] },
  { id: 'place2', english: 'Airport', vietnamese: 'Sân bay', pronunciation: 'san bay', category: 'place', chapter: 'chapter05', difficulty: 1, examples: ['Fly from international airport.'] },
  { id: 'place3', english: 'Bus stop', vietnamese: 'Trạm xe buýt', pronunciation: 'tram xe buyt', category: 'place', chapter: 'chapter05', difficulty: 1, examples: ['Wait at bus stop.'] },
  { id: 'place4', english: 'Parking lot', vietnamese: 'Bãi đậu xe', pronunciation: 'bai dau xe', category: 'place', chapter: 'chapter05', difficulty: 1, examples: ['Full parking lot downtown.'] },
  { id: 'place5', english: 'Gas station', vietnamese: 'Trạm xăng', pronunciation: 'tram xang', category: 'place', chapter: 'chapter05', difficulty: 1, examples: ['Fill up at gas station.'] },
  { id: 'place6', english: 'Highway', vietnamese: 'Đường cao tốc', pronunciation: 'duong cao toc', category: 'place', chapter: 'chapter05', difficulty: 1, examples: ['Fast travel on highway.'] },
  { id: 'place7', english: 'Road', vietnamese: 'Đường', pronunciation: 'duong', category: 'place', chapter: 'chapter05', difficulty: 1, examples: ['Smooth road through city.'] },
  { id: 'place8', english: 'Street', vietnamese: 'Phố', pronunciation: 'pho', category: 'place', chapter: 'chapter05', difficulty: 1, examples: ['Busy street with shops.'] },
  { id: 'place9', english: 'Bridge', vietnamese: 'Cầu', pronunciation: 'cau', category: 'place', chapter: 'chapter05', difficulty: 1, examples: ['Cross river on bridge.'] },
  { id: 'place10', english: 'Tunnel', vietnamese: 'Đường hầm', pronunciation: 'duong ham', category: 'place', chapter: 'chapter05', difficulty: 1, examples: ['Drive through mountain tunnel.'] },
  { id: 'place11', english: 'Intersection', vietnamese: 'Ngã tư', pronunciation: 'nga tu', category: 'place', chapter: 'chapter05', difficulty: 1, examples: ['Stop at busy intersection.'] },
  { id: 'place12', english: 'Roundabout', vietnamese: 'Vòng xoay', pronunciation: 'vong xoay', category: 'place', chapter: 'chapter05', difficulty: 1, examples: ['Navigate through roundabout.'] },
  { id: 'place13', english: 'Sidewalk', vietnamese: 'Vỉa hè', pronunciation: 'via he', category: 'place', chapter: 'chapter05', difficulty: 1, examples: ['Walk on sidewalk safely.'] },
  { id: 'place14', english: 'Crosswalk', vietnamese: 'Vạch kẻ đường', pronunciation: 'vach ke duong', category: 'place', chapter: 'chapter05', difficulty: 1, examples: ['Use crosswalk to cross street.'] },
  { id: 'place15', english: 'Traffic light', vietnamese: 'Đèn giao thông', pronunciation: 'den giao thong', category: 'place', chapter: 'chapter05', difficulty: 1, examples: ['Stop at red traffic light.'] },
  { id: 'place16', english: 'Speed limit', vietnamese: 'Giới hạn tốc độ', pronunciation: 'gioi han toc do', category: 'place', chapter: 'chapter05', difficulty: 2, examples: ['Follow speed limit signs.'] },
  { id: 'place17', english: 'Toll booth', vietnamese: 'Trạm thu phí', pronunciation: 'tram thu phi', category: 'place', chapter: 'chapter05', difficulty: 2, examples: ['Pay at toll booth.'] },
  { id: 'place18', english: 'Rest area', vietnamese: 'Khu nghỉ', pronunciation: 'khu nghi', category: 'place', chapter: 'chapter05', difficulty: 1, examples: ['Stop at highway rest area.'] },
  { id: 'place19', english: 'Garage', vietnamese: 'Ga ra', pronunciation: 'ga ra', category: 'place', chapter: 'chapter05', difficulty: 1, examples: ['Repair car at garage.'] },
  { id: 'place20', english: 'Harbor', vietnamese: 'Cảng', pronunciation: 'cang', category: 'place', chapter: 'chapter05', difficulty: 1, examples: ['Ships dock at harbor.'] },
  { id: 'place21', english: 'Railway', vietnamese: 'Đường sắt', pronunciation: 'duong sat', category: 'place', chapter: 'chapter05', difficulty: 1, examples: ['Train runs on railway.'] },
  { id: 'place22', english: 'Platform', vietnamese: 'Sân ga', pronunciation: 'san ga', category: 'place', chapter: 'chapter05', difficulty: 1, examples: ['Wait on train platform.'] },
  { id: 'place23', english: 'Terminal', vietnamese: 'Nhà ga', pronunciation: 'nha ga', category: 'place', chapter: 'chapter05', difficulty: 1, examples: ['Airport terminal building.'] },
  { id: 'place24', english: 'Runway', vietnamese: 'Đường băng', pronunciation: 'duong bang', category: 'place', chapter: 'chapter05', difficulty: 1, examples: ['Plane lands on runway.'] },
  { id: 'place25', english: 'Hangar', vietnamese: 'Nhà chứa máy bay', pronunciation: 'nha chua may bay', category: 'place', chapter: 'chapter05', difficulty: 2, examples: ['Store aircraft in hangar.'] },

  // Transportation Items (25 words)
  { id: 'item1', english: 'Ticket', vietnamese: 'Vé', pronunciation: 've', category: 'item', chapter: 'chapter05', difficulty: 1, examples: ['Buy train ticket online.'] },
  { id: 'item2', english: 'License', vietnamese: 'Bằng lái', pronunciation: 'bang lai', category: 'item', chapter: 'chapter05', difficulty: 1, examples: ['Show driving license to police.'] },
  { id: 'item3', english: 'Passport', vietnamese: 'Hộ chiếu', pronunciation: 'ho chieu', category: 'item', chapter: 'chapter05', difficulty: 1, examples: ['Need passport for travel.'] },
  { id: 'item4', english: 'Suitcase', vietnamese: 'Vali', pronunciation: 'vali', category: 'item', chapter: 'chapter05', difficulty: 1, examples: ['Pack clothes in suitcase.'] },
  { id: 'item5', english: 'Backpack', vietnamese: 'Ba lô', pronunciation: 'ba lo', category: 'item', chapter: 'chapter05', difficulty: 1, examples: ['Carry backpack on trip.'] },
  { id: 'item6', english: 'Map', vietnamese: 'Bản đồ', pronunciation: 'ban do', category: 'item', chapter: 'chapter05', difficulty: 1, examples: ['Follow route on map.'] },
  { id: 'item7', english: 'GPS', vietnamese: 'GPS', pronunciation: 'GPS', category: 'item', chapter: 'chapter05', difficulty: 1, examples: ['Use GPS for navigation.'] },
  { id: 'item8', english: 'Compass', vietnamese: 'La bàn', pronunciation: 'la ban', category: 'item', chapter: 'chapter05', difficulty: 1, examples: ['Find direction with compass.'] },
  { id: 'item9', english: 'Fuel', vietnamese: 'Nhiên liệu', pronunciation: 'nhien lieu', category: 'item', chapter: 'chapter05', difficulty: 1, examples: ['Car needs fuel to run.'] },
  { id: 'item10', english: 'Engine', vietnamese: 'Động cơ', pronunciation: 'dong co', category: 'item', chapter: 'chapter05', difficulty: 1, examples: ['Car engine runs smoothly.'] },
  { id: 'item11', english: 'Wheel', vietnamese: 'Bánh xe', pronunciation: 'banh xe', category: 'item', chapter: 'chapter05', difficulty: 1, examples: ['Four wheels on car.'] },
  { id: 'item12', english: 'Tire', vietnamese: 'Lốp xe', pronunciation: 'lop xe', category: 'item', chapter: 'chapter05', difficulty: 1, examples: ['Change flat tire.'] },
  { id: 'item13', english: 'Brake', vietnamese: 'Phanh', pronunciation: 'phanh', category: 'item', chapter: 'chapter05', difficulty: 1, examples: ['Press brake pedal to stop.'] },
  { id: 'item14', english: 'Steering wheel', vietnamese: 'Vô lăng', pronunciation: 'vo lang', category: 'item', chapter: 'chapter05', difficulty: 1, examples: ['Turn steering wheel left.'] },
  { id: 'item15', english: 'Seat belt', vietnamese: 'Dây an toàn', pronunciation: 'day an toan', category: 'item', chapter: 'chapter05', difficulty: 1, examples: ['Wear seat belt for safety.'] },
  { id: 'item16', english: 'Horn', vietnamese: 'Còi', pronunciation: 'coi', category: 'item', chapter: 'chapter05', difficulty: 1, examples: ['Sound horn to warn others.'] },
  { id: 'item17', english: 'Mirror', vietnamese: 'Gương', pronunciation: 'guong', category: 'item', chapter: 'chapter05', difficulty: 1, examples: ['Check rearview mirror.'] },
  { id: 'item18', english: 'Headlight', vietnamese: 'Đèn pha', pronunciation: 'den pha', category: 'item', chapter: 'chapter05', difficulty: 1, examples: ['Turn on headlights at night.'] },
  { id: 'item19', english: 'Signal light', vietnamese: 'Đèn xi nhan', pronunciation: 'den xi nhan', category: 'item', chapter: 'chapter05', difficulty: 1, examples: ['Use signal light when turning.'] },
  { id: 'item20', english: 'Windshield', vietnamese: 'Kính chắn gió', pronunciation: 'kinh chan gio', category: 'item', chapter: 'chapter05', difficulty: 1, examples: ['Clean windshield for visibility.'] },
  { id: 'item21', english: 'Dashboard', vietnamese: 'Táp lô', pronunciation: 'tap lo', category: 'item', chapter: 'chapter05', difficulty: 1, examples: ['Check dashboard indicators.'] },
  { id: 'item22', english: 'Speedometer', vietnamese: 'Đồng hồ tốc độ', pronunciation: 'dong ho toc do', category: 'item', chapter: 'chapter05', difficulty: 2, examples: ['Monitor speed on speedometer.'] },
  { id: 'item23', english: 'Trunk', vietnamese: 'Cốp xe', pronunciation: 'cop xe', category: 'item', chapter: 'chapter05', difficulty: 1, examples: ['Put luggage in car trunk.'] },
  { id: 'item24', english: 'Hood', vietnamese: 'Capo', pronunciation: 'capo', category: 'item', chapter: 'chapter05', difficulty: 1, examples: ['Open hood to check engine.'] },
  { id: 'item25', english: 'License plate', vietnamese: 'Biển số xe', pronunciation: 'bien so xe', category: 'item', chapter: 'chapter05', difficulty: 1, examples: ['Every car has license plate.'] }
]
