// Chapter 23: Communication & Language (100 Essential Words)
// Words related to speaking, writing, language, and communication methods

import { LanguageWord } from './chapter01-basic-everyday'

export const chapter23Words: LanguageWord[] = [
  // Speaking & Verbal Communication (25 words)
  { id: 'speaking1', english: 'Communication', vietnamese: 'Giao tiếp', pronunciation: 'giao tiep', category: 'speaking', chapter: 'chapter23', difficulty: 1, examples: ['Communication connects people.'] },
  { id: 'speaking2', english: 'Language', vietnamese: 'Ngôn ngữ', pronunciation: 'ngon ngu', category: 'speaking', chapter: 'chapter23', difficulty: 1, examples: ['English global language.'] },
  { id: 'speaking3', english: 'Speaking', vietnamese: 'Nói', pronunciation: 'noi', category: 'speaking', chapter: 'chapter23', difficulty: 1, examples: ['Speaking clearly important.'] },
  { id: 'speaking4', english: 'Talking', vietnamese: 'Nói chuyện', pronunciation: 'noi chuyen', category: 'speaking', chapter: 'chapter23', difficulty: 1, examples: ['Talking helps relationships.'] },
  { id: 'speaking5', english: 'Voice', vietnamese: 'Giọng nói', pronunciation: 'giong noi', category: 'speaking', chapter: 'chapter23', difficulty: 1, examples: ['Voice sounds pleasant.'] },
  { id: 'speaking6', english: 'Word', vietnamese: 'Từ', pronunciation: 'tu', category: 'speaking', chapter: 'chapter23', difficulty: 1, examples: ['Word has meaning.'] },
  { id: 'speaking7', english: 'Sentence', vietnamese: 'Câu', pronunciation: 'cau', category: 'speaking', chapter: 'chapter23', difficulty: 1, examples: ['Sentence expresses thought.'] },
  { id: 'speaking8', english: 'Phrase', vietnamese: 'Cụm từ', pronunciation: 'cum tu', category: 'speaking', chapter: 'chapter23', difficulty: 1, examples: ['Phrase group words.'] },
  { id: 'speaking9', english: 'Question', vietnamese: 'Câu hỏi', pronunciation: 'cau hoi', category: 'speaking', chapter: 'chapter23', difficulty: 1, examples: ['Question seeks answer.'] },
  { id: 'speaking10', english: 'Answer', vietnamese: 'Câu trả lời', pronunciation: 'cau tra loi', category: 'speaking', chapter: 'chapter23', difficulty: 1, examples: ['Answer solves question.'] },
  { id: 'speaking11', english: 'Conversation', vietnamese: 'Cuộc trò chuyện', pronunciation: 'cuoc tro chuyen', category: 'speaking', chapter: 'chapter23', difficulty: 1, examples: ['Conversation flows naturally.'] },
  { id: 'speaking12', english: 'Discussion', vietnamese: 'Thảo luận', pronunciation: 'thao luan', category: 'speaking', chapter: 'chapter23', difficulty: 1, examples: ['Discussion explores ideas.'] },
  { id: 'speaking13', english: 'Argument', vietnamese: 'Tranh luận', pronunciation: 'tranh luan', category: 'speaking', chapter: 'chapter23', difficulty: 1, examples: ['Argument presents views.'] },
  { id: 'speaking14', english: 'Debate', vietnamese: 'Tranh cãi', pronunciation: 'tranh cai', category: 'speaking', chapter: 'chapter23', difficulty: 1, examples: ['Debate requires evidence.'] },
  { id: 'speaking15', english: 'Speech', vietnamese: 'Bài phát biểu', pronunciation: 'bai phat bieu', category: 'speaking', chapter: 'chapter23', difficulty: 1, examples: ['Speech inspires audience.'] },
  { id: 'speaking16', english: 'Presentation', vietnamese: 'Thuyết trình', pronunciation: 'thuyet trinh', category: 'speaking', chapter: 'chapter23', difficulty: 1, examples: ['Presentation informative clear.'] },
  { id: 'speaking17', english: 'Pronunciation', vietnamese: 'Phát âm', pronunciation: 'phat am', category: 'speaking', chapter: 'chapter23', difficulty: 1, examples: ['Pronunciation affects understanding.'] },
  { id: 'speaking18', english: 'Accent', vietnamese: 'Giọng', pronunciation: 'giong', category: 'speaking', chapter: 'chapter23', difficulty: 1, examples: ['Accent shows origin.'] },
  { id: 'speaking19', english: 'Fluent', vietnamese: 'Lưu loát', pronunciation: 'luu loat', category: 'speaking', chapter: 'chapter23', difficulty: 1, examples: ['Fluent speaker confident.'] },
  { id: 'speaking20', english: 'Explain', vietnamese: 'Giải thích', pronunciation: 'giai thich', category: 'speaking', chapter: 'chapter23', difficulty: 1, examples: ['Explain concept clearly.'] },
  { id: 'speaking21', english: 'Describe', vietnamese: 'Mô tả', pronunciation: 'mo ta', category: 'speaking', chapter: 'chapter23', difficulty: 1, examples: ['Describe scene detail.'] },
  { id: 'speaking22', english: 'Tell', vietnamese: 'Kể', pronunciation: 'ke', category: 'speaking', chapter: 'chapter23', difficulty: 1, examples: ['Tell interesting story.'] },
  { id: 'speaking23', english: 'Whisper', vietnamese: 'Thì thầm', pronunciation: 'thi tham', category: 'speaking', chapter: 'chapter23', difficulty: 1, examples: ['Whisper secret quietly.'] },
  { id: 'speaking24', english: 'Shout', vietnamese: 'Hét', pronunciation: 'het', category: 'speaking', chapter: 'chapter23', difficulty: 1, examples: ['Shout get attention.'] },
  { id: 'speaking25', english: 'Silent', vietnamese: 'Im lặng', pronunciation: 'im lang', category: 'speaking', chapter: 'chapter23', difficulty: 1, examples: ['Silent moment peaceful.'] },

  // Writing & Written Communication (25 words)
  { id: 'writing1', english: 'Writing', vietnamese: 'Viết', pronunciation: 'viet', category: 'writing', chapter: 'chapter23', difficulty: 1, examples: ['Writing preserves thoughts.'] },
  { id: 'writing2', english: 'Reading', vietnamese: 'Đọc', pronunciation: 'doc', category: 'writing', chapter: 'chapter23', difficulty: 1, examples: ['Reading expands knowledge.'] },
  { id: 'writing3', english: 'Text', vietnamese: 'Văn bản', pronunciation: 'van ban', category: 'writing', chapter: 'chapter23', difficulty: 1, examples: ['Text message short.'] },
  { id: 'writing4', english: 'Letter', vietnamese: 'Thư', pronunciation: 'thu', category: 'writing', chapter: 'chapter23', difficulty: 1, examples: ['Letter personal communication.'] },
  { id: 'writing5', english: 'Email', vietnamese: 'Thư điện tử', pronunciation: 'thu dien tu', category: 'writing', chapter: 'chapter23', difficulty: 1, examples: ['Email fast convenient.'] },
  { id: 'writing6', english: 'Message', vietnamese: 'Tin nhắn', pronunciation: 'tin nhan', category: 'writing', chapter: 'chapter23', difficulty: 1, examples: ['Message arrives quickly.'] },
  { id: 'writing7', english: 'Note', vietnamese: 'Ghi chú', pronunciation: 'ghi chu', category: 'writing', chapter: 'chapter23', difficulty: 1, examples: ['Note helps remember.'] },
  { id: 'writing8', english: 'Document', vietnamese: 'Tài liệu', pronunciation: 'tai lieu', category: 'writing', chapter: 'chapter23', difficulty: 1, examples: ['Document contains information.'] },
  { id: 'writing9', english: 'Report', vietnamese: 'Báo cáo', pronunciation: 'bao cao', category: 'writing', chapter: 'chapter23', difficulty: 1, examples: ['Report summarizes findings.'] },
  { id: 'writing10', english: 'Article', vietnamese: 'Bài viết', pronunciation: 'bai viet', category: 'writing', chapter: 'chapter23', difficulty: 1, examples: ['Article discusses topic.'] },
  { id: 'writing11', english: 'Essay', vietnamese: 'Bài luận', pronunciation: 'bai luan', category: 'writing', chapter: 'chapter23', difficulty: 1, examples: ['Essay expresses opinion.'] },
  { id: 'writing12', english: 'Story', vietnamese: 'Câu chuyện', pronunciation: 'cau chuyen', category: 'writing', chapter: 'chapter23', difficulty: 1, examples: ['Story entertains readers.'] },
  { id: 'writing13', english: 'Book', vietnamese: 'Sách', pronunciation: 'sach', category: 'writing', chapter: 'chapter23', difficulty: 1, examples: ['Book contains chapters.'] },
  { id: 'writing14', english: 'Page', vietnamese: 'Trang', pronunciation: 'trang', category: 'writing', chapter: 'chapter23', difficulty: 1, examples: ['Page holds text.'] },
  { id: 'writing15', english: 'Paragraph', vietnamese: 'Đoạn văn', pronunciation: 'doan van', category: 'writing', chapter: 'chapter23', difficulty: 1, examples: ['Paragraph groups sentences.'] },
  { id: 'writing16', english: 'Chapter', vietnamese: 'Chương', pronunciation: 'chuong', category: 'writing', chapter: 'chapter23', difficulty: 1, examples: ['Chapter divides book.'] },
  { id: 'writing17', english: 'Title', vietnamese: 'Tiêu đề', pronunciation: 'tieu de', category: 'writing', chapter: 'chapter23', difficulty: 1, examples: ['Title introduces content.'] },
  { id: 'writing18', english: 'Signature', vietnamese: 'Chữ ký', pronunciation: 'chu ky', category: 'writing', chapter: 'chapter23', difficulty: 1, examples: ['Signature proves identity.'] },
  { id: 'writing19', english: 'Handwriting', vietnamese: 'Chữ viết tay', pronunciation: 'chu viet tay', category: 'writing', chapter: 'chapter23', difficulty: 1, examples: ['Handwriting personal unique.'] },
  { id: 'writing20', english: 'Typing', vietnamese: 'Đánh máy', pronunciation: 'danh may', category: 'writing', chapter: 'chapter23', difficulty: 1, examples: ['Typing faster writing.'] },
  { id: 'writing21', english: 'Keyboard', vietnamese: 'Bàn phím', pronunciation: 'ban phim', category: 'writing', chapter: 'chapter23', difficulty: 1, examples: ['Keyboard input device.'] },
  { id: 'writing22', english: 'Pen', vietnamese: 'Bút', pronunciation: 'but', category: 'writing', chapter: 'chapter23', difficulty: 1, examples: ['Pen writes ink.'] },
  { id: 'writing23', english: 'Pencil', vietnamese: 'Bút chì', pronunciation: 'but chi', category: 'writing', chapter: 'chapter23', difficulty: 1, examples: ['Pencil erases easily.'] },
  { id: 'writing24', english: 'Paper', vietnamese: 'Giấy', pronunciation: 'giay', category: 'writing', chapter: 'chapter23', difficulty: 1, examples: ['Paper holds writing.'] },
  { id: 'writing25', english: 'Notebook', vietnamese: 'Sổ tay', pronunciation: 'so tay', category: 'writing', chapter: 'chapter23', difficulty: 1, examples: ['Notebook organizes notes.'] },

  // Learning & Education (25 words)
  { id: 'learning1', english: 'Learning', vietnamese: 'Học tập', pronunciation: 'hoc tap', category: 'learning', chapter: 'chapter23', difficulty: 1, examples: ['Learning improves skills.'] },
  { id: 'learning2', english: 'Study', vietnamese: 'Nghiên cứu', pronunciation: 'nghien cuu', category: 'learning', chapter: 'chapter23', difficulty: 1, examples: ['Study requires focus.'] },
  { id: 'learning3', english: 'Education', vietnamese: 'Giáo dục', pronunciation: 'giao duc', category: 'learning', chapter: 'chapter23', difficulty: 1, examples: ['Education opens opportunities.'] },
  { id: 'learning4', english: 'School', vietnamese: 'Trường học', pronunciation: 'truong hoc', category: 'learning', chapter: 'chapter23', difficulty: 1, examples: ['School teaches students.'] },
  { id: 'learning5', english: 'Class', vietnamese: 'Lớp học', pronunciation: 'lop hoc', category: 'learning', chapter: 'chapter23', difficulty: 1, examples: ['Class starts morning.'] },
  { id: 'learning6', english: 'Lesson', vietnamese: 'Bài học', pronunciation: 'bai hoc', category: 'learning', chapter: 'chapter23', difficulty: 1, examples: ['Lesson teaches concept.'] },
  { id: 'learning7', english: 'Course', vietnamese: 'Khóa học', pronunciation: 'khoa hoc', category: 'learning', chapter: 'chapter23', difficulty: 1, examples: ['Course covers subject.'] },
  { id: 'learning8', english: 'Subject', vietnamese: 'Môn học', pronunciation: 'mon hoc', category: 'learning', chapter: 'chapter23', difficulty: 1, examples: ['Math challenging subject.'] },
  { id: 'learning9', english: 'Homework', vietnamese: 'Bài tập về nhà', pronunciation: 'bai tap ve nha', category: 'learning', chapter: 'chapter23', difficulty: 1, examples: ['Homework reinforces learning.'] },
  { id: 'learning10', english: 'Test', vietnamese: 'Bài kiểm tra', pronunciation: 'bai kiem tra', category: 'learning', chapter: 'chapter23', difficulty: 1, examples: ['Test measures knowledge.'] },
  { id: 'learning11', english: 'Exam', vietnamese: 'Kỳ thi', pronunciation: 'ky thi', category: 'learning', chapter: 'chapter23', difficulty: 1, examples: ['Exam determines grade.'] },
  { id: 'learning12', english: 'Grade', vietnamese: 'Điểm số', pronunciation: 'diem so', category: 'learning', chapter: 'chapter23', difficulty: 1, examples: ['Grade reflects performance.'] },
  { id: 'learning13', english: 'Student', vietnamese: 'Học sinh', pronunciation: 'hoc sinh', category: 'learning', chapter: 'chapter23', difficulty: 1, examples: ['Student studies hard.'] },
  { id: 'learning14', english: 'Teacher', vietnamese: 'Giáo viên', pronunciation: 'giao vien', category: 'learning', chapter: 'chapter23', difficulty: 1, examples: ['Teacher explains lesson.'] },
  { id: 'learning15', english: 'Knowledge', vietnamese: 'Kiến thức', pronunciation: 'kien thuc', category: 'learning', chapter: 'chapter23', difficulty: 1, examples: ['Knowledge empowers people.'] },
  { id: 'learning16', english: 'Skill', vietnamese: 'Kỹ năng', pronunciation: 'ky nang', category: 'learning', chapter: 'chapter23', difficulty: 1, examples: ['Skill requires practice.'] },
  { id: 'learning17', english: 'Practice', vietnamese: 'Luyện tập', pronunciation: 'luyen tap', category: 'learning', chapter: 'chapter23', difficulty: 1, examples: ['Practice makes perfect.'] },
  { id: 'learning18', english: 'Memory', vietnamese: 'Trí nhớ', pronunciation: 'tri nho', category: 'learning', chapter: 'chapter23', difficulty: 1, examples: ['Memory stores information.'] },
  { id: 'learning19', english: 'Remember', vietnamese: 'Nhớ', pronunciation: 'nho', category: 'learning', chapter: 'chapter23', difficulty: 1, examples: ['Remember important facts.'] },
  { id: 'learning20', english: 'Forget', vietnamese: 'Quên', pronunciation: 'quen', category: 'learning', chapter: 'chapter23', difficulty: 1, examples: ['Forget unimportant details.'] },
  { id: 'learning21', english: 'Understand', vietnamese: 'Hiểu', pronunciation: 'hieu', category: 'learning', chapter: 'chapter23', difficulty: 1, examples: ['Understand complex ideas.'] },
  { id: 'learning22', english: 'Translate', vietnamese: 'Dịch', pronunciation: 'dich', category: 'learning', chapter: 'chapter23', difficulty: 1, examples: ['Translate between languages.'] },
  { id: 'learning23', english: 'Dictionary', vietnamese: 'Từ điển', pronunciation: 'tu dien', category: 'learning', chapter: 'chapter23', difficulty: 1, examples: ['Dictionary defines words.'] },
  { id: 'learning24', english: 'Grammar', vietnamese: 'Ngữ pháp', pronunciation: 'ngu phap', category: 'learning', chapter: 'chapter23', difficulty: 1, examples: ['Grammar rules language.'] },
  { id: 'learning25', english: 'Vocabulary', vietnamese: 'Từ vựng', pronunciation: 'tu vung', category: 'learning', chapter: 'chapter23', difficulty: 1, examples: ['Vocabulary expands expression.'] },

  // Technology & Modern Communication (25 words)
  { id: 'technology1', english: 'Technology', vietnamese: 'Công nghệ', pronunciation: 'cong nghe', category: 'technology', chapter: 'chapter23', difficulty: 1, examples: ['Technology advances rapidly.'] },
  { id: 'technology2', english: 'Computer', vietnamese: 'Máy tính', pronunciation: 'may tinh', category: 'technology', chapter: 'chapter23', difficulty: 1, examples: ['Computer processes information.'] },
  { id: 'technology3', english: 'Internet', vietnamese: 'Internet', pronunciation: 'internet', category: 'technology', chapter: 'chapter23', difficulty: 1, examples: ['Internet connects world.'] },
  { id: 'technology4', english: 'Website', vietnamese: 'Trang web', pronunciation: 'trang web', category: 'technology', chapter: 'chapter23', difficulty: 1, examples: ['Website provides information.'] },
  { id: 'technology5', english: 'Social media', vietnamese: 'Mạng xã hội', pronunciation: 'mang xa hoi', category: 'technology', chapter: 'chapter23', difficulty: 1, examples: ['Social media connects friends.'] },
  { id: 'technology6', english: 'Phone', vietnamese: 'Điện thoại', pronunciation: 'dien thoai', category: 'technology', chapter: 'chapter23', difficulty: 1, examples: ['Phone enables calls.'] },
  { id: 'technology7', english: 'Smartphone', vietnamese: 'Điện thoại thông minh', pronunciation: 'dien thoai thong minh', category: 'technology', chapter: 'chapter23', difficulty: 1, examples: ['Smartphone multiple functions.'] },
  { id: 'technology8', english: 'Video call', vietnamese: 'Gọi video', pronunciation: 'goi video', category: 'technology', chapter: 'chapter23', difficulty: 1, examples: ['Video call shows faces.'] },
  { id: 'technology9', english: 'Chat', vietnamese: 'Trò chuyện', pronunciation: 'tro chuyen', category: 'technology', chapter: 'chapter23', difficulty: 1, examples: ['Chat online convenient.'] },
  { id: 'technology10', english: 'Blog', vietnamese: 'Blog', pronunciation: 'blog', category: 'technology', chapter: 'chapter23', difficulty: 1, examples: ['Blog shares thoughts.'] },
  { id: 'technology11', english: 'Post', vietnamese: 'Đăng bài', pronunciation: 'dang bai', category: 'technology', chapter: 'chapter23', difficulty: 1, examples: ['Post updates status.'] },
  { id: 'technology12', english: 'Comment', vietnamese: 'Bình luận', pronunciation: 'binh luan', category: 'technology', chapter: 'chapter23', difficulty: 1, examples: ['Comment shares opinion.'] },
  { id: 'technology13', english: 'Like', vietnamese: 'Thích', pronunciation: 'thich', category: 'technology', chapter: 'chapter23', difficulty: 1, examples: ['Like shows approval.'] },
  { id: 'technology14', english: 'Share', vietnamese: 'Chia sẻ', pronunciation: 'chia se', category: 'technology', chapter: 'chapter23', difficulty: 1, examples: ['Share spreads content.'] },
  { id: 'technology15', english: 'Upload', vietnamese: 'Tải lên', pronunciation: 'tai len', category: 'technology', chapter: 'chapter23', difficulty: 1, examples: ['Upload photos online.'] },
  { id: 'technology16', english: 'Download', vietnamese: 'Tải xuống', pronunciation: 'tai xuong', category: 'technology', chapter: 'chapter23', difficulty: 1, examples: ['Download saves files.'] },
  { id: 'technology17', english: 'Search', vietnamese: 'Tìm kiếm', pronunciation: 'tim kiem', category: 'technology', chapter: 'chapter23', difficulty: 1, examples: ['Search finds information.'] },
  { id: 'technology18', english: 'Password', vietnamese: 'Mật khẩu', pronunciation: 'mat khau', category: 'technology', chapter: 'chapter23', difficulty: 1, examples: ['Password protects account.'] },
  { id: 'technology19', english: 'Username', vietnamese: 'Tên người dùng', pronunciation: 'ten nguoi dung', category: 'technology', chapter: 'chapter23', difficulty: 1, examples: ['Username identifies user.'] },
  { id: 'technology20', english: 'Profile', vietnamese: 'Hồ sơ', pronunciation: 'ho so', category: 'technology', chapter: 'chapter23', difficulty: 1, examples: ['Profile shows information.'] },
  { id: 'technology21', english: 'Notification', vietnamese: 'Thông báo', pronunciation: 'thong bao', category: 'technology', chapter: 'chapter23', difficulty: 1, examples: ['Notification alerts user.'] },
  { id: 'technology22', english: 'Update', vietnamese: 'Cập nhật', pronunciation: 'cap nhat', category: 'technology', chapter: 'chapter23', difficulty: 1, examples: ['Update improves software.'] },
  { id: 'technology23', english: 'App', vietnamese: 'Ứng dụng', pronunciation: 'ung dung', category: 'technology', chapter: 'chapter23', difficulty: 1, examples: ['App provides service.'] },
  { id: 'technology24', english: 'Software', vietnamese: 'Phần mềm', pronunciation: 'phan mem', category: 'technology', chapter: 'chapter23', difficulty: 1, examples: ['Software runs computer.'] },
  { id: 'technology25', english: 'Network', vietnamese: 'Mạng', pronunciation: 'mang', category: 'technology', chapter: 'chapter23', difficulty: 1, examples: ['Network connects devices.'] }
]
