// Chapter 13: Emotions & Feelings (100 Essential Words)
// Words related to emotions, feelings, moods, and psychological states

import { LanguageWord } from './chapter01-basic-everyday'

export const chapter13Words: LanguageWord[] = [
  // Basic Emotions (25 words)
  { id: 'emotion1', english: 'Happy', vietnamese: 'Vui', pronunciation: 'vui', category: 'emotion', chapter: 'chapter13', difficulty: 1, examples: ['Feel happy about success.'] },
  { id: 'emotion2', english: 'Sad', vietnamese: 'Buồn', pronunciation: 'buon', category: 'emotion', chapter: 'chapter13', difficulty: 1, examples: ['Feel sad about loss.'] },
  { id: 'emotion3', english: 'Angry', vietnamese: 'Tức giận', pronunciation: 'tuc gian', category: 'emotion', chapter: 'chapter13', difficulty: 1, examples: ['Get angry at unfairness.'] },
  { id: 'emotion4', english: 'Excited', vietnamese: 'Phấn khích', pronunciation: 'phan khich', category: 'emotion', chapter: 'chapter13', difficulty: 1, examples: ['Excited about vacation.'] },
  { id: 'emotion5', english: 'Worried', vietnamese: 'Lo lắng', pronunciation: 'lo lang', category: 'emotion', chapter: 'chapter13', difficulty: 1, examples: ['Worried about exam results.'] },
  { id: 'emotion6', english: 'Scared', vietnamese: 'Sợ hãi', pronunciation: 'so hai', category: 'emotion', chapter: 'chapter13', difficulty: 1, examples: ['Scared of dark places.'] },
  { id: 'emotion7', english: 'Surprised', vietnamese: 'Ngạc nhiên', pronunciation: 'ngac nhien', category: 'emotion', chapter: 'chapter13', difficulty: 1, examples: ['Surprised by unexpected gift.'] },
  { id: 'emotion8', english: 'Confused', vietnamese: 'Bối rối', pronunciation: 'boi roi', category: 'emotion', chapter: 'chapter13', difficulty: 1, examples: ['Confused about directions.'] },
  { id: 'emotion9', english: 'Disappointed', vietnamese: 'Thất vọng', pronunciation: 'that vong', category: 'emotion', chapter: 'chapter13', difficulty: 1, examples: ['Disappointed with results.'] },
  { id: 'emotion10', english: 'Relieved', vietnamese: 'Nhẹ nhõm', pronunciation: 'nhe nhom', category: 'emotion', chapter: 'chapter13', difficulty: 1, examples: ['Relieved after exam.'] },
  { id: 'emotion11', english: 'Embarrassed', vietnamese: 'Xấu hổ', pronunciation: 'xau ho', category: 'emotion', chapter: 'chapter13', difficulty: 1, examples: ['Embarrassed by mistake.'] },
  { id: 'emotion12', english: 'Proud', vietnamese: 'Tự hào', pronunciation: 'tu hao', category: 'emotion', chapter: 'chapter13', difficulty: 1, examples: ['Proud of achievements.'] },
  { id: 'emotion13', english: 'Jealous', vietnamese: 'Ghen tị', pronunciation: 'ghen ti', category: 'emotion', chapter: 'chapter13', difficulty: 1, examples: ['Jealous of success.'] },
  { id: 'emotion14', english: 'Lonely', vietnamese: 'Cô đơn', pronunciation: 'co don', category: 'emotion', chapter: 'chapter13', difficulty: 1, examples: ['Feel lonely without friends.'] },
  { id: 'emotion15', english: 'Grateful', vietnamese: 'Biết ơn', pronunciation: 'biet on', category: 'emotion', chapter: 'chapter13', difficulty: 1, examples: ['Grateful for help.'] },
  { id: 'emotion16', english: 'Curious', vietnamese: 'Tò mò', pronunciation: 'to mo', category: 'emotion', chapter: 'chapter13', difficulty: 1, examples: ['Curious about new places.'] },
  { id: 'emotion17', english: 'Nervous', vietnamese: 'Lo lắng', pronunciation: 'lo lang', category: 'emotion', chapter: 'chapter13', difficulty: 1, examples: ['Nervous before interview.'] },
  { id: 'emotion18', english: 'Calm', vietnamese: 'Bình tĩnh', pronunciation: 'binh tinh', category: 'emotion', chapter: 'chapter13', difficulty: 1, examples: ['Stay calm under pressure.'] },
  { id: 'emotion19', english: 'Stressed', vietnamese: 'Căng thẳng', pronunciation: 'cang thang', category: 'emotion', chapter: 'chapter13', difficulty: 1, examples: ['Stressed about deadlines.'] },
  { id: 'emotion20', english: 'Relaxed', vietnamese: 'Thư giãn', pronunciation: 'thu gian', category: 'emotion', chapter: 'chapter13', difficulty: 1, examples: ['Relaxed during vacation.'] },
  { id: 'emotion21', english: 'Confident', vietnamese: 'Tự tin', pronunciation: 'tu tin', category: 'emotion', chapter: 'chapter13', difficulty: 1, examples: ['Confident about abilities.'] },
  { id: 'emotion22', english: 'Shy', vietnamese: 'Ngại ngùng', pronunciation: 'ngai ngung', category: 'emotion', chapter: 'chapter13', difficulty: 1, examples: ['Too shy to speak.'] },
  { id: 'emotion23', english: 'Brave', vietnamese: 'Dũng cảm', pronunciation: 'dung cam', category: 'emotion', chapter: 'chapter13', difficulty: 1, examples: ['Brave enough to try.'] },
  { id: 'emotion24', english: 'Hopeful', vietnamese: 'Hy vọng', pronunciation: 'hy vong', category: 'emotion', chapter: 'chapter13', difficulty: 1, examples: ['Hopeful for better future.'] },
  { id: 'emotion25', english: 'Hopeless', vietnamese: 'Tuyệt vọng', pronunciation: 'tuyet vong', category: 'emotion', chapter: 'chapter13', difficulty: 1, examples: ['Never feel hopeless.'] },

  // Positive Feelings (25 words)
  { id: 'positive1', english: 'Joyful', vietnamese: 'Vui mừng', pronunciation: 'vui mung', category: 'positive', chapter: 'chapter13', difficulty: 1, examples: ['Joyful celebration with family.'] },
  { id: 'positive2', english: 'Cheerful', vietnamese: 'Vui vẻ', pronunciation: 'vui ve', category: 'positive', chapter: 'chapter13', difficulty: 1, examples: ['Cheerful attitude helps.'] },
  { id: 'positive3', english: 'Delighted', vietnamese: 'Thích thú', pronunciation: 'thich thu', category: 'positive', chapter: 'chapter13', difficulty: 1, examples: ['Delighted with surprise.'] },
  { id: 'positive4', english: 'Thrilled', vietnamese: 'Hào hứng', pronunciation: 'hao hung', category: 'positive', chapter: 'chapter13', difficulty: 1, examples: ['Thrilled about opportunity.'] },
  { id: 'positive5', english: 'Elated', vietnamese: 'Phấn khởi', pronunciation: 'phan khoi', category: 'positive', chapter: 'chapter13', difficulty: 2, examples: ['Elated by good news.'] },
  { id: 'positive6', english: 'Ecstatic', vietnamese: 'Cực kỳ vui', pronunciation: 'cuc ky vui', category: 'positive', chapter: 'chapter13', difficulty: 2, examples: ['Ecstatic about promotion.'] },
  { id: 'positive7', english: 'Content', vietnamese: 'Hài lòng', pronunciation: 'hai long', category: 'positive', chapter: 'chapter13', difficulty: 1, examples: ['Content with simple life.'] },
  { id: 'positive8', english: 'Satisfied', vietnamese: 'Hài lòng', pronunciation: 'hai long', category: 'positive', chapter: 'chapter13', difficulty: 1, examples: ['Satisfied with results.'] },
  { id: 'positive9', english: 'Pleased', vietnamese: 'Hài lòng', pronunciation: 'hai long', category: 'positive', chapter: 'chapter13', difficulty: 1, examples: ['Pleased with progress.'] },
  { id: 'positive10', english: 'Amazed', vietnamese: 'Kinh ngạc', pronunciation: 'kinh ngac', category: 'positive', chapter: 'chapter13', difficulty: 1, examples: ['Amazed by beautiful view.'] },
  { id: 'positive11', english: 'Impressed', vietnamese: 'Ấn tượng', pronunciation: 'an tuong', category: 'positive', chapter: 'chapter13', difficulty: 1, examples: ['Impressed by performance.'] },
  { id: 'positive12', english: 'Inspired', vietnamese: 'Được truyền cảm hứng', pronunciation: 'duoc truyen cam hung', category: 'positive', chapter: 'chapter13', difficulty: 1, examples: ['Inspired by success story.'] },
  { id: 'positive13', english: 'Motivated', vietnamese: 'Có động lực', pronunciation: 'co dong luc', category: 'positive', chapter: 'chapter13', difficulty: 1, examples: ['Motivated to work harder.'] },
  { id: 'positive14', english: 'Enthusiastic', vietnamese: 'Nhiệt tình', pronunciation: 'nhiet tinh', category: 'positive', chapter: 'chapter13', difficulty: 1, examples: ['Enthusiastic about project.'] },
  { id: 'positive15', english: 'Optimistic', vietnamese: 'Lạc quan', pronunciation: 'lac quan', category: 'positive', chapter: 'chapter13', difficulty: 1, examples: ['Optimistic about future.'] },
  { id: 'positive16', english: 'Peaceful', vietnamese: 'Bình yên', pronunciation: 'binh yen', category: 'positive', chapter: 'chapter13', difficulty: 1, examples: ['Peaceful moment in garden.'] },
  { id: 'positive17', english: 'Comfortable', vietnamese: 'Thoải mái', pronunciation: 'thoai mai', category: 'positive', chapter: 'chapter13', difficulty: 1, examples: ['Comfortable in new home.'] },
  { id: 'positive18', english: 'Refreshed', vietnamese: 'Sảng khoái', pronunciation: 'sang khoai', category: 'positive', chapter: 'chapter13', difficulty: 1, examples: ['Refreshed after sleep.'] },
  { id: 'positive19', english: 'Energetic', vietnamese: 'Năng động', pronunciation: 'nang dong', category: 'positive', chapter: 'chapter13', difficulty: 1, examples: ['Feel energetic this morning.'] },
  { id: 'positive20', english: 'Loving', vietnamese: 'Yêu thương', pronunciation: 'yeu thuong', category: 'positive', chapter: 'chapter13', difficulty: 1, examples: ['Loving family relationship.'] },
  { id: 'positive21', english: 'Affectionate', vietnamese: 'Trìu mến', pronunciation: 'triu men', category: 'positive', chapter: 'chapter13', difficulty: 2, examples: ['Affectionate toward pets.'] },
  { id: 'positive22', english: 'Tender', vietnamese: 'Dịu dàng', pronunciation: 'diu dang', category: 'positive', chapter: 'chapter13', difficulty: 1, examples: ['Tender care for children.'] },
  { id: 'positive23', english: 'Compassionate', vietnamese: 'Từ bi', pronunciation: 'tu bi', category: 'positive', chapter: 'chapter13', difficulty: 2, examples: ['Compassionate toward others.'] },
  { id: 'positive24', english: 'Kind', vietnamese: 'Tử tế', pronunciation: 'tu te', category: 'positive', chapter: 'chapter13', difficulty: 1, examples: ['Kind gesture helps.'] },
  { id: 'positive25', english: 'Generous', vietnamese: 'Hào phóng', pronunciation: 'hao phong', category: 'positive', chapter: 'chapter13', difficulty: 1, examples: ['Generous with time.'] },

  // Negative Feelings (25 words)
  { id: 'negative1', english: 'Depressed', vietnamese: 'Chán nản', pronunciation: 'chan nan', category: 'negative', chapter: 'chapter13', difficulty: 1, examples: ['Feeling depressed lately.'] },
  { id: 'negative2', english: 'Upset', vietnamese: 'Buồn bã', pronunciation: 'buon ba', category: 'negative', chapter: 'chapter13', difficulty: 1, examples: ['Upset about argument.'] },
  { id: 'negative3', english: 'Frustrated', vietnamese: 'Bực bội', pronunciation: 'buc boi', category: 'negative', chapter: 'chapter13', difficulty: 1, examples: ['Frustrated with delays.'] },
  { id: 'negative4', english: 'Annoyed', vietnamese: 'Khó chịu', pronunciation: 'kho chiu', category: 'negative', chapter: 'chapter13', difficulty: 1, examples: ['Annoyed by noise.'] },
  { id: 'negative5', english: 'Irritated', vietnamese: 'Cáu kỉnh', pronunciation: 'cau kinh', category: 'negative', chapter: 'chapter13', difficulty: 1, examples: ['Irritated by interruptions.'] },
  { id: 'negative6', english: 'Furious', vietnamese: 'Giận dữ', pronunciation: 'gian du', category: 'negative', chapter: 'chapter13', difficulty: 1, examples: ['Furious about injustice.'] },
  { id: 'negative7', english: 'Disgusted', vietnamese: 'Ghê tởm', pronunciation: 'ghe tom', category: 'negative', chapter: 'chapter13', difficulty: 1, examples: ['Disgusted by bad behavior.'] },
  { id: 'negative8', english: 'Horrified', vietnamese: 'Kinh hoàng', pronunciation: 'kinh hoang', category: 'negative', chapter: 'chapter13', difficulty: 1, examples: ['Horrified by accident.'] },
  { id: 'negative9', english: 'Terrified', vietnamese: 'Khiếp sợ', pronunciation: 'khiep so', category: 'negative', chapter: 'chapter13', difficulty: 1, examples: ['Terrified of heights.'] },
  { id: 'negative10', english: 'Anxious', vietnamese: 'Lo âu', pronunciation: 'lo au', category: 'negative', chapter: 'chapter13', difficulty: 1, examples: ['Anxious about test.'] },
  { id: 'negative11', english: 'Panicked', vietnamese: 'Hoảng sợ', pronunciation: 'hoang so', category: 'negative', chapter: 'chapter13', difficulty: 1, examples: ['Panicked in emergency.'] },
  { id: 'negative12', english: 'Overwhelmed', vietnamese: 'Choáng ngợp', pronunciation: 'choang ngop', category: 'negative', chapter: 'chapter13', difficulty: 1, examples: ['Overwhelmed by work.'] },
  { id: 'negative13', english: 'Exhausted', vietnamese: 'Kiệt sức', pronunciation: 'kiet suc', category: 'negative', chapter: 'chapter13', difficulty: 1, examples: ['Exhausted after marathon.'] },
  { id: 'negative14', english: 'Drained', vietnamese: 'Cạn kiệt', pronunciation: 'can kiet', category: 'negative', chapter: 'chapter13', difficulty: 1, examples: ['Emotionally drained today.'] },
  { id: 'negative15', english: 'Bitter', vietnamese: 'Cay đắng', pronunciation: 'cay dang', category: 'negative', chapter: 'chapter13', difficulty: 1, examples: ['Bitter about betrayal.'] },
  { id: 'negative16', english: 'Resentful', vietnamese: 'Oán giận', pronunciation: 'oan gian', category: 'negative', chapter: 'chapter13', difficulty: 2, examples: ['Resentful toward unfairness.'] },
  { id: 'negative17', english: 'Guilty', vietnamese: 'Cảm thấy tội lỗi', pronunciation: 'cam thay toi loi', category: 'negative', chapter: 'chapter13', difficulty: 1, examples: ['Guilty about mistake.'] },
  { id: 'negative18', english: 'Ashamed', vietnamese: 'Xấu hổ', pronunciation: 'xau ho', category: 'negative', chapter: 'chapter13', difficulty: 1, examples: ['Ashamed of behavior.'] },
  { id: 'negative19', english: 'Regretful', vietnamese: 'Hối hận', pronunciation: 'hoi han', category: 'negative', chapter: 'chapter13', difficulty: 1, examples: ['Regretful about decision.'] },
  { id: 'negative20', english: 'Devastated', vietnamese: 'Tan nát', pronunciation: 'tan nat', category: 'negative', chapter: 'chapter13', difficulty: 2, examples: ['Devastated by loss.'] },
  { id: 'negative21', english: 'Heartbroken', vietnamese: 'Đau lòng', pronunciation: 'dau long', category: 'negative', chapter: 'chapter13', difficulty: 1, examples: ['Heartbroken after breakup.'] },
  { id: 'negative22', english: 'Miserable', vietnamese: 'Khổ sở', pronunciation: 'kho so', category: 'negative', chapter: 'chapter13', difficulty: 1, examples: ['Miserable in bad weather.'] },
  { id: 'negative23', english: 'Gloomy', vietnamese: 'Ủ rũ', pronunciation: 'u ru', category: 'negative', chapter: 'chapter13', difficulty: 1, examples: ['Gloomy mood today.'] },
  { id: 'negative24', english: 'Pessimistic', vietnamese: 'Bi quan', pronunciation: 'bi quan', category: 'negative', chapter: 'chapter13', difficulty: 1, examples: ['Pessimistic about chances.'] },
  { id: 'negative25', english: 'Cynical', vietnamese: 'Hoài nghi', pronunciation: 'hoai nghi', category: 'negative', chapter: 'chapter13', difficulty: 2, examples: ['Cynical about promises.'] },

  // Mental States & Expressions (25 words)
  { id: 'mental1', english: 'Feel', vietnamese: 'Cảm thấy', pronunciation: 'cam thay', category: 'mental', chapter: 'chapter13', difficulty: 1, examples: ['Feel good about choice.'] },
  { id: 'mental2', english: 'Emotion', vietnamese: 'Cảm xúc', pronunciation: 'cam xuc', category: 'mental', chapter: 'chapter13', difficulty: 1, examples: ['Control strong emotions.'] },
  { id: 'mental3', english: 'Feeling', vietnamese: 'Cảm giác', pronunciation: 'cam giac', category: 'mental', chapter: 'chapter13', difficulty: 1, examples: ['Strange feeling inside.'] },
  { id: 'mental4', english: 'Mood', vietnamese: 'Tâm trạng', pronunciation: 'tam trang', category: 'mental', chapter: 'chapter13', difficulty: 1, examples: ['Good mood all day.'] },
  { id: 'mental5', english: 'Attitude', vietnamese: 'Thái độ', pronunciation: 'thai do', category: 'mental', chapter: 'chapter13', difficulty: 1, examples: ['Positive attitude helps.'] },
  { id: 'mental6', english: 'Spirit', vietnamese: 'Tinh thần', pronunciation: 'tinh than', category: 'mental', chapter: 'chapter13', difficulty: 1, examples: ['High spirit today.'] },
  { id: 'mental7', english: 'Heart', vietnamese: 'Trái tim', pronunciation: 'trai tim', category: 'mental', chapter: 'chapter13', difficulty: 1, examples: ['Speak from heart.'] },
  { id: 'mental8', english: 'Mind', vietnamese: 'Tâm trí', pronunciation: 'tam tri', category: 'mental', chapter: 'chapter13', difficulty: 1, examples: ['Clear mind thinks better.'] },
  { id: 'mental9', english: 'Soul', vietnamese: 'Linh hồn', pronunciation: 'linh hon', category: 'mental', chapter: 'chapter13', difficulty: 1, examples: ['Music touches soul.'] },
  { id: 'mental10', english: 'Personality', vietnamese: 'Tính cách', pronunciation: 'tinh cach', category: 'mental', chapter: 'chapter13', difficulty: 1, examples: ['Friendly personality attracts.'] },
  { id: 'mental11', english: 'Character', vietnamese: 'Nhân cách', pronunciation: 'nhan cach', category: 'mental', chapter: 'chapter13', difficulty: 1, examples: ['Strong character endures.'] },
  { id: 'mental12', english: 'Temperament', vietnamese: 'Khí chất', pronunciation: 'khi chat', category: 'mental', chapter: 'chapter13', difficulty: 2, examples: ['Calm temperament helps.'] },
  { id: 'mental13', english: 'Sensitivity', vietnamese: 'Sự nhạy cảm', pronunciation: 'su nhay cam', category: 'mental', chapter: 'chapter13', difficulty: 2, examples: ['High sensitivity to criticism.'] },
  { id: 'mental14', english: 'Empathy', vietnamese: 'Sự đồng cảm', pronunciation: 'su dong cam', category: 'mental', chapter: 'chapter13', difficulty: 2, examples: ['Show empathy for others.'] },
  { id: 'mental15', english: 'Sympathy', vietnamese: 'Sự thông cảm', pronunciation: 'su thong cam', category: 'mental', chapter: 'chapter13', difficulty: 1, examples: ['Express sympathy for loss.'] },
  { id: 'mental16', english: 'Compassion', vietnamese: 'Lòng thương', pronunciation: 'long thuong', category: 'mental', chapter: 'chapter13', difficulty: 1, examples: ['Show compassion for suffering.'] },
  { id: 'mental17', english: 'Understanding', vietnamese: 'Sự hiểu biết', pronunciation: 'su hieu biet', category: 'mental', chapter: 'chapter13', difficulty: 1, examples: ['Deep understanding of problems.'] },
  { id: 'mental18', english: 'Patience', vietnamese: 'Sự kiên nhẫn', pronunciation: 'su kien nhan', category: 'mental', chapter: 'chapter13', difficulty: 1, examples: ['Patience brings success.'] },
  { id: 'mental19', english: 'Tolerance', vietnamese: 'Sự khoan dung', pronunciation: 'su khoan dung', category: 'mental', chapter: 'chapter13', difficulty: 2, examples: ['Tolerance for differences.'] },
  { id: 'mental20', english: 'Acceptance', vietnamese: 'Sự chấp nhận', pronunciation: 'su chap nhan', category: 'mental', chapter: 'chapter13', difficulty: 1, examples: ['Acceptance of reality.'] },
  { id: 'mental21', english: 'Denial', vietnamese: 'Sự từ chối', pronunciation: 'su tu choi', category: 'mental', chapter: 'chapter13', difficulty: 1, examples: ['Denial of obvious truth.'] },
  { id: 'mental22', english: 'Awareness', vietnamese: 'Sự nhận thức', pronunciation: 'su nhan thuc', category: 'mental', chapter: 'chapter13', difficulty: 1, examples: ['Self-awareness improves life.'] },
  { id: 'mental23', english: 'Consciousness', vietnamese: 'Ý thức', pronunciation: 'y thuc', category: 'mental', chapter: 'chapter13', difficulty: 2, examples: ['Higher consciousness level.'] },
  { id: 'mental24', english: 'Instinct', vietnamese: 'Bản năng', pronunciation: 'ban nang', category: 'mental', chapter: 'chapter13', difficulty: 1, examples: ['Trust your instinct.'] },
  { id: 'mental25', english: 'Intuition', vietnamese: 'Trực giác', pronunciation: 'truc giac', category: 'mental', chapter: 'chapter13', difficulty: 2, examples: ['Follow intuition sometimes.'] }
]
