// Chapter 18: Hobbies & Entertainment (100 Essential Words)
// Words related to leisure activities, hobbies, entertainment, and recreational pursuits

import { LanguageWord } from './chapter01-basic-everyday'

export const chapter18Words: LanguageWord[] = [
  // Creative Hobbies (25 words)
  { id: 'creative1', english: 'Hobby', vietnamese: 'Sở thích', pronunciation: 'so thich', category: 'creative', chapter: 'chapter18', difficulty: 1, examples: ['Reading is favorite hobby.'] },
  { id: 'creative2', english: 'Art', vietnamese: 'Nghệ thuật', pronunciation: 'nghe thuat', category: 'creative', chapter: 'chapter18', difficulty: 1, examples: ['Art expresses creativity.'] },
  { id: 'creative3', english: 'Drawing', vietnamese: 'Vẽ', pronunciation: 've', category: 'creative', chapter: 'chapter18', difficulty: 1, examples: ['Drawing improves skills.'] },
  { id: 'creative4', english: 'Painting', vietnamese: 'Vẽ tranh', pronunciation: 've tranh', category: 'creative', chapter: 'chapter18', difficulty: 1, examples: ['Painting landscapes beautiful.'] },
  { id: 'creative5', english: 'Sculpture', vietnamese: 'Điêu khắc', pronunciation: 'dieu khac', category: 'creative', chapter: 'chapter18', difficulty: 2, examples: ['Sculpture requires patience.'] },
  { id: 'creative6', english: 'Photography', vietnamese: 'Chụp ảnh', pronunciation: 'chup anh', category: 'creative', chapter: 'chapter18', difficulty: 1, examples: ['Photography captures moments.'] },
  { id: 'creative7', english: 'Writing', vietnamese: 'Viết', pronunciation: 'viet', category: 'creative', chapter: 'chapter18', difficulty: 1, examples: ['Writing stories imaginative.'] },
  { id: 'creative8', english: 'Poetry', vietnamese: 'Thơ', pronunciation: 'tho', category: 'creative', chapter: 'chapter18', difficulty: 1, examples: ['Poetry expresses emotions.'] },
  { id: 'creative9', english: 'Crafts', vietnamese: 'Thủ công', pronunciation: 'thu cong', category: 'creative', chapter: 'chapter18', difficulty: 1, examples: ['Arts and crafts fun.'] },
  { id: 'creative10', english: 'Knitting', vietnamese: 'Đan len', pronunciation: 'dan len', category: 'creative', chapter: 'chapter18', difficulty: 1, examples: ['Knitting sweaters warm.'] },
  { id: 'creative11', english: 'Sewing', vietnamese: 'May vá', pronunciation: 'may va', category: 'creative', chapter: 'chapter18', difficulty: 1, examples: ['Sewing clothes practical.'] },
  { id: 'creative12', english: 'Embroidery', vietnamese: 'Thêu', pronunciation: 'theu', category: 'creative', chapter: 'chapter18', difficulty: 2, examples: ['Embroidery patterns intricate.'] },
  { id: 'creative13', english: 'Origami', vietnamese: 'Nghệ thuật gấp giấy', pronunciation: 'nghe thuat gap giay', category: 'creative', chapter: 'chapter18', difficulty: 2, examples: ['Origami requires precision.'] },
  { id: 'creative14', english: 'Pottery', vietnamese: 'Gốm sứ', pronunciation: 'gom su', category: 'creative', chapter: 'chapter18', difficulty: 2, examples: ['Pottery making therapeutic.'] },
  { id: 'creative15', english: 'Woodworking', vietnamese: 'Chế tác gỗ', pronunciation: 'che tac go', category: 'creative', chapter: 'chapter18', difficulty: 2, examples: ['Woodworking creates furniture.'] },
  { id: 'creative16', english: 'Jewelry making', vietnamese: 'Làm trang sức', pronunciation: 'lam trang suc', category: 'creative', chapter: 'chapter18', difficulty: 2, examples: ['Jewelry making artistic.'] },
  { id: 'creative17', english: 'Scrapbooking', vietnamese: 'Làm album kỷ niệm', pronunciation: 'lam album ky niem', category: 'creative', chapter: 'chapter18', difficulty: 2, examples: ['Scrapbooking preserves memories.'] },
  { id: 'creative18', english: 'Calligraphy', vietnamese: 'Thư pháp', pronunciation: 'thu phap', category: 'creative', chapter: 'chapter18', difficulty: 2, examples: ['Calligraphy elegant writing.'] },
  { id: 'creative19', english: 'Sketching', vietnamese: 'Phác họa', pronunciation: 'phac hoa', category: 'creative', chapter: 'chapter18', difficulty: 1, examples: ['Sketching quick drawings.'] },
  { id: 'creative20', english: 'Decorating', vietnamese: 'Trang trí', pronunciation: 'trang tri', category: 'creative', chapter: 'chapter18', difficulty: 1, examples: ['Decorating house beautiful.'] },
  { id: 'creative21', english: 'Design', vietnamese: 'Thiết kế', pronunciation: 'thiet ke', category: 'creative', chapter: 'chapter18', difficulty: 1, examples: ['Design requires creativity.'] },
  { id: 'creative22', english: 'Collecting', vietnamese: 'Sưu tập', pronunciation: 'suu tap', category: 'creative', chapter: 'chapter18', difficulty: 1, examples: ['Collecting stamps interesting.'] },
  { id: 'creative23', english: 'Building', vietnamese: 'Xây dựng', pronunciation: 'xay dung', category: 'creative', chapter: 'chapter18', difficulty: 1, examples: ['Building models detailed.'] },
  { id: 'creative24', english: 'Creating', vietnamese: 'Sáng tạo', pronunciation: 'sang tao', category: 'creative', chapter: 'chapter18', difficulty: 1, examples: ['Creating art fulfilling.'] },
  { id: 'creative25', english: 'Making', vietnamese: 'Làm', pronunciation: 'lam', category: 'creative', chapter: 'chapter18', difficulty: 1, examples: ['Making crafts enjoyable.'] },

  // Music & Performance (25 words)
  { id: 'music1', english: 'Music', vietnamese: 'Âm nhạc', pronunciation: 'am nhac', category: 'music', chapter: 'chapter18', difficulty: 1, examples: ['Music soothes soul.'] },
  { id: 'music2', english: 'Singing', vietnamese: 'Hát', pronunciation: 'hat', category: 'music', chapter: 'chapter18', difficulty: 1, examples: ['Singing brings joy.'] },
  { id: 'music3', english: 'Dancing', vietnamese: 'Khiêu vũ', pronunciation: 'khieu vu', category: 'music', chapter: 'chapter18', difficulty: 1, examples: ['Dancing expresses rhythm.'] },
  { id: 'music4', english: 'Playing instrument', vietnamese: 'Chơi nhạc cụ', pronunciation: 'choi nhac cu', category: 'music', chapter: 'chapter18', difficulty: 1, examples: ['Playing piano relaxing.'] },
  { id: 'music5', english: 'Piano', vietnamese: 'Đàn piano', pronunciation: 'dan piano', category: 'music', chapter: 'chapter18', difficulty: 1, examples: ['Piano lessons weekly.'] },
  { id: 'music6', english: 'Guitar', vietnamese: 'Đàn guitar', pronunciation: 'dan guitar', category: 'music', chapter: 'chapter18', difficulty: 1, examples: ['Guitar chords difficult.'] },
  { id: 'music7', english: 'Violin', vietnamese: 'Đàn violin', pronunciation: 'dan violin', category: 'music', chapter: 'chapter18', difficulty: 1, examples: ['Violin sounds beautiful.'] },
  { id: 'music8', english: 'Drums', vietnamese: 'Trống', pronunciation: 'trong', category: 'music', chapter: 'chapter18', difficulty: 1, examples: ['Drums keep rhythm.'] },
  { id: 'music9', english: 'Flute', vietnamese: 'Sáo', pronunciation: 'sao', category: 'music', chapter: 'chapter18', difficulty: 1, examples: ['Flute melody gentle.'] },
  { id: 'music10', english: 'Saxophone', vietnamese: 'Saxophone', pronunciation: 'saxophone', category: 'music', chapter: 'chapter18', difficulty: 1, examples: ['Saxophone jazz sound.'] },
  { id: 'music11', english: 'Trumpet', vietnamese: 'Kèn trumpet', pronunciation: 'ken trumpet', category: 'music', chapter: 'chapter18', difficulty: 1, examples: ['Trumpet plays loudly.'] },
  { id: 'music12', english: 'Harmonica', vietnamese: 'Kèn harmonica', pronunciation: 'ken harmonica', category: 'music', chapter: 'chapter18', difficulty: 1, examples: ['Harmonica portable instrument.'] },
  { id: 'music13', english: 'Concert', vietnamese: 'Hòa nhạc', pronunciation: 'hoa nhac', category: 'music', chapter: 'chapter18', difficulty: 1, examples: ['Concert tickets expensive.'] },
  { id: 'music14', english: 'Performance', vietnamese: 'Biểu diễn', pronunciation: 'bieu dien', category: 'music', chapter: 'chapter18', difficulty: 1, examples: ['Performance impressed audience.'] },
  { id: 'music15', english: 'Orchestra', vietnamese: 'Dàn nhạc', pronunciation: 'dan nhac', category: 'music', chapter: 'chapter18', difficulty: 2, examples: ['Orchestra plays symphony.'] },
  { id: 'music16', english: 'Band', vietnamese: 'Ban nhạc', pronunciation: 'ban nhac', category: 'music', chapter: 'chapter18', difficulty: 1, examples: ['Rock band popular.'] },
  { id: 'music17', english: 'Choir', vietnamese: 'Dàn hợp xướng', pronunciation: 'dan hop xuong', category: 'music', chapter: 'chapter18', difficulty: 2, examples: ['Church choir sings.'] },
  { id: 'music18', english: 'Solo', vietnamese: 'Độc tấu', pronunciation: 'doc tau', category: 'music', chapter: 'chapter18', difficulty: 2, examples: ['Piano solo beautiful.'] },
  { id: 'music19', english: 'Duet', vietnamese: 'Song ca', pronunciation: 'song ca', category: 'music', chapter: 'chapter18', difficulty: 2, examples: ['Duet harmony perfect.'] },
  { id: 'music20', english: 'Karaoke', vietnamese: 'Karaoke', pronunciation: 'karaoke', category: 'music', chapter: 'chapter18', difficulty: 1, examples: ['Karaoke night fun.'] },
  { id: 'music21', english: 'Theater', vietnamese: 'Nhà hát', pronunciation: 'nha hat', category: 'music', chapter: 'chapter18', difficulty: 1, examples: ['Theater show entertaining.'] },
  { id: 'music22', english: 'Acting', vietnamese: 'Diễn xuất', pronunciation: 'dien xuat', category: 'music', chapter: 'chapter18', difficulty: 1, examples: ['Acting requires talent.'] },
  { id: 'music23', english: 'Comedy', vietnamese: 'Hài kịch', pronunciation: 'hai kich', category: 'music', chapter: 'chapter18', difficulty: 1, examples: ['Comedy makes laugh.'] },
  { id: 'music24', english: 'Drama', vietnamese: 'Kịch', pronunciation: 'kich', category: 'music', chapter: 'chapter18', difficulty: 1, examples: ['Drama tells stories.'] },
  { id: 'music25', english: 'Musical', vietnamese: 'Nhạc kịch', pronunciation: 'nhac kich', category: 'music', chapter: 'chapter18', difficulty: 1, examples: ['Musical combines singing.'] },

  // Games & Sports (25 words)
  { id: 'game1', english: 'Game', vietnamese: 'Trò chơi', pronunciation: 'tro choi', category: 'game', chapter: 'chapter18', difficulty: 1, examples: ['Board game family.'] },
  { id: 'game2', english: 'Video games', vietnamese: 'Trò chơi điện tử', pronunciation: 'tro choi dien tu', category: 'game', chapter: 'chapter18', difficulty: 1, examples: ['Video games popular.'] },
  { id: 'game3', english: 'Board games', vietnamese: 'Trò chơi bàn cờ', pronunciation: 'tro choi ban co', category: 'game', chapter: 'chapter18', difficulty: 1, examples: ['Board games strategic.'] },
  { id: 'game4', english: 'Card games', vietnamese: 'Trò chơi bài', pronunciation: 'tro choi bai', category: 'game', chapter: 'chapter18', difficulty: 1, examples: ['Card games social.'] },
  { id: 'game5', english: 'Puzzle', vietnamese: 'Trò chơi xếp hình', pronunciation: 'tro choi xep hinh', category: 'game', chapter: 'chapter18', difficulty: 1, examples: ['Puzzle challenges mind.'] },
  { id: 'game6', english: 'Chess', vietnamese: 'Cờ vua', pronunciation: 'co vua', category: 'game', chapter: 'chapter18', difficulty: 1, examples: ['Chess requires strategy.'] },
  { id: 'game7', english: 'Checkers', vietnamese: 'Cờ đam', pronunciation: 'co dam', category: 'game', chapter: 'chapter18', difficulty: 1, examples: ['Checkers simple rules.'] },
  { id: 'game8', english: 'Backgammon', vietnamese: 'Cờ backgammon', pronunciation: 'co backgammon', category: 'game', chapter: 'chapter18', difficulty: 2, examples: ['Backgammon ancient game.'] },
  { id: 'game9', english: 'Monopoly', vietnamese: 'Cờ tỷ phú', pronunciation: 'co ty phu', category: 'game', chapter: 'chapter18', difficulty: 1, examples: ['Monopoly teaches business.'] },
  { id: 'game10', english: 'Scrabble', vietnamese: 'Scrabble', pronunciation: 'scrabble', category: 'game', chapter: 'chapter18', difficulty: 1, examples: ['Scrabble improves vocabulary.'] },
  { id: 'game11', english: 'Poker', vietnamese: 'Poker', pronunciation: 'poker', category: 'game', chapter: 'chapter18', difficulty: 1, examples: ['Poker requires skill.'] },
  { id: 'game12', english: 'Bridge', vietnamese: 'Cầu', pronunciation: 'cau', category: 'game', chapter: 'chapter18', difficulty: 2, examples: ['Bridge complex card game.'] },
  { id: 'game13', english: 'Crossword', vietnamese: 'Ô chữ', pronunciation: 'o chu', category: 'game', chapter: 'chapter18', difficulty: 1, examples: ['Crossword puzzle daily.'] },
  { id: 'game14', english: 'Sudoku', vietnamese: 'Sudoku', pronunciation: 'sudoku', category: 'game', chapter: 'chapter18', difficulty: 1, examples: ['Sudoku number puzzle.'] },
  { id: 'game15', english: 'Jigsaw puzzle', vietnamese: 'Ghép hình', pronunciation: 'ghep hinh', category: 'game', chapter: 'chapter18', difficulty: 1, examples: ['Jigsaw puzzle relaxing.'] },
  { id: 'game16', english: 'Dice', vietnamese: 'Xúc xắc', pronunciation: 'xuc xac', category: 'game', chapter: 'chapter18', difficulty: 1, examples: ['Roll dice game.'] },
  { id: 'game17', english: 'Bingo', vietnamese: 'Bingo', pronunciation: 'bingo', category: 'game', chapter: 'chapter18', difficulty: 1, examples: ['Bingo night community.'] },
  { id: 'game18', english: 'Lottery', vietnamese: 'Xổ số', pronunciation: 'xo so', category: 'game', chapter: 'chapter18', difficulty: 1, examples: ['Lottery ticket lucky.'] },
  { id: 'game19', english: 'Billiards', vietnamese: 'Bi-a', pronunciation: 'bi-a', category: 'game', chapter: 'chapter18', difficulty: 1, examples: ['Billiards requires precision.'] },
  { id: 'game20', english: 'Pool', vietnamese: 'Bi-a pool', pronunciation: 'bi-a pool', category: 'game', chapter: 'chapter18', difficulty: 1, examples: ['Pool table bar.'] },
  { id: 'game21', english: 'Darts', vietnamese: 'Phi tiêu', pronunciation: 'phi tieu', category: 'game', chapter: 'chapter18', difficulty: 1, examples: ['Darts target practice.'] },
  { id: 'game22', english: 'Bowling', vietnamese: 'Bowling', pronunciation: 'bowling', category: 'game', chapter: 'chapter18', difficulty: 1, examples: ['Bowling strike score.'] },
  { id: 'game23', english: 'Arcade', vietnamese: 'Trò chơi điện tử', pronunciation: 'tro choi dien tu', category: 'game', chapter: 'chapter18', difficulty: 1, examples: ['Arcade games nostalgic.'] },
  { id: 'game24', english: 'Tournament', vietnamese: 'Giải đấu', pronunciation: 'giai dau', category: 'game', chapter: 'chapter18', difficulty: 1, examples: ['Tournament competition fierce.'] },
  { id: 'game25', english: 'Competition', vietnamese: 'Cuộc thi', pronunciation: 'cuoc thi', category: 'game', chapter: 'chapter18', difficulty: 1, examples: ['Competition motivates improvement.'] },

  // Entertainment & Leisure (25 words)
  { id: 'entertainment1', english: 'Entertainment', vietnamese: 'Giải trí', pronunciation: 'giai tri', category: 'entertainment', chapter: 'chapter18', difficulty: 1, examples: ['Entertainment industry growing.'] },
  { id: 'entertainment2', english: 'Movie', vietnamese: 'Phim', pronunciation: 'phim', category: 'entertainment', chapter: 'chapter18', difficulty: 1, examples: ['Movie tonight exciting.'] },
  { id: 'entertainment3', english: 'Television', vietnamese: 'Tivi', pronunciation: 'tivi', category: 'entertainment', chapter: 'chapter18', difficulty: 1, examples: ['Television shows variety.'] },
  { id: 'entertainment4', english: 'Show', vietnamese: 'Chương trình', pronunciation: 'chuong trinh', category: 'entertainment', chapter: 'chapter18', difficulty: 1, examples: ['Show starts eight.'] },
  { id: 'entertainment5', english: 'Book', vietnamese: 'Sách', pronunciation: 'sach', category: 'entertainment', chapter: 'chapter18', difficulty: 1, examples: ['Book reading relaxing.'] },
  { id: 'entertainment6', english: 'Reading', vietnamese: 'Đọc sách', pronunciation: 'doc sach', category: 'entertainment', chapter: 'chapter18', difficulty: 1, examples: ['Reading expands knowledge.'] },
  { id: 'entertainment7', english: 'Magazine', vietnamese: 'Tạp chí', pronunciation: 'tap chi', category: 'entertainment', chapter: 'chapter18', difficulty: 1, examples: ['Magazine articles interesting.'] },
  { id: 'entertainment8', english: 'Newspaper', vietnamese: 'Báo', pronunciation: 'bao', category: 'entertainment', chapter: 'chapter18', difficulty: 1, examples: ['Newspaper daily news.'] },
  { id: 'entertainment9', english: 'Radio', vietnamese: 'Đài phát thanh', pronunciation: 'dai phat thanh', category: 'entertainment', chapter: 'chapter18', difficulty: 1, examples: ['Radio morning program.'] },
  { id: 'entertainment10', english: 'Podcast', vietnamese: 'Podcast', pronunciation: 'podcast', category: 'entertainment', chapter: 'chapter18', difficulty: 1, examples: ['Podcast educational content.'] },
  { id: 'entertainment11', english: 'Internet', vietnamese: 'Internet', pronunciation: 'internet', category: 'entertainment', chapter: 'chapter18', difficulty: 1, examples: ['Internet browsing hours.'] },
  { id: 'entertainment12', english: 'Social media', vietnamese: 'Mạng xã hội', pronunciation: 'mang xa hoi', category: 'entertainment', chapter: 'chapter18', difficulty: 1, examples: ['Social media connects.'] },
  { id: 'entertainment13', english: 'Party', vietnamese: 'Tiệc', pronunciation: 'tiec', category: 'entertainment', chapter: 'chapter18', difficulty: 1, examples: ['Party celebration fun.'] },
  { id: 'entertainment14', english: 'Festival', vietnamese: 'Lễ hội', pronunciation: 'le hoi', category: 'entertainment', chapter: 'chapter18', difficulty: 1, examples: ['Festival cultural event.'] },
  { id: 'entertainment15', english: 'Picnic', vietnamese: 'Dã ngoại', pronunciation: 'da ngoai', category: 'entertainment', chapter: 'chapter18', difficulty: 1, examples: ['Picnic park family.'] },
  { id: 'entertainment16', english: 'Camping', vietnamese: 'Cắm trại', pronunciation: 'cam trai', category: 'entertainment', chapter: 'chapter18', difficulty: 1, examples: ['Camping nature adventure.'] },
  { id: 'entertainment17', english: 'Hiking', vietnamese: 'Đi bộ đường dài', pronunciation: 'di bo duong dai', category: 'entertainment', chapter: 'chapter18', difficulty: 1, examples: ['Hiking mountain trails.'] },
  { id: 'entertainment18', english: 'Gardening', vietnamese: 'Làm vườn', pronunciation: 'lam vuon', category: 'entertainment', chapter: 'chapter18', difficulty: 1, examples: ['Gardening therapeutic hobby.'] },
  { id: 'entertainment19', english: 'Cooking', vietnamese: 'Nấu ăn', pronunciation: 'nau an', category: 'entertainment', chapter: 'chapter18', difficulty: 1, examples: ['Cooking creative outlet.'] },
  { id: 'entertainment20', english: 'Baking', vietnamese: 'Làm bánh', pronunciation: 'lam banh', category: 'entertainment', chapter: 'chapter18', difficulty: 1, examples: ['Baking bread satisfying.'] },
  { id: 'entertainment21', english: 'Shopping', vietnamese: 'Mua sắm', pronunciation: 'mua sam', category: 'entertainment', chapter: 'chapter18', difficulty: 1, examples: ['Shopping weekend activity.'] },
  { id: 'entertainment22', english: 'Traveling', vietnamese: 'Du lịch', pronunciation: 'du lich', category: 'entertainment', chapter: 'chapter18', difficulty: 1, examples: ['Traveling broadens perspective.'] },
  { id: 'entertainment23', english: 'Sightseeing', vietnamese: 'Tham quan', pronunciation: 'tham quan', category: 'entertainment', chapter: 'chapter18', difficulty: 1, examples: ['Sightseeing tourist attractions.'] },
  { id: 'entertainment24', english: 'Relaxing', vietnamese: 'Thư giãn', pronunciation: 'thu gian', category: 'entertainment', chapter: 'chapter18', difficulty: 1, examples: ['Relaxing bath peaceful.'] },
  { id: 'entertainment25', english: 'Meditation', vietnamese: 'Thiền', pronunciation: 'thien', category: 'entertainment', chapter: 'chapter18', difficulty: 1, examples: ['Meditation calms mind.'] }
]
